### ISSUE TITLE
Windows Builds for Opencv.org binaries

### ISSUE THREAD

**Issue by photex** [twistedfall/opencv-rust#102]
I'm trying to build using the binaries provided by opencv.org but I'm having trouble linking apparently:

```
=== Setting up OpenCV library from environment, pkg_name: opencv4, link_libs: opencv_world420, link_paths: c:\OpenCV\x64\vc15\lib\, include_paths: C:\OpenCV\include      === OpenCV library configuration: Library {
    pkg_name: "opencv4",
    libs: [
        "opencv_world420.lib",
    ],
    link_paths: [
        "c:\\OpenCV\\x64\\vc15\\lib\\",
    ],
    framework_paths: [],
    include_paths: [
        "C:\\OpenCV\\include",
    ],
    version: "4.2.0",
    prefix: "",
    libdir: "c:\\OpenCV\\x64\\vc15\\lib\\",
    cargo_metadata: [
        "cargo:rustc-link-lib=opencv_world420",
        "cargo:rustc-link-search=native=c:\\OpenCV\\x64\\vc15\\lib\\",
    ],
}
=== Found OpenCV library version: 4.2.0 in headers located at: C:\Users\phote\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-0.31.0\headers/4
```

Why isn't it using the headers in the path I've specified?

I've attached the detailed build output.

[opencv_build_output.txt](https://github.com/twistedfall/opencv-rust/files/4293880/opencv_build_output.txt)

**Comment by twistedfall** [comment]
For building on windows please always use `buildtime-bindgen` feature (requires libclang from llvm choco/vcpkg package)

**Comment by photex** [comment]
🤦‍♂ Thanks.

**Comment by twistedfall** [comment]
The directory you're seeing specifically is controlled by `OPENCV_HEADER_DIR` env var, it's due to somewhat unnecessarily complicated separation between headers for binding generation and headers for building. I plan to simplify it in the future.

**Comment by photex** [comment]
Just as an afterthought, I'm using scoop and the official opencv binaries. I'd be happy to submit a PR to the readme with information for anyone else using Windows who does not want to endure the vcpkg build time of opencv and llvm.

**Comment by twistedfall** [comment]
Please do!
