### ISSUE TITLE
Feature request: Generic Ptr<_> smart pointer

### ISSUE THREAD

**Issue by jerry73204** [twistedfall/opencv-rust#103]
The current impl of code generator generates all enumeration of [PtrOf* types](https://docs.rs/opencv/0.32.0/opencv/?search=ptrof). It could be further generalized into a generic `Ptr<_>` type.

In principal, we can define `Ptr<_>` as a type with `Clone` and `Deref`. That would also simplify the #86 issue.

I made a little inspection on type generation before 0.30.0. Since the new rust header parser lands, could you give some hint on where the type information is collected?

**Comment by twistedfall** [comment]
Well, the module responsible for generating smart pointers is here: `binding-generator/src/smart_ptr.rs`. But creating a generic struct in Rust for it is not possible I'm afraid. Not without some additional external code generation at least. The thing is, to be able to forward calls to different C++ template instances from Rust you need to generate separate C linkage functions (with unique, but known in advance names) for every type used. And doing that using Rust generics alone is not possible. It would kind of possible with some macro help probably, but required features (being able to generate new function names in macros) are not implemented in yet (https://github.com/rust-lang/rust/issues/29599).

**Comment by twistedfall** [comment]
And regarding #86 issue, it shouldn't be an issue anymore, you can access all of the fields via setters and getters on the `PtrOf...` type itself

**Comment by jerry73204** [comment]
> The thing is, to be able to forward calls to different C++ template instances from Rust you need to generate separate C linkage functions (with unique, but known in advance names) for every type used.

I'm thinking of bold alternative: What if we generate C++ code on the fly using [cpp::cpp!](https://docs.rs/cpp/0.5.4/cpp/macro.cpp.html)? That is, we always forward each method of `Ptr<_>` generic to underlying C++ code.

This would somewhat solve our problem, but with considerations. For example, it implies the C++ is present when user use opencv-rust as dependency even if opencv-rust is compiled in anticipation.

**Comment by twistedfall** [comment]
It was actually used in versions before 0.30, but I dropped it. It increases build time considerably and at some point it started to generate such a big object file so that Windows compiler started to refuse to compile the project in debug mode. Plus it will not actually help here because you still need to generate separate manual implementation of functions calling the templated methods. Since you created this issue I actually had an idea of how to implement this so I’m playing with this at the moment.

**Comment by twistedfall** [comment]
In v0.36, `Ptr<T>` is now a thing.

**Comment by jerry73204** [comment]
Wow. It's really a decent work. I cannot wait for it!
