### ISSUE TITLE
Creating a Mat or UMat from Vec<u8>

### ISSUE THREAD

**Issue by photex** [twistedfall/opencv-rust#108]
I have no idea where else to ask this question. But I figure it could be somewhat related to the api wrapper.

I have a byte buffer created by gstreamer pipeline which is 'width * height * 3' bytes in size. In my appsink I get a slice &[u8] and I can copy it to a vec if needed.

I cannot easily see how to create a UMat or Mat from this. There isn't a variant of 'from_slice' that accepts the correct image dimensions for example. And the implementation of from_slice/from_slice_2d seem to create a Mat with totally undesirable setup for treating the buffer as an image.

Certainly part of my problem is just ignorance. :D 

Any suggestions, tips, or clarifications would really appreciated!

**Comment by twistedfall** [comment]
So you want to create a 2D Mat 3 channels deep from a 1D slice? So your target would be Mat with type `Vec3b::typ()` (`CV_8UC3` in OpenCV terms) with the `rows()` == height and `cols()` == height. It looks like a something like this should work:
```rust
// quick and dirty untested code
let m = Mat::from_slice(source_slice).unwrap(); // will give type=CV_8UC1, rows=1, cols=width*height*3
let m = m.reshape(3, height).unwrap(); // should give you type=CV_8UC3, rows=height, cols=width
```

**Comment by photex** [comment]
Ah, thank you for clarifying this for me. I understand more clearly why I was segfaulting when creating a mat from a pointer as well.
