### ISSUE TITLE
example video_capture.rs fails [OpenCV 3.2]

### ISSUE THREAD

**Issue by GRASBOCK** [twistedfall/opencv-rust#111]
opencv = {version = "0.33", default-features = false, features = ["opencv-32"]}
rustc 1.42.0
Ubuntu 18.04.4 LTS

I just copy pasted the example video_capture.rs and got this error
```
error[E0599]: no function or associated item named `new` found for struct 
`opencv::videoio::VideoCapture` in the current scope
  --> src/main.rs:16:42
   |
16 |     let mut cam = videoio::VideoCapture::new(0, videoio::CAP_ANY)?;  // 0 is the default camera
   |                                          ^^^ function or associated item not found in `opencv::videoio::VideoCapture`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `opencv_rust_test`.
```

I suspect the examples might be outdated with rust.
I just started with rust, so this is something that will take me longer than a pro to fix.

**Comment by twistedfall** [comment]
There is a feature fork in that example:
```rust
    #[cfg(feature = "opencv-32")]
    let mut cam = videoio::VideoCapture::new_default(0)?;  // 0 is the default camera
    #[cfg(not(feature = "opencv-32"))]
    let mut cam = videoio::VideoCapture::new(0, videoio::CAP_ANY)?;  // 0 is the default camera
```
It doesn't work out because your project doesn't have those features declared/enabled so rust picks up the second branch. In your case you need to only leave:
```rust
    let mut cam = videoio::VideoCapture::new_default(0)?;  // 0 is the default camera
```

**Comment by GRASBOCK** [comment]
Yep, now it compiles. However the windows immediately closes after being opened. This is because of line 25. I verified using print! . However no keys are pressed.

**Comment by twistedfall** [comment]
Hm, it looks like OpenCV 3.2 return value from `waitKey` is different from later versions. Please use this fixed code (I will also update the example):
```rust
        let key = highgui::wait_key(10)?;
        if key > 0 && key != 255 {
            break;
        }
```

**Comment by GRASBOCK** [comment]
Yep that fixed it. Thanks! I suppose -1 is the same as 255 on 8bit integers so thats why it failed.

Because I expected many issues to occur from using old versions of opencv I built the 4.2.0 version.
The .pc file has been generated. 
Compiling `opencv = {version = "0.33"}` has not worked however because of many linker errors. SO many infact, that I cannot show them here. I think I have not been able to successfully set the `PKG_CONFIG_PATH` and `LD_LIBRARY_PATH`. I will try to restart and find a way to be sure that those have been set. Help regarding this is appreciated.

**Comment by GRASBOCK** [comment]
I think it was because I compiled cmake statically. That is why no .so files were in the `LD_LIBRARY_PATH`. I am going to build the Shared Libraries for OpenCV 4.2.0 now and report back once that is done.

**Comment by twistedfall** [comment]
The static build is something that I still want to explore at some point, but yeah I haven't tested it at all.

**Comment by GRASBOCK** [comment]
Alright. I have compiled the shared Libraries and it works. Since the reason I switched from c++ to Rust in this case was to try if cross platforming is simpler, I will try the same on windows next.

If Issues occur I will create a new one. Thank you!
