### ISSUE TITLE
can't draw all draw contours

### ISSUE THREAD

**Issue by GRASBOCK** [twistedfall/opencv-rust#116]
opencvrs 0.33
Windows 10

I am trying to draw the contours found. However it only draws the first one when I want to draw all of them using "-1". Switching through the individual indices manually shows me the other contours; Meaning they do exist.
```
	let mut contours = types::VectorOfVectorOfPoint::new();
	imgproc::find_contours(&thresholded, &mut contours, imgproc::RETR_EXTERNAL, imgproc::CHAIN_APPROX_SIMPLE, core::Point::default()).unwrap();
	println!("contours: {}", contours.len()); // says there are 19
	imgproc::draw_contours(&mut display, &contours, -1, core::Scalar::new(255., 255.,255.,255.), 2, 0, &core::Mat::default().unwrap(), 0, core::Point::default() ).unwrap();
```

**Comment by twistedfall** [comment]
I'm using find_contours/draw_contours in my project and it works fine. I'd suggest trying to specify default values from the function documentation:
```rust
/// * thickness: 1
/// * line_type: LINE_8
/// * hierarchy: noArray()
/// * max_level: INT_MAX
/// * offset: Point()
```
For example your `line_type` is 0, and `max_level` is 0 too, that might be the problem.

This is what I have in my code:
```rust
imgproc::find_contours(&areas, &mut contours, imgproc::RETR_EXTERNAL, imgproc::CHAIN_APPROX_SIMPLE, Point::default())?;
...
imgproc::draw_contours(&mut img, &contours, -1, Scalar::new(0., 0., 255., 0.), 1, imgproc::LINE_8, &Mat::default()?, 100, Point::default())?;
```

**Comment by GRASBOCK** [comment]
Thanks, setting the max_level to 1 resolved the issue. The line-type had no influence.
I thought that level 0 was the first.
