### ISSUE TITLE
Unable to build crate on Ubuntu16 with OpenCV 4.2.0

### ISSUE THREAD

**Issue by photex** [twistedfall/opencv-rust#117]
Howdy!

Prototyped some work using Windows and 4.2.0. When trying to build on the Linux system I'm experiencing troubles. We're building OpenCV from source and it builds and installs without a hitch.
Unfortunately something is going wacky with the bindings generated by the crate. I'm worried that Ubuntu 16 is just too out of date for the code generator (we have a fairly hard requirement for Ubuntu 16 on this project).

I've tried opencv 0.33 and 0.34 (build_output.txt was with 0.34), the error is the same.

My cargo entry for opencv: `opencv = { version="0.34", features = ["buildtime-bindgen"] }`

When reporting an issue please state:
1. Ubuntu 16.04
2. Compiled from source: `cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/opencv-4.2.0 -DBUILD_PERF_TESTS:BOOL=OFF -DBUILD_TESTS:BOOL=OFF -DBUILD_DOCS:BOOL=OFF -DBUILD_EXAMPLES:BOOL=OFF -DINSTALL_CREATE_DISTRIB=ON ../opencv-4.2.0`
3. 4.2.0
4. [build_output.txt](https://github.com/twistedfall/opencv-rust/files/4476295/build_output.txt)

**Comment by photex** [comment]
Ok, appears that I've solved my issue.

I needed to install a more recent clang, and I had to also use the OPENCV_HEADER_DIR env var.

**Comment by twistedfall** [comment]
Can you please tell me what was the clang version that was failing? And how did you install a newer one in ubuntu 16?

**Comment by photex** [comment]
Clang version that wasn't working was apparently clang/llvm 3. But afaik the generated code was attempting to build with 'c++' which would have been gcc 5.

I installed llvm/clang 10 directly from apt using https://apt.llvm.org/

**Comment by twistedfall** [comment]
Thanks, I would say that the minimum supported libclang version is 6.0 so you're right.
