### ISSUE TITLE
How can I save a video than can be opened in browser

### ISSUE THREAD

**Issue by hyousefGopher** [twistedfall/opencv-rust#119]
In `Python` the below worked with me smoothly (after struggling in finding the proper codecs):
```python
import cv2, os

cap = cv2.VideoCapture(0)
frame_width = int(cap.get(3))
frame_height = int(cap.get(4))
fourcc = cv2.VideoWriter_fourcc(*"vp80")
out = cv2.VideoWriter("../file.webm", fourcc, 10,
                      (frame_width, frame_height))
directory = r"c:/photos"
os.chdir(directory)
while cap.isOpened():
    ret, frame = cap.read()
    if ret:
        out.write(frame)
        cv2.imshow("Frame", frame)
        if cv2.waitKey(25) & 0xFF == ord('q'):
            break
    else:
        break
cap.release()
out.release()
cv2.destroyAllWindows()
```
When I was able to open in the browser as:
```html5
<video width="320" height="240" preload="none" loop controls autoplay muted id="vid">
      <source src="file.webm" type="video/webm; codecs='vp8.0, vorbis'">
</video>
```

Trying to make the same with `OpenCV-Rust`:
```rust
fn run() -> opencv::Result<()> {
    let window = "video capture";
    highgui::named_window(window, 1)?;
    #[cfg(feature = "opencv-32")]
    let mut cam = videoio::VideoCapture::new_default(0)?;  // 0 is the default camera
    #[cfg(not(feature = "opencv-32"))]
    let mut cam = videoio::VideoCapture::new(0, videoio::CAP_ANY)?;  // 0 is the default camera

    let frame_width =  cam.get(3);
    let frame_height = cam.get(4);

    let opened = videoio::VideoCapture::is_opened(&cam)?;
    let fourcc = videoio::VideoWriter::fourcc(*"vp80");
    let out = videoio::VideoWriter("../file.webm", fourcc, 10, (frame_width, frame_height));

    if !opened {
        panic!("Unable to open default camera!");
    }
    loop {
        let mut frame = core::Mat::default()?;
        cam.read(&mut frame)?;
        if frame.size()?.width > 0 {
            highgui::imshow(window, &mut frame)?;
            out::Write(frame);
        }
        let key = highgui::wait_key(10)?;
        if key > 0 && key != 255 {
            break;
        }
    }
    Ok(())
}
```

But it looks the `fourcc` not accepting the same input as in python, and insists to have 4 parameters as input! if it is a must to enter 4 params, what are the ones suitable to the `.webm` other than the one I found.

![image](https://user-images.githubusercontent.com/60115476/80318248-8aa34980-8811-11ea-9c46-b90bb888b7ee.png)

**Comment by twistedfall** [comment]
Well, according to docs,`fourcc` function accepts 4 chars as 4 arguments so you should try something like:
```rust
fourcc('v' as i8, 'p' as i8, '8' as i8, '0' as i8)
```

**Comment by hyousefGopher** [comment]
Thanks, but I stuck with the [frame size](https://docs.rs/opencv/0.34.0/opencv/videoio/struct.VideoWriter.html#method.new), not clear for me how to be written :(

```rust
    let fourcc = match videoio::VideoWriter::fourcc(
        'v' as i8,
        'p' as i8,
        '8' as i8,
        '0' as i8
    ){
        Some(x) => x,
        None => 0
    };
    let out = videoio::VideoWriter::new(
        "../file.webm",
        fourcc,
        10.0,
        Size2i<frame_width, frame_height>
    );
```

**Comment by twistedfall** [comment]
```rust
opencv::core::Size::new(frame_width, frame_height)
```

**Comment by hyousefGopher** [comment]
mm, well, considering now all setup done, how to write for the `out` I could not find `video codecs`

![image](https://user-images.githubusercontent.com/60115476/80320363-ad882a80-881e-11ea-960a-563a695b523a.png)

I tried the below, but did not work:

```rust
    let fourcc = videoio::VideoWriter::fourcc(
        'v' as i8,
        'p' as i8,
        '8' as i8,
        '0' as i8
    )?;
    let mut out = videoio::VideoWriter::new(
        "file.webm",
        fourcc,
        10.0,
        Size2i::new(frame_width, frame_height),
        true
    ).expect("Can not open video writer");

        if frame.size()?.width > 0 {
            highgui::imshow(window, &mut frame)?;
            videoio::VideoWriter::write(&mut out, &frame);
        }
```

The file had been created, but I could not open it:
![image](https://user-images.githubusercontent.com/60115476/80321214-04dcc980-8824-11ea-9cfd-891ec5319bf8.png)

**Comment by hyousefGopher** [comment]
I tried this one, and it worked, but once I display it it is slow in both Windows media player and browser:

```rust
    let fourcc = videoio::VideoWriter::fourcc(
        'm' as i8,
        'p' as i8,
        '4' as i8,
        'v' as i8
    )?;
    let mut out = videoio::VideoWriter::new(
        "output.mp4",
        fourcc,
        10.0,
        Size2i::new(frame_width, frame_height),
        true
    ).expect("Can not open video writer");
```

Also worked with:
```rust
    let fourcc = videoio::VideoWriter::fourcc(
        'h' as i8,
        '2' as i8,
        '6' as i8,
        '4' as i8
    )?;
```
And in theweb:
```html5
<video width="320" height="240" preload="none" loop controls autoplay muted id="vid">
            <source src="output.mp4" type="video/mp4">
 </video>
```

**Comment by hyousefGopher** [comment]
I fixed the speed by improving frames per second, thanks

![image](https://user-images.githubusercontent.com/60115476/80379231-7b221000-88a6-11ea-87f4-af285aeabbc8.png)

**Comment by twistedfall** [comment]
It’s great to hear that! So the problem was in the codecs in your system? But the python script still produced the correct video on the same system with the same OpenCV version?

**Comment by hyousefGopher** [comment]
yes, correct.
I'm new to OpenCV and interested about Rust, will try my best to work with rust, and cross check with python result, hope you have enough time to keep this crate improving, wish you all the best.

**Comment by twistedfall** [comment]
So that’s also a “yes” to the fact that python script can actually produce a working video file, right? That’s very strange. Are you sure you are using the same OpenCV version between rust and python?

**Comment by hyousefGopher** [comment]
mm, not sure if I got your question correctly, video is a sequence of frames, it is not having sound, which is not within the scope of opencv.

OpenCV installed by Chocolaty is: 4.1.2
![image](https://user-images.githubusercontent.com/60115476/80398727-c3e6c280-88c0-11ea-8cdc-5aa3e39fb9e7.png)



OpenCV installed by Python is: 4.2.0.34
![image](https://user-images.githubusercontent.com/60115476/80398798-dc56dd00-88c0-11ea-855b-e7a9cc417a4e.png)


I'll try doing it with older version and update you.
![image](https://user-images.githubusercontent.com/60115476/80398894-07d9c780-88c1-11ea-892e-6068e970d43d.png)

**Comment by twistedfall** [comment]
Initially you said that you were translating a python script to rust, so I assume that this script was producing a video file that you were able to use in browser. Then you translated it to rust and while you succeeded in producing the file, you couldn’t play it. So I wonder why. Since the logic between rust program and python file is the same then they should both produce the same playable file.

**Comment by hyousefGopher** [comment]
sorry may mistake in explanation then, the one I generated with python was `.webm`, which got generated using the `fourcc = cv2.VideoWriter_fourcc(*"vp80")` by problem was in translating this code  with `opencv-rust`. 
so, below python code generated a working video (though it was sowing: OpenCV: FFMPEG: tag 0x30387076/'vp80' is not supported with codec id 139 and format 'webm / WebM')
 
```python
fourcc = cv2.VideoWriter_fourcc(*"vp80")
```

While below rust code, generated a non-working video:
```rust
    let fourcc = videoio::VideoWriter::fourcc(
        'v' as i8,
        'p' as i8,
        '8' as i8,
        '0' as i8
    )?;
```

![image](https://user-images.githubusercontent.com/60115476/80406191-56d92a00-88cc-11ea-8469-3898244ed05a.png)

The rust codes that generated a working video with me are:
```rust
    let fourcc = videoio::VideoWriter::fourcc(
        'm' as i8,
        'p' as i8,
        '4' as i8,
        'v' as i8
    )?;
```
And
```rust
    let fourcc = videoio::VideoWriter::fourcc(
        'h' as i8,
        '2' as i8,
        '6' as i8,
        '4' as i8
    )?;
```

**Comment by ozgurSULUM** [comment]
When I tried "H264" codec it worked in chrome and firefox.

I used in my code like in below.
`
fourcc = cv2.VideoWriter_fourcc(*'H264')
`
`
videoWriter = cv2.VideoWriter("output.mp4", fourcc, fps, (width,  height), True)
`

When I tried to run I got this message. I downloaded corresponding .dll file and put it in my project folder and it worked!
![image](https://user-images.githubusercontent.com/41192900/156940317-ab7d97e2-2de8-41b3-bedd-4066dab0a2cd.png)

**Comment by sjbeskur** [comment]
Has there ever  been a solution to this?   I too seem to be experiencing the same issues.  The capture device opens and seems to write but only a small video file is ever written that is unreadable by my system (ubuntu  22.04, OpenCV 4.9.0)

Here is my sample code:
```
pub fn capture() {
	let mut device = VideoCapture::new(2, cv::videoio::CAP_ANY).unwrap();
	let mask = Mat::default();

	let mut img = cv::prelude::Mat::default();

	//let fourcc = cv::videoio::VideoWriter::fourcc('X', 'V', 'I', 'D').unwrap();
	let fourcc = cv::videoio::VideoWriter::fourcc('m', 'p', '4', 'v').unwrap();

	let fps = cv::videoio::CAP_PROP_FPS;
	let fps = device.get(fps).unwrap();

	let frame_width = device.get(3).unwrap();
	let frame_height = device.get(4).unwrap();
	println!("width {}, height {}", frame_width, frame_height);

	let mut writer = cv::videoio::VideoWriter::new(
		"detects.mp4",
		fourcc,
		fps,
		cv::core::Size2i::new(frame_width, frame_height),
		false,
	)
	.unwrap();

	loop {
		let _ = device.read(&mut img).unwrap();

		cv::highgui::imshow("Display Window", &out_img).unwrap();

		writer.write(&out_img).unwrap();

		let k = opencv::highgui::wait_key(1).unwrap();
		if k == 32 {
			break;
		}
	}
	// writer.release().unwrap();
	device.release().unwrap();
}


```

**Comment by learncodingforweb** [comment]
it does not record, video. i have following code. Running code on ubuntu22.04LTS 
*Linux notebook 6.5.0-28-generic #29~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  4 14:39:20 UTC 2 x86_64 x86_64 x86_64 GNU/Linux*

Cargo.toml
```
opencv = "0.91"
```
```
use opencv::prelude::*;
use opencv::{core::Mat, highgui, videoio};

fn main() {
    let mut cam = videoio::VideoCapture::new(0, videoio::CAP_ANY).unwrap();
    // let fourcc = videoio::VideoWriter::fourcc('m', 'p', '4', 'v').unwrap();
    // let fourcc = videoio::VideoWriter::fourcc('X', 'V', 'I', 'D').unwrap();
    let fourcc = videoio::VideoWriter::fourcc('X', 'V', 'I', 'D').unwrap();

    let w = cam.get(videoio::CAP_PROP_FRAME_WIDTH).unwrap();
    let h = cam.get(videoio::CAP_PROP_FRAME_HEIGHT).unwrap();
    let fps = cam.get(videoio::CAP_PROP_FPS).unwrap();
    println!("got fps {} {} {}", fps, w, h);

    let mut out = videoio::VideoWriter::new(
        "detects.avi",
        fourcc,
        fps,
        opencv::core::Size::new(w as i32, h as i32),
        false,
    )
    .unwrap();
    loop {
        let mut frame = Mat::default();
        let _ = cam.read(&mut frame);
        if let Ok(sz) = frame.size() {
            out.write(&frame).unwrap();
            highgui::imshow("Display Window", &frame).unwrap();
            // println!("{:?}", r);
        }
        let key = highgui::wait_key(20).unwrap();
        if key > 0 && key != 255 {
            break;
        }
    }

    let _ = out.release();
    let _ = cam.release();
}
```

```
rustc --version
rustc 1.77.2 (25ef9e3d8 2024-04-09)
```

can any help to resolve this issue to save video in any format on pc
