### ISSUE TITLE
How can I save an image

### ISSUE THREAD

**Issue by hyousefGopher** [twistedfall/opencv-rust#120]
I've the below working python code:
```python
import cv2 # importing cv2
import os # importing os module

cap = cv2.VideoCapture(0)  # open camera
ret, frame = cap.read()  # read camera frame

directory = r'c:/photos' # image directory
os.chdir(directory) # change the current directory to specified directory
filename = 'savedImage.jpg' # set filename

# save frame with given filename at the given directory
cv2.imwrite(filename, frame)
```

I tried to replicated it with `opencv-rust` but couldn't find `imwrite`?
I read the documents [here](https://docs.rs/opencv/0.34.0/opencv/imgcodecs/fn.imwrite.html), but did not understand what is neither the `img: &dyn ToInputArray,` nor the `params: &VectorOfi32`
I tried the following, but it is wrong:
```rust
let filename = "savedImage.jpg";
imgcodecs::imwrite(filename, frame, &[1]); 
```

**Comment by twistedfall** [comment]
Try:
```rust
imgcodecs::imwrite(filename, &frame, &opencv::types::VectorOfi32::new()); 
```

**Comment by hyousefGopher** [comment]
Work perfectly, thanks.
But is it required to add: `&opencv::types::VectorOfi32::new()` can not be considered in the background without having the user to write it?

**Comment by twistedfall** [comment]
Rust by itself doesn’t support default function arguments so it’s not straightforward. I have an idea of maybe generating 2 versions of those functions with and without those arguments, but it’s still in plans.
