### ISSUE TITLE
TermCriteria should be taken by reference

### ISSUE THREAD

**Issue by m-ou-se** [twistedfall/opencv-rust#123]
OpenCV version: 0.34

Functions like [`opencv::calib3d::calibrate_camera`](https://docs.rs/opencv/0.34.0/opencv/calib3d/fn.calibrate_camera.html) take [`opencv::core::TermCriteria`](https://docs.rs/opencv/0.34.0/opencv/core/struct.TermCriteria.html) by value, consuming it. Since `TermCriteria` is neither Clone nor Copy, this means having to create a new `TermCriteria` for every call that needs it.

This makes it impossible to use it multiple times like in C++, as is done in this example: https://docs.opencv.org/master/d2/d1d/samples_2cpp_2lkdemo_8cpp-example.html#_a5

**Comment by twistedfall** [comment]
I see, it's a rather simple class so it might be possible to mark it as simple. I'll keep this in mind for the next release. Meanwhile as a workaround it should be easy to write a cloning function that takes an existing `TermCriteria` by reference and creates a new one by copying its 3 fields.

**Comment by twistedfall** [comment]
It's now fixed in v0.36
