### ISSUE TITLE
Interorp for OCR / Construct leptess::capi::Pix from opencv::core::Mat

### ISSUE THREAD

**Issue by mashedcode** [twistedfall/opencv-rust#126]
It's very common to do OCR on top of OpenCV with the help of Tesseract and Leptonica.
It would be bad if one would have to save the cropped image to disk and decode it to get this to work.

To construct [leptess::capi::Pix](https://houqp.github.io/leptess/leptess/capi/struct.Pix.html) one would need to know how to access Mat `.data`.

IIUC it should be some magic offset from `.as_raw_Mat() as *mut u8`.  I'm however having trouble to figure out how exactly to access it.
It would therefore be great if `.data` would be exposed clearly via the rust interface.

**Comment by twistedfall** [comment]
Well it is: https://docs.rs/opencv/0.36.0/opencv/core/trait.MatTraitManual.html#method.data :)

**Comment by mashedcode** [comment]
Thank you so much!!

**Comment by mashedcode** [comment]
As there're not many examples in rust. My implementation looked more or less like this:
```rust
// let mat: Mat ...
let input = mat.data()? as *const u8;
let channels = mat.channels()? as usize;
let width = mat.cols() as usize;
let height = mat.rows() as usize;
let mut data = Vec::with_capacity(width * height);
for i in (0..(width * height * channels)).step_by(channels) {
    let b = unsafe { *input.add(i) as u32 };
    let g = unsafe { *input.add(i + 1) as u32 };
    let r = unsafe { *input.add(i + 2) as u32 };
    let mut value = (r << 24) | (g << 16) | (b << 8) | 0xff;
    data.push(value);
}
let mut raw = leptess::capi::Pix {
    w: width as u32,
    h: height as u32,
    d: 32,
    spp: 3,
    wpl: width as u32,
    informat: 9,
    special: 0,
    refcount: 1,
    xres: 300,
    yres: 300,
    text: ptr::null_mut(),
    colormap: ptr::null_mut(),
    data: data.as_mut_ptr(),
};
let mut pix = leptonica::Pix {
    raw: &mut raw,
};
tesseract.set_image(&pix);
let text = tesseract.get_utf8_text()?;
// I hope that this is right..?!
mem::forget(data);
pix.raw = ptr::null_mut();
text
```

**Comment by twistedfall** [comment]
```rust
mem::forget(data);
mem::forget(raw);
```
That doesn’t look right. I’m not familiar with tesseract and leptess APIs, but they should handle the deletion of the object and moreover you don’t seem to need `data` vec  after you extracted image from it. So `mem::forget` will just leak memory without any benefit.

**Comment by mashedcode** [comment]
Thanks, removed `mem::forget(raw);`.
The idea is that the `leptess::capi::Pix` structure owns (responsible for freeing) ` data`. Without the remaining one I get double-free crashes.
I was happy with the fact that it works.
