### ISSUE TITLE
Imencode example

### ISSUE THREAD

**Issue by hyousefGopher** [twistedfall/opencv-rust#127]
I read the documentation explaining the signature of the mentioned, but could not understand how to use it, in Python it is just passing the frame and the required extension, here there are buffers and flags, can you pls provide simple example about using that could be equivalent to Python code:
```python
(flag, encodeImage) = cv2.imencode(".JPG", frame)
```

Thanks

**Comment by twistedfall** [comment]
Generally it’s easier to map the API functions to C++ rather than Python, because sometimes in Python functions are changed in regards to the return or their arguments. In this particular case `encodeImage` is the output `buf` argument. `flag` is the return result.

```rust
let mut encodeImage = opencv::core::Vector::<u8>::new();
let flag = opencv::imgcodecs::imencode(“.JPG”, frame, &mut encodeImage, &opencv::core::Vector::<i32>::new())?;
```

**Comment by hyousefGopher** [comment]
mmm, is gave me error that 4 arguments expected, , while 3 arguments supplied.

Also the `::Vector` did not appear with auto complete

**Comment by hyousefGopher** [comment]
Also, for the frame, it gave me mismatched type, expected `&ToInputArray`, found `Mat`

**Comment by twistedfall** [comment]
Yep, I updated the sample in the comment, but it was too late :) Regarding autocomplete, what are you using for that? I’ve only tested locally with idea plugin. For frame error just pass a reference `&frame`.

**Comment by hyousefGopher** [comment]
I use PyCharm with Rust plugin, I found something there as:
`opencv::opencv::hub::types::core_types` => `VectorOfu8` and `VectorOfi3`

**Comment by twistedfall** [comment]
What version of the crate are you using?

**Comment by hyousefGopher** [comment]
"0.34"

**Comment by twistedfall** [comment]
Then you are right, it should be like this:
```rust
let mut encodeImage = opencv::types::VectorOfu8::new();
let flag = opencv::imgcodecs::imencode(“.JPG”, &frame, &mut encodeImage, &opencv::types::VectorOfi32::new())?;
```

**Comment by hyousefGopher** [comment]
Thanks, worked perfectly as below (I updated to `opencv = {version = "0.36", features = ["buildtime-bindgen"]}`

```rust
let mut cam = videoio::VideoCapture::new_default(0)?;
let mut frame = core::Mat::default()?;
cam.read(&mut frame)?;
let mut encodedImage = VectorOfu8::new();
let mut params = VectorOfi32::new();
match opencv::imgcodecs::imencode(".JPG", &frame,
                                              &mut encodedImage, &params).unwrap()  {
      true => { let filename = "savedImageX.jpg"; 
                      imwrite(&filename, &frame,  &params);
      },
      false => println!("not encoded")
}

So now the image is continuously updated, and need to see how to keep updating it at `<img src="">`  :)

**Comment by hyousefGopher** [comment]
Just in case another one wanted to do the system, I was upload it so far in the browser (but slow, specially if there is motion, as below:

```html
<img id="theImage" src = "http://localhost:8000/static/savedImageX.jpg">
<script>
    newImage = document.getElementById("theImage");
    (function(){
          newImage.src = "http://localhost:8000/static/savedImageX.jpg?" + new Date().getTime();
          setTimeout(arguments.callee, 1000);
    })();
</script>
```
