### ISSUE TITLE
Converting VectorOfu8 to Bytes

### ISSUE THREAD

**Issue by hyousefGopher** [twistedfall/opencv-rust#128]
In Rust normal Vec can be converted into byte using `as_bytes()`

I'm trying to convert the `encoded image` discussed at [#127](https://github.com/twistedfall/opencv-rust/issues/127)  into Bytes, so I push it from the server to the browser, which should be faster than repeating JavaScript function,

Hire can I convert this `VectorOfu8` into Bytes?

**Comment by twistedfall** [comment]
Depends on what Bytes you mean, but there are both [`to_slice`](https://docs.rs/opencv/0.36.0/opencv/core/struct.Vector.html#method.to_slice) and [`to_vec`](https://docs.rs/opencv/0.36.0/opencv/core/struct.Vector.html#method.to_vec) methods.
