### ISSUE TITLE
How to share Facemark between thread

### ISSUE THREAD

**Issue by linrium** [twistedfall/opencv-rust#139]
Hello, I want to share Facemark lbf between Tokio thread but it isn't working.
```
unsafe impl Send for Facemark {}

#[tokio::main]
async fn main() {
    let mut face_mark = create_facemark_lbf().unwrap();
    Facemark::load_model(&mut face_mark, "haarcascades/lbfmodel.yml").unwrap();
    let face_mark = Arc::new(Mutex::new(face_mark));

    for i in 0..10 {
        let face_mark = face_mark.clone();
        tokio::spawn(async move {
            let a = face_mark;
        });
    }
}
```
I got this error when trying to compile
![image](https://user-images.githubusercontent.com/14315537/84159529-59b46680-aa97-11ea-80fe-61664844c31e.png)

**Comment by twistedfall** [comment]
I think I need to add `unsafe impl Send` for all boxed objects, I'll check it out. Meanwhile I think the only workaround is to make your own type which wraps the `Facemark` and provides `unsafe impl Send` itself.

**Comment by twistedfall** [comment]
On the other hand, it looks like it's not such a good idea, it seems that OpenCV makes extensive use of thread-local data, so at least some of its objects are `!Send`. If you could find some proof that Facemark can indeed be send to another thread I'm going to implement selective `impl Send` for those types.

You can also use some kind of channel for message passing to keep it in only one thread. Or use a single-threaded reactor.

**Comment by linrium** [comment]
It would be nice if you implement it. Meanwhile I will try to use other way. Thank you very much.

**Comment by twistedfall** [comment]
Implementation is easy, it’s the safety I’m concerned with. Do you have any knowledge to assume that Facemark is safe to send between threads?

**Comment by linrium** [comment]
Sorry, I'm new in Rust so I don't have experience in it.

**Comment by twistedfall** [comment]
Well `create_facemark_lbf` actually returns `Ptr<dyn Facemark>` so you want to share a mutable reference between threads, it's highly unsafe unless pointed to object (Facemark in this case) is thread-safe. OpenCV is rarely thread-safe in regards to data so in this case universally marking `Ptr` as `unsafe impl Send` is not a way to go.

**Comment by sunsided** [comment]
To allow finding this issue a bit more easily, this is the error message in the picture:

```
`*mut std::ffi::c_void` cannot be sent between threads safely
```
