### ISSUE TITLE
Build fails when target is a lib

### ISSUE THREAD

**Issue by igormq** [twistedfall/opencv-rust#140]
1. Operating system

Ubuntu 18.04

2. The way you installed OpenCV: package, official binary distribution, manual compilation, etc.

OpenCV from homebrew

3. OpenCV version

4.3.0

4. Attach the full output of the following command from your project directory:
   ```shell script
   RUST_BACKTRACE=full cargo build -vv 
   ```
[Full output](https://pastebin.com/bsrrJuGj)

**Comment by twistedfall** [comment]
Please try running with `buildtime-bindgen` feature enabled

**Comment by igormq** [comment]
wow, it worked! \o/

Thank you!

By the way, amazing work that you are doing here ! It helped me a lot.
