### ISSUE TITLE
Feature requests: public `VectorElement` trait and `impl From<Vec<T>> for Vector<T>` and vice versa

### ISSUE THREAD

**Issue by jerry73204** [twistedfall/opencv-rust#143]
`Vector<_>` generic is great. It saves me the hassle of `VectorOf*` types. I pulled it into my project for a while, and here is my feedback.

- Please make `VectorElement` public so that it can be used as trait bounds for custom traits.
- Though we have `Vector::to_vec`, it's better to have `impl From<Vec<T>> for Vector<T>` and vice versa. In this way, I can make `fn my_func<T: Into<Vector<i32>>>(values: T)` compile.
- `Vector::to_slice` should be named `Vector::as_slice` by convention. Also, If possible, add `AsRef<[T]>` for `Vector`.

**Comment by twistedfall** [comment]
Makes sense, I’ll implement that! PRs are also always welcome :)

**Comment by jerry73204** [comment]
`VectorElement` is public but marked `#[doc(hidden)]`. I was confused in the first place. If it is preferred not to contaminate the `opencv::core` names, perhaps we could add a `opencv::core::marker` or something else.

**Comment by jerry73204** [comment]
I sent PR #144. Unfortunately, I cannot figure out making `impl From<Vec<T>> for Vector<T>` compile. It needs to get around with `OpenCVType` trait.

**Comment by twistedfall** [comment]
Thanks! I’ll check it out

**Comment by twistedfall** [comment]
Fixed in 0.45.0
