### ISSUE TITLE
ORB Feature Extraction How do I use it?

### ISSUE THREAD

**Issue by zoain-it** [twistedfall/opencv-rust#146]
I want to implement ORB feature extraction with this library, but he doesn't have documentation and I'm having a hard time doing it.

**Comment by twistedfall** [comment]
Do you have a particular code snippet in another language in mind? Generally the functions and classes in this crate map to C++ 1 to 1 so it should be trivial to translate the code from C++.

**Comment by zoain-it** [comment]
Well, I don't know c++. Guess I'll just have to try it the hard way.

**Comment by twistedfall** [comment]
Well, this crate is just a wrapper around OpenCV, a well known computer vision library written in C++. So if you look for tutorials, you should search for something like “OpenCV orb tutorial” and then adjust the C++ (or often Python) code to Rust.

**Comment by zoain-it** [comment]
Well, I've already let him work now. It's great.
