### ISSUE TITLE
How to clone VectorOfVectorOfPoint2f?

### ISSUE THREAD

**Issue by carbotaniuman** [twistedfall/opencv-rust#147]
Forgive me if I am missing something, but there does not appear to be away way I can clone this type. I've looked for Copy/Clone impls as well as functions, and I can't seem to find anything. My use case is I get a reference to a Vector of contours I want to filter, but I can't make a clone of it.

**Comment by twistedfall** [comment]
You're right, currently clone is not implemented for `Vector`s. There is no particular reason it shouldn't be implemented for vectors of copyable types like `Point2f`, just the lack of attention. For now you'd need to implement a function to clone all values manually, but I'll try to add it in the upcoming releases.

**Comment by carbotaniuman** [comment]
Got it. I'm trying to PR the implementation of some Iterator traits for ease of use, and I'm wondering what the point of

`<T as OpenCVType<'a>>::Arg>` in  `pub fn from_iter<'a>(s: impl IntoIterator<Item=<T as OpenCVType<'a>>::Arg>) -> Self {` is, compared to just `<Item=T>`?

Edit: I just forgot a trait bound.

**Comment by twistedfall** [comment]
Most Vectors store the same type that they accept as argument to push or insert. With the exception of Vector of String, it must accept &str to not require allocation on the caller site. That’s why we need this kind of connection and String::Arg is &str.

**Comment by twistedfall** [comment]
Should be fixed in 0.43.0. I had to update code from your PR, that implementation was only valid for `Copy` types. `Vector<Mat>` or `Vector<Vector<_>>` would only do a shallow copy keeping references to the same objects. It is now fixed.
