### ISSUE TITLE
morphologyEx function not work I try any time no result from this function 

### ISSUE THREAD

**Issue by yuthstyle88** [twistedfall/opencv-rust#149]
morphologyEx function not work I try any time no result from this function

**Comment by twistedfall** [comment]
Can you please post the code that doesn’t work?

**Comment by yuthstyle88** [comment]
let filename = format!("src/{}", "sp.png");

    let mut img = match imread(&filename, IMREAD_COLOR) {
        Ok(ok) => ok,
        Err(error) => {
            panic!("Fatal ERROR reading the image : {}. Is this file exist? Have you the right to read it? Is it empty? . Error : {:?}", filename, error)
        }
    };

let mut img_gray= Mat::default().unwrap();

cvt_color(&img, &mut img_gray, COLOR_BGR2GRAY, 0).unwrap();

 let morph_size = 0;
 let morph_elem = 1;

let  img = img_gray.clone().unwrap();
 let mut dst= Mat::default().unwrap();

let element = get_structuring_element( morph_elem, Size{ width:2*morph_size + 1, height:  2*morph_size+1} ).unwrap();
    morphology_ex( &img, &mut dst, 4, &element ,Point::new(morph_size,morph_size),1,BORDER_CONSTANT,morphology_default_border_value().unwrap());

imshow(" dst ", &dst);
    let _key = wait_key(0);

see data in   "dst" not change  
and these are function 
sort , draw_contours , erode  , dilate  not work 

sort can't sort because  data out put from contours have 2  channels   i input data single  single-channel 



let filename = format!("src/{}", "sp.png");

    let src = match imread(&filename, IMREAD_COLOR) {
        Ok(ok) => ok,
        Err(error) => {
            panic!("Fatal ERROR reading the image : {}. Is this file exist? Have you the right to read it? Is it empty? . Error : {:?}", filename, error)
        }
    };


 let temp = no_array().unwrap();
    let mut dst = VectorOfMat::new();
    //bitwise_not(&src, &mut dst, &temp);
    let zero_offset = Point::new(7, 20);
    let mut vec = VectorOfMat::new();
    let mut gray_img = Mat::default().unwrap();
    cvt_color(&src, &mut gray_img, COLOR_BGR2GRAY, 0).unwrap();
    threshold(&gray_img.clone().unwrap(), &mut gray_img, 50., 255., THRESH_BINARY | THRESH_OTSU);
    //canny(&gray_img,&mut dst,100.,200.,3,false);

    let thres_img = gray_img.clone().unwrap();


    match find_contours(&thres_img, &mut vec, RETR_LIST, CHAIN_APPROX_NONE, zero_offset) {
        Ok(_ok) => {
            println!("[OK] find contours");
        }
        Err(error) => {
            println!("[KO] find contours: {}", error);
        }
    };
    //let sort_img = vec.clone().unwrap();

    // let mut xxx = src.clone().unwrap();
    let mut idx = 0;
    // let maxresult: i32 = 2147483647;
    //let mut hierachy = VectorOfMat::new();
    let mut dst =  Mat::default().unwrap();
    sort(&vec, &mut dst, 0);

**Comment by yuthstyle88** [comment]
https://github.com/yuthstyle88/opencv-rust-recognition-card.git
my project for test card recognition

**Comment by twistedfall** [comment]
As far as I can see you import the function `get_structuring_element` from `ximgproc` module, not `imgproc`. I'm not sure what exactly it does there, but the documentation states: "Returns a run length encoded structuring element of the specified size and shape." which seems to be different from what `imgproc::get_structuring_element` does. I imagine it needs to be paired with `ximgproc::morphology_ex`. You most probably want functions only from `imgproc`. Can you please adjust your imports and see if it fixes the issue?

**Comment by yuthstyle88** [comment]
Yes, i import  it use opencv::ximgproc::get_structuring_element;  
see it on my repository https://github.com/yuthstyle88/opencv-rust-recognition-card.git

**Comment by twistedfall** [comment]
But you are using it with `imgproc::morphology`. You should import `imgproc::get_structuring_element` instead.

**Comment by yuthstyle88** [comment]
thank you!
