### ISSUE TITLE
sort function not work

### ISSUE THREAD

**Issue by yuthstyle88** [twistedfall/opencv-rust#152]
i try to sort contours  

    let filename = format!("src/{}", "sp010.png");
    let src = match imread(&filename, IMREAD_COLOR) {
        Ok(ok) => ok,
        Err(error) => {
            panic!("Fatal ERROR reading the image : {}. Is this file exist? Have you the right to read it? Is it empty? . Error : {:?}", filename, error)
        }
    };
    let temp = no_array().unwrap();
    let mut dst = VectorOfMat::new();
    let zero_offset = Point::new(7, 20);
    let mut vec = VectorOfMat::new();
    let mut gray_img = Mat::default().unwrap();
    cvt_color(&src, &mut gray_img, COLOR_BGR2GRAY, 0).unwrap();
    threshold(&gray_img.clone().unwrap(), &mut gray_img, 50., 255., THRESH_BINARY | THRESH_OTSU);

    let thres_img = gray_img.clone().unwrap();

    match find_contours(&thres_img, &mut vec, RETR_LIST, CHAIN_APPROX_NONE, zero_offset) {
        Ok(_ok) => {
            //  println!("[OK] find contours");
        }
        Err(error) => {
            //   println!("[KO] find contours: {}", error);
        }
    };
    
    sort(&vec, &mut dst, 0);

    for cnt in vec.iter() {

       let area = contour_area(&cnt, false).unwrap();
        
    }

**Comment by twistedfall** [comment]
Are you getting a specific error? Which one? Can you please explain what behavior you expect and what do you see? I also note that you don't check the result of `sort`. It might be returning an error, please do a `sort(&vec, &mut dst, 0).unwrap()` to check that. Also according to the documentation at https://docs.opencv.org/master/d2/de8/group__core__array.html#ga45dd56da289494ce874be2324856898f the `dst` will contain the sorted vector, not `vec` so you might be iterating the wrong array.

**Comment by yuthstyle88** [comment]
it error on this 

sort(&vec, &mut dst, 0).unwrap()

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -215, message: "OpenCV(4.3.0) /tmp/opencv-20200616-49166-1dqpga1/opencv-4.3.0/modules/core/src/matrix_wrap.cpp:88: error: (-215:Assertion failed) 0 <= i && i < (int)v.size() in function \'getMat_\'\n" }', src/main.rs:126:14

**Comment by twistedfall** [comment]
It's coming from within OpenCV, looks like `dst` argument is not sized properly. You should check the documentation link I posted earlier for some more info.

**Comment by yuthstyle88** [comment]
i think incorrect input   parameter for sort function 
  
https://stackoverflow.com/questions/13495207/opencv-c-sorting-contours-by-their-contourarea

**Comment by twistedfall** [comment]
Have you managed to find out the correct arguments?
