### ISSUE TITLE
What's the best way to flatten a `Mat` or a `[Vec3<T>]` into a `Vec<T>` ?

### ISSUE THREAD

**Issue by kahlil29** [twistedfall/opencv-rust#160]
In a previous issue #79 I had asked a similar question: 
I have method that works for this but I feel like it's a sub-optimal way of doing things that's bug/error-prone. I would like to know if there's a better way of doing the equivalent of the following function : 

To clarify, I need it of the form `Vec<>T>` because I create a `Tensor` from it that I feed as input to a Machine Learning model.

- First I call `data_typed` on the `Mat` and type-cast (if that's the correct name for that) it to a `Vec3b` (since that seems to be the correct way to represent a 3-channel image). This gives me a `[Vec3<u8>]`
- Next I loop over this and extract the values of red, green and blue pixels (using `deref`) and accumulate them in 3 different variables and finally append them all together to get my `Vec<u8>` 

```
fn readImgGetMat(imgPath : String) ->Result<Vec<u8>, String>{

    info!("File to be processed {}",imgPath);

    let imgMatrix = match imgcodecs::imread(&imgPath, imgcodecs::IMREAD_COLOR) {
        Ok(imgMatVal) => imgMatVal,
        Err(opencvReadErr) => {
            return Err(format!("Error while reading food image: {}", opencvReadErr))
        }
    };

    let matDataVec= match Mat::data_typed::<Vec3b>(&imgMatrix) {
        Ok(matData) => matData,
        Err(matDataErr) => {
            return Err(format!(
                "Error while transforming img pixels: {}",
                matDataErr
            ))
        }
    };

    // NOTE : OpenCV reads in BGR order by default.

    let pixelCountPerChan = 262144;   // Because we expect the input image to be of dimension 512 x 512 
    let mut redPixels: Vec<u8> = vec![0; pixelCountPerChan];
    let mut greenPixels: Vec<u8> = vec![0; pixelCountPerChan];
    let mut bluePixels: Vec<u8> = vec![0; pixelCountPerChan];


    for i in 0..matDataVec.len() {
        let pixVal: &[u8; 3] = Vec3::deref(&matDataVec[i]);

        redPixels[i] = pixVal[2];
        greenPixels[i] = pixVal[1];
        bluePixels[i] = pixVal[0];
    }
   
    bluePixels.append(&mut greenPixels);
    bluePixels.append(&mut redPixels);

    let allPixels = bluePixels;
  
    return Ok(allPixels);

}
```

Is there something I can do better or some standard function(s) I can use to do this better or in a more optimal/correct manner? 

PS: Excuse my naming of variables (e.g. I have named the red/blue/green components of a pixel as redPixels, etc)

**Comment by twistedfall** [comment]
I'd say that the way you do it is more or less correct. This kind of transformation is non-trivial, so I don't think there is a readily available function for it. What you could do to cut down allocations is to allocate (and fill with zeroes) all of the `allPixel` from the beginning and fill it directly instead of using intermediate arrays.

**Comment by kahlil29** [comment]
Thanks for your advice on this @twistedfall  👍
