### ISSUE TITLE
Fails to link any program using opencv due to multiple missing dependencies

### ISSUE THREAD

**Issue by unjello** [twistedfall/opencv-rust#161]
I am unable to produce a binary using opencv-rust, due to linkage errors as below.

1. Operating system

Windows 10 19041.421

2. The way you installed OpenCV: package, official binary distribution, manual compilation, etc.

`vpkg install opencv[contrib,cuda,dnn,ffmpeg,jpeg,nonfree,opengl,png,tiff,webp]:x64-windows-static-md`

3. OpenCV version

`opencv4:x64-windows-static-md                      4.3.0            computer vision library`

Cuda is also installed as a dependency, automatically by vcpkg:
```
cuda:x64-windows-static-md                         10.1#2           A parallel computing platform and programming model
cudnn:x64-windows-static-md                        7.6#2            NVIDIA's cuDNN deep neural network acceleration ...
```

4. Attach the full output of the following command from your project directory:
There's multiple dependencies missing for cuda, native windows (tls, bcrypt, win32 windows), and in protobuf (dnn component of opencv depends on it) too.

Full log here:
https://gist.github.com/unjello/93b3f7ff8d7ee092e426c98e2a03d2f0

**Comment by twistedfall** [comment]
Hi, I'd like to see the full build log as you get it when you run `cargo build -vv`

**Comment by unjello** [comment]
Hi, thanks for getting back. I've updated the gist to show the full log.

**Comment by twistedfall** [comment]
I think that the last lines of the log are cut out, I can't see the linking error anymore

**Comment by unjello** [comment]
Yes, the gist does truncate the output. Here's the link to full raw (you can find it at the top of initial screen too):
https://gist.githubusercontent.com/unjello/93b3f7ff8d7ee092e426c98e2a03d2f0/raw/8170e475dbd529e02c84a2f0fcc45da8287081ca/gistfile1.txt

**Comment by twistedfall** [comment]
Are you using a nightly compiler? If so which particular version? Can you try with a stable Rust? 1.45.2 that is

**Comment by unjello** [comment]
FWIW, I just dig through docs enough to find `$env:VCPKGRS_DYNAMIC="True"` and when it picks `x64-windows` triplet instead of `x64-windows-static-md` it works. All compiles successfuly.

And I'm using:
```
PS> rustc --version
rustc 1.47.0-nightly (f9d422ea7 2020-08-04)
```

**Comment by twistedfall** [comment]
Ah, I'm going to update the troubleshooting guide with that info, thanks!

**Comment by unjello** [comment]
I am not sure if it's not closed too early. Static linking would me more idiomatic for rust. But that also may be `vcpkg` crate issue.

**Comment by twistedfall** [comment]
Well, for static linking the is a separate issue: https://github.com/twistedfall/opencv-rust/issues/104 but so far I haven't investigated that. It would definitely be good to have such option.
