### ISSUE TITLE
Add padding to an image Mat (with a constant color/value)

### ISSUE THREAD

**Issue by kahlil29** [twistedfall/opencv-rust#174]
This is more of a general question rather than an `OpenCV` specific question, but since I'm using OpenCV to pre-process & resize my image (before & after the padding that I want to do), it would make much more sense for me to try and not convert out of the `Mat`, if possible. 

- I read an image in from file & call some opencv functions on it to process it (gaussian_blur, sharpness, contrast, etc). 
- The next step I want to do is pad (with black color) in order to make the height == width (square shape) before resizing the image. 

Here is the equivalent python code for the same operation : 

```
        #eq_image is the processed image (array?)
        #add padding to image
        h, w = img.shape[:2]
        if h > w:
            diff = h-w
            pad_width = np.floor((diff)/2).astype(np.int)
            if (diff % 2) == 0:
                padded_image= np.pad(eq_image, ((0, 0), (pad_width, pad_width), (0, 0)),
                              'constant', constant_values=0)
            else:
                padded_image= np.pad(eq_image, ((0, 0), (pad_width, pad_width+1), (0, 0)),
                              'constant', constant_values=0)
        elif h < w:
            diff = w-h
            pad_width = np.floor((diff)/2).astype(np.int)
            if (diff % 2) == 0:
                padded_image=  np.pad(eq_image, ((pad_width, pad_width), (0, 0), (0, 0)),
                              'constant', constant_values=0)
            else:
                padded_image= np.pad(eq_image, ((pad_width, pad_width+1), (0, 0), (0, 0)),
                              'constant', constant_values=0)
        else:
            padded_image= eq_image
``` 

In my Rust code, I have a `Mat`, so I wanted to know if there is any inbuilt function I can use to do this padding or, if not, what's the best way to do it myself?

**Comment by twistedfall** [comment]
You should use the [`warp_affine`](https://docs.rs/opencv/0.46.1/opencv/imgproc/fn.warp_affine.html) function.

An example:
```rust
use std::error::Error;

use opencv::{
	core,
	highgui,
	imgcodecs,
	imgproc,
	prelude::*,
};

fn main() -> Result<(), Box<dyn Error>> {
	let img = imgcodecs::imread("src.png", imgcodecs::IMREAD_COLOR)?;
	let src_size = img.size()?;
	let max_side = src_size.width.max(src_size.height);
	let dst_size = core::Size::new(max_side, max_side);
	let mut out = Mat::default()?;
	let m = Mat::from_slice_2d(&[
		[1., 0., (max_side - src_size.width) as f32 / 2.],
		[0., 1., (max_side - src_size.height) as f32 / 2.],
	])?;
	imgproc::warp_affine(&img, &mut out, &m, dst_size, imgproc::INTER_NEAREST, core::BORDER_CONSTANT, core::Scalar_::all(0.))?;
	highgui::imshow("Result", &out)?;
	highgui::wait_key(10000)?;
	Ok(())
}

```

**Comment by kahlil29** [comment]
That's very helpful! Thank you :D

**Comment by kahlil29** [comment]
Hey @twistedfall 
If I had a `GpuMat` instead of a `Mat` as the input, (I'm trying to leverage the GPU to do this work for me, hoping for a performance boost), there is a `opencv::cudawarping::warp_affine` function that I can use. 
However, there doesn't seem to be an equivalent of `from_slice_2d()` for `GpuMat`. 

Any idea if that would be possible? 

Also, side question: Any idea if (the wrapper) `gaussian_blur` for `cudaimgproc` would be possible? i.e. is it in the roadmap or something like that? just curious.

**Comment by twistedfall** [comment]
You don't create `GpuMat` (cuda) and `UMat` (opencl) directly, you first create a `Mat` and then convert it to the corresponding accelerated variant: [`Mat::get_umat()`](https://docs.rs/opencv/0.46.1/opencv/core/prelude/trait.MatTrait.html#method.get_umat) for `UMat` and [`GpuMat::upload()`](https://docs.rs/opencv/0.46.1/opencv/core/prelude/trait.GpuMatTrait.html#method.upload) for `GpuMat`.

Regarding `cudaimgproc::gaussian_blur`, is it implemented in the OpenCV itself? I don't seem to be able to find it in the OpenCV docs, can you point me to the right place?

**Comment by kahlil29** [comment]
I did some digging and it seems like they use a different approach for the cuda version of `gaussian_blur`. 
It seems like they create a filter and then apply it (and it would be located under `cudafilters`). 
Seems like we already have that in `opencv-rust` i.e. `opencv::cudafilters::create_gaussian_filter`. 
I'll try to take a stab at it. It seems straightforward on the outset.

Maybe this answer would be able to give more context: https://stackoverflow.com/questions/26909194/where-are-the-gpu-functions-on-opencv-3-0/26916773#26916773

**Comment by twistedfall** [comment]
You should check this example: https://github.com/twistedfall/opencv-rust/blob/master/examples/cuda.rs it has this functionality.

**Comment by kahlil29** [comment]
Oh that's right! I went through that example but totally missed that step. Thanks a lot 😄
