### ISSUE TITLE
OpenCV 4 with extensions fails to link under Linux

### ISSUE THREAD

**Issue by zalanlevai** [twistedfall/opencv-rust#176]
# Environment

**Operating System**: Linux (Pengwin Linux running under WSL 2)
**OpenCV Installation**: _vcpkg_ under Linux
**OpenCV Version**: 4.3.0
**_rustc_ version**: `rustc 1.47.0 (18bf6b4f0 2020-10-07)` (latest stable)

# Problem

The application builds and runs successfuly with the following base install of OpenCV, installed using `vcpkg` under Linux:
```sh
vcpkg install "opencv4[core,contrib,nonfree]"
```

With the same configuration, the OpenCV install with the following extensions fails to link properly, citing undefined references. This occurs with a clean build of the application as well as with a clean installation of OpenCV.
```sh
vcpkg install "opencv4[core,contrib,nonfree,dnn,ffmpeg,jpeg,opengl,openmp,png,webp]"
```

# Sample Project

<details>
<summary>cargo.toml</summary>

```toml
[package]
name = "hex-vision"
version = "0.1.0"
authors = ["Zalán Bálint Lévai <zalan.levai@gmail.com>"]
edition = "2018"

[dependencies]
opencv = { version = "0.46.1", features = ["opencv-4", "contrib", "buildtime-bindgen"] }
```

</details>

<details>
<summary>src/main.rs</summary>

```rust
#[allow(clippy::all)]

use opencv::prelude::*;
use opencv::videoio::{
    VideoCapture,
    // CAP_FFMPEG,
    // CAP_GSTREAMER,
    CAP_ANY,
};
use opencv::highgui::{
    imshow,
    named_window,
    wait_key,
    // WindowFlags,
    WINDOW_AUTOSIZE,
};

#[derive(Debug)]
enum ControlError {
    InternalError { error: opencv::Error },
    VideoStreamNotOpenError,
    VideoStreamEmptyError,
}

impl From<opencv::Error> for ControlError {
    fn from(error: opencv::Error) -> Self {
        ControlError::InternalError { error }
    }
}

fn run_control() -> Result<(), ControlError> {
    let mut video = VideoCapture::from_file("footage.mp4", CAP_ANY)?;

    if !video.is_opened()? {
        return Err(ControlError::VideoStreamNotOpenError);
    }

    let window = "Camera 0";
    named_window(window, WINDOW_AUTOSIZE)?;

    loop {
        let mut frame = Mat::default()?;
        video.read(&mut frame)?;

        if frame.empty()? {
            return Err(ControlError::VideoStreamEmptyError);
        }

        imshow(window, &frame)?;

        let ch = wait_key(1)?;
        if ch == 27 {
            break;
        }
    }

    Ok(())
}

fn main() {
    run_control().unwrap()
}

```

</details>

# Build Log

[Build Log (`RUST_BACKTRACE=full cargo build -vv` output)](https://pastebin.com/fpjQtdYg)

**Comment by twistedfall** [comment]
When doing static linking on Linux the link argument order becomes critical and vcpkg discovery doesn't seem to get it always right. In your case the cmake discovery (which yields correct argument order) process failed so the crate is falling back to pure vcpkg. So to fix it you have 2 options:
1. Fix cmake discovery, it's currently failing with: `CMake Error at /home/zalanlevai/vcpkg/scripts/buildsystems/vcpkg.cmake:536 (_find_package):\n  Could not find a package configuration file provided by \"OpenMP\" with any\n  of the following names:\n\n    OpenMPConfig.cmake\n    openmp-config.cmake\n\n  Add the installation prefix of \"OpenMP\" to CMAKE_PREFIX_PATH or set\n  \"OpenMP_DIR\" to a directory containing one of the above files`.
2. Use the `OPENCV_LINK_LIBS` environment variable to fix the link argument order. For the specific error you're getting you need to specify OPENCV_LINK_LIBS="+,opencv_core". But you're most likely receive another bunch of linking errors with different symbols so you'll need to add another library to the list and so on until it compiles. If you go this way and get stuck please do post the new linking errors you're getting I will help you in figuring out which library they belong to.

**Comment by twistedfall** [comment]
Have you managed to get it to work?

**Comment by twistedfall** [comment]
I'll assume that you managed to workaround the issue and close this issue, if it's not the case please feel free to reopen it.
