### ISSUE TITLE
How to use moments

### ISSUE THREAD

**Issue by famattsson** [twistedfall/opencv-rust#180]
Hi!

I am trying to convert a vector of points, a contour, into moments, but the documentation seems rather unclear as to how to do this.

I am referring to the `core::Moments` struct ([moments docs](https://docs.rs/opencv/0.5.3/opencv/core/struct.Moments.html)) ([find countours docs](https://docs.rs/opencv/0.8.0/opencv/imgproc/fn.find_contours.html))

**Comment by twistedfall** [comment]
Well, `Moments` is just a simple struct with public fields, so you'd just copy the values from the `Vector` into proper `Moments` fields. As far as I can see in the OpenCV itself it's the same https://docs.opencv.org/master/d8/d23/classcv_1_1Moments.html so there is nothing missing in the bindings in that regard. Can you maybe tell me more about what exactly you are trying to achieve with such a conversion?

**Comment by twistedfall** [comment]
Did you get it to work?

**Comment by famattsson** [comment]
We worked around it by calculating it on our own. Thanks for the help anyway!
