### ISSUE TITLE
Linux running error: (-218:No OpenGL support) Library was built without OpenGL support in function 'cvNamedWindow'

### ISSUE THREAD

**Issue by wisonye** [twistedfall/opencv-rust#183]
After I solved the #182 issue, my project runs fine on **MacOSX**, then I try to build and run on **Linux-mint(x86_64)**  and **Raspberry Pi4 (aarch64)**. Both build successfully but **cannot** run, it shows the error below:

Title             | Description
------------ | ---------
OS                | Linux mint 20 (X86_64)</br>Ubuntu-server 20.04 (aarch64)
Rust version| `rustc 1.48`
OpenCV       | `sudo apt install libopencv-dev`, version is **4.2.0**
Cargo.toml  | `opencv = { version = "0.46", features = ["clang-runtime"] }`
Error             |   **OpenCV(4.2.0) ../modules/highgui/src/window_gtk.cpp:1065: error: (-218:No OpenGL support) Library was built without OpenGL support in function 'cvNamedWindow' (code: -218)**

There is NO any error during the building process, only fail when running.

I also had a try on installing [`XQuartz`](https://www.xquartz.org/) then run `ssh -X` to run the program, got the same error.

As the error mentions about `GTK`, then I remember there is a `WITH_GTK=OFF` option in the `ci` build [script](https://github.com/twistedfall/opencv-rust/blob/master/ci/install-bionic.sh) in this repo like below:

```bash
-D WITH_GTK=OFF
-D WITH_GTK_2_X=OFF
```

Is that the reason to cause the problem???

## How to reproduce

 `Linux Mint 20` clean installation, then install the `opencv` compilation dependencies:

```bash
sudo apt install libopencv-dev libclang-dev build-essential clang
```

Create new rust project

```bash
cargo new opencv-issue-183-test
cd opencv-issue-183-test
```
**`Cargo.toml`**:

```rust
[package]
name = "opencv-issue-183-test"
version = "0.1.0"
authors = ["Wison Ye <wisonye@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = { vesion = "0.46", features = ["clang-runtime"] }
```

**`src/main.rs`**:

```rust
use opencv::{ highgui, imgcodecs };

///
fn main() -> opencv::Result<()> {
    // Pay attention that CANNOT use relative path, otherwise report -215 error
    let test_file = "/home/wison/Downloads/adas-demo-test-resources/images/1.png";

    let window_name = "Test Image Preview";
    let image = imgcodecs::imread(test_file, imgcodecs::IMREAD_COLOR)?;

    let window_flags = highgui::WINDOW_AUTOSIZE
        | highgui::WINDOW_KEEPRATIO
        | highgui::WINDOW_OPENGL // This flag cause -218 error
        | highgui::WINDOW_GUI_NORMAL;
    highgui::named_window(window_name, window_flags)?;

    highgui::imshow(window_name, &image)?;

    let _ = highgui::wait_key(0);
    let _ = highgui::destroy_window(window_name);
    Ok(())
}
```

Then `cargo run` to see the error.

**Comment by twistedfall** [comment]
That’s weird, are you using any OpenGL functionality in your application? Will it be possible for you to crate and share minimum reproducible example for that issue?

**Comment by wisonye** [comment]
> That’s weird, are you using any OpenGL functionality in your application? Will it be possible for you to crate and share minimum reproducible example for that issue?

@twistedfall I've already updated the issue with reproduce steps, plz have a try :)

**Comment by twistedfall** [comment]
I see, and if you omit the `highgui::WINDOW_OPENGL` flag, the application works as expected?

**Comment by wisonye** [comment]
> I see, and if you omit the `highgui::WINDOW_OPENGL` flag, the application works as expected?

Yes, exactly, if you don't think this is a bug related to `opencv` or no fix a this moment, then just close it:)

**Comment by twistedfall** [comment]
Well, it looks like the distro's OpenCV is built without OpenGL support and you explicitly require it with `window_flags`. The fact that you get the error from OpenCV (the C++ library, not the crate) is only logical. I don't really see it as a bug in neither OpenCV lib nor the crate :)
