### ISSUE TITLE
How to use the warp_affine method?

### ISSUE THREAD

**Issue by gmg137** [twistedfall/opencv-rust#184]
Hi, I'm having a problem with the warp_affine function and don't know how to construct M parameters.
```rust
let mut matrix = Mat::zeros(2, 3, core::CV_32F).unwrap();
```
I'm using zeros to create mat, and I can't find a put method on how to insert data into it.

**Comment by twistedfall** [comment]
`Mat::zeros` returns a `MatExpr`, basically an formula to generate a `Mat`. To execute it and get a real `Mat` you need to call [`to_mat()`](https://docs.rs/opencv/0.46.3/opencv/core/prelude/trait.MatExprTrait.html#method.to_mat) on it. After that you will be able to modify it. Another option is to create `Mat` on the spot with:
```rust
let matrix = Mat::from_slice_2d(&[
   &[1., 2., 3.],
   &[4., 5., 6.],
])?;
```

**Comment by gmg137** [comment]
Thank you very much, the problem has been solved.
