### ISSUE TITLE
Install dependencies for Ubuntu 20.04

### ISSUE THREAD

**Issue by IshitaTakeshi** [twistedfall/opencv-rust#186]
When `cargo build` I needed these packages before installation on Ubuntu 20.04

```
sudo apt install llvm  // Install llvm-config command
sudo apt install libclang-10-dev // Fix 'error: failed to run custom build command for `clang-sys v1.0.3`'
sudo apt install clang // Fix 'error: failed to run custom build command for `opencv v0.46.3`'
```

Is it better to add these lines to README?

### 1. Operating system

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

### 2. The way you installed OpenCV: package, official binary distribution, manual compilation, etc.

From apt. I cannot remember the command I used but maybe something like `apt install libopencv-dev`

### 3. OpenCV version

4.2.0

### 4. rustc version (`rustc --version`)

rustc 1.45.2 (d3fb005a3 2020-07-31)

### 5. Attach the full output of the following command from your project directory:
   ```shell script
   RUST_BACKTRACE=full cargo build -vv 
   ```

I have saved the whole log but it's too long to pate here. Sorry

**Comment by twistedfall** [comment]
Well, it is mentioned that you need to have clang/llvm installed, but it can surely be done more explicitly. I'll update the README, thanks!

**Comment by twistedfall** [comment]
I have updated the readme, thanks for the report!
