### ISSUE TITLE
How to set capture resolution

### ISSUE THREAD

**Issue by Jess4Tech** [twistedfall/opencv-rust#192]
How do I set the capture resolution for `opencv::videoio::VideoCapture`? I checked both the source code and the documentation but couldn't find anything on it. I also didn't see any issues on it.

**Comment by twistedfall** [comment]
Quick googling reveals this: https://answers.opencv.org/question/34461/how-to-set-camera-resolution-webcam-with-opencv/

All referenced functionality seems to be there: [set](https://docs.rs/opencv/0.47.0/opencv/videoio/prelude/trait.VideoCaptureTrait.html#method.set) and [CAP_PROP_FRAME_WIDTH](https://docs.rs/opencv/0.47.0/opencv/videoio/constant.CAP_PROP_FRAME_WIDTH.html)

Can you check it out?

**Comment by Jess4Tech** [comment]
I... Didn't even think to check the trait, I'd just been looking on the struct itself. Sorry again for my stupidity!

**Comment by twistedfall** [comment]
No worries, the crate docs in that regard **are** tricky. I'm not really sure how to fix that though, due to how we need to map Rust structs to C++ classes.
