### ISSUE TITLE
unresolved import opencv::dnn::TextDetectionModel_EAST

### ISSUE THREAD

**Issue by flixstn** [twistedfall/opencv-rust#193]
When working with the opencv-rust repository, I encountered the following problem:
I wanted to implement the EAST text detector in Rust but importing the structure results in a compilation error, even though the struct is available in the `dnn module`. Everything else is working perfectly fine.
1. Operating system
    > Linux Manjaro 20.2
2. The way you installed OpenCV: package, official binary distribution, manual compilation, etc.
    > AUR
3. OpenCV version
    > OpenCV 4
4. rustc version (`rustc --version`)
    > rustc 1.48.0 (7eac88abb 2020-11-16)
5. Attach the full output of the following command from your project directory:
   ```shell script
   error[E0432]: unresolved import `opencv::dnn::TextDetectionModel_EAST`
 --> src/main.rs:1:20
  |
1 | use opencv::{dnn::{TextDetectionModel_EAST, read_net}, imgcodecs::{IMREAD_COLOR, imread}};
  |                    ^^^^^^^^^^^^^^^^^^^^^^^ no `TextDetectionModel_EAST` in `dnn`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `east-rust`

Caused by:
  process didn't exit successfully: `CARGO=/home/flix/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo CARGO_BIN_NAME=east-rust CARGO_CRATE_NAME=east_rust CARGO_MANIFEST_DIR=/home/flix/dev/east-rust CARGO_PKG_AUTHORS=flix CARGO_PKG_DESCRIPTION='' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE='' CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=east-rust CARGO_PKG_REPOSITORY='' CARGO_PKG_VERSION=0.1.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' LD_LIBRARY_PATH='/home/flix/dev/east-rust/target/debug/deps:/home/flix/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib:/home/flix/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib' rustc --crate-name east_rust --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=d7b3ccb91ea9b41a -C extra-filename=-d7b3ccb91ea9b41a --out-dir /home/flix/dev/east-rust/target/debug/deps -C incremental=/home/flix/dev/east-rust/target/debug/incremental -L dependency=/home/flix/dev/east-rust/target/debug/deps --extern opencv=/home/flix/dev/east-rust/target/debug/deps/libopencv-3ba241a02552b65c.rlib -L native=/home/flix/dev/east-rust/target/debug/build/opencv-be627d5d2a6aee84/out -L /usr/lib` (exit code: 1)
   ```

**Comment by twistedfall** [comment]
Hi, I would need a detailed build log dump to be able to help further as outlined [here](https://github.com/twistedfall/opencv-rust#reporting-issues). If I would guess it be that your particular OpenCV version doesn't contain this functionality and it's not being generated, but yes, please do provide the full build log.

**Comment by flixstn** [comment]
Hey, here is the full output i got from running `RUST_BACKTRACE=full cargo build -vv`:

       Fresh glob v0.3.0
       Fresh lazy_static v1.4.0
       Fresh regex-syntax v0.6.21
       Fresh percent-encoding v2.1.0
       Fresh once_cell v1.5.2
       Fresh dunce v1.0.1
       Fresh semver-parser v0.7.0
       Fresh autocfg v1.0.1
       Fresh maplit v1.0.2
       Fresh shlex v0.1.1
       Fresh vcpkg v0.2.11
       Fresh pkg-config v0.3.19
       Fresh thread_local v1.0.1
       Fresh semver v0.10.0
       Fresh libc v0.2.81
       Fresh memchr v2.3.4
       Fresh jobserver v0.1.21
       Fresh aho-corasick v0.7.15
       Fresh clang-sys v1.0.3
       Fresh cc v1.0.66
       Fresh num-traits v0.2.14
       Fresh clang v1.0.3
       Fresh regex v1.4.2
       Fresh opencv-binding-generator v0.22.0
       Fresh opencv v0.47.0
   Compiling east-rust v0.1.0 (/home/flix/dev/east-rust)
     Running `CARGO=/home/flix/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo CARGO_BIN_NAME=east-rust CARGO_CRATE_NAME=east_rust CARGO_MANIFEST_DIR=/home/flix/dev/east-rust CARGO_PKG_AUTHORS=flix CARGO_PKG_DESCRIPTION='' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE='' CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=east-rust CARGO_PKG_REPOSITORY='' CARGO_PKG_VERSION=0.1.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' CARGO_PRIMARY_PACKAGE=1 LD_LIBRARY_PATH='/home/flix/dev/east-rust/target/debug/deps:/home/flix/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib:/home/flix/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib' rustc --crate-name east_rust --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=e3e9650df33da9c2 -C extra-filename=-e3e9650df33da9c2 --out-dir /home/flix/dev/east-rust/target/debug/deps -C incremental=/home/flix/dev/east-rust/target/debug/incremental -L dependency=/home/flix/dev/east-rust/target/debug/deps --extern opencv=/home/flix/dev/east-rust/target/debug/deps/libopencv-f08ee54028b052e7.rlib -L native=/home/flix/dev/east-rust/target/debug/build/opencv-14de9ba87fac8c64/out -L /usr/lib/x86_64-linux-gnu`
error[E0432]: unresolved import `opencv::dnn::TextDetectionModel_EAST`
 --> src/main.rs:1:21
  |
1 | use opencv::{Error, dnn::TextDetectionModel_EAST};
  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `TextDetectionModel_EAST` in `dnn`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `east-rust`

Caused by:
  process didn't exit successfully: `CARGO=/home/flix/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo CARGO_BIN_NAME=east-rust CARGO_CRATE_NAME=east_rust CARGO_MANIFEST_DIR=/home/flix/dev/east-rust CARGO_PKG_AUTHORS=flix CARGO_PKG_DESCRIPTION='' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE='' CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=east-rust CARGO_PKG_REPOSITORY='' CARGO_PKG_VERSION=0.1.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' CARGO_PRIMARY_PACKAGE=1 LD_LIBRARY_PATH='/home/flix/dev/east-rust/target/debug/deps:/home/flix/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib:/home/flix/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib' rustc --crate-name east_rust --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=e3e9650df33da9c2 -C extra-filename=-e3e9650df33da9c2 --out-dir /home/flix/dev/east-rust/target/debug/deps -C incremental=/home/flix/dev/east-rust/target/debug/incremental -L dependency=/home/flix/dev/east-rust/target/debug/deps --extern opencv=/home/flix/dev/east-rust/target/debug/deps/libopencv-f08ee54028b052e7.rlib -L native=/home/flix/dev/east-rust/target/debug/build/opencv-14de9ba87fac8c64/out -L /usr/lib/x86_64-linux-gnu` (exit code: 1)

**Comment by twistedfall** [comment]
Can you please do a `cargo clean` and post it again? In your case `opencv` was already built so it didn't produce any output.

**Comment by twistedfall** [comment]
Any luck?

**Comment by flixstn** [comment]
Ok, I tried it several times, even with another Linux distro. Turns out even the C++ examples I found are not working either. But I found a way to implement the algorithm without the use of the dedicated class. 
I guess the issue can be closed, thank you for your help!

**Comment by twistedfall** [comment]
Glad to help!

**Comment by onelson** [comment]
I'm seeing the same thing while trying to run the text detection example. I'm running ubuntu 20.04, with opencv 4.2 (installed via apt).

Not sure what the story is, but the dnn module produced locally is quite a bit shorter than the one I see hosted with the docs on docs.rs. Wondering if I need to do something special to get the bindgen to run for this feature.

**Comment by twistedfall** [comment]
The current text detection example will only work with OpenCV 4.5.1+, so this is expected. I will update it with the comment about that restriction.

**Comment by onelson** [comment]
Ah, good to know! I'll get myself updated :+1:

**Comment by twistedfall** [comment]
Just don't update to OpenCV 4.5.2 just yet, it's broken atm
