### ISSUE TITLE
Failure to Build on Windows 10

### ISSUE THREAD

**Issue by hntd187** [twistedfall/opencv-rust#194]
Before reporting an issue please first check the
[troubleshooting guide](https://github.com/twistedfall/opencv-rust/blob/master/README.md#troubleshooting). If
the issue you're encountering is not solved thereby please state the following in your bugreport:
1. Operating system Windows 10
2. The way you installed OpenCV: package, official binary distribution, manual compilation, etc. official binary distro
3. OpenCV version 4.5.1
4. rustc version (`rustc --version`) 1.49.0
5. Attach the full output of the following command from your project directory:
   ```shell script
   RUST_BACKTRACE=full cargo build -vv 
   ```
https://pastebin.com/raw/hSVMRSxK

Here is my log. 

```toml
[dependencies]
opencv = { version = "0.47", features = ["opencv-4", "contrib", "buildtime-bindgen", "clang-runtime" ] }
```

```
LIBCLANG_PATH=C:\Program Files\LLVM\bin\libclang.dll;
CLANG_PATH=C:\Program Files\LLVM\bin\clang.exe;
OPENCV_INCLUDE_PATHS=C:\Users\shcar\Downloads\opencv\build\include;
OPENCV_LINK_LIBS=opencv_world451;
OPENCV_LINK_PATHS=C:\Users\shcar\Downloads\opencv\build\x64\vc15\bin,C:\Users\shcar\Downloads\opencv\build\x64\vc15\lib
```

I'm at a lost to understand what I'm doing wrong here. It's also not clear to me what features to use and why I use them or if the order they are provided in matters. I should also mention my binary does not build at all, the build fails before I get any linking issues with the crate.

**Comment by twistedfall** [comment]
The log doesn’t mention the error that happened for some reason, can you please enable the `RUST_BACKTRACE=full` environment variable and try `cargo build -vv` again?

Regarding the feature flags: your features are fine, just “opencv-4” and “ buildtime-bindgen” are enabled by default so you can omit them (unless you also specify default-features = false). The order doesn’t matter.

You can also try to remove the “clang-runtime” to see if it helps with the build. Or you might get a more sensible error message at least.

**Comment by hntd187** [comment]
If I remove clang-runtime I get 

```
error: failed to run custom build command for `opencv v0.47.0`
Caused by:
  process didn't exit successfully: `C:\Users\shcar\IdeaProjects\drink-bot\homebase\target\debug\build\opencv-ce31f12c638a59d6\build-script-build` (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)
```

Which other issues seem to imply that I should move the dll to the same folder but the binary doesn't even build so I don't think that would be the answer here.

**Comment by twistedfall** [comment]
Quite the opposite, that really explains what's happening. Windows can't find `libclang.dll` to run the binary (the build script in this case). You need to update the system `PATH` with the path where this library is located. The exact path depends on how LLVM was installed, but if you installed it via chocolatey it can be `C:\Program Files\LLVM\bin`. You can check [this line](https://github.com/twistedfall/opencv-rust/blob/master/ci/script.sh#L6) in the CI script for the more specific instructions.

**Comment by hntd187** [comment]
Incredible, no idea how I totally missed this. Awesome, thanks!
