### ISSUE TITLE
Mat creation with given data

### ISSUE THREAD

**Issue by riomus** [twistedfall/opencv-rust#20]
How can i create Mat with given data? Currently there is no method for that.

**Comment by Kibouo** [comment]
Were you able to resolve this? If yes, how?

**Comment by riomus** [comment]
Unfortunately, I had to resign from the usage of opencv-rust because of lack of many methods. I used unsafe calls to some wrappers of C api.

**Comment by twistedfall** [comment]
It's not pretty, but this would work:

```rust
pub fn mat2d_get<T>(mat: &mut Mat, row: i32, col: i32) -> Result<&mut T> {
	unsafe {
		mat.ptr(row, col)
			.map_err(|e| e.into())
			.and_then(|x| (x as *mut T).as_mut().ok_or_else(|| format_err!("Got null pointer")))
	}
}

fn vec2d_to_mat_f32(s: &[impl AsRef<[f32]>]) -> Result<Mat> {
	let row_count: i32 = s.len() as _;
	let col_count: i32 = if row_count > 0 {
		s[0].as_ref().len() as _
	} else {
		0
	};
	let mut out = Mat::new_rows_cols(row_count, col_count, core::CV_32F)?;
	for (row_n, row) in s.into_iter().enumerate() {
		for (col_n, val) in row.as_ref().into_iter().enumerate() {
			*mat2d_get(&mut out, row_n as _, col_n as _)? = *val;
		}
	}
	Ok(out)
}
```

**Comment by Kibouo** [comment]
Thanks a lot @twistedfall ! This was the only thing holding me back from using the library.

Maybe we gotta look at a way to make a generic, baked-in function of this?

**Comment by twistedfall** [comment]
And way more efficient too, copying element by element with Result for each of them is not very performant. If you can give a shot in it, PRs are always welcome, I'll try to look into it as time allows.

**Comment by twistedfall** [comment]
In version 0.5.0 there is now `Mat::from_slice`/`Mat::from_slice_2d` with more efficient data insertion
