### ISSUE TITLE
Questions regarding this crate

### ISSUE THREAD

**Issue by Joe23232** [twistedfall/opencv-rust#202]
Hi, I have some questions regarding this crate.

1. In regards to comparison between Python and Rust in terms of ease of use

![image](https://user-images.githubusercontent.com/34926497/105653488-0d2b7780-5f10-11eb-8a80-cd061f1ed1c3.png)

If I wanted to simply import an image and show an image (this image is from an [opencv Python tutorial from YouTube](https://youtu.be/oXlwWbU8l2o?t=390), if I were to write the same logic in Rust using the `opencv-rust` crate, would it be written in a similar fashion or would it be a lot more complicated the code? If it is written in the same logic, may I have an example of how would it be written please?

2. Would the APIs change over time?

**Comment by twistedfall** [comment]
Hi!
1. The api is more or less similar. It’s actually almost identical to the C++ one (with some adaptations). So do expect some deviation from what you have in Python, but most programs can be ported to Rust trivially. The corresponding example is https://github.com/twistedfall/opencv-rust/blob/master/examples/window.rs
2. The API is still subject to change. Mostly it’s coming from adjusting function names and their arguments to fit Rust better.

**Comment by Joe23232** [comment]
> The corresponding example is https://github.com/twistedfall/opencv-rust/blob/master/examples/window.rs

Surprisingly it's not too bad. I am quite impressed given how other crates tend to be just messy af.

> The API is still subject to change. Mostly it’s coming from adjusting function names and their arguments to fit Rust better.


I see, thanks mate :) But will there be dramatic changes by any chance?

**Comment by twistedfall** [comment]
I don't expect any dramatic changes, just incremental improvements, so any breaking update shouldn't require much time to adjust.

**Comment by Joe23232** [comment]
I see, thanks mate
