### ISSUE TITLE
Unable to build only core & imgproc modules

### ISSUE THREAD

**Issue by nsabovic** [twistedfall/opencv-rust#203]
I am trying to compile opencv-rust on macOS with just core and imgproc modules by doing:

```bash
export OPENCV_MODULE_WHITELIST=core,imgproc
```

I am on macOS Big Sur, using Rust nightly with opencv installed from Homebrew:

```bash
> uname -v
Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64

> rustc --version
rustc 1.51.0-nightly (1d0d76f8d 2021-01-24)

> brew info opencv
opencv: stable 4.5.1 (bottled)
```

Seems like not including `dnn` and `features2d` is not optional:

```
error[E0432]: unresolved import `crate::dnn`
 --> /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.48.0/src/manual/dnn.rs:7:2
  |
7 |     dnn::{DictValue, LayerParams},
  |     ^^^
  |     |
  |     unresolved import
  |     help: a similar path exists: `crate::manual::dnn`

error[E0432]: unresolved import `crate::features2d`
 --> /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.48.0/src/manual/features2d.rs:5:2
  |
5 |     features2d::ORB,
  |     ^^^^^^^^^^
  |     |
  |     unresolved import
  |     help: a similar path exists: `crate::manual::features2d`

error[E0433]: failed to resolve: could not find `PtrOfORB` in `types`
  --> /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.48.0/src/manual/features2d.rs:14:70
   |
14 |         unsafe { cv_ORB_create() }.into_result().map(|ptr| unsafe { types::PtrOfORB::from_raw(ptr) })
   |                                                                            ^^^^^^^^ could not find `PtrOfORB` in `types`

error[E0412]: cannot find type `PtrOfORB` in module `types`
  --> /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.48.0/src/manual/features2d.rs:12:36
   |
12 |     pub fn default() -> Result<types::PtrOfORB> {
   |                                       ^^^^^^^^ not found in `types`

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0412, E0432, E0433.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `opencv`
```

The minimal list of modules that compiles is:

```bash
export OPENCV_MODULE_WHITELIST=core,imgproc,dnn,features2d,flann
```

**Comment by twistedfall** [comment]
Yes, you're right, there are some manual implementations for those modules you mentioned. I need to think about how to fix that, it looks like you can only exclude those with `cfg` blocks, but I'd like to avoid having a separate feature for every module.

**Comment by nsabovic** [comment]
Coming back to this, I see that majority of my problems come from compiling dnn so now I *really* need this functionality.

Without touching the features, I can modify build.rs to [emit configuration options](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-cfg) for each module, say `module-dnn` when dnn is enabled, and then just use `#[cfg(module-dnn)]`. This will avoid having any features for modules. But I'm not familiar enough to know what I have to disable in the rest of the code.

**Comment by twistedfall** [comment]
This is a good idea, I'll try to add this asap.

**Comment by twistedfall** [comment]
Will you please check the `rel` branch? It should fix the problems you're experiencing.

**Comment by nsabovic** [comment]
@twistedfall thank you so much, that fixed everything! Now I can compile just core & imgproc. I get one warning only:
```
warning: unused macro definition
  --> /Users/nsabovic/projects/oss/opencv-rust/src/templ.rs:86:1
   |
86 | / macro_rules! string_array_arg_mut {
87 | |     ($name: ident) => {
88 | |         let mut $name = $name.iter().map(|x| x.as_ptr() as _).collect::<Vec<_>>();
89 | |     };
90 | | }
   | |_^
   |
   = note: `#[warn(unused_macros)]` on by default
```

but everything works. Thank you again!

**Comment by twistedfall** [comment]
Glad to hear! I'd say that such warnings are expected with some module combinations. I'll release the fixed version as soon as I sort out the CI breakage.

**Comment by twistedfall** [comment]
0.52.0 released
