### ISSUE TITLE
Converting Mat_<T> into &Mat/ToInputArray?

### ISSUE THREAD

**Issue by nemosupremo** [twistedfall/opencv-rust#206]
I'm not sure if this an oversight with the API, but `Mat_<T>` seems kind of useless when trying to also interact with the rest of library. My use case is I prefer to work with [rust-ndarray/ndarray](https://github.com/rust-ndarray/ndarray), which I use `data_typed()` to provide a view for `ndarray`. However when I want to use the `Mat` in an opencv function I can't pass a reference. This makes it difficult to use `Mat_<T>` in struct fields, as I always need to do `std::mem::take` (and always ensure to put it back when I'm done) or use the unsafe `new_nd_with_data` or `mat.row_bounds(0, mat.rows())`.

**Comment by twistedfall** [comment]
Hi, it is indeed an oversight, the `Mat_` can't be generated automatically (at least not yet, until we can generate template classes reliably) so it's implemented completely by hand. I'll try to fix it asap, thanks for the report!

**Comment by twistedfall** [comment]
Actually, do you mind checking `master` to see if it works for you? For now I can only semi-safely implement unmutable access (so only `ToInputArray`) otherwise the element type of the underlying mat can be changed which will lead to mismatch between the generic type for `Mat_` and the type of the `Mat` it wraps.

**Comment by nemosupremo** [comment]
It works for half of my use cases - I also wanted to be able to use `Mat::roi`, which takes `&Mat`. However the more I work with it, the more I realize how difficult `Mat` is to work with in Rust. I've hit a couple bugs where I managed to have multiple mutable references to the same underlying data in "safe" Rust. 

Thanks for your quick response however.

**Comment by twistedfall** [comment]
Can you tell me more about those bugs you encountered? Maybe there is a way to make that usage more robust.

**Comment by nemosupremo** [comment]
I'm not sure if the issue is with opencv or the library; but it's hard to understand how things are allocated with C++ "retval" pattern, and opencv use of function overloading that doesn't translate well to Rust. The issue I was hitting was like so:

```rust
//
pub struct Example {
    net: opencv::dnn::Net,
    names: opencv::core::Vector<String>,
}
//

let mut output = Vector::<Mat>::new();
let r = self
                .net
                .set_input(&blobs, "", 1., opencv::core::Scalar::default())
                .map_err(Error::from)
                .and_then(|_| Ok(self.net.forward(&mut output, &self.names)?));
let output = output.get(0).unwrap();
```

What I would expect here is for `Mat` here to point to be a newly allocated `Mat`, that I could then do whatever I wanted. What I discovered is that successive runs to `forward` actually return a `Mat` referencing the same data. In Rust terms, I was actually getting `&Mat`, not a `Mat`, meaning I would have to clone the Mat if I wanted to own it.

Unfortunately the opencv documentation doesn't seem to make this clear and/or has different semantics (ex. there is a definition of `forward` that returns a Mat).

**Comment by twistedfall** [comment]
I see. I’ll try to reproduce that, but yeah, most probably it’s not fixable in an automated manner at this moment (or at all?).
