### ISSUE TITLE
The imported image becomes squashed when displaying it and it is displayed in black and white

### ISSUE THREAD

**Issue by Joe23232** [twistedfall/opencv-rust#209]
Hi, the image that I am importing becomes squashed when importing it as well as it becomes black and white.

This is how it looks like when being displayed without using `opencv-rust`:

![cat](https://user-images.githubusercontent.com/34926497/107134407-db6dd400-6945-11eb-9377-6a88c63be578.jpg)

This is how it is being displayed _when_ using `opencv-rust`

![image](https://user-images.githubusercontent.com/34926497/107134421-048e6480-6946-11eb-8e6a-af0f7bce9d75.png)

The resolution for the image file is `640` x `427`.

I am following this [tutorial](https://youtu.be/oXlwWbU8l2o?t=392)

![image](https://user-images.githubusercontent.com/34926497/107134446-43bcb580-6946-11eb-9b64-e7bd5d6cce36.png)

Here is my source code:

```rust
extern crate opencv;
//use opencv::prelude::*;

use opencv::highgui;
use opencv::imgcodecs;

#[allow(dead_code)]
fn main()
{
    let image = imgcodecs::imread(r"opencv-course\Resources\Photos\cat.jpg", 0).unwrap();
    highgui::named_window("hello opencv!", 0).unwrap();
    highgui::imshow("hello opencv!", &image).unwrap();
    highgui::wait_key(10000).unwrap();
}
```

**Comment by twistedfall** [comment]
You are not passing any flags to `imread` (just 0), that’s probably why.

**Comment by Joe23232** [comment]
> You are not passing any flags to `imread` (just 0), that’s probably why.

What flags am I supposed to pass?

**Comment by twistedfall** [comment]
Depends on the representation of pixels in the resulting `Mat` you want to achieve. You should read the documentation for OpenCV library: https://docs.opencv.org/4.5.1/ it has some tutorials too. Usually translating those C++ and Python tutorials to Rust is trivial.

**Comment by Joe23232** [comment]
@twistedfall 

> You should read the documentation for OpenCV library: https://docs.opencv.org/4.5.1/ it has some tutorials too.

I am not too sure where to find how to import image files.

>Depends on the representation of pixels in the resulting Mat you want to achieve.

`let image = imgcodecs::imread(r"opencv-course\Resources\Photos\cat.jpg", 0).unwrap();` so I replace `0` with a flag, what do I put as a replacement mate?

**Comment by Joe23232** [comment]
@twistedfall Hey man, the tutorials for opencv C++ does not have the flag specification in `imread()`.

![image](https://user-images.githubusercontent.com/34926497/107180206-5d382d00-6a2c-11eb-930c-876a53f8af21.png)


Take a look at this [video](https://www.youtube.com/watch?v=2FYm3GOonhk&t=1723s).

I have taken look at the [opencv docs](https://docs.rs/opencv/0.49.1/opencv/imgcodecs/fn.imread.html) but the docs fails to specify what `i32` number I should pass in the argument of `opencv::imgcodecs::imread()` function. What number should I pass if you happen to know?

**Comment by twistedfall** [comment]
The default argument values are documented under “C++ default parameters”, in this case it says:
```
flags: IMREAD_COLOR
```
https://docs.rs/opencv/0.49.1/opencv/imgcodecs/constant.IMREAD_COLOR.html

**Comment by Joe23232** [comment]
![image](https://user-images.githubusercontent.com/34926497/107186777-fff6a880-6a38-11eb-90a6-aa14d491cb40.png)

It is better but the image is coming out as squashed, here is the code I am using:

```rust
extern crate opencv;
//use opencv::prelude::*;

use opencv::highgui;
use opencv::imgcodecs;

#[allow(dead_code)]
fn main()
{
    let image = imgcodecs::imread(r"opencv-course\Resources\Photos\cat.jpg", 1).unwrap();
    highgui::named_window("hello opencv!", 0).unwrap();
    highgui::imshow("hello opencv!", &image).unwrap();
    highgui::wait_key(10000).unwrap();
}
```

**Comment by twistedfall** [comment]
Same thing with `named_window`, you are passing 0, which probably means not what you want

**Comment by Joe23232** [comment]
Seems to work now, thanks :)

So what does `1` mean and what does `0` mean when passing it as a flag?

---

I know I am going off topic but like does `opencv` use GPU acceleration?

**Comment by twistedfall** [comment]
You shouldn't be passing raw numbers there, the flags that are accepted are described in the documentation: https://docs.rs/opencv/0.49.1/opencv/highgui/fn.named_window.html

OpenCV supports GPU acceleration given that you enable them during the compilation. This crate exposes support for both CUDA and OpenCL

**Comment by Joe23232** [comment]
Ah I see, thanks mate :)

> OpenCV supports GPU acceleration given that you enable them during the compilation. This crate exposes support for both CUDA and OpenCL

How would I enable this mate?

**Comment by twistedfall** [comment]
I suggest you do a google search for something like "opencv enable cuda" or "opencv enable opencl". Don't get me wrong, I'm ready to provide support for the crate, but for support on the OpenCV itself it's better to refer to specialized channels like OpenCV forums or Stackoverflow.

**Comment by Joe23232** [comment]
Ah right thanks mate
