### ISSUE TITLE
How do I display videos?

### ISSUE THREAD

**Issue by Joe23232** [twistedfall/opencv-rust#210]
![image](https://user-images.githubusercontent.com/34926497/107317732-53c3c900-6aef-11eb-985b-f731663de1c9.png)

In the python [tutorial](https://youtu.be/oXlwWbU8l2o?t=701) it shows to use `cv.VideoCapture('Videos/dog.mp4)`.

I have tried to search for `videocapture` in the [docs](https://docs.rs/opencv/0.49.1/opencv/videoio/enum.VideoCaptureAPIs.html?search=videocapture) but I couldn't quite find it. Apparently `opencv::videoio::VideoCapture` is a `Struct`.

Is it by any chance `pub fn as_raw_VideoCapture(&self)`?

**Comment by twistedfall** [comment]
You need to call one of the new methods on it, see example: https://github.com/twistedfall/opencv-rust/blob/master/examples/video_capture.rs

**Comment by Joe23232** [comment]
What if I wanted to just capture a video file, not from a camera. Maybe I am missing something from the example? I am sorry I am kinda new so maybe I am not understanding something?

**Comment by twistedfall** [comment]
You are probably looking for that method: https://docs.rs/opencv/0.49.1/opencv/videoio/struct.VideoCapture.html#method.from_file

**Comment by Joe23232** [comment]
Thanks mate
