### ISSUE TITLE
Unsupported depth! Only CV_8U is supported for NORM_L2 in function \'cv::fastNlMeansDenoising\'\n" }'

### ISSUE THREAD

**Issue by CarbonPool** [twistedfall/opencv-rust#212]
Read a 16bit image for noise reduction.

`
use opencv::{imgcodecs, imgproc, photo};
use opencv::core::{self, Vector, CV_16U, Size, MatTrait};
use opencv::types::{VectorOfMat};
use std::fs;
use std::path;
use std::io::prelude::*;

fn main() {
    let input = "C:\\Users\\GM-PROJIN\\Desktop\\test1";
    let output = "C:\\Users\\GM-PROJIN\\Desktop\\test2\\";
    for entry in fs::read_dir(input).unwrap() {
        let file_path = entry.unwrap().path();
        // let file_name = file_path.file_stem().unwrap().to_str().unwrap();
        let file = fs::read(&file_path).unwrap();
        // let write_path = output.to_string() + file_name + ".png";
        let vector: Vector<u8>  = Vector::from_iter(file);
        let img = imgcodecs::imdecode(&vector, -1).unwrap();
        let mut img2 = core::Mat::default().unwrap();
        photo::fast_nl_means_denoising(&img, &mut img2, 1.1, 7, 32).unwrap();
        println!("{:?}", img2);
    }
}

`

**Comment by twistedfall** [comment]
Well, the error message pretty much explains it so you can't use NORM_L2 with Mat that contains something other than just plain 1-channel u8. You should try importing the image as grayscale in `imdecode` (btw you can use `imread` to read the image directly from disk without reading it into memory first). Just to note: this error comes from the OpenCV itself, not the Rust bindings crate so in this case you might get more support in the general OpenCV support channels.

**Comment by CarbonPool** [comment]
> Well, the error message pretty much explains it so you can't use NORM_L2 with Mat that contains something other than just plain 1-channel u8. You should try importing the image as grayscale in `imdecode` (btw you can use `imread` to read the image directly from disk without reading it into memory first). Just to note: this error comes from the OpenCV itself, not the Rust bindings crate so in this case you might get more support in the general OpenCV support channels.

For color images, I can’t perform grayscale conversion. I did not find a solution, but I can use `IMREAD_COLOR` to read and convert. It seems that the `imread` function does not support paths containing special coded characters, so I read it into memory for decoding. I am not sure if there are other solutions.

**Comment by twistedfall** [comment]
Have you managed to solve the issue?

**Comment by CarbonPool** [comment]
> Have you managed to solve the issue?

Unfortunately, I have not found a solution at present. It seems that this function does not support 16bit images in the current version of opencv, but it can be read and processed as 8bit images, which will cause color loss.

**Comment by twistedfall** [comment]
I see, well, this is the limitation of the OpenCV and the Rust bindings can't fix that, so I'm going to close this issue.
