### ISSUE TITLE
Example with Github Action CI

### ISSUE THREAD

**Issue by hediet** [twistedfall/opencv-rust#219]
Thanks for creating/maintaining this crate!

Is there an example/demo rust app that uses this crate and has a github action CI setup, ideally targeting each Windows, Linux and Mac?

I got my rust opencv app working on Windows, but no clue how to distribute it or how to build releases for mac and Linux.
I would really appreciate a demo repository with working CI for all platforms!

**Comment by twistedfall** [comment]
Well, there is the Github Actions CI for the crate itself: https://github.com/twistedfall/opencv-rust/tree/master/.github/workflows, https://github.com/twistedfall/opencv-rust/tree/master/ci. It will give you working OpenCV installation for Linux/Windows/macos so it should be pretty easy to take it from there.

There are also crates that depend on opencv: https://crates.io/crates/opencv/reverse_dependencies Some of them might be using Github Actions so you can use their setup as a start.

**Comment by hediet** [comment]
Thanks for your super quick reply!
I guess your `src` job is the only one that I need?
How long did it take you to configure all this?

None of the reverse dependencies uses CI, I guess for obvious reasons ;)

**Comment by twistedfall** [comment]
> I guess your src job is the only one that I need?

Well, it depends. The `src` job is the one that builds OpenCV from sources, some jobs are using pre-built binaries which is way faster.

> How long did it take you to configure all this?

It would be really difficult to estimate this now, I was improving it over time + initial setup was ported from travis so it wasn't completely from scratch.

**Comment by hediet** [comment]
May I ask why you excluded `opencv-4` from linux [here](https://github.com/twistedfall/opencv-rust/blob/master/.github/workflows/opencv-rust.yml#L162)?

Thanks!

**Comment by twistedfall** [comment]
That's because there is no official binary OpenCV 4 for Ubuntu 18.04 as far as I know

**Comment by hediet** [comment]
After a lot of trial and error, I managed to create an example repository [here](https://github.com/hediet/rust-opencv-demo).

Btw., building from source is actually very fast with caching (and the cache usually always hits).

I don't know how to distribute the linux build though. Would be nice if opencv could be linked statically.

**Comment by eadf** [comment]
For anyone interested, i got a recent github workflow CI example for rust 2024 and opencv 4.11.0  [here](https://github.com/eadf/libstacker.rs/blob/f78d6dc7f4459d2958a0f0354e6cccc90449aa67/.github/workflows/rust.yml#L1)
