### ISSUE TITLE
Api docs appear to be down.

### ISSUE THREAD

**Issue by BenTheElder** [twistedfall/opencv-rust#22]
The [main page ](http://www.poumeyrol.fr/doc/opencv-rust/opencv/index.html) is up but all of the module links eg [video](http://www.poumeyrol.fr/doc/opencv-rust/opencv/video/index.html) appear to be dead.

This may be related to: https://github.com/rust-lang/rust/issues/34025
A possible work around would be generating the docs with rust `1.8.0` if this is the case.

**Comment by virtigo** [comment]
Seconded, they're 404ing. Is there any other way to view the documentation? I'm new to Rust so it would be much appreciated

**Comment by BenTheElder** [comment]
If you clone the repository you can CD to it and run `cargo doc --open`.
You'll need rust 1.8 or maybe a recent nightly though due to the bug
mentioned above.
On Jun 11, 2016 3:20 PM, "Stephan Lensky" <notifications@github.com> wrote:

Seconded, they're 404ing. Is there any other way to view the documentation?
I'm new to Rust so it would be much appreciated

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kali/opencv-rust/issues/22#issuecomment-225388586>, or mute
the thread
<https://github.com/notifications/unsubscribe/AA4Bq9SJnNaDtKB6nreqGwR-mkxSwPqhks5qKwqEgaJpZM4Isvdv>
.

**Comment by kali** [comment]
i'm trying a travis build with 1.8 to get the doc. It's building right now.

**Comment by kali** [comment]
and it worked !

Leaving the issue open for when we will be able to switch the doc building back to stable.

**Comment by twistedfall** [comment]
Docs are now available at https://docs.rs/opencv/

**Comment by theduke** [comment]
Docs are down again: `docs.rs failed to build opencv-0.15.1`

**Comment by twistedfall** [comment]
Yep, I’m looking into it, thanks.

**Comment by twistedfall** [comment]
Fixed now
