### ISSUE TITLE
How to save video from (stabilized ) frames?

### ISSUE THREAD

**Issue by chanble** [twistedfall/opencv-rust#220]
c++ can do like this:

```cpp
Ptr<IFrameSource> stabFrames;
stabFrames.reset(dynamic_cast<IFrameSource*>(onePassStabilizer));
```
But IFrameSource's reset method have not expected parameter.

**Comment by twistedfall** [comment]
As far as I can see, the `reset` method doesn't accept any arguments: https://docs.opencv.org/4.5.1/d1/d81/classcv_1_1videostab_1_1IFrameSource.html#a4aca86a6810f2330f4934db4dce65822 Does that C++ code substitute `this` with `dynamic_cast<IFrameSource*>(onePassStabilizer)` in this case? Is it any different than calling `dynamic_cast<IFrameSource*>(onePassStabilizer).reset()`? Maybe just calling `onePassStabilizer.reset()` is what you looking for?

**Comment by chanble** [comment]
Sorry , the code is for old opencv version(may be 2.x).  It do not work on `onePassStabilizer.reset()`, I close issue and try to other solution. Thanks.

**Comment by chanble** [comment]
I get it, trait `IFrameSource` and `OnePassStabilizerTrait` are have reset method. I use `OnePassStabilizerTrait::reset(&mut onePassStabilizer)`. It works.

**Comment by twistedfall** [comment]
You should just call `onePassStabilizer.reset()`, it's doing the same, but in a more convenient and concise form. What kind of problem do you have with this type of call?

**Comment by chanble** [comment]
```multiple `reset` found``` error occurred because of two trait(IFrameSource and OnePassStabilizerTrait) be use.

**Comment by twistedfall** [comment]
I see now, yes, your solution is the best in this case

**Comment by chanble** [comment]
Yes, Thanks
