### ISSUE TITLE
Confusion about signature for `opencv::imgproc::calc_hist`

### ISSUE THREAD

**Issue by onelson** [twistedfall/opencv-rust#223]
```rust
pub fn calc_hist(
    images: &dyn ToInputArray, 
    channels: &Vector<i32>, // !! Only seems to accept a single value
    mask: &dyn ToInputArray, 
    hist: &mut dyn ToOutputArray, 
    hist_size: &Vector<i32>, 
    ranges: &Vector<f32>, // !! Should be Vector of Vector of f32 
    accumulate: bool
) -> Result<()>
```

Looking at the docs on the C++ side, 
https://docs.opencv.org/4.5.1/d6/dc7/group__imgproc__hist.html#ga4b2b5fd75503ff9e6844cc4dcdaed35d

They show using multiple channels, and a pair of f32 *per channel* to use as the min/max for the ranges.

When I pass a `channels` param with a length greater than 1, the function fails with:

```
Error { code: -215, message: "OpenCV(4.5.1) /home/owen/projects/opencv/modules/imgproc/src/histogram.cpp:1293: error: (-215:Assertion failed) csz == 0 || csz == dims in function \'calcHist\'\n" }
```

Based on the type for the `ranges` param, it's not possible to express different ranges per channel.

**Comment by twistedfall** [comment]
Looking at the function [source](https://github.com/opencv/opencv/blob/4.5.2/modules/imgproc/src/histogram.cpp#L1274) I can see that the types for `channels` and `ranges` in the bindings seem ok. Judging by that assert for `channels` it expects either an empty `Vector` or a `Vector` of the same length as `hist`. And for `ranges` it expects a `Vector` twice as long as `hist` and it looks like it's storing 2 elements per 1 element of `hist`, likely start/end. If that doesn't help, can you please provide a source code that you expect to work, but it doesn't? It would be really helpful if you could also provide the corresponding C++ code that works and does what you need.

**Comment by onelson** [comment]
I was trying to follow along with this tutorial in the opencv docs.
https://docs.opencv.org/4.5.1/d8/dc8/tutorial_histogram_comparison.html

```C++
#include "opencv2/imgcodecs.hpp"
#include "opencv2/highgui.hpp"
#include "opencv2/imgproc.hpp"
#include <iostream>
using namespace std;
using namespace cv;
const char* keys =
    "{ help  h| | Print help message. }"
    "{ @input1 | | Path to input image 1. }"
    "{ @input2 | | Path to input image 2. }"
    "{ @input3 | | Path to input image 3. }";
int main( int argc, char** argv )
{
    CommandLineParser parser( argc, argv, keys );
    Mat src_base = imread( parser.get<String>("input1") );
    Mat src_test1 = imread( parser.get<String>("input2") );
    Mat src_test2 = imread( parser.get<String>("input3") );
    if( src_base.empty() || src_test1.empty() || src_test2.empty() )
    {
        cout << "Could not open or find the images!\n" << endl;
        parser.printMessage();
        return -1;
    }
    Mat hsv_base, hsv_test1, hsv_test2;
    cvtColor( src_base, hsv_base, COLOR_BGR2HSV );
    cvtColor( src_test1, hsv_test1, COLOR_BGR2HSV );
    cvtColor( src_test2, hsv_test2, COLOR_BGR2HSV );
    Mat hsv_half_down = hsv_base( Range( hsv_base.rows/2, hsv_base.rows ), Range( 0, hsv_base.cols ) );
    int h_bins = 50, s_bins = 60;
    int histSize[] = { h_bins, s_bins };
    // hue varies from 0 to 179, saturation from 0 to 255
    float h_ranges[] = { 0, 180 };
    float s_ranges[] = { 0, 256 };
    const float* ranges[] = { h_ranges, s_ranges };
    // Use the 0-th and 1-st channels
    int channels[] = { 0, 1 };
    Mat hist_base, hist_half_down, hist_test1, hist_test2;
    calcHist( &hsv_base, 1, channels, Mat(), hist_base, 2, histSize, ranges, true, false );
    normalize( hist_base, hist_base, 0, 1, NORM_MINMAX, -1, Mat() );
    calcHist( &hsv_half_down, 1, channels, Mat(), hist_half_down, 2, histSize, ranges, true, false );
    normalize( hist_half_down, hist_half_down, 0, 1, NORM_MINMAX, -1, Mat() );
    calcHist( &hsv_test1, 1, channels, Mat(), hist_test1, 2, histSize, ranges, true, false );
    normalize( hist_test1, hist_test1, 0, 1, NORM_MINMAX, -1, Mat() );
    calcHist( &hsv_test2, 1, channels, Mat(), hist_test2, 2, histSize, ranges, true, false );
    normalize( hist_test2, hist_test2, 0, 1, NORM_MINMAX, -1, Mat() );
    for( int compare_method = 0; compare_method < 4; compare_method++ )
    {
        double base_base = compareHist( hist_base, hist_base, compare_method );
        double base_half = compareHist( hist_base, hist_half_down, compare_method );
        double base_test1 = compareHist( hist_base, hist_test1, compare_method );
        double base_test2 = compareHist( hist_base, hist_test2, compare_method );
        cout << "Method " << compare_method << " Perfect, Base-Half, Base-Test(1), Base-Test(2) : "
             <<  base_base << " / " << base_half << " / " << base_test1 << " / " << base_test2 << endl;
    }
    cout << "Done \n";
    return 0;
}
```

For `ranges` I thought it accepted ranges as a Vector of pairs rather than the flattened equivalent. I don't read much C++ so maybe I just read it wrong. :sweat_smile: I have been struggling a bit to do the necessary translation while working with the crate.

Given the summary of the assertions you've given, I think it makes sense. Given the shape of the parameter is flat, they'd need to validate them in terms of each other's sizes.

I now realize an (additional) error in my code as I re-read the C++ example. I had neglected to pass two ints to hist_size which could leave the parameters unaligned, causing another assertion error.

> Judging by that assert for channels it expects either an empty Vector or a Vector of the same length as hist

Another surprise to me based on the C++ example code, but maybe I need to change the way I initialize those output `Mat` so they corroborate the expected length.

**Comment by onelson** [comment]
Refining with the advice you've already given, here's what I'm looking at from the rust side.

```rust
use opencv::{core, highgui, imgcodecs, imgproc, prelude::*, Result};

fn main() -> Result<()> {

    let target = imgcodecs::imread(
        &std::env::args().nth(1).expect("input image"),
        imgcodecs::IMREAD_COLOR,
    )?;

    let mask = Mat::default()?;

    let mut hsv1 = Mat::default()?;
    imgproc::cvt_color(&target, &mut hsv1, imgproc::COLOR_BGR2HSV, 0)?;

    debug_assert_eq!(hsv1.channels()?, 3);
    debug_assert_ne!(hsv1.size()?.width, 0);
    debug_assert_ne!(hsv1.size()?.height, 0);

    let mut hist1 = Mat::default()?;
    imgproc::calc_hist(
        &hsv1,
        &core::Vector::from(vec![0, 1]),
        &mask,
        &mut hist1,
        &core::Vector::from(vec![50, 60]),
        &core::Vector::from(vec![0., 180., 0., 256.]),
        false,
    )
    .expect("calc hist 1");
    Ok(())
}
```

Something's still incorrect. Best I can tell, this matches the example from the docs, but fails with:
```
thread 'main' panicked at 'calc hist 1: Error { code: -215, message: "OpenCV(4.5.1) /home/owen/projects/opencv/modules/core/src/matrix.cpp:768: error: (-215:Assertion failed) 0 <= _rowRange.start && _rowRange.start <= _rowRange.end && _rowRange.end <= m.rows in function \'Mat\'\n" }', src/main.rs:42:6
```

**Comment by twistedfall** [comment]
Well, this code works for me (or at least doesn't throw any error):
```rust
#[test]
fn calc_histogram() -> Result<()> {
	use opencv::{core, highgui, imgcodecs, imgproc, prelude::*, Result};

	const PIXEL: &[u8] = include_bytes!("pixel.png");
	let img_data = Mat::from_slice::<u8>(PIXEL)?;
	let target = imgcodecs::imdecode(&img_data, imgcodecs::IMREAD_COLOR)?;

	let mask = Mat::default();

	let mut hsv1 = Mat::default();
	imgproc::cvt_color(&target, &mut hsv1, imgproc::COLOR_BGR2HSV, 0)?;

	debug_assert_eq!(hsv1.channels()?, 3);
	debug_assert_ne!(hsv1.size()?.width, 0);
	debug_assert_ne!(hsv1.size()?.height, 0);

	let mut hist1 = Mat::default();
	imgproc::calc_hist(
		&hsv1,
		&core::Vector::from(vec![0, 1]),
		&mask,
		&mut hist1,
		&core::Vector::from(vec![50, 60]),
		&core::Vector::from(vec![0., 180., 0., 256.]),
		false,
	)
		.expect("calc hist 1");
	Ok(())
}
```

The only difference is the image reading code (pixel.png is here https://github.com/twistedfall/opencv-rust/blob/master/tests/pixel.png). I'm using OpenCV 4.5.2 and crate v0.52.0. So it looks like your source image is somewhat different from what's expected.

**Comment by onelson** [comment]
Okay, great. I'll try it again with 4.5.2 (I'm using 4.5.1). If it's me, it's me - I'll try and identify what could be going on with the input image if updating opencv doesn't magically fix this.

Thanks for looking at this with me.

Looks like the title of this issue is *poor* at this point. I'll revise. :sweat_smile:

**Comment by onelson** [comment]
Quick follow-up on this. I upgraded to OpenCV 4.5.2 and this crate to 0.53.0, but so far the only image this code has worked on (for me) is the single-pixel image you're testing against. I get the same error with `blox.jpg`, for example.

```
...
     Running `target/debug/bodycount /home/owen/Downloads/blox.jpg`
thread 'main' panicked at 'calc hist 1: Error { code: -215, message: "OpenCV(4.5.2) /home/owen/projects/opencv/modules/core/src/matrix.cpp:768: error: (-215:Assertion failed) 0 <= _rowRange.start && _rowRange.start <= _rowRange.end && _rowRange.end <= m.rows in function \'Mat\'\n" }', src/main.rs:47:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by twistedfall** [comment]
Will you please share the rust code you’re trying to get running? I’ll take a look at it as the time permits

**Comment by onelson** [comment]
Sure. It's essentially what you wrote in your test, but here:

- https://github.com/onelson/bodycount/blob/hist-compare/src/main.rs (active tinkering)
- https://github.com/onelson/bodycount/blob/0a063ee567b19c1dc5117cf74fa2fe856b34823e/src/main.rs (point in time - now)

I've been feeding in `dark-souls-3-gundyr.png` as the 2nd image, but naturally, the program doesn't get far enough for this to matter.

**Comment by onelson** [comment]
I feel like I'm going crazy but your test code seems to work for any image that has a width of 1px. I just ran this with these images (for "target"):

- 3x6 *failed* ![pixel 3x6](https://user-images.githubusercontent.com/301388/115127246-f4b87f80-9f89-11eb-9218-250861d1adb3.png)
- 1x6 *worked* ![pixel 1x6](https://user-images.githubusercontent.com/301388/115127247-f5511600-9f89-11eb-9c29-398da247e08e.png)
- 1x2 *worked* ![pixel 1x2](https://user-images.githubusercontent.com/301388/115127248-f5511600-9f89-11eb-82dd-4bd1a12e6bbb.png)
- 2x1 *failed* ![pixel 2x1](https://user-images.githubusercontent.com/301388/115127249-f5511600-9f89-11eb-8b0b-89fc672cf917.png)
- 2x2 *failed* ![pixel 2x2](https://user-images.githubusercontent.com/301388/115127250-f5511600-9f89-11eb-8636-50b66f689d5b.png)

Only the images with 1px width worked.

**Comment by onelson** [comment]
I had some success, but I'm not sure what to make of it. I modded the python example in the opencv docs so I could verify my inputs (they should work):

```python
from __future__ import print_function
from __future__ import division
import cv2 as cv
import numpy as np

src_base = cv.imread("you-died.png")
src_test1 = cv.imread("dark-souls-3-gundyr.png")

hsv_base = cv.cvtColor(src_base, cv.COLOR_BGR2HSV)
hsv_test1 = cv.cvtColor(src_test1, cv.COLOR_BGR2HSV)
h_bins = 50
s_bins = 60
histSize = [h_bins, s_bins]
# hue varies from 0 to 179, saturation from 0 to 255
h_ranges = [0, 180]
s_ranges = [0, 256]
ranges = h_ranges + s_ranges # concat lists
# Use the 0-th and 1-st channels
channels = [0, 1]
hist_base = cv.calcHist([hsv_base], channels, None, histSize, ranges, accumulate=False)
cv.normalize(hist_base, hist_base, alpha=0, beta=1, norm_type=cv.NORM_MINMAX)
hist_test1 = cv.calcHist([hsv_test1], channels, None, histSize, ranges, accumulate=False)
cv.normalize(hist_test1, hist_test1, alpha=0, beta=1, norm_type=cv.NORM_MINMAX)

for compare_method in range(4):
    base_base = cv.compareHist(hist_base, hist_base, compare_method)
    base_test1 = cv.compareHist(hist_base, hist_test1, compare_method)
    print('Method:', compare_method, 'Perfect, Base-Test(1) :', base_base, '/', base_test1)
```

This ran well and spat out some reasonable output. I noticed the `cv.calcHist()` calls were written in this version as a list of numpy matrices, which got me thinking....

https://github.com/onelson/bodycount/commit/e7893c215263dd86fe49b4c2899e4e974b4825c7

If I wrap my input Mats in a `types::VectorOfMat` things seem to work as expected. Very confusing.

@twistedfall do you think there's anything actionable here? I'm not sure if a documentation change would be possible since the underlying C++ docs are being brought through (describing a different signature as it is).

**Comment by twistedfall** [comment]
I see. It's great that you got that working! Looking closely at the generated documentation it does indeed refers to the first argument in plural: "images", "arrays" and it indexes into it in the description of the `channels` argument. So while the docs can indeed be clearer I'm not sure there is anything actionable here. The docs are translated automatically from the C++ headers so they are not always spot on in the Rust environment unfortunately.

**Comment by sjbeskur** [comment]
@onelson I'm struggling with the same issue ... Tried wrapping mats into VectorOfMat but I must be doing something wrong.  Any chance  you might share your snippet in rust?

**Comment by onelson** [comment]
@sjbeskur https://github.com/onelson/bodycount/commit/e7893c215263dd86fe49b4c2899e4e974b4825c7 this was the change I made that got it to not panic :sweat_smile: 
I honestly can't remember much about this project. April 2021 was such a long time ago...

**Comment by IGeorgilas** [comment]
@twistedfall I was wondering what is the correct approach to implement calc_hist now that @onelson's pinpointing of the issue does not seem possible with the deprecation of VectorOfMat

**Comment by twistedfall** [comment]
@IGeorgilas Only the type alias is deprecated, you should just use `Vector<Mat>` instead
