### ISSUE TITLE
MacOS CI Jobs Fail

### ISSUE THREAD

**Issue by hediet** [twistedfall/opencv-rust#226]
[opencv-rust CI jobs on MacOS](https://github.com/twistedfall/opencv-rust/actions/runs/744138856) are failing.

This is caused by brew installing Open CV 4.5.2 instead of Open CV 4.5.1.
Sadly I was unable to configure brew to install the old Open CV version 4.5.1.

**Comment by twistedfall** [comment]
Well, OpenCV 4.5.2 is supported since v0.52.0 so it’s probably not related. I’m in the process of doing some quite significant internal changes and that’s what causing them to fail in the `rel` branch. For example src build of OpenCV 4.5.2 worked before these changes: https://github.com/twistedfall/opencv-rust/runs/2277624506

**Comment by hediet** [comment]
Interestingly my CI jobs for macos start failing too and I didn't change anything. Only thing that changed was the opencv version.

**Comment by twistedfall** [comment]
Just to confirm, you are using crate version 0.52.0, right?

**Comment by hediet** [comment]
Oh, I guess that's it. I'm on 0.48, I'll try 0.52 tomorrow.
Thanks for your help! 

Nontheless, uncool that a minor update of opencv can let CI fail without any changes to the repo.

**Comment by twistedfall** [comment]
Well, OpenCV often introduces some new functionality even in minor releases and this might require changes to the binding generator (like it happened this time), so the new version is backwards compatible, but the generator needs to be adjusted. No one to blame here, it’s just like it is.

**Comment by hediet** [comment]
Do you know how I can configure `brew` to install a fixed version of opencv?

**Comment by twistedfall** [comment]
Not really, unfortunately. I think that brew installs whatever is in the repository. So you’d just need to check it out at the specific revision in theory.

**Comment by hediet** [comment]
This seems to work (from [here](https://cmichel.io/how-to-install-an-old-package-version-with-brew/)):
```sh
brew tap-new $USER/local-opencv
brew extract --version=$OPENCV_VERSION opencv $USER/local-opencv
brew install opencv@$OPENCV_VERSION
```

However, even if opencv_version is the latest version (4.5.2), brew compiles opencv from source (which is very slow, not even caching seems to help).

**Comment by twistedfall** [comment]
The tests are now green in v0.53.0, please check the [changelog](https://github.com/twistedfall/opencv-rust/blob/master/CHANGES.md) too when updating.
