### ISSUE TITLE
Unable to build with opencv2.framework on macOS and iOS

### ISSUE THREAD

**Issue by nsabovic** [twistedfall/opencv-rust#232]
I am trying to build on macOS 11.2.3 using OpenCV 4.5.2 built as a framework. The original intent is to build an iOS library which is shipped as a framework but I also tried building on macOS with `opencv2.framework` built using the [official script](https://github.com/opencv/opencv/blob/4.5.2/platforms/osx/build_framework.py). I'm using nightly rustc `rustc 1.53.0-nightly (b84932674 2021-04-21)`.

I started by setting `OPENCV_LINK_LIBS`,  `OPENCV_LINK_PATHS` and `OPENCV_INCLUDE_PATHS` and setting `OPENCV_DISABLE_PROBES` to make sure the environment is used. I made sure that `/Users/test/mac/opencv-4.5.2-build/opencv2.framework/Versions/A/Headers/core/version.hpp` is present (I've pasted its contents below the build output).

If I try building using the headers from Homebrew-installed OpenCV 4.5.2 (from `/usr/local/opt/opencv/include`) then the build completes but trying to link with the framework reports missing symbols `cv::ocl::PlatformInfo::versionMinor()` and `cv::ocl::PlatformInfo::versionMajor()`.

What would be a good place to start trying to figure out why the version comes back as 0.0.0?

Build log:

```
      Compiling opencv v0.53.0
error: failed to run custom build command for `opencv v0.53.0`

Caused by:
  process didn't exit successfully: `/Users/test/target/release/build/opencv-4beda3e5bead2c8d/build-script-build` (exit status: 101)
  --- stderr
  === Crate version: Some("0.53.0")
  === Environment configuration:
  ===   OPENCV_PACKAGE_NAME = None
  ===   OPENCV_PKGCONFIG_NAME = None
  ===   OPENCV_CMAKE_NAME = None
  ===   OPENCV_CMAKE_BIN = None
  ===   OPENCV_VCPKG_NAME = None
  ===   OPENCV_LINK_LIBS = Some("opencv2.framework")
  ===   OPENCV_LINK_PATHS = Some("/Users/test/mac/opencv-4.5.2-build")
  ===   OPENCV_INCLUDE_PATHS = Some("/Users/test/mac/opencv-4.5.2-build/opencv2.framework/Versions/A/Headers/")
  ===   OPENCV_DISABLE_PROBES = Some("pkg_config,cmake")
  ===   OPENCV_MODULE_WHITELIST = None
  ===   OPENCV_MODULE_BLACKLIST = None
  ===   CMAKE_PREFIX_PATH = None
  ===   OpenCV_DIR = None
  ===   PKG_CONFIG_PATH = Some("/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:/opt/X11/lib/pkgconfig:/opt/X11/share/pkgconfig")
  ===   VCPKG_ROOT = None
  ===   VCPKGRS_DYNAMIC = None
  === Enabled features:
  === Detected probe priority based on environment vars: pkg_config: true, cmake: false, vcpkg: false
  === Probing the OpenCV library in the following order: environment, pkg_config, cmake, vcpkg_cmake, vcpkg
  === Configuring OpenCV library from the environment:
  ===   include_paths: /Users/test/mac/opencv-4.5.2-build/opencv2.framework/Versions/A/Headers/
  ===   link_paths: /Users/test/mac/opencv-4.5.2-build
  ===   link_libs: opencv2.framework
  === OpenCV library configuration: Library {
      include_paths: [
          "/Users/test/mac/opencv-4.5.2-build/opencv2.framework/Versions/A/Headers/",
      ],
      version: Version {
          major: 0,
          minor: 0,
          patch: 0,
          pre: [],
          build: [],
      },
      cargo_metadata: [
          "cargo:rustc-link-search=/Users/test/mac/opencv-4.5.2-build",
          "cargo:rustc-link-search=framework=/Users/test/mac/opencv-4.5.2-build",
          "cargo:rustc-link-lib=framework=opencv2",
      ],
  }
  thread 'main' panicked at 'Unsupported OpenCV version: 0.0.0, must be from 3.2, 3.4 or 4.x branch', /Users/test/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.53.0/build.rs:310:9
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/b849326744a8eec939e592f0ab13bff85cc865d3/library/std/src/panicking.rs:493:5
     1: std::panicking::begin_panic_fmt
               at /rustc/b849326744a8eec939e592f0ab13bff85cc865d3/library/std/src/panicking.rs:435:5
     2: build_script_build::main
     3: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Here are the contents of `version.hpp`:

```c
// This file is part of OpenCV project.
// It is subject to the license terms in the LICENSE file found in the top-level directory
// of this distribution and at http://opencv.org/license.html.

#ifndef OPENCV_VERSION_HPP
#define OPENCV_VERSION_HPP

#define CV_VERSION_MAJOR    4
#define CV_VERSION_MINOR    5
#define CV_VERSION_REVISION 2
#define CV_VERSION_STATUS   ""

#define CVAUX_STR_EXP(__A)  #__A
#define CVAUX_STR(__A)      CVAUX_STR_EXP(__A)

#define CVAUX_STRW_EXP(__A)  L ## #__A
#define CVAUX_STRW(__A)      CVAUX_STRW_EXP(__A)

#define CV_VERSION          CVAUX_STR(CV_VERSION_MAJOR) "." CVAUX_STR(CV_VERSION_MINOR) "." CVAUX_STR(CV_VERSION_REVISION) CV_VERSION_STATUS

/* old  style version constants*/
#define CV_MAJOR_VERSION    CV_VERSION_MAJOR
#define CV_MINOR_VERSION    CV_VERSION_MINOR
#define CV_SUBMINOR_VERSION CV_VERSION_REVISION

#endif // OPENCV_VERSION_HPP
```

**Comment by nsabovic** [comment]
Looking at [the binding generator](https://github.com/twistedfall/opencv-rust/blob/master/binding-generator/src/bin/binding-generator.rs) I saw that the path for include files should be set to the framework dir (`/Users/test/mac/opencv-4.5.2-build/opencv2.framework`) and then that part passes but now I get a different error:

```
  === Found OpenCV version: 4.5.2 in headers located at: /Users/test/opencv-4.5.2-build/opencv2.framework
  === Generating code in: /Users/test/target/debug/build/opencv-bfdc314b3a8ad2b4/out
  === Placing generated bindings into: /Users/test/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.53.0/src/opencv
  === Using OpenCV headers from: /Users/test/opencv-4.5.2-build/opencv2.framework/opencv2
  === Clang command line args: [
      "-isystem/usr/local/include",
      "-isystem/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1",
      "-isystem/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include",
      "-isystem/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include",
      "-isystem/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
      "-isystem/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks",
      "-I/Users/test/projects/opencv-4.5.2-build/opencv2.framework",
      "-I/Users/test/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.53.0/src_cpp",
      "-DOCVRS_PARSING_HEADERS",
      "-includeocvrs_ephemeral.hpp",
      "-std=c++14",
  ]
  === Total binding generation time: 9.262µs


  error occurred: Command "ar" "s" "/Users/test/target/debug/build/opencv-bfdc314b3a8ad2b4/out/libocvrs.a" with args "ar" did not execute successfully (status code exit status: 1).
```

The file mentioned, `opencv-bfdc314b3a8ad2b4/out/libocvrs.a` is not there.

**Comment by twistedfall** [comment]
Can you please first check the CI scripts at https://github.com/twistedfall/opencv-rust/blob/master/ci/install-macos-framework.sh and https://github.com/twistedfall/opencv-rust/blob/master/ci/script.sh#L29-33 they produce the working OpenCV framework build and environment setup for a successful crate test run. Judging by the error I think you are missing linking to the OpenCL.framework. In case it still fails please post a full build log as produced by `cargo build -vv` from your last attempt.

**Comment by nsabovic** [comment]
@twistedfall—thanks! I had used the `install-macos-framework.sh` script to build the framework but somehow I missed the main `script.sh` that sets all the environment variables. When I add all the PATHs and LIBs, it compiles! This should unblock me for a while so I can close this.

**Comment by fzyzcjy** [comment]
Hi did you successfully build the **ios** version? I am stuck in https://github.com/twistedfall/opencv-rust/issues/270#issuecomment-930180077

I am using the official ios opencv2.framework downloaded by opencv.org

**EDIT:** Almost the same problem... https://github.com/twistedfall/opencv-rust/issues/270#issuecomment-930223119

**Comment by nsabovic** [comment]
Reopening this issue because the CI script is cheating.

Here's an excerpt from the actual CI script:

```
		export OPENCV_LINK_PATHS="$HOME/build/opencv/opencv-$OPENCV_VERSION-build,$clang_dir/lib/darwin"
		export OPENCV_LINK_LIBS="opencv2.framework,OpenCL.framework,Cocoa.framework,Accelerate.framework,AVFoundation.framework,CoreGraphics.framework,CoreMedia.framework,CoreVideo.framework,QuartzCore.framework,clang_rt.osx"
#		export OPENCV_INCLUDE_PATHS="$HOME/build/opencv/opencv-$OPENCV_VERSION-build/opencv2.framework"
		export OPENCV_INCLUDE_PATHS="$HOME/build/opencv/opencv-$OPENCV_VERSION-build/build/build-x86_64-macosx/install/include"
```

As you can see it doesn't actually use the headers from `opencv2.framework` but the ones from `build/build-x86_64-macosx/install/include` which is an intermediary build product when building `opencv2.framework` from source. In other words you can only link with the framework if you have the sources and can build it yourself.

For my use case I need to use a binary `opencv2.framework` (even worse, I need the xcframework but I can make that work if the framework case is working).

I've attached the outputs of running successfully [using the headers from the build folder](https://github.com/twistedfall/opencv-rust/files/7725627/build.txt) and failing [using the headers from the actual framework](https://github.com/twistedfall/opencv-rust/files/7725628/framework.txt). It fails with `libocvrs.a (No such file or directory)`. Where should I look?

**Comment by twistedfall** [comment]
I have fixed this problem now, so please check v0.61.3 version. The `OPENCV_INCLUDE_PATHS` is now set like this:
```
export OPENCV_INCLUDE_PATHS="$HOME/build/opencv/opencv-$OPENCV_VERSION-build"
```
so the value shouldn't include the `opencv2.framework` part.

**Comment by nsabovic** [comment]
Thanks for the quick update, however I don't think I explained the problem correctly.

The value **should** include `opencv2.framework` part. That `opencv-$OPENCV_VERSION-build` directory is some intermediary build directory which is not available if you didn't build the framework locally. So currently I can't compile using the actual framework (like the one downloaded from [opencv.org](https://opencv.org/releases/), see iOS pack).

I would expect everything to work just by adding the framework in `OPENCV_LINK_LIBS` and should not involve setting `OPENCV_INCLUDE_PATHS`. The reason being that frameworks are treated differently by the preprocessor too (and not just the linker) and this took me a long while to figure out. Let's say you have this piece of code:
```c++
#include <opencv2/core/version.hpp>
```

When compiling with a framework you will have `opencv2.framework/Headers/core/version.hpp`. So there's no directory you can add to `-I` to have `opencv2/core/version.hpp` available. But when you compile with `-framework=opencv2.framework` the preprocessor will look for `opencv2/*` in `opencv2.framework/Headers/*` and this will work.

I hope that makes sense.

**Comment by twistedfall** [comment]
Yep, that makes perfect sense and I've come through all of that discovery while fixing this issue :)

I'm just saying that it works right now in the new crate version. Although you'd still need to set up the `OPENCV_INCLUDE_PATHS` to point to the directory that contains `opencv2.framework`. Internally the crate uses this environment variable to find the module header files that it needs to parse even before it starts to invoke the compiler. So now the crate will try to also look inside `$OPENCV_INCLUDE_PATHS/opencv2.framework/Headers` directory: https://github.com/twistedfall/opencv-rust/blob/v0.61.3/build.rs#L87

**Comment by nsabovic** [comment]
It works!

Thank you. You are the best open-source author out there, I hope you know this.
