### ISSUE TITLE
Can `Mat` be `Sync`?

### ISSUE THREAD

**Issue by jerry73204** [twistedfall/opencv-rust#239]
I came across this when passing a `Mat` received from `VideoCapture` to many other worker threads. It is wrapped into `Arc` and is copied to other threads as reference counted image. However, `Arc` requires the inner type to be `Sync`.  The `Mat` is `!Sync` and I'm unsure that if this restriction is necessary. If no `Mat`s share the underlying buffer, perhaps we can relax this restriction?

**Comment by twistedfall** [comment]
Not with `Mat` unfortunately, at least not at the current stage. One can easily crate a seemingly independent `Mat` (with [`roi`](https://docs.rs/opencv/0.53.0/opencv/core/struct.Mat.html#method.roi) for example) which is actually a [mutable] reference to the original one. This actually makes `roi()` (and similar methods) unsound, but it's just like it is at the moment. I have an idea of implementing some kind of `MatRef<'parent_mat>` which will allow such operations to be sound, but it's still in the planning stage.

**Comment by jerry73204** [comment]
Currently I hack with a type wrapper to give it `Sync`.

```rust
struct MatWrapper(Mat);

unsafe impl Sync for MatWrapper {}

let mat = Arc::new(MatWrapper(orig_mat));
```

I wonder the situation of `roi` can be solved by "phantom reference", while `MatRef` does not actually store the pointer to the parent `Mat`. You can see the playground to see if it is relevant to you.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2060b77719a0df23ac6de0f43d4de955

**Comment by twistedfall** [comment]
Yep, this is more or less how I envision solving it.

**Comment by fzyzcjy** [comment]
@twistedfall Hi I still wonder whether it can be sync: the `roi` problem always exists, no matter it is Sync or !Sync. On the other hand, Mat itself seems to be Sync because when I was using opencv C++, I can happily play with Mat in multiple worker threads without problems.

**Comment by twistedfall** [comment]
By saying "play" what exactly do you mean? Can you modify the same `Mat` using multiple threads without running into race conditions?

**Comment by fzyzcjy** [comment]
@twistedfall You are right. It will have race conditions and Rust indeed successfully refuse to do so. Thanks for pointing out!

**Comment by eadf** [comment]
It seems like the wrapper `Sync` hack does not work in 2021 edition:
```
the trait `std::marker::Sync` is not implemented for `*mut std::ffi::c_void`
```
Can be tested by switching to 2021 edition in [this repository](https://github.com/eadf/libstacker.rs)

**Comment by nico-abram** [comment]
@eadf the fix still works, nothing about Sync changed in edition 2021
What changed was something about disjoint closure captures: https://doc.rust-lang.org/edition-guide/rust-2021/disjoint-capture-in-closures.html
That's what's giving you problems. I can send you a fix later

**Comment by jerry73204** [comment]
Sorry that I'd like to bring the issue back. The `roi()` or `range()` is unsound because it introduces potential data races regardless of `Sync`. We can let `roi()` to borrow the owning Mat to solve this.

```rust
let owner: Mat = /* wthatever */;
let roi: MatRef<'_> = Mat::roi(&owner, rect)?;
```

I see this solution is unfriendly to multi-thread programming. The borrow checker complains lifetime not enough if you send the borrowing ROI to a thread. It can be worked around by special containers from [ownref](https://docs.rs/ownref), [owning_ref](https://docs.rs/owning_ref/) or detangled lifetime from [qcell](https://docs.rs/qcell/). Unfortunately, boilerplate code is unavoidable.

```rust
use ownref::ArcOwnedC;

let owner: ArcOwnedC<Mat> = ArcOwnedC::new(/* wthatever */);
let roi1: ArcOwnedC<Mat, MatRef<'_>> = owner.clone().try_map(|owner: Mat| Mat::roi(&owner, rect1))?;
let roi2: ArcOwnedC<Mat, MatRef<'_>> = owner.clone().try_map(|owner: Mat| Mat::roi(&owner, rect2))?;
```

Another solution is to have a read-only and auto reference-counted Mat. It can safely creating read-only owned ROIs. However, it's not possible to partition the Mat to mutable pieces and let threads to write data on each piece. This implementation is basically re-inventing what `ownref::ArcOwnedC` has done.

```rust
let owner: Mat = /* whatever */;
let ro_owner: MatReadOnly = owner.into_read_only();
let roi1 = ro.roi(rect1);
let roi2 = ro.roi(rect2);
```

To safely divide a Mat into exclusive and mutable ROIs, we may have a [slice::split_mut](https://doc.rust-lang.org/std/primitive.slice.html#method.split_mut)-like method. The implementation involves non-trivial range checks.

My opinion is to make things simple: Mark the `roi()` and similar methods to be `unsafe` and provide `.roi_ref()` and `.ref_mut()` returning borrowed types. Let the user to choose to go unsafe or write boilerplate code, and we can give `Sync` back.
