### ISSUE TITLE
setMouseCallback from HighGui is missing

### ISSUE THREAD

**Issue by michael-p** [twistedfall/opencv-rust#24]
Dear all,

I just noticed that the [setMouseCallback](http://docs.opencv.org/2.4/modules/highgui/doc/user_interface.html#setmousecallback) function is not available in the Rust bindings, probably because of its function pointer argument. Since I would consider this a rather important function to have I thought I'd report it here and ask if you think it is possible to add this to the bindings?

Thanks,
Michael

**Comment by twistedfall** [comment]
Support for callbacks has been implemented in the latest version: 0.5.0
