### ISSUE TITLE
Unable to construct opencv::types::PtrOfCLAHE

### ISSUE THREAD

**Issue by b0ggyb33** [twistedfall/opencv-rust#243]
There seems to be no way to consuct a PtrOfCLAHE in order to use the CLAHE algorithm.

The [documentation](https://docs.rs/opencv/0.53.0/opencv/types/type.PtrOfCLAHE.html) provides methods to convert the type to a raw c ptr, but nothing to allow construction of the Rust struct.

Can you provide some information about how this algorithm is intended to be used?

**Comment by twistedfall** [comment]
Can you please give me an example of how you can use it? I’m not familiar with that particular class, but a quick check in the OpenCV documentation itself doesn’t reveal any obvious constrictors.

**Comment by alexkscott** [comment]
We want to use [`CLAHE::apply`](https://docs.rs/opencv/0.53.0/opencv/imgproc/trait.CLAHE.html#provided-methods). This seems to require you creating a `PtrOfCLAHE` first. However, there is no obvious way to construct it.

**Comment by b0ggyb33** [comment]
I've found it in the documentation. https://docs.rs/opencv/0.53.0/opencv/imgproc/fn.create_clahe.html

**Comment by b0ggyb33** [comment]
I think we can consider this closed now, as this is an OpenCV style issue more than anything else. Thanks for engaging.
