### ISSUE TITLE
How to copy ROI to another image

### ISSUE THREAD

**Issue by foxzool** [twistedfall/opencv-rust#245]
cpp code
`imageSmall.copyTo(imageBigger(Rect(iTargetX,
                                   iTargetY, 
                                   imageSmall.size().width, 
                                   imageSmall.size().height)))`

when i use [roi](https://docs.rs/opencv/0.53.0/opencv/core/struct.Mat.html#method.roi),  the mat is not mutable
how can i do it?

**Comment by twistedfall** [comment]
You can basically use the cpp code without adjustments. This is the corresponding Rust code:
```rust
let mut image_bigger = Mat::new_rows_cols_with_default(5, 5, u8::typ(), Scalar::all(10.))?;
let mut image_bigger_roi = Mat::roi(&image_bigger, Rect::new(1, 1, 3, 3))?;
let image_small = Mat::new_rows_cols_with_default(3, 3, u8::typ(), Scalar::all(3.))?;
image_small.copy_to(&mut image_bigger_roi)?;
```
Currently the `roi` function is unsound, it allows (and forces) you to create a reference to the source `Mat` from unmutable reference, but you can actually make the result mutable and modify it. I have plans to fix it, but it will require some effort.
