### ISSUE TITLE
Enabling the `clang-runtime` feature does not seem to solve the known issue in #troubleshooting

### ISSUE THREAD

**Issue by MacTuitui** [twistedfall/opencv-rust#247]
I am hitting the " thread 'main' panicked at 'a `libclang` shared library is not loaded on this thread' " error, yet I believe I have enabled the `clang-runtime` feature, as suggested in the help. Is there anything else to try?

1. MacOS Catalina 10.15.7 on MacBook Pro 16" 2019
2. OpenCV from homebrew
3. OpenCV 4.5.2_4
4. rustc 1.52.1 (9bc8c42bb 2021-05-09)

Here is the complete log that I get when running:
```
env METAL_DEVICE_WRAPPER_TYPE=1 RUST_BACKTRACE=full DYLD_FALLBACK_LIBRARY_PATH="/Library/Developer/CommandLineTools/usr/lib" cargo -vv run --release
```
(I'm using fish so that's how I set the env vars for that run)

[log.txt](https://github.com/twistedfall/opencv-rust/files/6680063/log.txt)

Here is my Cargo.toml:
```
[package]
name = "svsclock"
version = "0.1.0"
authors = ["AA"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
clang-runtime = []

[dependencies]
nannou = { git = "https://github.com/nannou-org/nannou" }
nannou_audio = { git = "https://github.com/nannou-org/nannou" }
rand_xorshift = "0.2"
opencv = "0.53"
```

I'm surely doing something wrong, but I would appreciate another pair of eyes!

I am able to build and run as long as I don't add `nannou-audio` to my project.

**Comment by twistedfall** [comment]
The way you use `clang-runtime` feature makes it an optional feature of your crate, it doesn’t get passed on to dependencies. To fix this declare the opencv dependency like this:
```toml
opencv = { version = “0.53”, features = [“clang-runtime”] }
```

**Comment by MacTuitui** [comment]
And of course it works! Sorry for the newb mistake.
