### ISSUE TITLE
Can't use opencv::viz widgets

### ISSUE THREAD

**Issue by Heavenston** [twistedfall/opencv-rust#250]
Hi !
I used opencv-rust to make "mosaic images/videos" (big image composed of lots of small ones), i wanted to add a visualizer for all image-colors available in the dataset
So anyway, i wanted to use the WCloud widget from the viz module, but, if i'm not making any mistakes, the viz::Viz3d::show_widget method cannot be used because it uses the struct Widget and not the WidgetTrait, making it unusable with the WCloud widget

So i'd like to know if there's is a workaround that i didn't see or if it is an /bug/ !

**Comment by twistedfall** [comment]
Can you please provide the sample code? If possible the working C++ one too. I’m not really familiar with the viz module and haven’t tested it at all so it can perfectly happen that this is a binding generation bug.

**Comment by Heavenston** [comment]
The C++ example:
```cpp
viz::WCloud cw(cloud, viz::Color::red());
myWindow.showWidget("CloudWidget1", cw);
```
What i think rust should look like:
```rust
let cw = opencv::viz::WCloud::new(cloud, opencv::viz::Color::red());
my_window.show_widget("CloudWidget1", cw);
// Fail because show_widget expect a Widget struct, which WCloud isn't
```
myWindow being of type opencv::viz::Viz3d

**Comment by twistedfall** [comment]
Yep, it is a deficiency in binding generation. I'll try to fix it. For now you should be able to use the following workaround:
```rust
...
let cw_widget = unsafe { opencv::viz::Widget::from_raw(cw.into_raw()) }
my_window.show_widget("CloudWidget1", &cw_widget);
```

**Comment by Heavenston** [comment]
Ok perfect and the work around works
Thanks for helping and for the fast response !

**Comment by twistedfall** [comment]
Since version 0.53.1 you should be able to just use `.into()` to convert a descendant to the necessary base class:
```rust
let cw_widget = cw.into();
my_window.show_widget("CloudWidget1", &cw_widget);
```
