### ISSUE TITLE
Use of NOTICE log level in cmake probe precludes using CMAKE 3.14 or older

### ISSUE THREAD

**Issue by CattleProdigy** [twistedfall/opencv-rust#253]
The `NOTICE` log level was introduced in CMake ~3.15. If you run `message(NOTICE "OCVRS_INCLUDE_DIRS:${OpenCV_INCLUDE_DIRS}` with an older version of CMake, it will emit `NOTICEOCVRS_INCLUDE_DIRS:/path/to/opencv` to stderr which can't be interpreted by `cmake_probe.rs`.

The cleanest way to support this would be to simply drop `NOTICE` from the `message` lines in `cmake/CMakeLists.txt`. This will support CMake back to 3.0 at least (as far as this particular problem is concerned). I'm happy to do it, if the maintainers find it agreeable.

For some motivating context, I use the `rust:latest` docker image at work and it's based on Debian Buster which comes with CMake 3.13

**Comment by twistedfall** [comment]
Great find! It would be really helpful if you could make the PR with those change, thank you.

**Comment by CattleProdigy** [comment]
> Great find! It would be really helpful if you could make the PR with those change, thank you.

The PR is up here: https://github.com/twistedfall/opencv-rust/pull/254

Most of the CI stuff passed. I'm not sure what's going on with the tests that didn't. It has something to do with windows so it's a bit out of my wheelhouse.

**Comment by twistedfall** [comment]
Yeah, the problem in the tests has no relation to your changes. Something wrong with the vcpkg installation, I'll sort it out and merge it (to not make master red). Thank you!

**Comment by twistedfall** [comment]
Released in 0.53.2, thank you!
