### ISSUE TITLE
error: (-215:Assertion failed) on VectorOfVector* 

### ISSUE THREAD

**Issue by danielvschoor** [twistedfall/opencv-rust#256]
Before reporting an issue please first check the
[troubleshooting guide](https://github.com/twistedfall/opencv-rust/blob/master/README.md#troubleshooting). If
the issue you're encountering is not solved thereby please state the following in your bugreport:
1. Operating system
Windows 10
2. The way you installed OpenCV: package, official binary distribution, manual compilation, etc.
Chocolatey
3. OpenCV version
4.5.3
4. rustc version (`rustc --version`)
1.54.0
5. Attach the full output of the following command from your project directory:
   ```shell script
   RUST_BACKTRACE=full cargo build -vv 
   ```
N/A

I get the following error whenever I try to display a VectorOfVectorOf Anything with highgui::imshow:

```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -215, message: "OpenCV(4.5.3) C:\\build\\master_winpack-build-win64-vc14\\opencv\\modules\\core\\src\\matrix_wrap.cpp:72: error: (-215:Assertion failed) 0 <= i && i < (int)vv.size() in function 'cv::_InputArray::getMat_'\n" }'```

Simplified code:
```rust
let mut mat: Vector<Vector<u8>> = Vector::new();
for _ in 0..100 {
    let mut new_vec = Vector::new();
    for x in 0..100 {
        if x % 2 == 0 {
            new_vec.push(15);
        } else {
            new_vec.push(150);
        }
    }
    mat.push(new_vec);
}
opencv::highgui::imshow("something", &mat).unwrap(); //Error occurs here
opencv::highgui::wait_key(1);
```

I used to do it this way in Python:
```python
image = np.array(vector_of_ints_2d, dtype=np.uint8)
cv2.imshow(image_name, image)
cv2.waitKey(1)
```

The error is a bit cryptic. It seems like the size of the vector I'm passing is not correct?

Any help would be appreciated!

**Comment by twistedfall** [comment]
From my tests it looks like the `Vector` of `Vector` is not handled the same way as a numpy's array in Python. There is a special handling for those in https://github.com/opencv/opencv/blob/4.5.3/modules/core/src/matrix_wrap.cpp#L68. Basically it interprets it as a 100 of `Mat`s every of which is 100x1 in size. So in this case I would say that it's just the way it is and you can't use `Vector<Vector<u8>>` for that purpose. You can always call `Mat::from_slice_2d` or `Mat::from_slice` to convert raw data into a `Mat`.
