### ISSUE TITLE
How to convert Mat object to tensorflow Tensor?

### ISSUE THREAD

**Issue by HIGH-IQ** [twistedfall/opencv-rust#257]
```
let image = imgcodecs::imread("image_2021_08_02T09_11_01_447Z.png", imgcodecs::IMREAD_GRAYSCALE).unwrap();

let mut resized_image = Mat::default();
imgproc::resize(&image, &mut resized_image, Size::new(320, 320), 3., 3., 0);

let mut rgb_image = Mat::default();
imgproc::cvt_color(&resized_image, &mut rgb_image, imgproc::COLOR_BGR2RGB, 0)?;

let mut padded_f32 = Mat::default();
rgb_image.convert_to(&mut padded_f32, f32::typ(), 1., 0.)?;
```
this is my opencv code, how to convert padded_f32 mat object to tensorflow Tensor ?

**Comment by twistedfall** [comment]
I'm not really familiar with Tensorflow API, what type of the data can it be initialized with?

**Comment by dhavalv83** [comment]
@twistedfall I want to convert preprocessed image to tensor for feed input tensor to model

**Comment by HIGH-IQ** [comment]
@twistedfall I want to convert preprocessed image to tensor for feed input tensor to model

**Comment by twistedfall** [comment]
It depends on the binary data format you need to initialize a Tensor. I'm not familiar with the exact requirements so it's difficult to give the specific advice. You can try using `Mat::data_typed::<u8>()` to get the `&[u8]` of the underlying `Mat` data.
