### ISSUE TITLE
Build fails with opencv 2.4.13

### ISSUE THREAD

**Issue by RainbowZephyr** [twistedfall/opencv-rust#26]
Using Arch Linux and compiled opencv2 from aur

4 |     let img = opencv::highgui::imread("house.jpg",1);
  |         ^^^

error: linking with `cc` failed: exit code: 1
  = note: /usr/bin/ld: cannot find -locvrs
collect2: error: ld returned 1 exit status

**Comment by twistedfall** [comment]
I'm currently not targeting 2.4.x branch in master anymore, sorry
