### ISSUE TITLE
highgui::create_trackbar() deprecation warning

### ISSUE THREAD

**Issue by ggasilveira** [twistedfall/opencv-rust#261]
When calling highgui::create_trackbar(), I get this deprecation warning:
`[ WARN:0] global /build/opencv/src/opencv-4.5.3/modules/highgui/src/window.cpp (703) createTrackbar UI/Trackbar(test bar@test window): Using 'value' pointer is unsafe and deprecated. Use NULL as value pointer. To fetch trackbar value setup callback.`

In the C++ api, you could just use a nullptr, but in rust, the argument is a reference, so I tried changing to an Option<&mut i32>, but the binding generator overrides it.

**Comment by twistedfall** [comment]
Thanks for the report, it should be fixed in v0.54.0, you can now pass `None` there.
