### ISSUE TITLE
get Mat pixel data

### ISSUE THREAD

**Issue by ggasilveira** [twistedfall/opencv-rust#263]
I'm trying to convert a Mat to a SDL2 Texture, since highgui is pretty bad. But I can't seem to figure out how to get the Mat internal data. I tried using data(), but it returns &u8. Shouldn't it return &[u8]? Or am I getting something wrong? If someone knows another way to do this, please, enlighten me. Thanks.

**Comment by twistedfall** [comment]
You can try using [`data_typed::<u8>()`](https://docs.rs/opencv/0.54.0/opencv/core/trait.MatTraitConstManual.html#method.data_typed). It would work if your `Mat` type is suitable. But generally you're right, `data()` should return `&[u8]`, I'll fix this.

**Comment by ggasilveira** [comment]
Thanks.  I ended up encoding the image to bitmap and then loading into a texture. Turns out it isn't nearly as slow as I thought, and way easier to deal with. Thanks anyway.
