### ISSUE TITLE
Missing bilinear interpolation constants

### ISSUE THREAD

**Issue by rdelfin** [twistedfall/opencv-rust#264]
> Before reporting an issue please first check the
> [troubleshooting guide](https://github.com/twistedfall/opencv-rust/blob/master/README.md#troubleshooting). If
> the issue you're encountering is not solved thereby please state the following in your bugreport:
> 1. Operating system
> 2. The way you installed OpenCV: package, official binary distribution, manual compilation, etc.
> 3. OpenCV version
> 4. rustc version (`rustc --version`)
> 5. Attach the full output of the following command from your project directory:
>    ```shell script
>    RUST_BACKTRACE=full cargo build -vv 
>    ```

The demosaic codes in `opencv::cudaimgproc` are incomplete. The [current file](https://github.com/rdelfin/opencv-rust/blob/master/src/opencv/hub/cudaimgproc.rs#L33-L56) contains all MHT demosaic modes and nothing else. On the other hand, the [OpenCV documentation](https://docs.opencv.org/3.4.15/d8/d01/group__imgproc__color__conversions.html) points towards a large number of other conversions that use bilinear interpolation (this is also present in [this crate's documentation](https://docs.rs/opencv/0.54.0/opencv/cudaimgproc/fn.demosaicing.html)).

I was gonna send a PR to fix this but I quickly realised that the relevant code is autogenerated, so I imagine something in the generator itself needs to be fixed. How do you add in these overrides, or what could be causing this?

**Comment by twistedfall** [comment]
Well, as long as these definitions are in the header files, they should generally be generated, it might be the case of missing `#include` or `#define`. Thanks for the reporting, I'll check it out!

**Comment by twistedfall** [comment]
The documentation is referring to the constants from the `imgproc` module, so e.g. `COLOR_BayerBG2GRAY` is here: https://docs.rs/opencv/0.54.0/opencv/imgproc/constant.COLOR_BayerBG2GRAY.html. So in this case there aren't any lapses in the binding generation.

**Comment by rdelfin** [comment]
Ah! Intersting. Does that mean that they don't support the algorithm in CUDA?

**Comment by twistedfall** [comment]
They are specifically mentioned in the cuda version of the [`demosaicing`](https://docs.opencv.org/3.4.15/db/d8c/group__cudaimgproc__color.html#ga7fb153572b573ebd2d7610fcbe64166e) function, so those constants should be supported.
