### ISSUE TITLE
Error in documentation: "download data from GpuMat"?

### ISSUE THREAD

**Issue by fzyzcjy** [twistedfall/opencv-rust#266]
I start trying this lib, and when looking at the definition of Mat - you know, the most basic class in opencv, I see: https://docs.rs/opencv/0.54.0/src/opencv/opencv/hub/core.rs.html#10311

```
	/// download data from GpuMat
	/// 
	/// ## Overloaded parameters
	/// 
	/// ## Parameters
	/// * rows: Number of rows in a 2D array.
	/// * cols: Number of columns in a 2D array.
	/// * type: Array type. Use CV_8UC1, ..., CV_64FC4 to create 1-4 channel matrices, or
	///    CV_8UC(n), ..., CV_64FC(n) to create multi-channel (up to CV_CN_MAX channels) matrices.
	pub unsafe fn new_rows_cols(rows: i32, cols: i32, typ: i32) -> Result<core::Mat> {
		{ sys::cv_Mat_Mat_int_int_int(rows, cols, typ) }.into_result().map(|r| { core::Mat::opencv_from_extern(r) } )
	}
```

Hmm but as we know, this has nothing to do with **GPU**?

**Comment by twistedfall** [comment]
Yep, you are right, this is a known problem with documentation generation. I get the info information like this from libclang and I haven’t found a way to work that around yet.

**Comment by fzyzcjy** [comment]
Not a big deal.

**Comment by twistedfall** [comment]
Please leave this open, this is a legitimate bug, which can be worked around

**Comment by fzyzcjy** [comment]
All right
