### ISSUE TITLE
Simple hello-world example takes 2.7MB (even excluding STL), but the equivalent in C++ only takes <1.0MB, so a 300% size increase

### ISSUE THREAD

**Issue by fzyzcjy** [twistedfall/opencv-rust#269]
1. Operating system: MacOS
2. The way you installed OpenCV: I am doing android, so download from official website
3. OpenCV version: 4.5
4. rustc version (`rustc --version`): rustc 1.55.0 (c8dfcfe04 2021-09-06)
5. Attach the full output of the following command from your project directory: see below
   ```shell script
   RUST_BACKTRACE=full cargo build -vv 
   ```

---

Hi thanks for the lib! I use it on Android, and see the hello-world example is even 2.7MB huge. So I wonder what am I doing wrong? Thanks!

rust code (very simple):

```
use opencv::core::*;

pub fn add(a: i64, b: i64) -> i64 {
    let m = Mat::zeros(a as i32, b as i32, CV_8UC1).unwrap();
    let size = m.size().unwrap();
    return (size.width + size.height) as i64;
}
```

cargo:

```
[package]
name = "vision_utils_rs"
version = "0.1.0"
edition = "2018"

[lib]
name = "vision_utils_rs"
crate-type = ["cdylib"]

[dependencies]
opencv = "0.54"
```

my build script:

```
export DYLD_FALLBACK_LIBRARY_PATH="$(xcode-select --print-path)/Toolchains/XcodeDefault.xctoolchain/usr/lib/"

export OPENCV_BASE_DIR=/Users/tom/Others/OpenCVRelease/OpenCV-android-sdk
export ANDROID_ABI=armeabi-v7a

export OPENCV_LINK_PATHS=$OPENCV_BASE_DIR/sdk/native/staticlibs/$ANDROID_ABI,$OPENCV_BASE_DIR/sdk/native/3rdparty/libs/$ANDROID_ABI
export OPENCV_LINK_LIBS=opencv_imgcodecs,opencv_features2d,opencv_calib3d,opencv_imgproc,opencv_highgui,opencv_core,tbb,cpufeatures,ittnotify,tegra_hal,IlmImf,liblibpng,liblibtiff,liblibwebp,liblibjasper,liblibjpeg-turbo,z
export OPENCV_INCLUDE_PATHS=$OPENCV_BASE_DIR/sdk/native/jni/include/

cargo ndk --target armeabi-v7a -o /Users/tom/QAPMain/Development/frontend/vision_utils/android/src/main/jniLibs build --release -vv
```

outputs:

```
(base) ➜  rust git:(master) ✗ cargo ndk --target armeabi-v7a -o /Users/tom/QAPMain/Development/frontend/vision_utils/android/src/main/jniLibs build --release -vv
[2021-09-29T07:23:14Z INFO  cargo_ndk::cli] Using NDK at path: /Users/tom/Library/Android/sdk/ndk/21.2.6472646
[2021-09-29T07:23:14Z INFO  cargo_ndk::cli] NDK API level: 21
[2021-09-29T07:23:14Z INFO  cargo_ndk::cli] Building targets: armeabi-v7a
[2021-09-29T07:23:14Z INFO  cargo_ndk::cli] Building armeabi-v7a (armv7-linux-androideabi)
       Fresh glob v0.3.0
       Fresh regex-syntax v0.6.25
       Fresh maplit v1.0.2
       Fresh dunce v1.0.2
       Fresh autocfg v1.0.1
       Fresh percent-encoding v2.1.0
       Fresh vcpkg v0.2.15
       Fresh shlex v1.1.0
       Fresh pkg-config v0.3.20
       Fresh once_cell v1.8.0
       Fresh memchr v2.4.1
       Fresh semver v1.0.4
       Fresh libc v0.2.103
       Fresh aho-corasick v0.7.18
       Fresh clang-sys v1.2.2
       Fresh jobserver v0.1.24
       Fresh num-traits v0.2.14
       Fresh clang v1.0.3
       Fresh regex v1.5.4
       Fresh cc v1.0.70
       Fresh opencv-binding-generator v0.29.0
       Fresh opencv v0.54.0
       Fresh vision_utils_rs v0.1.0 (/Users/tom/QAPMain/Development/frontend/vision_utils/rust)
    Finished release [optimized] target(s) in 0.03s
[2021-09-29T07:23:14Z INFO  cargo_ndk::cli] Copying libraries to /Users/tom/QAPMain/Development/frontend/vision_utils/android/src/main/jniLibs...
[2021-09-29T07:23:14Z INFO  cargo_ndk::cli] /Users/tom/QAPMain/Development/frontend/vision_utils/rust/target/armv7-linux-androideabi/release/libvision_utils_rs.so -> /Users/tom/QAPMain/Development/frontend/vision_utils/android/src/main/jniLibs/armeabi-v7a/libvision_utils_rs.so
```

look at size:

```
(base) ➜  rust git:(master) ✗ ls -al /Users/tom/QAPMain/Development/frontend/vision_utils/android/src/main/jniLibs/armeabi-v7a/libvision_utils_rs.so
-rwxr-xr-x  1 tom  staff  2853104  9 29 15:23 /Users/tom/QAPMain/Development/frontend/vision_utils/android/src/main/jniLibs/armeabi-v7a/libvision_utils_rs.so
```

**EDIT:** That size is for another demo code. Using the demo code I provide, it differs by several KB, so no big deal.

or look at size again, inside the apk file:

![image](https://user-images.githubusercontent.com/5236035/135222075-6fe07a96-0127-4f9d-ac01-37645558ed9a.png)

On the contrary, looking at this tutorial: https://stackoverflow.com/questions/63127202/how-to-use-opencv-4-in-native-c-of-flutter-in-2021-support-flutter-2-0/63127203#63127203 . 

> If you build in release mode and look at the apk size, you will see our .so file is less than 1MB. Thus static linking and file size reduction does work :)

that tutorial uses the code here: https://github.com/fzyzcjy/flutter_cpp_with_opencv/blob/master/ios/Classes/native_add.cpp . So it is equivalent to our code shown above.

Of course, if our code is:

```
use opencv::core::*;

pub fn add(a: i64, b: i64) -> i64 {
    a+b
}
```

I get result of 13.8KB (0.013MB) for the .so file, which is reasonable and small.

**Comment by twistedfall** [comment]
I'm not sure about how the Android build process works (but I'm really glad to know that it works there!), but when I build your example on the `x86_64-unknown-linux-gnu` target I'm indeed getting a 3,3M sized binary. The crate generates a lot of glue C++ code in the build process so that must be it. But just doing a simple `strip <output_binary>` reduces the size to 351K which is acceptable I think. Can you please try running `strip` (or equivalent) on your resulting binary?

**Comment by fzyzcjy** [comment]
@twistedfall Thanks for the reply! Well strip has no use... It is already "stripped" when I `file` it. Did you build in `--release` mode? If you built in debug mode I guess it should be big.

In addition, "a lot of glue c++ code" seems not to be as big as >1MB ;)

```
(base) ➜  rust git:(master) ✗ ls -al /Users/tom/QAPMain/Development/frontend/vision_utils/android/src/main/jniLibs/armeabi-v7a/libvision_utils_rs.so
-rwxr-xr-x  1 tom  staff  2844912  9 29 15:36 /Users/tom/QAPMain/Development/frontend/vision_utils/android/src/main/jniLibs/armeabi-v7a/libvision_utils_rs.so
(base) ➜  rust git:(master) ✗ file /Users/tom/QAPMain/Development/frontend/vision_utils/android/src/main/jniLibs/armeabi-v7a/libvision_utils_rs.so 
/Users/tom/QAPMain/Development/frontend/vision_utils/android/src/main/jniLibs/armeabi-v7a/libvision_utils_rs.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
(base) ➜  rust git:(master) ✗ strip /Users/tom/QAPMain/Development/frontend/vision_utils/android/src/main/jniLibs/armeabi-v7a/libvision_utils_rs.so 
(base) ➜  rust git:(master) ✗ ls -al /Users/tom/QAPMain/Development/frontend/vision_utils/android/src/main/jniLibs/armeabi-v7a/libvision_utils_rs.so
-rwxr-xr-x  1 tom  staff  2844912  9 29 15:36 /Users/tom/QAPMain/Development/frontend/vision_utils/android/src/main/jniLibs/armeabi-v7a/libvision_utils_rs.so
```

**Comment by fzyzcjy** [comment]
Wait a minute... Seems that this crate generates **all** functions binding to opencv. So, will the whole opencv be linked? Or compiler is smart enough, such that it knows "though you define thousands of functions, you never use it, so I also do not link opencv functions as well"?

**Comment by twistedfall** [comment]
Yes, I did build in release mode. The compiler should eliminate all the dead code, that's right. Are you linking `opencv` statically or dynamically? Can you please also post the output of `readelf -aC <output_so_name>`?

**Comment by fzyzcjy** [comment]
Sure. Here is the file:

[readelf.txt](https://github.com/twistedfall/opencv-rust/files/7249980/readelf.txt)

Indeed I can upload the .so file itself:

[libvision_utils_rs.so.zip](https://github.com/twistedfall/opencv-rust/files/7250008/libvision_utils_rs.so.zip)

> Are you linking opencv statically or dynamically?

Statically I guess. Looking at my configs, I link a lot of opencv_xxx.a

**Comment by fzyzcjy** [comment]
By the way, I see why I do not have symbols while you have: I use the `-o` in cargo ndk build, and it seems that it is not simply copying files to the output dir, but instead, copying and stripping. Because I see the raw .so file is not stripped, while the file in output folder is stripped.

**Comment by fzyzcjy** [comment]
So here is the .so file with symbols:

```
...target/armv7-linux-androideabi/release/libvision_utils_rs.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, with debug_info, not stripped
```

[libvision_utils_rs.so.zip](https://github.com/twistedfall/opencv-rust/files/7250243/libvision_utils_rs.so.zip)

**Comment by fzyzcjy** [comment]
Hi, is there any updates/suggestions? Thanks!

**Comment by twistedfall** [comment]
So far I don't really have any new information, the biggest 2 sections in this ELF are `.text` (program code) and `.rodata` (read-only statics). I'm not so good with ARM assembly so I haven't gotten too far as to finding out why `.text` is so large.

**Comment by fzyzcjy** [comment]
Well thank you all the same!

**Comment by fzyzcjy** [comment]
Later I find that, after implementing several algorithms, the Rust code size is not bigger than C++ code size. So I think this issue is indeed no problem.
