### ISSUE TITLE
cv::BackgroundSubtractorMOG::operator() is ignored

### ISSUE THREAD

**Issue by tfheen** [twistedfall/opencv-rust#27]
It seems like all operators are intentionally ignored. This is a bit problematic for the background subtractors, since that's how you compute a new mask. Would it be possible to have that exposed? The python bindings expose them as `apply()`, but I'm fine with any name.

See http://docs.opencv.org/2.4/modules/video/doc/motion_analysis_and_object_tracking.html#backgroundsubtractor-operator and its siblings for the function I'm talking about.

**Comment by kali** [comment]
I'm in "maintenance mode" on this project. Feel free to experiment and send a patch, though.

**Comment by johnfercher** [comment]
I'm trying to use MOG2, but the method `apply()` still ignored. Any news about this issue?

**Comment by tfheen** [comment]
I ended up not doing anything further with opencv-rust, but I think just removing "apply" from the blacklist of functions to ignore ought to work.

**Comment by twistedfall** [comment]
`apply` method is currently (since version 0.4) included in the generated bindings
