### ISSUE TITLE
Error build on MacOS

### ISSUE THREAD

**Issue by virtuehive** [twistedfall/opencv-rust#271]
error: failed to run custom build command for `opencv v0.54.0 (/Users/newmac/opencv-rust)`

Caused by:
  process didn't exit successfully: `/Users/newmac/opencv-rust/target/release/build/opencv-e8b62b34db1e2c4c/build-script-build` (signal: 6, SIGABRT: process abort signal)
  --- stderr
  dyld: Library not loaded: @rpath/libclang.dylib
    Referenced from: /Users/newmac/opencv-rust/target/release/build/opencv-e8b62b34db1e2c4c/build-script-build
    Reason: image not found

**Comment by twistedfall** [comment]
Please check [Troubleshooting](https://github.com/twistedfall/opencv-rust#troubleshooting), item 6

**Comment by virtuehive** [comment]
ouw sure .  I didn't read that . it works! thanks
