### ISSUE TITLE
Passing Mat to C++ library binding

### ISSUE THREAD

**Issue by JonBoyleCoding** [twistedfall/opencv-rust#274]
Hi,

I'm having to use a C++ project as an interface to a library due it containing some template code that bindgen doesn't work with. Is there an easy way to pass through a Mat from this library to a cv::Mat from a C++ library? At the moment, I've got code that attempts to pass the image data through to the C++ project and create a cv::Mat to return for later usage (as below) but it has a number of side effects (as below). I was wondering to have a more elegant way to just have a Mat from this library and pass it through somehow?

```
cv::Mat OpenCVInterface::GetMat(int frameWidth, int frameHeight, int cv_type, const uint8_t *p_imageData) {
    cv::Mat image(frameHeight, frameWidth, cv_type, (void*) p_imageData);
    return image;
}
```

**Comment by twistedfall** [comment]
Hi, you should be able to use [`Mat::into_raw()`](https://docs.rs/opencv/0.54.0/opencv/core/struct.Mat.html#method.into_raw) to get a `cv::Mat*` then pass it into the C++ lib. Just be sure to `delete` that pointer when it's no longer needed. This pointer is allocated by C++ side with just `new Mat()`.

**Comment by twistedfall** [comment]
I hope you managed to fix the issue you were having. If not please feel free to reopen the issue.
