### ISSUE TITLE
(Willing to make a PR) add "Mat view" struct for easier manipulation on raw bytes data

### ISSUE THREAD

**Issue by fzyzcjy** [twistedfall/opencv-rust#278]
Hi thanks for the lib! I am writing a MatView struct for easier manipulation of raw data. A draft is as follows. If you want I can make a PR.

Draft

```
use std::ops::*;

use anyhow::{anyhow, Result};
use opencv::core::CV_8UC1;
use opencv::prelude::*;

pub struct MatView<'a, T> {
    rows: usize,
    cols: usize,
    data: &'a mut [T],
}

impl<'a> MatView<'a, T> {
    pub fn new(rows: usize, cols: usize, data: &'a mut [T]) -> Self {
        assert_eq!(rows * cols, data.len());
        MatView { rows, cols, data }
    }

    pub fn from_mat(mat: &'a mut Mat) -> Result<Self> {
        let size = mat.size()?;
        Ok(Self::new(
            size.height as usize,
            size.width as usize,
            mat.data_typed_mut::<T>()?,
        ))
    }
}

impl<T> MatView<'_, T> {
    unsafe fn get_unchecked(&self, i: usize, j: usize) -> &T {
        self.data.get_unchecked(self.calc_index_unchecked(i, j))
    }

    unsafe fn get_unchecked_mut(&mut self, i: usize, j: usize) -> &mut T {
        let idx = self.calc_index_unchecked(i, j);
        self.data.get_unchecked_mut(idx)
    }
}

impl<T> MatView<'_, T> {
    fn calc_index(&self, i: usize, j: usize) -> usize {
        assert!(i < self.rows);
        assert!(j < self.cols);
        self.calc_index_unchecked(i, j)
    }

    fn calc_index_unchecked(&self, i: usize, j: usize) -> usize {
        i * self.cols + j
    }
}

impl<T> Index<(usize, usize)> for MatView<'_, T> {
    type Output = T;

    fn index(&self, (i, j): (usize, usize)) -> &Self::Output {
        &self.data[self.calc_index(i, j)]
    }
}

impl<T> IndexMut<(usize, usize)> for MatView<'_, T> {
    fn index_mut(&mut self, (i, j): (usize, usize)) -> &mut Self::Output {
        let idx = self.calc_index(i, j);
        &mut self.data[idx]
    }
}
```

**Comment by twistedfall** [comment]
Can you please give me a bit of context? What's the advantage of `MatView` over `Mat`?

**Comment by fzyzcjy** [comment]
Shortly speaking: Tons of access to the individual pixels of a Mat, such as scanning images, do transforms based on pixels and its neighbors, etc. I do that a lot in my algorithms, and imho that is quite common.

If using Mat's `at`, it is obviously too slow. If using Mat's `data_bytes_mut`, it is surely OK, but that is a flattened 1D array, so it is not that easy to work with. Thus, MatView is nothing but a simple wrapper for the `mat.data_bytes_mut()`, allowing you to say the x and y coordinate and it transfer to the corresponding pixel location.

Related: https://docs.opencv.org/master/db/da5/tutorial_how_to_scan_images.html

**Comment by twistedfall** [comment]
Well, it certainly can be useful, but I see this more as a separate crate. I'd like to keep the manual code in the `opencv` crate to the minimum required to mimic OpenCV entities that can not be automatically translateable to Rust (yet) like generic classes (e.g. `core::Point_`). Otherwise it increases the support burden which is already quite high.

**Comment by fzyzcjy** [comment]
Ok. Indeed this is so simple that making it a separate crate seems to heavy ;) So I may just leave this issue here such that it may hint other people.
