### ISSUE TITLE
(Willing to make a PR) Can we support C++ operators? This will make code much neater!

### ISSUE THREAD

**Issue by fzyzcjy** [twistedfall/opencv-rust#279]
Hi thanks for the lib! README mentions:

> C++ operators
> Some C++ operators are supported, they are converted to the corresponding functions on Rust side. Here is the list with the corresponding function name:
> 
> [] → get() or get_mut()
> + → add()
> - → sub()
> * → mul()
> / → div()
> * (deref) → deref() or deref_mut()

However, we know in Rust we can also override such operators. For example, `impl Sub<Sth> for Mat {...}`, then use like `mat_one - mat_two`. Therefore, I wonder whether we can have that? Thanks!

The reason is that, this will make code much, much, much neater. Seems that, currently, I have to call things like `sub_mat_mat` which is quite ugly, because I have a lot of long expressions on matrixs :(

**EDIT**

I guess the reason of "no" is because the return type is `Result<...>`. Therefore, can we make a simple macro + impl Add/Sub/...? The proposal is as follows:

```
impl Sub<Mat> for Mat {
  type Output = Result<MatExpr>; // NOTE, it is Result
  ...
}
```

Then, write a procedural macro. It inputs an expression such as `my_macro! { a - b * c / d }`, and when traversing the syntax tree, it adds "?" accordingly. For example, it becomes `(a-((b*c)?/d)?)?`.

Then it is much neater than `(a.sub((b.mul(c)?.div(d)?)))?`

p.s. [procedural macros](https://doc.rust-lang.org/reference/procedural-macros.html) gives a TokenStream. Then we can use [syn](https://docs.rs/syn/1.0.80/syn/) to construct an AST that knows, for example, "*" has higher precedence over "+".
Indeed, for the procedural macro, we only need to blindly find out the `std::ops::*` nodes such as Add or Sub, then inject a new node of "?" above it.

**Comment by twistedfall** [comment]
Let me think about it a little. But yes, you are right, the initial reason is the necessity to return `Result`.

**Comment by fzyzcjy** [comment]
I can do the part of macro and make a PR, probably using https://docs.rs/syn/1.0.80/syn/fold/index.html to transfer the AST. I am not familiar with opencv-rust's code generator, so may not be able to do the `impl Sub<Something> for Another` part - but imho that part is not hard, just change a little bit of output.

**Comment by fzyzcjy** [comment]
I have started working on the macro part.

**Comment by fzyzcjy** [comment]
@twistedfall Hi, the procedure macro is done now. See: https://github.com/fzyzcjy/opencv-rust-ext

Example:

```
// not compile yet, since Mat does not support Add/Sub/...
#[test]
fn test_expr_macro_opencv() -> Result<()> {
    let a = Mat::new_rows_cols_with_default(3, 5, CV_8UC1, 42.0.into())?;
    let b = Mat::new_rows_cols_with_default(3, 5, CV_8UC1, 100.0.into())?;
    let c = 10u8;
    assert_eq!(
        failable_expr! { a + b - c },
        Mat::new_rows_cols_with_default(3, 5, CV_8UC1, 132.0.into())
    );
    Ok(())
}

#[test]
fn test_expr_macro_simple() -> Result<()> {
    let a = 42;
    let b = 100;
    let c = 10u8;
    assert_eq!(failable_expr! { a + b - c }, 132,);
    Ok(())
}
```

**Comment by fzyzcjy** [comment]
The `impl Sub<Something> for Mat` have to be implemented in the opencv crate, instead of any other crates. Otherwise:

```
error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
 --> src/ops.rs:5:1
  |
5 | impl Add<Mat> for Mat {
  | ^^^^^--------^^^^^---
  | |    |            |
  | |    |            `opencv::prelude::Mat` is not defined in the current crate
  | |    `opencv::prelude::Mat` is not defined in the current crate
  | impl doesn't use only types from inside the current crate
  |
  = note: define and implement a trait or new type instead

For more information about this error, try `rustc --explain E0117`.
error: could not compile `opencv_ext` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by fzyzcjy** [comment]
Any updates? Or could you please give some hints on where I should dig into the source code?

**Comment by twistedfall** [comment]
Thanks! I'll try to find some time this weekend to add the `impl`s into the binding generation

**Comment by fzyzcjy** [comment]
Looking forward to it!

**Comment by fzyzcjy** [comment]
Wait a bit - I find a problem in the procedural macro approach. Indeed, now I am trying another approach, with with you can just need do do *nothing* except merging my PR (will create a PR soon).

**Comment by fzyzcjy** [comment]
PR created: https://github.com/twistedfall/opencv-rust/pull/280

Just need to merge the PR, no need for anything more - no need for writing down even a single line of code generator code ;)

**Comment by fzyzcjy** [comment]
What it achieves (example):

```
    let a = Mat::new_rows_cols_with_default(2, 3, CV_8UC1, 100.0.into())?;
    let b = Mat::new_rows_cols_with_default(2, 3, CV_8UC1, 10.0.into())?;
    let c = Mat::new_rows_cols_with_default(2, 3, CV_8UC1, 50.0.into())?;
    let d = Mat::new_rows_cols_with_default(2, 3, CV_8UC1, 2.0.into())?;
    let x = (&a / d - &b + &c / 2.0f64 - Scalar::from(10f64))
        .into_result()?
        .to_mat()?;
    println!("x={:?}", x.data_bytes());
```

Notice that it:

* handles error. only one `.into_result()?` after *finishing all* chained operators is enough. no need for verbose `?` after each math operation, such as `(((a+b)?+c)?+d)?`.
* handles Mat, MatExpr, Scalar, f64 and interaction between them
* handles both Something and &Something (e.g. Mat and &Mat; MatExpr and &MatExpr). If only handles Mat but no &Mat, after math operations your original Mat can never be reused, which is awful. If only handles &Mat but no Mat, you have to write `&(&(a+b)+c)+d` and so on, which is still too verbose.
