### ISSUE TITLE
example text detection does not compile, and also does not work?

### ISSUE THREAD

**Issue by zzlk** [twistedfall/opencv-rust#282]
Before reporting an issue please first check the
[troubleshooting guide](https://github.com/twistedfall/opencv-rust/blob/master/README.md#troubleshooting). If
the issue you're encountering is not solved thereby please state the following in your bugreport:
1. Operating system 
arch linux

2. The way you installed OpenCV: package, official binary distribution, manual compilation, etc.
arch linux package

3. OpenCV version
4.5.4

4. rustc version (`rustc --version`)
rustc 1.55.0 (c8dfcfe04 2021-09-06)

5. Attach the full output of the following command from your project directory:
   ```shell script
   RUST_BACKTRACE=full cargo build -vv 
   ```
I can attach this if it is necessary.

I noticed that the text detection example is commented out in the cargo.toml file
https://github.com/twistedfall/opencv-rust/blob/master/Cargo.toml#L35

and I suspect that the api for dnn detector has changed since that example was ported over. I think the "detector.detect" function no longer exists and has been replaced by "detector.predict".

https://github.com/twistedfall/opencv-rust/blob/master/examples/text_detection.rs#L80

once you replace detector.detect with detector.predict it can then compile, however, I could not get the example to work as it now fails at runtime with an internal opencv error which is thrown from line 80 in text_detection.rs.

`Err` value: Error { code: -213, message: "OpenCV(4.5.4) /build/opencv/src/opencv-4.5.4/modules/core/src/matrix_wrap.cpp:2052: error: (-213:The function/feature is not implemented)  in function 'assign'\n" }

I think this is coming from here:
https://github.com/opencv/opencv/blob/master/modules/core/src/matrix_wrap.cpp#L1906

but i don't really understand anything about opencv. I noticed that it is doing some sort of conditional on the kind of the matrix and I am wondering if something is being lost by the bindings?

Alternatively if you could confirm that the example still works then that would also help me a lot.

**Comment by zzlk** [comment]
I have looked into it a lot more and now I think this is a bindgen issue. in C++ TextDetectionModel_EAST is supposed to inherit from TextDetectionModel. and the detect() method comes from TextDetectionModel. But this is not really reflected in the bindgen output, there's no implementation of detect() for TextDetectionModel_EAST.

I have run other examples and they seem to work fine, so I'm not sure why I have this issue unless this example is specifically broken.

**Comment by twistedfall** [comment]
Hi, it looks like it broke because of the changes in OpenCV 4.5.4 or 4.5.3, let me verify that

**Comment by zzlk** [comment]
with opencv 4.5.2 installed I get:

error[E0599]: no method named `detect` found for struct `TextDetectionModel_EAST` in the current scope
   --> src/main.rs:104:12
    |
104 |         detector.detect(&frame, &mut det_results).unwrap();
    |                  ^^^^^^ method not found in `TextDetectionModel_EAST`

For more information about this error, try `rustc --explain E0599`.

and if i downgrade to opencv 4.5.1 it compiles successfully (and then fails to link, but I'm pretty sure that is my problem). So, I think the change occured between 4.5.1 and 4.5.2.

**Comment by twistedfall** [comment]
Thanks for checking! I'll update the example to work on the newer OpenCV

**Comment by twistedfall** [comment]
It's been fixed in 0.58.0, the example was still correct, there just was a need to apply some tuning to the binding generation for the newer OpenCV.
