### ISSUE TITLE
Problems using SimpleBlobDetector

### ISSUE THREAD

**Issue by ggasilveira** [twistedfall/opencv-rust#284]
I'm trying to use `SimpleBlobDetector`, but the constructor returns a `Ptr<SimpleBlobDetector>`, and I don't know how to dereference the pointer. I tried to cast it into a raw pointer, but I didn't find a suitable `SimpleBlobDetector` constructor.

I don't know if this is a bug, but I didn't find anywhere else to post this. Thanks.

**Comment by twistedfall** [comment]
What method are you trying to call? `Ptr<SimpleBlobDetector>` implements all methods of `SimpleBlobDetector` so you shouldn’t have any problems using it. Just be sure to import the prelude: `use opencv::prelude::*`, it has a lot of vital traits.

**Comment by ggasilveira** [comment]
Well, damn me, that was it. Thanks.
