### ISSUE TITLE
Can we have a OpenCV-Python like API?

### ISSUE THREAD

**Issue by fzyzcjy** [twistedfall/opencv-rust#286]
Hi thanks for the lib! I wonder whether we can have a OpenCV-Python like API? For example, the following is current signature:

`pub fn connected_components_with_stats(image: &dyn core::ToInputArray, labels: &mut dyn core::ToOutputArray, stats: &mut dyn core::ToOutputArray, centroids: &mut dyn core::ToOutputArray, connectivity: i32, ltype: i32) -> Result<i32>`

But I hope we can use the python-like:

`let (num_cc, all_labels, all_stats, all_centroids) = connected_components_with_stats(im);`

**Comment by twistedfall** [comment]
Hi! That’s unlikely at least for the current implementation. The current API is a direct translation of the C++ headers and I’m trying to keep it as close to it as possible. The upside is that it currently covers way more functions than Python OpenCV bindings.

**Comment by fzyzcjy** [comment]
Ah... Thank you!

**Comment by fzyzcjy** [comment]
Hi, maybe it is not that hard to do imho. OpenCV has already given hints in its source code such that its python binding can be generated automatically. We may be able to use this information as well imho.

Another way is that, it seems that the opencv-rust already knows which are outputs (and inject `output_array_arg!(...)` code there). So maybe just simply move them to return types.

We can make a new sub-module instead of modifying the old API, so people can use both of the styles. You know, the python style is much less verbose.

**Comment by twistedfall** [comment]
Well, not all of the output arguments imply a new object. Sometimes you want to modify one that you already have. Like for example ellipse drawing function.

The Python hints are all in the corresponding Python file that handles the binding generation. So to read that you need to parse Python code.

**Comment by fzyzcjy** [comment]
Sounds reasonable. Originally I thought, when looking at files like https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core.hpp, the `CV_EXPORTS` macro may be helpful. But then I see it is not.

**Comment by fzyzcjy** [comment]
After some digging, seems that

> The Python hints are all in the corresponding Python file that handles the binding generation

may not be accurate. python code maybe generated from c++ code? https://github.com/opencv/opencv/blob/39c3334147/modules/python/src2/gen2.py

**Comment by twistedfall** [comment]
OpenCV implements its own ad-hoc C++ header parser, which is used by Java and Python binding generators (and by this crate prior to version 0.30) but all the additional hints regarding the Python code specifically are in that Python file.

After some closer look I think you were right initially and arguments marked as `OutputArray` in contrast with `InputOutputArray` are purely for output so it should be possible to return them as tuple in theory. It presents some additional challenges though because now you can pass anything that implements `ToOutputArray` (e.g. `Mat`, `UMat`, `Vector<T>`) and if you return it as a tuple you'll need to either restrict it to one specific type or make a function generic over the return type(s).

**Comment by fzyzcjy** [comment]
Thanks for the reply!

> if you return it as a tuple you'll need to either restrict it to one specific type or make a function generic over the return type(s).

IMHO generic is no problem. The generated rust function itself is quite small, so even if generic causes the binary size to be bigger it seems not a lot; and moreover people seldomly use multiple kinds of outputarrays.
Then it sounds like not a huge workload, since we already know which are OutputArray.
