### ISSUE TITLE
Implement `Default` for `Mat`?

### ISSUE THREAD

**Issue by fzyzcjy** [twistedfall/opencv-rust#287]
Hi thanks for the lib! We already have `Mat::default`, so what about trivially impl the `Default`? Then we can use things like `let (mut a, mut b, mut c): (Mat,Mat,Mat) = Default::default();`

**Comment by twistedfall** [comment]
Makes perfect sense, I’ll update it!

**Comment by twistedfall** [comment]
Can you please test the `rel` branch to see if it fixes the issue for you?

**Comment by twistedfall** [comment]
Fixed in v0.56.1

**Comment by fzyzcjy** [comment]
:tada:
