### ISSUE TITLE
Support equality? (Example usage: When testing matrices)

### ISSUE THREAD

**Issue by fzyzcjy** [twistedfall/opencv-rust#288]
Hi thanks for the lib! I wonder how to check two mat are equal? It does not seem to implement Eq trait while imho it can be implemented, by, for example, checking types and data bytes.

**Comment by twistedfall** [comment]
Support for `==` operator is now available in v0.57.0. OpenCV doesn't seem to implement a direct comparison between `Mat`s yielding `bool`. There is [`core::equals`](https://github.com/twistedfall/opencv-rust/blob/master/src/opencv/hub/core.rs#L5212) function which does per-element comparison. I hope that helps!

**Comment by fzyzcjy** [comment]
Thanks!

**Comment by fzyzcjy** [comment]
Hi, I find that there is no Eq or PartialEq implemented for Mat. Using == will error:

```
error[E0369]: binary operation `==` cannot be applied to type `opencv::prelude::Mat`
  --> src/utils/indexed_image.rs:22:18
   |
22 |         self.mat == other.mat && self.palette == other.palette
   |         -------- ^^ --------- opencv::prelude::Mat
   |         |
   |         opencv::prelude::Mat
```

**Comment by twistedfall** [comment]
OpenCV itself doesn't implement a comparison between 2 `Mat`s that yields bool, i.e. this C++ code fails:
```c++
int main(int argc, char** argv)
{
	Mat a;
	Mat b;
	bool c = a == b;
}

test.cpp: In function ‘int main(int, char**)’:
test.cpp:16:20: error: cannot convert ‘cv::MatExpr’ to ‘bool’ in initialization
   16 |         bool c = a == b;
      |                  ~~^~~~
      |                    |
      |                    cv::MatExpr
```
so there is no way to implement `PartialEq` in a way that's native to OpenCV.

**Comment by fzyzcjy** [comment]
> Support for == operator is now available in v0.57.0.

Then I wonder what is available then...

IMHO we can make a very short function manually, e.g. (ignore grammar error)

```
impl PartialEq for Mat {
fn eq(&self, other) {
  self.typ() == other.typ() && self.get_data_bytes() == other.get_data_bytes()
}
}
```

**Comment by eadf** [comment]
>IMHO we can make a very short function manually

Maybe a quick test for C ptr equality first (+ other metadata needed to cover the Mat::roi case)?

```
if mat1_ptr.eq(mat2_ptr) && compare_roi_parameters(mat1,mat2) 
  return true
else 
  compare_value_by_value(mat1, mat2)
```

**Comment by twistedfall** [comment]
> Then I wonder what is available then...

The `operator ==` is now converted to `equals` function, e.g. [MatSize::equals](https://docs.rs/opencv/0.61.0/opencv/core/trait.MatSizeTraitConst.html#method.equals).

For `Mat` it's [equals](https://docs.rs/opencv/0.61.0/opencv/core/fn.equals.html), but it's defined not as an instance method, but as a free function that takes 2 `Mat`s and returns `MatExpr` having a per-element comparison matrix. So you can't implement `PartialEq` from that.

**Comment by fzyzcjy** [comment]
Maybe write down our own small function instead of reusing an existing opencv function

**Comment by twistedfall** [comment]
That might not be as easy, for example your variant doesn't take shape and size into account, there are other properties that are more dubious, do you need to take `is_continous` into account or not? That might depend on the particular use case, so writing universal comparison function is more difficult than it seems. Comparing `Mat`s by pointer value will not really work in this case because all `Mat`s are different in that regard.

**Comment by fzyzcjy** [comment]
@twistedfall Good question... Maybe we should look at how numpy or Rust ndarray compare equality and choose a style that is similar?

**Comment by twistedfall** [comment]
I generally try to not (manually) implement any functionality that's not already available in OpenCV itself, so let's keep it as it is.
