### ISSUE TITLE
(willing to make a pr) Must impl `ToOutputArray` for `VectorOfMat2f`, otherwise `HoughLines` cannot output (may be trivial since already impl its neighbors)

### ISSUE THREAD

**Issue by fzyzcjy** [twistedfall/opencv-rust#289]
Hi thanks for the lib! Looking at this example https://docs.opencv.org/4.5.3/d5/df9/samples_2cpp_2tutorial_code_2ImgTrans_2houghlines_8cpp-example.html#a9, seems that HoughLines's `lines` output is `vector<Vec2f>`. So it is `VectorOfVec2f` in Rust. However, [ToOutputArray](https://docs.rs/opencv/0.56.0/opencv/core/trait.ToOutputArray.html) only implements things like VectorOfVec2i, VectorOfVec3f, etc, but forget this particular one.

**Comment by twistedfall** [comment]
A quick solution would be to use `Mat` instead of `VectorOfVec2f` for output argument. But I will update the bindings to include that impl too.

**Comment by fzyzcjy** [comment]
I have found that workaround just now, but thanks for the info as well!

**Comment by twistedfall** [comment]
Can you please test the `rel` branch to see if it fixes the issue for you?

**Comment by twistedfall** [comment]
Fixed in v0.56.1

**Comment by fzyzcjy** [comment]
:tada:
