### ISSUE TITLE
opencv::contrib

### ISSUE THREAD

**Issue by mario-s** [twistedfall/opencv-rust#29]
I'm trying to include the contrib module of opencv 2.4.13.2.

So I added this snippet to the build.rs:
`("contrib", vec!["contrib/contrib.hpp" ]),`

Then I run into a problem that a method is already defined:
contrib.cpp:1289:31: error: redefinition of 'cv_contrib_cv_SpinImageModel_getMesh
contrib.cpp:1265:31: note: previous definition is here

So I added this line of code to the Python script (gen_rust.py):
`"cv_contrib_cv_SpinImageModel_getMesh": "getMesh",`

However I still get the same error.

How can I solve this?

**Comment by twistedfall** [comment]
You can now build crate against opencv with contrib and some contrib modules are being generated
