### ISSUE TITLE
Allow generic channel size for at_* methods.

### ISSUE THREAD

**Issue by szandara** [twistedfall/opencv-rust#291]
I am  doing some image manipulation on a 7 channels image (coming from a neural network) and I am unable to read the data or write the data (at least using these methods). I am interested in reading the data from a single pixel (7-channel pixel) using something like ```mat.at_2d::Vec<f32>(x, y)``` but it simply complains that it's not implemented.

```
        let pixel_info = self.at_2d::<Vec<f32>>(row as i32, col as i32)?;
```
leads to

```
^^^^^ the trait `opencv::prelude::DataType` is not implemented for `Vec<T>
````

I tried to fetch the data manually but it does not work as the returned row size is not n_channels * n_cols but just n_cols.

```
        unsafe {
            let self_data = self.at_row_unchecked_mut::<f32>(row as i32)?;
            self_data[pixel_position..pixel_position + channels].copy_from_slice(&data);
        }
```

```
---- inference::nd_array_utils::tests::test_get_2d stdout ----
isContinuous Ok(true), step [
    800,
    4,
]
, elemSize Ok(4), size Size_ { width: 200, height: 100 }
thread 'inference::nd_array_utils::tests::test_get_2d' panicked at 'range end index 404 out of range for slice of length 200', ./nd_array_utils.rs:47:16
```

The methods under MatTrait and MatTraitConst, namely ```at_*``` do seem to work only with a pre-defined number of Vec types: Vec1, Vec2, Vec3, Vec4, Vec6 and Vec8. This is not flexible enough.

I think that ```DataType``` traits should be extended for a generic Vector size which depends on the number of channels.

Am I using the right tools? Is there another way to achieve what I want?

## Prefilled data

Before reporting an issue please first check the
[troubleshooting guide](https://github.com/twistedfall/opencv-rust/blob/master/README.md#troubleshooting). If
the issue you're encountering is not solved thereby please state the following in your bugreport:
1. Operating system 
Ubuntu on WSL2 (Windows 11)
2. The way you installed OpenCV: package, official binary distribution, manual compilation, etc. 
Ubuntu apt
3. OpenCV version: 
4
4. rustc version (`rustc --version`)
5. Attach the full output of the following command from your project directory:
```
---- inference::nd_array_utils::tests::test_get_2d stdout ----
isContinuous Ok(true), step [
    800,
    4,
]
, elemSize Ok(4), size Size_ { width: 200, height: 100 }
thread 'inference::nd_array_utils::tests::test_get_2d' panicked at 'range end index 404 out of range for slice of length 200', ./nd_array_utils.rs:47:16
```

**Comment by twistedfall** [comment]
I'm actually rewriting the crate `Vec` implementation to use const generics which should make it flexible enough for your case. Can you check the `new_vec` branch and see if it works for you? You'd use `opencv::core::Vec<f32, 7>` type for the `at_2d` call. Note the name `Vec` is the same as the Rust built-in `Vec` so be mindful of which you specify.

**Comment by twistedfall** [comment]
This is now part of the 0.57.0 release, please test

**Comment by szandara** [comment]
Thanks a lot for the quick response. I have tested the change and it works perfectly!

It's somehow disappointing that OpenCV does not allow accessing a pixel of unknown channel size. Working with tensors you don't have this problem. In OpenCV you are forced to do

```
mat.at<Vec3b>(x, y)
```

it would be great to have the option to do

```
mat.at<Vec<u8>>(x, y)
```

I don't see why the size must be known at compile time.  Do you happen to know if that's possible?
I am anyway closing the ticket as I am now unblocked!

**Comment by twistedfall** [comment]
> I don't see why the size must be known at compile time.

In this particular case Rust needs to know the size of the structure to lay it out on stack. But in theory it should be possible to return a dynamic heap allocated object that would allow such access. Can you please point me to where it's used like this in `tensors` (I imply you're referring to the crate/lib)? I might take inspiration in their approach.

**Comment by szandara** [comment]
It looks like this is a limitation of OpenCV in general. In NDArray or Tensors implementations (for Rust I use  https://docs.rs/ndarray/0.15.3/ndarray/) you can do something like

```
let image_cropped = image_area.slice(s![0, 5..205, 8..108, ..]);
```

image_cropped is an NDArray 3 channels but unknown channel size at compile time.

**Comment by twistedfall** [comment]
And how would you retrieve a single pixel from `image_cropped` after that?

**Comment by szandara** [comment]
You can for example take it as an array in this way

```
        println!(
            "image_pixel at 1,1 {:?}",
            image_cropped.slice(s![1, 1, ..]).as_slice()
        );
```

it will print this

``` Some([-0.5, 0.44117647, -0.22549018])```

**Comment by twistedfall** [comment]
I see, well, you should be able to convert a `Mat` to ndarray's `Array` and then you can work with that. There is actually a separate crate for such conversions: https://crates.io/crates/cv-convert

**Comment by szandara** [comment]
Yea absolutelty, I have just been using them interchangebly. I have made my own conversions lib but indeed each conversion has a cost, if you can avoid it it's better :)

**Comment by twistedfall** [comment]
I see. I'll try to look into making this easier to use
