### ISSUE TITLE
Portability issue on AArch64

### ISSUE THREAD

**Issue by YuanYuYuan** [twistedfall/opencv-rust#292]
Hi, we encountered a problem while using `fourcc` as below.

~~~
let fourcc = videoio::VideoWriter::fourcc('M' as i8, 'J' as i8, 'P' as i8, 'G' as i8)?;
    |                                                           ^^^^^^^^^ expected `u8`, found `i8`
    |
help: you can convert an `i8` to a `u8` and panic if the converted value doesn't fit
~~~

This is caused by treating char the same way crossing different architecture. 
Our machine is AArch64, which treats char as unsigned char by default.  
Maybe we can use `std::os::raw::c_uchar` alternatively [here](https://github.com/twistedfall/opencv-rust/blob/master/binding-generator/src/type_ref.rs#L135-L157)?

**Comment by twistedfall** [comment]
That's a sound suggestion, I'll look into it. In the meanwhile can you please tell me where this code is coming from and what's going to happen if you cast it as `u8` instead of `i8`?

**Comment by YuanYuYuan** [comment]
Hi, thanks for your reply. The code is part of our own lab project, which handles the video recording. And the program can pass the compilation after changing from i8 to u8. Since our code may run on both x86_64 and aarch64, we think there is still a need to make this compatible.

**Comment by twistedfall** [comment]
The thing is, the underlying OpenCV API is using char type: https://docs.opencv.org/4.5.4/dd/d9e/classcv_1_1VideoWriter.html#afec93f94dc6c0b3e28f4dd153bc5a7f0 so I can’t strictly choose either signed or unsigned type. In your case casting the arguments as `std::os::raw::c_char` instead of `i8` or `u8` will fix the issue with cross-compilation.

**Comment by YuanYuYuan** [comment]
Thanks! This change makes our code work. Let's close the issue.
