### ISSUE TITLE
Select bindings to generate

### ISSUE THREAD

**Issue by ggasilveira** [twistedfall/opencv-rust#293]
I'm currently only using a subset of the API, but the entirety of the bindings gets generated, making compile times / rust-analyzer very slow. Is there a way to choose which modules to generate bindings from? I tried setting OPENCV_MODULES_WHITELIST, but it still generated all of the bindings.

**Comment by twistedfall** [comment]
`OPENCV_MODULE_WHITELIST` should work, can you tell me more about how you use it?

**Comment by ggasilveira** [comment]
I think I got it. I was trying to set it in the build.rs file, but I think that didn't work. Setting it manually is working. Is there a way to set it in the build.rs file?

**Comment by twistedfall** [comment]
I’m not sure what you mean by setting it manually. `OPENCV_MODULE_WHITELIST` is an environment variable that build.rs will read during the build phase. It’s expected that you set it before building your crate that depends on OpenCV.

**Comment by ggasilveira** [comment]
What i mean is setting the variable in my custom build.rs, with something like `println!("cargo:rustc-env=VAR=KEY")`, so I don't have to set it in the shell.

**Comment by twistedfall** [comment]
The thing is your build.rs runs after the build.rs of the crate so I am not sure it’s possible.

**Comment by ggasilveira** [comment]
Oh, so that's it. Thanks for the help.

**Comment by ggasilveira** [comment]
I think I figured it out. this [cargo feature](https://doc.rust-lang.org/nightly/cargo/reference/config.html#env) makes it possible to pass environment variables to upstream crates.

**Comment by twistedfall** [comment]
Hm, I didn’t know about it! Thanks!
