### ISSUE TITLE
Types like "MatView" or "MatViewMut" (jut like ndarray's ArrayView/ArrayViewMut), allowing a Mat that does not own its data?

### ISSUE THREAD

**Issue by fzyzcjy** [twistedfall/opencv-rust#294]
Hi thanks for the lib! I have a `ndarray::Array` (or `image::Image` or something like that) that holds data. Then I want to use some opencv functions, so I want to create a Mat that does not *own* its data, but instead, it simply *borrows* the data from that ndarray/image/...

This seems to be technically feasible (please correct me if I am wrong!), because [new_rows_cols_with_data](https://docs.rs/opencv/0.57.0/opencv/core/struct.Mat.html#method.new_rows_cols_with_data) and the underlying opencv implementation allows a Mat to use an external pointer pointing to a buffer, instead of allocating things inside it. 

For more detail see this link: https://docs.opencv.org/4.5.2/d3/d63/classcv_1_1Mat.html#a51615ebf17a64c968df0bf49b4de6a3a

> data | Pointer to the user data. Matrix constructors that take data and step parameters do not allocate matrix data. Instead, they just initialize the matrix header that points to the specified data, which means that no data is copied. This operation is very efficient and can be used to process external data using OpenCV functions. The external data is not automatically deallocated, so you should take care of it.

However, when implementing it by myself I do see some problems in the Rust details. Ideally we want something like `fn ndarray_as_mat(a: &Array) -> &Mat`. However, the `Mat` has some headers, so it is impossible to "borrow" it while its real instance disappears.

Thus, I suggest a way similar to ndarray's approach:

```
pub struct MatView { raw_ptr: *mut void }
impl MatTraitConst for MatView {}

pub struct MatViewMut { raw_ptr: *mut void }
impl MatTraitConst for MatViewMut {}
impl MatTrait for MatViewMut {} // mutable
```

By doing this, we can now happily write `fn ndarray_as_mat(a: &Array) -> MatView` without any problems.

**Comment by twistedfall** [comment]
Well, in the suggested form `MatViewMut` is in no way different from `Mat` or I'm missing something. The idea is to make such struct accept a lifetime to the source `Mat`. I.e. your example would be `fn ndarray_as_mat<'a>(a: &'a Array) -> MatView<'a>`. I'm moving in that direction (e.g. a recent split into `MatTraitConst` and `MatTrait` is a step), but it's still not implemented. My idea would be to also go through the functions and fixup functions that return a reference `Mat`. `Mat::roi` is the biggest offender on my list.

**Comment by fzyzcjy** [comment]
Looking forward to the new feature!

> The idea is to make such struct accept a lifetime to the source Mat. I.e. your example would be fn ndarray_as_mat<'a>(a: &'a Array) -> MatView<'a>.

Yes I mean that. I wrote the wrong things (no lifetime) in the post above.

> Mat::roi is the biggest offender on my list.

Totally agree!

**Comment by fzyzcjy** [comment]
By the way, I am not sure about the following case: 

```
let array = ndarray::Array::zeros(...);
let mat = MatViewMut::from(array); // now it is `MatViewMut<'a>` where 'a is shorter than array's lifetime
some_opencv_function(&mut mat);
```

Now, if the `some_opencv_function` *reallocates memory* inside the function, what will happen? You know, if the Mat provided to opencv function is not compatible with the size/type that the function wants to output, it will simply do `mat.create(...)` to re-allocate. In this case, MatViewMut can be very misleading: the array will *not* be changed indeed. Please correct me if I am wrong!

**Comment by twistedfall** [comment]
You're not wrong, it's really tricky and it requires careful inspection of the API to even start trying to make the bindings sound from the Rust perspective.

**Comment by twistedfall** [comment]
I think this is a dup of https://github.com/twistedfall/opencv-rust/issues/277 which is currently implemented.
