### ISSUE TITLE
Rename `Vec` to other names such as `Vector`, or change its namespace

### ISSUE THREAD

**Issue by fzyzcjy** [twistedfall/opencv-rust#295]
Hi thanks for the lib! I use opencv extensively, so I `use opencv::core::*` for convenience (otherwise need to import ~10 things for each file...) However, the new version seems to have a struct named `Vec` in opencv::core, which conflicts with std's Vec. Thus I have to fallback to use opencv::core::{each, thing, I, need}. IMHO, maybe having a name conflicting with std is not a perfect approach.

**Comment by twistedfall** [comment]
I suspected that this will be a problem at some point, thanks for the report, I'll fix it

**Comment by fzyzcjy** [comment]
You are welcome!

**Comment by twistedfall** [comment]
It's been fixed in 0.58.0, the new name is `VecN`

**Comment by fzyzcjy** [comment]
:tada:
