### ISSUE TITLE
Use cargo features instead of OPENCV_MODULE_*

### ISSUE THREAD

**Issue by nsabovic** [twistedfall/opencv-rust#297]
When working with OpenCV I frequently need only few modules. The current way of selecting it with environment variables causes all sorts of ruckus:

  - If your target is a static library, the pain of setting the variable is pushed onto the library consumer.
  - Any editor which uses rust-analyzer/RLS needs to have the exact same environment vars set otherwise you get full rebuilds every time.
   - When invoking `cargo` from external build systems such as Xcode or CMake it becomes a pain.

I see that having feature selection hidden from the build system caused friction in my tam and I don't think it's a coincidence that no other package uses environment variables for feature selection :)

It would be amazing if we could select features with cargo features!

The tradeoff would be that cargo requires potential features to be declared in `Cargo.toml` which means we'd have to forego automatic detection of new modules. But I guess that each time OpenCV adds a new module we'd need to test it and mark somehow that it works so I don't think this actually adds more work.

**Comment by twistedfall** [comment]
I see your point and it makes sense. The set of modules between OpenCV versions is not constant, they come and go. How do you see the “default” feature set in this case? Only the limited set of core modules?

**Comment by nsabovic** [comment]
In the pull request I made the feature compiles the module only if it is present on the system so a default feature set with all possible features works for all versions.

**Comment by twistedfall** [comment]
It's now released in 0.59.0

**Comment by nsabovic** [comment]
Thank you!
