### ISSUE TITLE
`Vector<u8>`'s constructor is too slow?

### ISSUE THREAD

**Issue by fzyzcjy** [twistedfall/opencv-rust#301]
Hi thanks for the lib! It seems that `Vector<u8>::from( ...a Vec<u8>... )` calls `from_iter`, which is

```
	pub fn from_iter<'a>(s: impl IntoIterator<Item=<T as OpenCVType<'a>>::Arg>) -> Self {
		let mut out = Self::new();
		out.extend(s);
		out
	}
```

and the `extend` is 

```
	fn extend<I: IntoIterator<Item=<T as OpenCVType<'a>>::Arg>>(&mut self, s: I) {
		let s = s.into_iter();
		let (lo, hi) = s.size_hint();
		self.reserve(hi.unwrap_or(lo));
		s.for_each(|elem| {
			self.push(elem);
		});
	}
```

the `push` is

```
	pub fn push(&mut self, val: <T as OpenCVType>::Arg) {
		let val = val.opencv_into_extern_container_nofail();
		unsafe { self.extern_push(val.opencv_as_extern()) }
	}
```

In conclusion: To create, say, a 1MB-size `Vector<u8>`, the `push` ffi call is called a million times, which will make it much slower than one simple call with parameter of 1MB data.

To solve this problem, maybe create a function that calls C++'s STL Vector's "push an array of elements into the vector" function.

**Comment by twistedfall** [comment]
Since version 0.59.0 you can use `Vector::from_slice` for a more efficient `Vector` construction

**Comment by fzyzcjy** [comment]
Thank you!
