### ISSUE TITLE
rgb 0.8 is "maybe insecure"

### ISSUE THREAD

**Issue by eadf** [twistedfall/opencv-rust#303]
According to rustsec.org `rgb` 0.8 is "[maybe insecure](https://deps.rs/crate/opencv/0.59.0)",  `rgb` >= 0.8.20 is patched.
I could make a PR but it's just one line..

**Comment by twistedfall** [comment]
From what I read in the description it's not really applicable to how the `rgb` crate is used in `opencv`. But thanks for the report. I'll bump the dep version in master, but not do a release right away.
