### ISSUE TITLE
The problem of getting non-UTF-8 data from a QR code

### ISSUE THREAD

**Issue by kosrk** [twistedfall/opencv-rust#304]
1. Linux Mint
2. The way you installed OpenCV: manual compilation (https://docs.opencv.org/4.x/d7/d9f/tutorial_linux_install.html)
3. OpenCV version: 4.5.4
4. rustc version: 1.55.0
5. opencv crate version: 0.60

I have a problem with `opencv::objdetect::QRCodeDetector` when I try to decode QR of byte/binary type using `detect_and_decode` function. Binary/byte QR payload is an byte array (https://en.wikipedia.org/wiki/QR_code "Storage" chapter and "Encoding" chapter).

QR decoding is correct when I use C++.

Function `detect_and_decode` returns `Result<String>` type. C++ function `detectAndDecode` from `libopencv_objdetect.so` returns `std::string` type.

When I use `detect_and_decode` from the `opencv` crate - all non-UTF-8 characters in the payload are replaced with the replacement character `EF BF BD` and the data is corrupted.

I am trying to modify the `opencv` crate to get `Vec<u8>` instead of a `String`, but without success.

I think the best option is to add a new function that handles non-UTF payload correctly (to keep backward compatibility).

Test data:
![test](https://user-images.githubusercontent.com/49599551/141644100-60c889f9-e330-4c8a-80d0-841481bb9510.png)
Correct payload (hex): `6db224ccf060b23334e552a3435a9b5a`
Result from Rust `detect_and_decode` function: "m�$��\`�34�R�CZ�Z" (hex: `6defbfbd24efbfbdefbfbd60efbfbd3334efbfbd52efbfbd435aefbfbd5a`)

**Comment by twistedfall** [comment]
Nice find, I’ll fix that!

**Comment by twistedfall** [comment]
This has been fixed in v0.61.0, those functions now return `Vec<u8>` instead of `String`, thanks for the report!

**Comment by kosrk** [comment]
I have already applied the new version. `detect_and_decode` function works correctly.
Thank you very much!
