### ISSUE TITLE
text module does not implemented ?

### ISSUE THREAD

**Issue by duducv** [twistedfall/opencv-rust#309]
1. Windows 10 x64
2. installation via chocolatey.
3. OpenCV version: 0.60.0
4. rustc version (`rustc --version`): 1.56.1
5. 
are Module opencv::text not implemented ? I'm trying to use ocr functions but I can't access the text module which are written in rust docs.

**Comment by twistedfall** [comment]
The OpenCV version from chocolately doesn't contain the "text" module, so that's why. You should either install OpenCV from vcpkg or build it manually.
