### ISSUE TITLE
What does Mat::clone do?

### ISSUE THREAD

**Issue by JonBoyleCoding** [twistedfall/opencv-rust#310]
I wanted to ask what a clone on the Mat does. Does it:

- Create a new Mat with a copy of the data
- Create a reference to the original (like the default C++ behaviour)

If it is the second, what would the easiest way be to create a new mat with a copy of the original data - would you actually have to create a new mat and use the copy_to method?

Thanks

**Comment by twistedfall** [comment]
Well, in this case the docs are pretty self-explanantory: [Mat::clone()](https://docs.rs/opencv/latest/opencv/core/struct.Mat.html#method.clone) and [Mat::try_clone()](https://docs.rs/opencv/latest/opencv/core/prelude/trait.MatTraitConst.html#method.try_clone) so it's a first option from your list. That function delegates to C++ [Mat::clone()](https://docs.opencv.org/4.5.4/d3/d63/classcv_1_1Mat.html#a03d2a2570d06dcae378f788725789aa4)

**Comment by JonBoyleCoding** [comment]
Ok, thanks! I just wanted to make sure.
