### ISSUE TITLE
Creating a Vector of Mats

### ISSUE THREAD

**Issue by JonBoyleCoding** [twistedfall/opencv-rust#311]
I was trying to use the opencv stitcher, but I'm having issues creating a Vector of Mats. My attempt to do so is as follows:

```
	let images = opencv::core::Vector::<Mat>::from_slice(&[Mat::copy(&gradient_normalized).unwrap(), Mat::copy(&gh2).unwrap(), Mat::copy(&gv2).unwrap()]);
```
However, I'm getting the following error:

```
894 |     let images = opencv::core::Vector::<Mat>::from_slice(&[Mat::copy(&gradient_normalized).unwrap(), Mat::copy(&gh2).unwrap(), Mat::copy(...
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `VectorExternCopyNonBool<opencv::prelude::Mat>` is not implemented for `Vector<opencv::prelude::Mat>`
```

Would anyone be able to assist? Thanks.

**Comment by twistedfall** [comment]
`from_slice()` will not work here because `Vector` needs to take ownership of the `Mat`, but slice will not give it up, it will only work with `Copy` types. You should instead just call `push()` for every `Mat` that you want to add.

**Comment by JonBoyleCoding** [comment]
Ok, thank you.

And thank you for all the quick responses - I've been having to port some code in a very short amount of time so it's been very helpful.
