### ISSUE TITLE
‘cannot open shared object file’ even though library is in correct location

### ISSUE THREAD

**Issue by Aankhen** [twistedfall/opencv-rust#315]
I’m trying to use rust-opencv in a Docker container deriving from `rust:1.57.0-bullseye`. I manually built OpenCV 4.5.1 with the nonfree modules through a lot of trial and error (by downloading the source for 4.5.1 and following the CMake instructions, using Clang). When I run a test (which is where the library is used), Rust says the .so doesn’t exist:
```
Finished test [unoptimized + debuginfo] target(s) in 1m 59s
     Running `/usr/src/app/rust/target/debug/deps/backend-e32510369b055f2d`
/usr/src/app/rust/target/debug/deps/backend-e32510369b055f2d: error while loading shared libraries: libopencv_xfeatures2d.so.4.5: cannot open shared object file: No such file or directory
error: test failed, to rerun pass '--bin backend'
```
But I can see the file:
```
# ls -al /usr/local/lib/libopencv_xfeatures2d.so.4.5
lrwxrwxrwx 1 root root 30 Jan  3 20:59 /usr/local/lib/libopencv_xfeatures2d.so.4.5 -> libopencv_xfeatures2d.so.4.5.1
```
From running <kbd>cargo test -vv</kbd>, it seems like rust-opencv has already added the directory as a link path:
```
[opencv 0.61.3]     cargo_metadata: [
[opencv 0.61.3]         "cargo:rustc-link-search=/usr/local/lib",
```
[(Full output with `RUST_BACKTRACE=1`)](https://github.com/twistedfall/opencv-rust/files/7804181/cargo.txt)

I also tried with `OPENCV_LINK_PATHS=+/usr/local/lib` for good measure, but the result was the same. Note that I’m running <kbd>cargo clean</kbd> between attempts to make sure there’s no cache-related issue.

To help reproduce the issue, this is my Dockerfile for development purposes (I mount my source directory as a volume):
```dockerfile
FROM rust:1.57.0-bullseye

ARG OPENCV_VERSION=4.5.1

RUN apt-get update -qq && apt-get install -qqy wget software-properties-common libclang-dev cmake make unzip

RUN bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

RUN cd /tmp && \
    wget -O opencv.zip https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.zip && \
    wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/${OPENCV_VERSION}.zip && \
    unzip opencv.zip && \
    unzip opencv_contrib.zip && \
    mkdir build && \
    cd build && \
    cmake -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib-${OPENCV_VERSION}/modules -DOPENCV_ENABLE_NONFREE:BOOL=ON ../opencv-${OPENCV_VERSION} && \
    cmake --build . -j $(nproc) && \
    make install

RUN ln -s /usr/lib/llvm-13/bin/llvm-config /usr/local/bin/llvm-config
```

**Comment by Aankhen** [comment]
Apparently, I also needed to set `LD_LIBRARY_PATH` or an equivalent. There’s [a way to do that programmatically](https://www.reddit.com/r/rust/comments/crl2b0/comment/exaunzi/?utm_source=reddit&utm_medium=web2x&context=3), which I added to the Dockerfile. I can’t pretend to understand it, but it works now!

**Comment by twistedfall** [comment]
This environment variable instructs system on where to search for additional dynamic libraries when running an executable. Because your OpenCV installation is not in the standard system path (like /usr/lib) you need to specify this additional search path.

**Comment by Aankhen** [comment]
I didn’t realize /usr/local/lib wasn’t a standard path. I’ll keep that in mind. Thanks for the information!

EDIT:
Confirmed: I added `-DCMAKE_INSTALL_PREFIX=/usr` to the build and now I don’t need to set the library path.
