### ISSUE TITLE
net.forward report an error

### ISSUE THREAD

**Issue by hziwei** [twistedfall/opencv-rust#323]
error: test failed, to rerun pass '-p opencvplay --bin opencvplay'

Caused by:
  process didn't exit successfully: `/home/tab/src/rustsrc/opencvplay/target/debug/deps/opencvplay-0ad8e995eaf25ae1 'test::test03::tests::test' --exact --nocapture` (signal: 11, SIGSEGV: invalid memory reference)

终端进程“cargo 'test', '--package', 'opencvplay', '--bin', 'opencvplay', '--', 'test::test03::tests::test', '--exact', '--nocapture'”已终止，退出代码: 101。

**Comment by twistedfall** [comment]
It would be quite difficult to help without any information :) Please provide the minimum example of the code producing the error and full dump of `cargo build -vv` after `cargo clean`.

**Comment by twistedfall** [comment]
I'm closing it for now, please feel free to reopen if you have more details.
