### ISSUE TITLE
Cargo.toml updates?

### ISSUE THREAD

**Issue by nweisenfeld** [twistedfall/opencv-rust#33]
Hi there @twistedfall -- I'm glad to see that you've adopted this crate as I'm interested in using it (and hopefully contributing back any fixes that I can come up with).

There was some agreement [here](https://github.com/twistedfall/opencv-rust/issues/18) about switching the license to MIT.

This is just a quick ping about updating the Cargo.toml sometime with the new license (and owner and repo, etc.).

**Comment by twistedfall** [comment]
Fixed in master
