### ISSUE TITLE
Hardware accelerated video decoding

### ISSUE THREAD

**Issue by ac-freeman** [twistedfall/opencv-rust#334]
OS: Ubuntu 20.04
Installed OpenCV by manual compilation
OpenCV version 4.5.0
rustc 1.58.1

I'm trying to us the hardware accelerated backend for video decoding, but when opencv-rust compiles, it removes the relevant hooks in videoio.rs. Specifically, CAP_PROP_HW_ACCELERATION is missing.

I used [this guide](https://github.com/opencv/opencv/wiki/Video-IO-hardware-acceleration#installation-bkc) to compile OpenCV with hardware acceleration support enabled for FFmpeg.

Has anyone successfully done hardware-accelerated decoding? I could be missing something, in which case I think the crate documentation could be improved for this use case.

[rust_backtrace.txt](https://github.com/twistedfall/opencv-rust/files/8484107/rust_backtrace.txt)

**Comment by twistedfall** [comment]
Well, if it's missing from the bindings after the compilation then it means that your installed OpenCV headers doesn't have it. It could mean that your OpenCV doesn't actually have HW accelerated decoding enabled. Can you please share the full cmake log from your OpenCV build?
