### ISSUE TITLE
 failed to run custom build command for `opencv v0.63.1` 

### ISSUE THREAD

**Issue by Frank1126lin** [twistedfall/opencv-rust#337]
When I add opencv in my bindgen programs, the complier throw the error as below:
1. Operating system
WIN 10 X64
2. The way you installed OpenCV: package, official binary distribution, manual compilation, etc.
Official binary distribution.
3. OpenCV version
 4.5.5
4. rustc version (`rustc --version`)
1.60.0
5. Attach the full output of the following command from your project directory:
```
...
  === Detected OpenCV module header dir at: D:\00-Program\opencv\build\include\opencv2
  === Found OpenCV version: 4.5.5 in headers located at: D:\00-Program\opencv\build\include
  === Generating code in: D:\00-Program\05-Rust\10-MVC\MVCam3\target\debug\build\opencv-a92b9f2d0b29dfa8\out   
  === Placing generated bindings into: C:\Users\FRANK1126LIN\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\opencv-0.63.1\src\opencv
  === Using OpenCV headers from: D:\00-Program\opencv\build\include
  thread 'main' panicked at 'a `libclang` shared library is not loaded on this thread', C:\Users\FRANK1126LIN\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\clang-sys-1.3.1\src\lib.rs:1692:1
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by twistedfall** [comment]
Please check https://github.com/twistedfall/opencv-rust#troubleshooting item 7

**Comment by Frank1126lin** [comment]
> Please check https://github.com/twistedfall/opencv-rust#troubleshooting item 7

Thanks, problem solved.
