### ISSUE TITLE
Help with trying to generate opencv version 4.0.1 bindings

### ISSUE THREAD

**Issue by colepoirier** [twistedfall/opencv-rust#34]
High @twistedfall, I’m interested in using your methods of parsing c++ header files and generating rust code for opencv versions 2.X and 3.4.5, for the 4.0.1 release. I’ve been able to use your gen_rust.py script to generate most of the bindings for the basic libraries, but I am coming up against the issue of the cv::sys crate as I haven’t been able to figure out how the script should generate these bindings and from which open cv header files. It’s very possible that I’m missing something bigger and more fundamental (perhaps the api in 3.4.5 is completely incompatible with the 4.0.1 api?) so please correct me if that is the case. Part of the problem is that I only know rust and some C but very little c++, so I’m doubtful I’ll be able to figure this out without your guidance. Thank you in advance for any help you can provide.

**Comment by twistedfall** [comment]
Hi, I haven't tried creating bindings for opencv-4 yet, so I don't know the details. Maybe if you can provide something more specific (error message?) I'll be able to help you.

**Comment by colepoirier** [comment]
Apologies for my late response. Thank you for upgrading the official package to opencv 4.1.0!
