### ISSUE TITLE
How to use core::merge and core::merge_slice?

### ISSUE THREAD

**Issue by Kubuxu** [twistedfall/opencv-rust#344]
Hey, I need to combine some number single channel of Mats into a single multi-channel Mat.
In C++ this would be done via core::merge.

It is unclear how to use it properly in opencv-rust as it seems to be raw translation with references instead of pointers.

https://docs.rs/opencv/latest/opencv/core/fn.merge_slice.html
https://docs.rs/opencv/latest/opencv/core/fn.merge.html

```
let m1 = Mat::Mat::new_size_with_default()
let m2 = Mat::Mat::new_size_with_default()
let m3 = Mat::Mat::new_size_with_default()

let mc = [m1, m2, m3]
let dst = Mat::default();
core::merge(??? 3, dst)
```
`core::merge_slice` as exposed today cannot work as it requires a number of Mat objects allocated in uninterrupted memory space which I don't think is exposed today.

**Comment by twistedfall** [comment]
Hey, thanks for the heads-up. The `merge_slice` generation is definitely broken, I'll check it out. The `merge` function should work all right though as long as you supply `VectorOfMat` as the `mv` argument.

**Comment by twistedfall** [comment]
Yeah, `merge_slice` is unusable, please use just `merge`. I'm removing `merge_slice` in the next release.

**Comment by Kubuxu** [comment]
Ahh, I somehow missed VectorOfMat. Thanks.
