### ISSUE TITLE
where is crop function to crop roi of image?

### ISSUE THREAD

**Issue by wangm23456** [twistedfall/opencv-rust#345]
where is crop function to crop roi of image?
I'm going crazy. I'm really going crazy.

**Comment by twistedfall** [comment]
Did you solve it? My quick check shows that there is no such function in OpenCV API. But you should be able to use https://docs.rs/opencv/latest/opencv/core/struct.Mat.html#method.roi to achieve the same functionality.

**Comment by wangm23456** [comment]
> Did you solve it? My quick check shows that there is no such function in OpenCV API. But you should be able to use https://docs.rs/opencv/latest/opencv/core/struct.Mat.html#method.roi to achieve the same functionality.

Yes, `Mat::rowscols` and `Mat::roi` are what I want. I missed them because of description: "download data from GpuMat".
 `Mat::rowscols` is equivalent to `img[a:b, c:d]` in python or `img(Range(a,b),Range(c,d))` in c++.

**Comment by twistedfall** [comment]
> description: "download data from GpuMat".

Yep, unfortunately it's a known issue, the function annotation is reported this way by libclang for some reason. I'm yet to find a workaround for that issue.
