### ISSUE TITLE
Request to fix opencv::calib3d::get_optimal_new_camera_matrix params

### ISSUE THREAD

**Issue by qwerty19106** [twistedfall/opencv-rust#349]
The `validPixROI` param in C++ :
``` C++
Rect * validPixROI = 0,
```

It should corresponds in Rust:
``` Rust
valid_pix_roi: Option<&mut Rect>,
```

I want send null pointer (as in C++) into function, but it is impossible with current API.

[Current Rust API](https://docs.rs/opencv/latest/opencv/calib3d/fn.get_optimal_new_camera_matrix.html)
[C++ API](https://docs.opencv.org/4.5.5/d9/d0c/group__calib3d.html#ga7a6c4e032c97f03ba747966e6ad862b1)

**Comment by twistedfall** [comment]
You are right, thanks for the report! I’ll try to fix it asap

**Comment by twistedfall** [comment]
This should now be fixed in v0.66.0, thanks!
