### ISSUE TITLE
Didn't find the cvAvgSdv function, not yet implemented?

### ISSUE THREAD

**Issue by constlhq** [twistedfall/opencv-rust#352]
as title

**Comment by twistedfall** [comment]
I can't find this function in the documentation (https://docs.opencv.org/4.6.0/), are you sure it exists? Ah, wait, disregard that, it is available in 3.4 (https://docs.opencv.org/3.4.18/d2/df8/group__core__c.html#ga1097c00ea927c9eb5243136d1e34d609). It is in the C header (`*.h`), let me check if we export that at all.
