### ISSUE TITLE
Missing `resize` function?

### ISSUE THREAD

**Issue by blyxyas** [twistedfall/opencv-rust#353]
I noticed that in the `Vector` struct doesn't have a `resize` function. Is there another `resize` function in another module or is it to be implemented?

I'm working in a PR for this, but it will take some time as this is my first PR on the project.

**Comment by twistedfall** [comment]
Thanks for the suggestion, your contribution would be very welcome!

**Comment by blyxyas** [comment]
Ok I think I have it, but, what should be the `module` argument for `binding-generator`? It isn't really clear what it should be

**Comment by twistedfall** [comment]
It's the opencv module for the currently generated bindings, it's a string like "imgproc", "core", "dnn" and so on

**Comment by blyxyas** [comment]
Mmmm... It gives me this error even in the original commit. It seems the binding generator can't parse the `vector` module, but I can't find a reason for the error.

This is the command I used:

```console
./bgen /usr/include src_cpp bindings vector
```

And this is the error:

```
thread 'main' panicked at 'Cannot parse module: vector', /home/alex/git/rust/opencv-rust/binding-generator/src/generator.rs:562:41
stack backtrace:
   0: rust_begin_unwind
             at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/core/src/panicking.rs:142:14
   2: opencv_binding_generator::generator::Generator::process_opencv_module
   3: binding_generator::main
```

tbh I feel ashamed to take 2+ days to implement a simple function

**Comment by twistedfall** [comment]
Please don't be, the code in binding generator + supporting code in the opencv crate is quite complex and all those parts need to work together and it severely lacks documentation (sorry for that). `vector` is not a module in this case. Module can only be an OpenCV own module (e.g. what you see here: https://github.com/opencv/opencv/tree/4.x/modules).

To implement a new function for a `Vector<T>` type I would check how other functions are implemented. A good example would be `Vector::set` function in https://github.com/twistedfall/opencv-rust/blob/master/src/manual/core/vector.rs#L139.

After adding an additional function you want to create a possibility to call the C++ side, this is controlled by the `VectorExtern` trait and facilitated by the `vector_extern!` macro in https://github.com/twistedfall/opencv-rust/blob/master/src/manual/core/vector/vector_extern.rs#L18.

And then you need to generate the proper call to the `vector_extern!` macro for each of the possible `Vector<T>` implementation, that's in https://github.com/twistedfall/opencv-rust/blob/master/binding-generator/src/writer/rust_native/tpl/vector/rust.tpl.rs and corresponding C++ code in https://github.com/twistedfall/opencv-rust/blob/master/binding-generator/src/writer/rust_native/tpl/vector/cpp.tpl.cpp

I hope that helps!

**Comment by blyxyas** [comment]
Ok I think it worked! :cat:
I tested it and it didn't, but I achieved to get the binding generator work, it generated a lot of files, but it seems that only three were important:

* `core.cpp`
* `core.extern.rs`
* `core.rs`

I don't know the importance of `050-core-VectorOfu8.type.cpp`, so I just ignored the rest.
But here's the catch, **I don't know where these would be**, I tried searching for files to replace with:

```bash
find . -name core.cpp
```

But it didn't showed up nothing, same thing with `core.extern.rs`, I could replace `core.rs` with `src/opencv/hub/core.rs`, so I did that. After writing a small test (Didn't even asserted nothing) I run the test just to see if the function couldn't run, it seems that it doesn't and it gives this error:


(This was repited for each type):
```
  cargo:warning=In file included from /home/alex/git/rust/opencv-rust/target/debug/build/opencv-a75f6b7102a5d7e1/out/dpm.cpp:3:
  cargo:warning=/home/alex/git/rust/opencv-rust/target/debug/build/opencv-a75f6b7102a5d7e1/out/dpm_types.hpp:44:17: error: expected initializer before ‘<’ token
  cargo:warning=   44 |         void cv_<parameter not found>_resize(std::vector<cv::dpm::DPMDetector::ObjectDetection>* instance, size_t new_size) {
  cargo:warning=      |                 ^
```

We can visit that file, and the `resize` declaration seems to be:
*(Not actually the same file)*

```cpp
void cv_<parameter not found>_resize(std::vector<cv::dnn::MatShape>* instance, size_t new_size) {
	instance->resize(new_size)
}
```

The declaration is alright except for that something (?) could find a parameter (?) I think I did everything right:

1. I added the Rust declaration to `src/manual/core/vector.rs @ impl Vector<T>`:

```rust
/// Free extra capacity
#[inline]
pub fn shrink_to_fit(&mut self) {
	unsafe { self.extern_shrink_to_fit() }
}
```

2. I added the necessary macro thing in `src/manual/core/vector/vector_extern.rs @ vector_extern` & a new unsafe method `extern resize` for `trait VectorExtern<T: for<'a> OpenCVType<'a>>`.

```rust
// ...
pub trait VectorExtern<T: for<'a> OpenCVType<'a>> {
    // ...
    #[doc(hidden)] unsafe fn extern_resize(&mut self, new_size: size_t);
    // ...
}

macro_rules! vector_extern {
    (
        // ...
        $extern_resize: ident,
        // ...
    ) => {
        extern "C" {
            // ...
            fn $extern_resize(instance: $vector_extern_mut, new_size: $crate::platform_types::size_t);
            // ...
        }
        // ...
        #[inline]
        unsafe fn extern_resize(&mut self, new_size: $crate::platform_types::size_t) {
            $extern_resize(self.as_raw_mut(), new_size)
        }
        // ...
    }

}

```
*(There can be a typo there because I transcribed that by hand, I hate Github comments)*

3. I added the new method to `bindings-generator/src/writer/rust_native/tpl/vector/rust.tpl.rs`
The error happened here.
```rust
{{alias}}
vector_extern! { /* ... */ 
    // ...
    cv_{{rust_localalias}}_resize
    // Things failed here, but I don't know why.
    // ...
}
// ...
```

4. I generated everything.
5. I replaced the old version with the new version of `src/opencv/hub/core.rs`

It seems that the binding generator did several more things, like updating `types.rs`
What did I do wrong? Were do I need to put the parameter to be found?

**Comment by twistedfall** [comment]
https://github.com/twistedfall/opencv-rust/blob/master/binding-generator/src/writer/rust_native/vector.rs is responsible for generating `Vector` implementations for all necessary element types. We're interested in 2 its methods `gen_rust()` and `gen_cpp()`. They both take templates, pass some variables to them and generate definitions. When you get `<parameter not found>` in the generated file it means that the value wasn't found in the template parameters. The hashmap with template parameters is being built in the `inter_vars` variable in those 2 methods. So you need to make sure that `rust_localalias` template parameter is passed to the corresponding template.

There is also one thing that I should have mentioned from the beginning. For such work where you want to introduce something and want to see its effect the following works pretty well for me.
1. Copy the `tools/config.tpl.sh` to `tools/config.sh` and set up the `opencv_lib_base_dir` and `OPENCV_4_*` vars.
2. Create the `out/generator` dir in the root of the project.
3. Run the `tools/generate-bindings.sh` script on the unmodified sources. That would create a ton of files in the `out/generator` directory, these are all of the generated files, just in one visible dir.
4. Commit this directory to git
5. Make the changes to the source code and run the `tools/generate-bindings.sh` and check the differences in the generated files.

**Comment by blyxyas** [comment]
I think I'm going to give up on this, the project is very complex, with low documentation and I cannot continue doing this, I already wasted multiple days.

Thanks for creating Rust bindings for OpenCV, but I will not make this PR, as I cannot complete it.
