### ISSUE TITLE
Can't manipulate Vector

### ISSUE THREAD

**Issue by NoxFelis** [twistedfall/opencv-rust#354]
Hello, I'm currently trying to use the OpenCV package, I've added it to my cargo.toml and i'm using the 1.59.0 version of rust
I'm trying to create a VectorOfVectorOfPoint2f and fill it in but I've realised something doesn't work (or I can't see to get it to work)
I've tried in a simpler version with just a VectorOff64 and same issue: 
Here's the basic code I wrote : 

```
`use opencv::types::VectorOff64;
fn main() {
    println!("Hello, world!");
    let mut test = VectorOff64::new();
    test.push(64.0);
}`
```

thing is when I check the value of 'test' with the debugger after the push, I have this: 
`'ptr: (invalid enum value) 96``

I have tried to create a std::vec and then create my vector from it using 'from_slice' and 'from_iter', I have tried initializing my vector using 'with_capacity' and the vector is already like that. I have tried to reserve then add or insert and element, same result too. 
Truthfully I'm really lost as whether I'm doing something wrong or if there's a problem

Thanks in advance

**Comment by twistedfall** [comment]
Hi, to be honest I don't really understand the nature of the problem. The introspection in the debugger is unlikely to be able to show the list of elements because this `Vector` is a basically a binding to the C++ vector and Rust side only stores a pointer to it. But in your example, what happens that you don't expect?

**Comment by NoxFelis** [comment]
Alright, so if I understand well, it works correctly but I just can't use the debugger to directly check what's in it. Would I have a way then to check it up nonetheless then like through a print or something?
Because yeah I did expect being able to find the value of what's in the vector with the debugger ^^"

**Comment by twistedfall** [comment]
Well, there is a `Debug` implementation for it as long as the type of the element implements `Debug` too. You can also convert `Vector` to Rust `Vec` by calling `.to_vec()`, to slice with `as_slice()` or to `Iterator` with `iter()`. Not sure if it's enough :)

**Comment by NoxFelis** [comment]
I'll check it up as soon as I'm back on a computer thank you very much I was losing my hair with this ^^
(Also cause I'm really new to rust and actually using opencv)
