### ISSUE TITLE
hough_circles throwing weird errors

### ISSUE THREAD

**Issue by Sha-dos** [twistedfall/opencv-rust#356]
Working on windows 10 here and when I try and use hough_circles I get some weird errors.

Here is my code: 
```
let mut circles: Vec3f = Vec3f::from([0 as f32; 3]);

let hough_cir = hough_circles(
     &mat_roi,
     &mut circles,
     HOUGH_GRADIENT,
     1.0,
     0.1,
     100.0,
     100.0,
     0,
     0
).expect("some exception message");

println!("{:?}", circles);
```

When I run this I get:
```
thread 'main' panicked at 'some exception message: Error { code: -2, message: "OpenCV(4.5.5) C:\\build\\master_winpack-build-win64-vc15\\opencv\\modules\\imgproc\\src\\hough.cpp:2254: error: (-2:Unspecified error) in function 'void 
__cdecl cv::HoughCircles(const class cv::_InputArray &,const class cv::_OutputArray &,int,double,double,double,double,int,int,int,double)'\n> Wrong type of output circles:\n>     'type == CV_32FC3 || type == CV_32FC4'\n> where\n>   
  'type' is 5 (CV_32FC1)\n" }', src\main.rs:106:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\Tracker.exe` (exit code: 101)

```

When I run without the .expect() it runs, however `circles` is `0, 0, 0`. I looked into the type CV_32FC3 and the CV_MAKETYPE which returns an i32. I am at a loss at the moment, I am trying to get the center of the circles from my mat.

Should `circles` be a different type? Am I doing anything wrong or is this the bindings? 

OpenCV: 0.66.0

**Comment by twistedfall** [comment]
Well, what it says is:
```
Wrong type of output circles:  'type == CV_32FC3 || type == CV_32FC4' where 'type' is 5 (CV_32FC1)
```
So it expects a 3 or 4 channel output and gotten only 1 channel. The documentation says it's a `Output vector of found circles. Each vector is encoded as 3 or 4 element floating-point vector (x,y,radius) or (x,y,radius,votes)`. So you need not just a `Vec3f` (a 3 element array of `f32`), but a `VectorOfVec3f`, so a `Vector` where each element is `Vec3f`. In short just init `circles` like this:
```rust
let mut circles = VectorOfVec3f::new();
```
