### ISSUE TITLE
How to create Mat from image loaded from Web

### ISSUE THREAD

**Issue by mbajlo** [twistedfall/opencv-rust#358]
Hello all,

I am struggling to create a `cv::Mat` from a image `(640*480*3 jpg)` loaded from web. I have tried a lot of stuff(from image, ndarray or cv_convert) but it seems I cannot create cv::Mat if it is not loaded from file or read from Cam. 

I am tried to save the image by `image::save` and that is working so I am sure the image is correct.
Now I need to convert it to cv::Mat to draw on image.

Is it possible to create a cv::Mat from `bytes::Bytes` or from `image` or in some other way to be shown by cv::imshow?
Do you have some suggestions?

**Comment by twistedfall** [comment]
Hi, the general idea is to load the image, get its pixel data and load it into `Mat` while specifying the correct format, CV_8U3C most probably. I’ll be able to provide the example a little bit later.

**Comment by mbajlo** [comment]
Hello Twisted fall,

Please do, now I am kind of stuck here and I am still learning Rust.

Thanks in advance

**Comment by twistedfall** [comment]
Something like this would work (uses the [image](https://crates.io/crates/image) crate):
```rust
use std::error::Error;
use std::fs::File;
use std::io::BufReader;

use image::ImageFormat;
use opencv::{highgui, imgproc};
use opencv::core::{Scalar, Vec4b};
use opencv::prelude::*;

fn main() -> Result<(), Box<dyn Error>> {
	let img_file = BufReader::new(File::open("/var/tmp/opencv-image/logo.png")?);
	let img = image::load(img_file, ImageFormat::Png)?;
	let mut img_mat = Mat::new_rows_cols_with_default(img.height().try_into()?, img.width().try_into()?, Vec4b::typ(), Scalar::all(0.))?;
	img_mat.data_bytes_mut()?.copy_from_slice(img.as_bytes());
	let mut bgr_img_mat = Mat::default();
	imgproc::cvt_color(&img_mat, &mut bgr_img_mat, imgproc::COLOR_RGBA2BGR, 0)?;
	highgui::imshow("Image", &bgr_img_mat)?;
	while highgui::wait_key(10)? < 0 {}
	Ok(())
}
```
The image display functions in OpenCV expect the BGR subpixel order, so it's important to convert it from the RGB one that's usually supplied by the image handling libraries (done by the `cvt_color` function call).

**Comment by mbajlo** [comment]
Thanks for the example, I wasn't aware of the function `Mat::new_rows_cols_with_default()`
I was trying to do it in a python style.

Anyway I got it working, but I am wondering why did you use `Vec4b::typ()`? 
It should be `Vec3b::typ()` or `CV_8UC3` because the image is RGB 640x480?
Or am I missing something?

**Comment by twistedfall** [comment]
The image loaded by `image` crate is RGBA, so 4-channel (at least in my case). So to be able to just copy the data over from the pixel byte array into `Mat` you need them to be compatible. After you do the `cvt_color` the output `Mat` is 3-channel.

**Comment by mbajlo** [comment]
Ok, thanks, in my case image is loaded from memory and it is 3 channel.
Thanks a lot, I got it working.
