### ISSUE TITLE
G-API bindings aren't implemented

### ISSUE THREAD

**Issue by sugol-a** [twistedfall/opencv-rust#363]
There are currently no bindings to G-API. This would be super handy to have!

**Comment by twistedfall** [comment]
It is indeed. I think it's the only module that's not supported at the moment. But the API is really more complicated in that module so it's going to take a non-trivial amount of effort. But it's definitely planned.

**Comment by sugol-a** [comment]
Given this is the only module that's not supported, perhaps a note should be added to README.md in the meantime? It's kind of confusing to see a feature flag for a feature that doesn't exist, and with no explanation :grin:

**Comment by twistedfall** [comment]
You're absolutely right, I'll fix that in the next release

**Comment by twistedfall** [comment]
Fixed in 0.67, it's no longer possible to enable `gapi` module. I still plan to implement it some day :)

**Comment by twistedfall** [comment]
The initial support for the gapi is implemented in v0.73.0, you can check this example: https://github.com/twistedfall/opencv-rust/blob/master/examples/gapi_api_example.rs I would love to hear the feedback!
