### ISSUE TITLE
statically compiling opencv

### ISSUE THREAD

**Issue by rhobro** [twistedfall/opencv-rust#364]
Hi there,

I saw on your README that opencv has to be installed on the device for it to run. I am writing an app in flutter (aimed at android, ios, windows, linux, macos) which has bits of rust using opencv. How can I package opencv with the app? This is mostly for the mobile versions which may not have it installed.

Thanks

**Comment by twistedfall** [comment]
Probably static linking is a solution, I haven’t tested this option, but there were a couple of successful mentions. And working with mobile devices is also something I haven’t really considered so far. So if you manage to get something working I would  really like to hear about it!

**Comment by rhobro** [comment]
Hi there,

I read on the opencv website that the library was adjusted for ios and android. So I think compiling them for the platforms should work?

I am new to rust bindings to C and C++. I'm trying to dig through the build script. How does one go about statically linking opencv?

Thanks @twistedfall

**Comment by rhobro** [comment]
Would it be possible to introduce a feature flag on the crate to decide between static and dynamic linking?

**Comment by twistedfall** [comment]
> So I think compiling them for the platforms should work?

In theory, yes, but I can't say that I tried that myself

> How does one go about statically linking opencv? Would it be possible to introduce a feature flag on the crate to decide between static and dynamic linking?

In theory it's just about the linker flags. If you manage to get something working I would really appreciate the PR. Having a feature flag for switching between dynamic and static linking is a good idea!

**Comment by rhobro** [comment]
I've forked the repo and have edited the RUSTFLAGS. I've been trying to test it out in a local cargo project but it seems to return errors saying that all the probes failed to find opencv.

It is returning errors that environment and vcpkg cannot probe it properly - how can I fix this in the build script?

**Comment by rhobro** [comment]
It seems to work when I build my program for my host but it seems to break when cross-compiling. It says environment and vcpkg cannot probe opencv.

**Comment by rhobro** [comment]
And it seems to have environment variables as None?
```
  ===   OPENCV_PACKAGE_NAME = None
  ===   OPENCV_PKGCONFIG_NAME = None
  ===   OPENCV_CMAKE_NAME = None
  ===   OPENCV_CMAKE_BIN = None
  ===   OPENCV_VCPKG_NAME = None
  ===   OPENCV_LINK_LIBS = None
  ===   OPENCV_LINK_PATHS = None
  ===   OPENCV_INCLUDE_PATHS = None
  ===   OPENCV_DISABLE_PROBES = None
  ===   CMAKE_PREFIX_PATH = None
  ===   OpenCV_DIR = None
  ===   PKG_CONFIG_PATH = None
  ===   VCPKG_ROOT = None
  ===   VCPKGRS_DYNAMIC = None
  ```

**Comment by spoorn** [comment]
> Probably static linking is a solution, I haven’t tested this option, but there were a couple of successful mentions. And working with mobile devices is also something I haven’t really considered so far. So if you manage to get something working I would really like to hear about it!

Are there any examples of how to do the static linking?

**Comment by rhobro** [comment]
I read that changing the LDFLAGS can switch between dynamic and static. But it seems to not include opencv in the dylib.

**Comment by twistedfall** [comment]
I'm going to close this issue in favor of the already existing one about static compilation: https://github.com/twistedfall/opencv-rust/issues/104

**Comment by jb-alvarado** [comment]
Hello,
I don't know if it fits here, but I wanted to share my steps, to build with static openCV libs. I was not able to use as target _x86_64-unknown-linux-musl_, I think for that openCV has to compile also with a musl compiler.

In my project I only use features: **face** and **imgproc**:
`opencv = { version = "0.73", default-features = false, features = ["face", "imgproc"]}`

Here are the compiling steps:

1. download sources:
    - ```
        wget -O opencv.zip https://github.com/opencv/opencv/archive/4.x.zip
        wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.x.zip
        ```
2. unzip sources, and delete archive:
    - ```
        unzip opencv.zip && rm opencv.zip
        unzip opencv_contrib.zip && rm opencv_contrib.zip
        ```
3. create build folder and switch to it:
    - ```
        mkdir -p build && cd build
        ```
4. configure build
    - ```
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=NO \
        -DCMAKE_INSTALL_PREFIX=/opt/opencv -DBUILD_DOCS=OFF -DBUILD_EXAMPLES=OFF \
        -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_opencv_java=OFF \
        -DBUILD_opencv_python=OFF -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib-4.x/modules \
        ../opencv-4.x
        ```
5. compile and install opencv
    - ```
        make -j8 && make install
        ```
6. go to rust project
7. compile rust project with:
    - ```
        OPENCV_LINK_LIBS="opencv_imgproc,opencv_face,opencv_objdetect,opencv_dnn,opencv_dnn_objdetect,opencv_core,ippiw,ittnotify,ippicv,liblibprotobuf,z" \
        OPENCV_LINK_PATHS=/opt/opencv/lib,/opt/opencv/lib/opencv4/3rdparty,/usr/lib/x86_64-linux-gnu \
        OPENCV_INCLUDE_PATHS=/opt/opencv/include/opencv4 \
        cargo build --release
        ```

**Comment by twistedfall** [comment]
That's really helpful, thank you! I will try to include this step into the CI and update the readme

**Comment by jb-alvarado** [comment]
> I will try to include this step into the CI and update the readme

Maybe you should also mention that it is a bit tricky to get the right ordering from libs in `OPENCV_LINK_LIBS`, for example when you put `libippicv` before `libippiw` the compiler doesn't find all dependencies.

With **libz** I was not sure which one to choice, the static or the dynamic one. The rust program will link against the dynamic library, but openCV I guess will link to the static one.

**Comment by twistedfall** [comment]
I've added the static build to CI and updated the readme: https://github.com/twistedfall/opencv-rust#static-build

**Comment by 00hello** [comment]
> I've added the static build to CI and updated the readme: https://github.com/twistedfall/opencv-rust#static-build

@twistedfall 

Question: I'm trying to statically compile opencv, as well (on Ubuntu focal fossa). I'm not sure which script I'm supposed to run, [install-focal.sh](https://github.com/twistedfall/opencv-rust/blob/master/ci/install-focal.sh) or [script.sh](https://github.com/twistedfall/opencv-rust/blob/master/ci/script.sh). Why do you have a linux install script in both; what does one do that the other doesn't? 

And if I do run install-focal.sh, how do I run it? Do I run `./install-focal.sh` directly from command line? or do I run `./install.sh` ([install.sh](https://github.com/twistedfall/opencv-rust/blob/master/ci/install.sh), which seems to call install-focal.sh) with $OS_FAMILY environment variable set to Linux?

**Comment by twistedfall** [comment]
For installation of the static OpenCV itself on Ubuntu use the `install-focal.sh` (Focal stands for Ubuntu Focal Fossa, 20.04 version), just be sure to set up env var `OPENCV_VERSION=4.7.0-static` before doing that. The build will be done in `$HOME/build/opencv/` directory and installed to `/usr` (you might want to change that to `/usr/local` or something like this by editing the script before running).

**Comment by hsyan2008** [comment]
> Hello, I don't know if it fits here, but I wanted to share my steps, to build with static openCV libs. I was not able to use as target _x86_64-unknown-linux-musl_, I think for that openCV has to compile also with a musl compiler.
> 
> In my project I only use features: **face** and **imgproc**: `opencv = { version = "0.73", default-features = false, features = ["face", "imgproc"]}`
> 
> Here are the compiling steps:
> 
> 1. download sources:
>    
>    * ```
>        wget -O opencv.zip https://github.com/opencv/opencv/archive/4.x.zip
>        wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.x.zip
>      ```
> 2. unzip sources, and delete archive:
>    
>    * ```
>        unzip opencv.zip && rm opencv.zip
>        unzip opencv_contrib.zip && rm opencv_contrib.zip
>      ```
> 3. create build folder and switch to it:
>    
>    * ```
>        mkdir -p build && cd build
>      ```
> 4. configure build
>    
>    * ```
>        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=NO \
>        -DCMAKE_INSTALL_PREFIX=/opt/opencv -DBUILD_DOCS=OFF -DBUILD_EXAMPLES=OFF \
>        -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_opencv_java=OFF \
>        -DBUILD_opencv_python=OFF -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib-4.x/modules \
>        ../opencv-4.x
>      ```
> 5. compile and install opencv
>    
>    * ```
>        make -j8 && make install
>      ```
> 6. go to rust project
> 7. compile rust project with:
>    
>    * ```
>        OPENCV_LINK_LIBS="opencv_imgproc,opencv_face,opencv_objdetect,opencv_dnn,opencv_dnn_objdetect,opencv_core,ippiw,ittnotify,ippicv,liblibprotobuf,z" \
>        OPENCV_LINK_PATHS=/opt/opencv/lib,/opt/opencv/lib/opencv4/3rdparty,/usr/lib/x86_64-linux-gnu \
>        OPENCV_INCLUDE_PATHS=/opt/opencv/include/opencv4 \
>        cargo build --release
>      ```

thread 'main' panicked at 'Cannot initialize clang: "the `libclang` shared library at /usr/lib/libclang.so.15.0.7 could not be opened: Dynamic loading not supported"', /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/opencv-0.81.2/build/generator.rs:49:37

how can i fix now?

**Comment by spoorn** [comment]
For anyone looking at this in the future, I have a [github actions workflow file that statically links OpenCV into my binary for Windows, macOS, and Linux](https://github.com/spoorn/media-to-ascii/blob/a01017fbb3dc883a89b0a1aff237c69b072542b2/.github/workflows/build.yml)

There are also comments in workflow file to help understand the differences between platforms

**Comment by HuakunShen** [comment]
> For anyone looking at this in the future, I have a [github actions workflow file that statically links OpenCV into my binary for Windows, macOS, and Linux](https://github.com/spoorn/media-to-ascii/blob/a01017fbb3dc883a89b0a1aff237c69b072542b2/.github/workflows/build.yml)
> 
> There are also comments in workflow file to help understand the differences between platforms

I am trying to statically link on Mac, but could not get it working.
I am using `brew install opencv` instead of building from source.

```bash
clang_dir="$(clang --print-search-dirs | awk -F= '/^libraries: =/ { print $2 }')"
export OPENCV_LINK_LIBS="opencv_imgproc,opencv_core,opencv_videoio"
export OPENCV_LINK_PATHS=/opt/homebrew/lib,/opt/homebrew/lib/opencv4/3rdparty,$clang_dir/lib/darwin
export OPENCV_INCLUDE_PATHS=/opt/homebrew/include,/opt/homebrew/include/opencv4
cargo build --release
```

The final output is only 408KB.

**Comment by twistedfall** [comment]
`brew install` only installs dynamic build of OpenCV as far as I know, you can't build statically with it

**Comment by B-Acharya** [comment]
Hey,  

I was able to build OpenCV statically, but when I ran `cargo build`, I encountered linker errors related to `zlib` and `libpng`. I resolved this by explicitly setting the following in my environment:

```bash
OPENCV_LINK_LIBS="opencv_objdetect,opencv_videoio,opencv_imgcodecs,opencv_imgproc,opencv_core,zlib,liblibpng"
```
I am not sure if this is the right way to go about it.

**Comment by twistedfall** [comment]
> I am not sure if this is the right way to go about it.

It is, if we don't get proper link library list from the package manager, you have those controls to fix it. You can also use the "+" notation, to only add the libraries to what package manager provided without overwriting the whole list:
```
OPENCV_LINK_LIBS="+zlib,liblibpng"
```

**Comment by B-Acharya** [comment]
Are there any guides available for getting FFmpeg to work with OpenCV, specifically for processing videos? I'm trying to build FFmpeg statically, but I'm running into linker issues and haven't had much luck getting it to work.

If anyone knows of a reliable reference or step-by-step guide, that would be really helpful.

Alternatively, is there another way to process video files in OpenCV without relying on FFmpeg?

**Comment by jb-alvarado** [comment]
> I'm trying to build FFmpeg statically, but I'm running into linker issues and haven't had much luck getting it to work.
> 

The easiest is, that you search for compiler scripts, many of them compile static libs.


> Alternatively, is there another way to process video files in OpenCV without relying on FFmpeg?

You can process your video with a ffmpeg instance to stdout and use the stream in opencv.
