### ISSUE TITLE
Request for missed C++ cv::fisheye::projectPoints function.

### ISSUE THREAD

**Issue by qwerty19106** [twistedfall/opencv-rust#365]
The [opencv::calib3d::fisheye_undistort_points](https://docs.rs/opencv/latest/opencv/calib3d/fn.fisheye_undistort_points.html) Rust function corresponds to [cv::fisheye::undistort_points](https://docs.opencv.org/4.5.5/db/d58/group__calib3d__fisheye.html#gab738cdf90ceee97b2b52b0d0e7511541) C++ function.

But [cv::fisheye::distort_points](https://docs.opencv.org/4.5.5/db/d58/group__calib3d__fisheye.html#ga75d8877a98e38d0b29b6892c5f8d7765) C++ function has not analog in Rust.
I expected to see something like **opencv::calib3d::fisheye_distort_points**.

**Comment by twistedfall** [comment]
Hi, sorry for the late reply, the function you're looking for is actually this one: https://docs.rs/opencv/latest/opencv/calib3d/fn.distort_points.html, it just doesn't have the `fisheye_` prefix. I'll add the prefix in the next release, but for now you can use the function.

**Comment by twistedfall** [comment]
v0.69.0 has been released with this fix

**Comment by qwerty19106** [comment]
P.S. CHANGES.md contains two 0.68.0 releases.
