### ISSUE TITLE
using opencv tracker

### ISSUE THREAD

**Issue by yeokiwi** [twistedfall/opencv-rust#375]
Hi, 
I am a newbie in Rust but I have substantial experience in opencv and c++.

does anyone know how to call the following statements in Rust?

Ptr<Tracker> tracker = TrackerKCF::create();

and

tracker->init(frame,roi);

I have tried the following:
let mut tracker = \<dyn TrackerKCF\> :: create(param)?;

but it doesn't seem to be correct and I could not reference the init method

https://docs.opencv.org/4.x/d2/d0a/tutorial_introduction_to_tracker.html
and
https://docs.rs/opencv/0.68.0/opencv/tracking/index.html

**Comment by twistedfall** [comment]
It might as well be an omission in the binding generation. Can you please post some minimal example that works in C++ and your attempt to translate this example to Rust? I can try to help from there. But other than that, here is the `init` method you're looking for: https://docs.rs/opencv/0.68.0/opencv/types/type.PtrOfTrackerKCF.html#method.init and your creation `PtrOfTrackerKCF` seems to be legit, so I'll need some example I can work with.

**Comment by yeokiwi** [comment]
[tracker.txt](https://github.com/twistedfall/opencv-rust/files/9697969/tracker.txt)
[main - Copy_rs.txt](https://github.com/twistedfall/opencv-rust/files/9697978/main.-.Copy_rs.txt)

The error messages are as followed:

PS D:\rust\cargo\hello_cargo> cargo build
   Compiling hello_cargo v0.1.0 (D:\rust\cargo\hello_cargo)
warning: unused import: `tracking`
 --> src\main.rs:6:2
  |
6 |     tracking,
  |     ^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0599]: no method named `init` found for struct `Ptr` in the current scope
    --> src\main.rs:38:10
     |
38   |     tracker.init(&m, bounding_box).unwrap();
     |             ^^^^ method not found in `Ptr<dyn opencv::prelude::TrackerKCF>`
     |
    ::: C:\Users\yeoki\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-0.68.0\src\opencv\hub\video.rs:2101:8
     |
2101 |     fn init(&mut self, image: &dyn core::ToInputArray, bounding_box: core::Rect) -> Result<()> {
     |        ---- the method is available for `Ptr<dyn opencv::prelude::TrackerKCF>` here
     |
     = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
     |
1    | use opencv::video::Tracker;
     |

error[E0599]: no method named `update` found for struct `Ptr` in the current scope
    --> src\main.rs:44:12
     |
44   |             tracker.update(&m, &mut bounding_box).unwrap();
     |                     ^^^^^^ method not found in `Ptr<dyn opencv::prelude::TrackerKCF>`
     |
    ::: C:\Users\yeoki\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-0.68.0\src\opencv\hub\video.rs:2121:8
     |
2121 |     fn update(&mut self, image: &dyn core::ToInputArray, bounding_box: &mut core::Rect) -> Result<bool> {
     |        ------ the method is available for `Ptr<dyn opencv::prelude::TrackerKCF>` here
     |
     = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
     |
1    | use opencv::video::Tracker;
     |

For more information about this error, try `rustc --explain E0599`.
warning: `hello_cargo` (bin "hello_cargo") generated 1 warning
error: could not compile `hello_cargo` due to 2 previous errors; 1 warning emitted
PS D:\rust\cargo\hello_cargo>

**Comment by twistedfall** [comment]
I can see the issue now, to work this around you need to have an explicit import for:
```rust
use opencv::video::Tracker;
```
In theory it shouldn't be needed because you already imported `opencv::prelude::*` but I can see that there is currently 2 traits named `Tracker` and wildcard imports only import the first one. I'll try to fix it later, but for now an explicit import should do.

**Comment by yeokiwi** [comment]
Thanks for the troubleshoot, i can init and update the tracker now.

For anyone that is interested, the code is attached.
[main_rs - Copy.txt](https://github.com/twistedfall/opencv-rust/files/9739333/main_rs.-.Copy.txt)
