### ISSUE TITLE
Also Can't get kind of parent for cpp namespace

### ISSUE THREAD

**Issue by jingsupo** [twistedfall/opencv-rust#376]
I checked https://github.com/twistedfall/opencv-rust/issues/369 , but the problem still occurred:

1. Operating system : Windows 10
2. The way you installed OpenCV: https://github.com/opencv/opencv/releases/download/4.6.0/opencv-4.6.0-vc14_vc15.exe
3. OpenCV version : 4.6.0
4. rustc version : rustc 1.64.0
5. Attach the full output of the following command from your project directory : 
[error.txt](https://github.com/twistedfall/opencv-rust/files/9692333/error.txt)

![image](https://user-images.githubusercontent.com/7351235/193451332-b0e5926c-acb5-4b61-a132-df822173bb08.png)

![image](https://user-images.githubusercontent.com/7351235/193451372-e079f602-a233-436b-b235-2bbc6001fd59.png)

**Comment by twistedfall** [comment]
I can see that it's still referring to version 0.47.0 of the `opencv-binding-generator`:
```
 C:\Users\admin\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-binding-generator-0.47.0\src\element.rs
```
Can you please try doing a `cargo clean` followed up by `cargo update` and then `cargo build`? It should work.

**Comment by jingsupo** [comment]
I emptied three directories :

![image](https://user-images.githubusercontent.com/7351235/193458940-427b08ef-4002-4504-8646-b13cf8c6dbe8.png)

I dont know why, its showing `Compiling opencv-binding-generator v0.47.1`

![image](https://user-images.githubusercontent.com/7351235/193458837-e3229105-81a8-401f-b025-59d40a79545f.png)

but when i build the project, its also referring to
`C:\Users\admin\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-binding-generator-0.47.0\src\element.rs:75:21`

![image](https://user-images.githubusercontent.com/7351235/193458891-f12cddb5-53f2-4540-8e69-17e434dad2b0.png)

**Comment by jingsupo** [comment]
Even if I emptied the relevant directory and run cargo update, when i build the project, there were always two versions of the opencv-binding-generator, why?

![image](https://user-images.githubusercontent.com/7351235/193459569-753219ad-c3ed-4041-9b82-a4b19097701d.png)

How to refer to version 0.47.1 of the opencv-binding-generator?

**Comment by twistedfall** [comment]
But did you actually run `cargo clean` from the project directory?

**Comment by jingsupo** [comment]
I run `cargo clean` followed up by `cargo update` and then `cargo build` many times, but all not work.

Finally, I edited this file, the problem above is gone.

![image](https://user-images.githubusercontent.com/7351235/193466614-aa15a7b5-ab8b-44d9-a271-89d4b9185a9d.png)

But another problem arises : **fatal error: 'limits' file not found**

The problem was solved by the following methods :

![image](https://user-images.githubusercontent.com/7351235/193466718-1f72413c-6625-4a00-9652-c09f7c4a97b7.png)

![image](https://user-images.githubusercontent.com/7351235/193466845-4a6672a5-1981-46e4-9f80-12a11b01ef79.png)

Finally, I built the project successfully.

**Comment by twistedfall** [comment]
Thanks for the investigation! I'll bump the minimum version requirement for `opencv-binding-generator` in the next release

**Comment by jingsupo** [comment]
Thank you very much! 👍

**Comment by twistedfall** [comment]
v0.69.0 has been released with the fix
