### ISSUE TITLE
undefined reference to `cv::Mat::~Mat()'

### ISSUE THREAD

**Issue by jingsupo** [twistedfall/opencv-rust#377]
Operating system : Windows 10
The way you installed OpenCV: https://github.com/opencv/opencv/releases/download/4.6.0/opencv-4.6.0-vc14_vc15.exe
OpenCV version : 4.6.0
rustc version : rustc 1.64.0
Attach the full output of the following command from your project directory:
[build.txt](https://github.com/twistedfall/opencv-rust/files/9695046/build.txt)

My Cargo.toml : 

```
[package]
name = "opencv-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = { version = "0.68.0" }

```

My main.rs : 

```
use opencv::{highgui, prelude::*, videoio, Result};

fn main() -> Result<()> {
    let window = "video capture";
    highgui::named_window(window, highgui::WINDOW_AUTOSIZE)?;
    opencv::opencv_branch_32! {
        let mut cam = videoio::VideoCapture::new_default(0)?; // 0 is the default camera
    }
    opencv::not_opencv_branch_32! {
        let mut cam = videoio::VideoCapture::new(0, videoio::CAP_ANY)?; // 0 is the default camera
    }
    let opened = videoio::VideoCapture::is_opened(&cam)?;
    if !opened {
        panic!("Unable to open default camera!");
    }
    loop {
        let mut frame = Mat::default();
        cam.read(&mut frame)?;
        if frame.size()?.width > 0 {
            highgui::imshow(window, &mut frame)?;
        }
        let key = highgui::wait_key(10)?;
        if key > 0 && key != 255 {
            break;
        }
    }
    Ok(())
}

```

**Comment by jingsupo** [comment]
running `cargo build -vv` after `cargo clean`
[build.txt](https://github.com/twistedfall/opencv-rust/files/9695170/build.txt)

**Comment by twistedfall** [comment]
I don't see anything obviously out of ordinary in your setup. By the sheer amount of linking issues it looks like the `opencv_world460.lib` is not getting linked at all. You might try building with Visual Studio C++ instead of Mingw, I haven't tested the mingw toolchain at all.

**Comment by jingsupo** [comment]
Thanks! There may be a problem with my opencv installation, lets close the issue and when I have time i will reinstall opencv.
