### ISSUE TITLE
Cannot build on Windows 11, followed all the guides

### ISSUE THREAD

**Issue by stachbial** [twistedfall/opencv-rust#378]
1. Operating system: **Windows 11**
2. The way you installed OpenCV: package, official binary distribution, manual compilation, etc. : ** choco install llvm opencv**
3. OpenCV version **4.6.0 (opencv 0.68.0 crate)**
4. rustc version (`rustc --version`) : **rustc 1.64.0**
5. Attach the full output of the following command from your project directory:
   ```shell script
   RUST_BACKTRACE=full cargo build -vv 
[out.txt](https://github.com/twistedfall/opencv-rust/files/9716452/out.txt)

   ```

Hello, I am trying to use this opencv rust crate , but can not build it at all. I 
followed the README guide in this repository as well as the linked issues (eg. 
https://github.com/twistedfall/opencv-rust/issues/118), unfortunatelly with no 
effects. My enviroment variables are configured as in the following screenshot :

![image](https://user-images.githubusercontent.com/62152942/194089575-c3651235-6a15-406c-bb1b-d4deeadce56e.png)

Ihave also added "C:\tools\opencv\build\x64\vc15\bin" to the PATH variable.

Apparently the building process begins to struggle while the following message is 
visible in the terminal: "[opencv 0.68.0] === Waiting until the binding-generator 
binary is built...
    Building [=======================>   ] 36/39: opencv(build)"

I know that there are several simillar issues already brought up, but despite 
followng all the guids I have not managed to make the build work. I wanted to use
 this crate for my Uni project and now I am worried if I can make it on time. Thanks 
for Your time in advance:)

Ps: Can the version of vs build tools make any difference? I have installed 2022, 
2019 and 2017 ones but it does not seem to be the case

**Comment by stachbial** [comment]
Ok, I found the problem. Basically I had to change the version of the binding generator to 0.47.1 just as documented in [this](https://github.com/twistedfall/opencv-rust/issues/376) Issue :)

**Comment by twistedfall** [comment]
v0.69.0 has been released with the fix
