### ISSUE TITLE
how can I insert train_descriptors in function flann.knn_match() 

### ISSUE THREAD

**Issue by ChenLingxm** [twistedfall/opencv-rust#379]
System:Ubantu 22.04
version:opencv=0.70

I am try to use opencv-rust to do some image retrieval task,
when I use opencv::hub::features2d  knn_match(),I can't find param's position to insert train_descriptors,it's only supply query_descriptors param.
I used to use Python can do it,i don't know Is it my coding error .

// python
// matchs=flann.knnMatch(des1,des2,k=2)

// rust
// flann.knn_match(query_descriptors, matches, k, masks, compact_result);
//flann.knn_match(&des1,&mut matches, 2,&masks, false);

Can someone show the usage of knn_match()?

**Comment by koriwi** [comment]
im sitting here, thinking the same for standard match_

**Comment by twistedfall** [comment]
@ChenLingxm The function you're looking for is [`knn_train_match()`](https://docs.rs/opencv/latest/opencv/prelude/trait.DescriptorMatcherConst.html#method.knn_train_match). Now seeing the confusion probably the better name for it would be `knn_match_train`, what do you think?

@koriwi In your case it's just [`train_match()`](https://docs.rs/opencv/latest/opencv/prelude/trait.DescriptorMatcherConst.html#method.train_match)

**Comment by koriwi** [comment]
Thx. I already found it by comparing python, c++ and rust opencv code :)

Also the train_match function errored because my needle image was too small. So i was double confused for a second.

**Comment by ChenLingxm** [comment]
thanks for you hard work.I think both are ok.
