### ISSUE TITLE
Missing pacman installs on Arch

### ISSUE THREAD

**Issue by dcellucci** [twistedfall/opencv-rust#381]
For whatever reason, the below packages were not installed with the `pacman` command attached in the README and needed to be manually installed for linking to work:
```
vtk
glew
fmt
openmpi
```
If you're cool with it, I am happy to update the README with these packages

**Comment by twistedfall** [comment]
That would be really helpful, thank you!

**Comment by twistedfall** [comment]
Readme is now updated
