### ISSUE TITLE
Vector can be Sync and Send

### ISSUE THREAD

**Issue by jerry73204** [twistedfall/opencv-rust#384]
The [Vector<_>](https://docs.rs/opencv/latest/opencv/core/struct.Vector.html) is not `Sync` and `Send`. It could be as far as its element type is also Sync and Send, and the API ensures safety guarantees. It gives more convenience when it works with multi-threaded code.

**Comment by gyk** [comment]
Also, could we have `Vector::<T>::from_elem(elem, n)` for `T: Clone`?

**Comment by Mibu287** [comment]
@jerry73204, in Rust's `std::Vec` [docs](https://doc.rust-lang.org/std/vec/struct.Vec.html#impl-Sync-for-Vec%3CT%2C%20A%3E), `std::Vec` implement `Sync` iff the underlying data and **the allocator** implement `Sync`. The same logic apply to C++ vector (which is wrapped by `opencv::core::Vector).

Can we assume that C++ vector's allocator always implement `Sync`?

I know, it's a rather pedantic question but I ask for the sake of completeness.

**Comment by twistedfall** [comment]
This has been introduced in v0.71.0 together with `Vector::from_elem()`
