### ISSUE TITLE
Make `VectorRefIterator` clonable

### ISSUE THREAD

**Issue by gyk** [twistedfall/opencv-rust#385]
I want to iterate over the line segments of a contour. Preferably it can be written as

```rust
contour
    .iter()
    .zip(contour.iter().cycle().skip(1))
    .for_each(|(p1, p2)| /* do something*/)
```

However, unlike `std::slice::Iter`, `VectorRefIterator` has not implemented `Clone` trait so we can't call `.cycle()` on it. It would be nice to add `#[derive(Clone)]` to `VectorRefIterator`.

**Comment by pavel-procopiuc** [comment]
Hi, thank you for the suggestion! It seems like an easy fix, can you please try making a PR for that?

**Comment by twistedfall** [comment]
Hi, thank you for the suggestion! It seems like an easy fix, can you please try making a PR for that?

**Comment by gyk** [comment]
@twistedfall Certainly.
