### ISSUE TITLE
Mat struct should not implement Send trait

### ISSUE THREAD

**Issue by Mibu287** [twistedfall/opencv-rust#386]
Currently, the `Mat` struct implement `Send` trait, but I don't think it's correct.

### Problems:
Consider a case below:

```
- Thread 1
Construct mat0
mat1 = mat0.copy() // Or mat1 = mat0.roi(...) or mat1 = mat0.rowscols(...)
// mat0 and mat1 now share the same data buffer
Move mat0 to Thread 2
Mutate mat1

- Thread 2
Mutate mat0

=> Now, the same underlying data is mutated by 2 concurrent threads => data race/undefined behavior.
```

#### 1. Not implement `Send` trait for `Mat` struct
Pros: Easy to implement
Cons: Limit multi-threading capabilities

#### 2. Introduce non-owning structs like `MatView` and `MatViewMut` whose lifetime is bounded by `Mat`
```
- Thread 1
Construct mat0
mat1: MatViewMut = mat0.copy()
Move mat0 to Thread 2 // COMPILER ERROR: Can not move mat0 since it's still being borrowed
Mutate mat1

==> Data race problem is solved
```
Pros: Ownership is clear. This solution also eliminate the possibility of passing the same data buffer as both Input and Output arguments. AFAIK, it's not clear whether it's safe to pass the same buffer as Input and Output arguments.
Cons: Requires more work as opposed to solution 1.

**Comment by twistedfall** [comment]
You're completely right and this is a problem even without considering multiple threads. So I'd say that point 2 is the way to go. There is already a task with that suggestion: https://github.com/twistedfall/opencv-rust/issues/294 but as you said it would require a considerable effort. I'm going to close this bug in favor of 294 if you don't mind.

**Comment by Mibu287** [comment]
> this is a problem even without considering multiple threads.

I agree. The functions like `Mat.copy`, `Mat.roi`, etc create aliasing pointers which is a nasty business.

> I'm going to close this bug in favor of 294 if you don't mind.

Sure. I'm looking forward to future releases.

Btw, thank you for this awesome library.
