### ISSUE TITLE
cargo run returns error: can find libclang.dll but cannot load it

### ISSUE THREAD

**Issue by lishinko** [twistedfall/opencv-rust#388]
I installed llvm from vcpkg, and then when I execute "cargo run", it reports an error, saying it can find libclang.dll, but LoadLibraryExW failed.
I then dumpbined the libclang.dll, it outputs is exported functions just fine.

note: I have seen that the code throwing the panic is in generator.rs:
clang::Clang::new()
but I don't know where the clang::Clang trait is.
Also, please report what concrete error LoadLibraryExW returns, you can call GetLastError() function to achieve this
1. Operating system : Windows 10
2. The way you installed OpenCV: package, official binary distribution, manual compilation, etc. : Vcpkg
3. OpenCV version 4.6.0
4. rustc version (`rustc --version`) rustc 1.64.0 (a55dd71d5 2022-09-19)
5. Attach the full output of the following command from your project directory:
   ```shell script
   RUST_BACKTRACE=full cargo build -vv 
   ```

=== Detected OpenCV module header dir at: D:/software/vcpkg/installed/x64-windows/include\opencv2
  === Found OpenCV version: 4.6.0 in headers located at: D:/software/vcpkg/installed/x64-windows/include
  === Generating code in: E:\repos\remove_shadow_rust\target\debug\build\opencv-9a16a281bce82e6c\out
  === Placing generated bindings into: C:\Users\Admin\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\opencv-0.71.0\src\opencv
  === Using OpenCV headers from: D:/software/vcpkg/installed/x64-windows/include
  thread 'main' panicked at 'Cannot initialize clang: "the `libclang` shared library at D:\\software\\vcpkg\\packages\\llvm_x64-windows\\bin\\libclang.dll could not be opened: LoadLibraryExW failed"', C:\Users\Admin\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\opencv-0.71.0\build\generator.rs:75:37
  stack backtrace:
     0:     0x7ff73bfdaa4f - std::backtrace_rs::backtrace::dbghelp::trace
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
     1:     0x7ff73bfdaa4f - std::backtrace_rs::backtrace::trace_unsynchronized
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
     2:     0x7ff73bfdaa4f - std::sys_common::backtrace::_print_fmt
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\sys_common\backtrace.rs:66
     3:     0x7ff73bfdaa4f - std::sys_common::backtrace::_print::impl$0::fmt
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\sys_common\backtrace.rs:45
     4:     0x7ff73bff84fa - core::fmt::write
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\fmt\mod.rs:1198
     5:     0x7ff73bfd4479 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\io\mod.rs:1672
     6:     0x7ff73bfdd70b - std::sys_common::backtrace::_print
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\sys_common\backtrace.rs:48
     7:     0x7ff73bfdd70b - std::sys_common::backtrace::print
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\sys_common\backtrace.rs:35
     8:     0x7ff73bfdd70b - std::panicking::default_hook::closure$1
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\panicking.rs:295
     9:     0x7ff73bfdd385 - std::panicking::default_hook
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\panicking.rs:314
    10:     0x7ff73bfddcb9 - std::panicking::rust_panic_with_hook
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\panicking.rs:698
    11:     0x7ff73bfddbbd - std::panicking::begin_panic_handler::closure$0
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\panicking.rs:588
    12:     0x7ff73bfdb687 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\sys_common\backtrace.rs:138
    13:     0x7ff73bfdd899 - std::panicking::begin_panic_handler
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\panicking.rs:584
    14:     0x7ff73c0001c5 - core::panicking::panic_fmt
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\panicking.rs:142
    15:     0x7ff73c0002d3 - core::result::unwrap_failed
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\result.rs:1814
    16:     0x7ff73bd3dc73 - enum$<core::result::Result<clang::Clang,alloc::string::String>, 1, 18446744073709551615, Err>::expect<clang::Clang,alloc::string::String>
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52\library\core\src\result.rs:1064
    17:     0x7ff73bd40ca0 - build_script_build::generator::gen_wrapper
                                 at C:\Users\Admin\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\opencv-0.71.0\build\generator.rs:75
    18:     0x7ff73bd59cd1 - build_script_build::main
                                 at C:\Users\Admin\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\opencv-0.71.0\build.rs:388
    19:     0x7ff73bd47a9b - core::ops::function::FnOnce::call_once<enum$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<std::error::Error>,alloc::alloc::Global> >, 1, 18446744073709551615, Err> (*)(),tuple$<> >
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52\library\core\src\ops\function.rs:248
    20:     0x7ff73bd5af8b - std::sys_common::backtrace::__rust_begin_short_backtrace<enum$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<std::error::Error>,alloc::alloc::Global> >, 1, 18446744073709551615, Err> (*)(),enum$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52\library\std\src\sys_common\backtrace.rs:122
    21:     0x7ff73bd47281 - std::rt::lang_start::closure$0<enum$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<std::error::Error>,alloc::alloc::Global> >, 1, 18446744073709551615, Err> >
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52\library\std\src\rt.rs:145
    22:     0x7ff73bfcdaab - core::ops::function::impls::impl$2::call_once
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\ops\function.rs:280
    23:     0x7ff73bfcdaab - std::panicking::try::do_call
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\panicking.rs:492
    24:     0x7ff73bfcdaab - std::panicking::try
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\panicking.rs:456
    25:     0x7ff73bfcdaab - std::panic::catch_unwind
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\panic.rs:137
    26:     0x7ff73bfcdaab - std::rt::lang_start_internal::closure$2
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\rt.rs:128
    27:     0x7ff73bfcdaab - std::panicking::try::do_call
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\panicking.rs:492
    28:     0x7ff73bfcdaab - std::panicking::try
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\panicking.rs:456
    29:     0x7ff73bfcdaab - std::panic::catch_unwind
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\panic.rs:137
    30:     0x7ff73bfcdaab - std::rt::lang_start_internal
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\rt.rs:128
    31:     0x7ff73bd4724f - std::rt::lang_start<enum$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<std::error::Error>,alloc::alloc::Global> >, 1, 18446744073709551615, Err> >
                                 at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52\library\std\src\rt.rs:144
    32:     0x7ff73bd5a466 - main
    33:     0x7ff73bffe86c - invoke_main
                                 at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    34:     0x7ff73bffe86c - __scrt_common_main_seh
                                 at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    35:     0x7ffadceb7034 - <unknown>
    36:     0x7ffadd5226a1 - RtlUserThreadStart

**Comment by twistedfall** [comment]
Can you check the Troubleshooting section here: https://github.com/twistedfall/opencv-rust#troubleshooting ? Specifically items 3 and 4.

**Comment by twistedfall** [comment]
Did it work?

**Comment by twistedfall** [comment]
I'll close the issue, but feel free to reopen if you're still experiencing issues
