### ISSUE TITLE
Crate always recompiling

### ISSUE THREAD

**Issue by twantonie** [twistedfall/opencv-rust#390]
Including the PATH variable in ENV_VARS of the build.rs script is causing my workflow to pretty much continuously recompile opencv. I'd suggest reverting commit 94b0d1ead6c8151316c3c4d80666b8a02e658530 since the PATH variable isn't actually used in the building of opencv.

For context my workflow is as follows:
- Make changes in vscode
- cargo check runs after saving
- run cargo build in the console

Since vscode uses a different path environment than my console the opencv-rust crate recompiles every single time, costing me quite a bit of development time (on my reasonably chunky pc compiling opencv-rust takes at least 30 seconds).

I'll be downgrading to version 0.69.0 to avoid this issue, but I'd thought I'd mention it here for other people noticing the same thing.

**Comment by twistedfall** [comment]
Thanks for the report, it should be fixed in v0.72.1!
