### ISSUE TITLE
could not find `aruco_detector`

### ISSUE THREAD

**Issue by kevleyski** [twistedfall/opencv-rust#391]
1. MacOS
2. manual compilation
3. Tip of github x4.1 branch
4. rustc 1.66.0-nightly (9062b780b 2022-09-21)
5. Attach the full output of the following command from your project directory:
   ```shell script
error[E0433]: failed to resolve: could not find `aruco_detector` in the crate root
   --> /Users/klambert/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.71.0/src/opencv/hub/aruco.rs:811:488
    |
811 | ...ray, parameters: &core::Ptr<crate::aruco_detector::DetectorParameters>) -> Result<()> {
    |                                       ^^^^^^^^^^^^^^ could not find `aruco_detector` in the crate root
   ```

**Comment by twistedfall** [comment]
Thanks for the report! There is already an issue about it, I'll close this bug in favor of https://github.com/twistedfall/opencv-rust/issues/382
