### ISSUE TITLE
Mat::zeros() returns a MatExpr

### ISSUE THREAD

**Issue by JPGygax68** [twistedfall/opencv-rust#393]
...instead of a `Mat`, and I find no indication on how to convert.

**Comment by twistedfall** [comment]
[`to_mat()`](https://docs.rs/opencv/latest/opencv/prelude/trait.MatExprTraitConst.html#method.to_mat) will do the trick

**Comment by JPGygax68** [comment]
Ouch. I was missing that method because I didn't include the prelude.. Sorry.
