### ISSUE TITLE
JPEG Sampling factor missing

### ISSUE THREAD

**Issue by AsriFox** [twistedfall/opencv-rust#397]
opencv::imgcodecs::ImwriteFlags::[IMWRITE_JPEG_SAMPLING_FACTOR](https://docs.opencv.org/4.x/d8/d6a/group__imgcodecs__flags.html#ga292d81be8d76901bff7988d18d2b42ac) flag and [ImwriteJPEGSamplingFactorParams](https://docs.opencv.org/4.x/d8/d6a/group__imgcodecs__flags.html#ga4b97ca569a53587801257896d79656e1) enum are missing from this crate.

**Comment by twistedfall** [comment]
This flag was added in the master branch of the OpenCV only, i.e. it's missing from the latest release 4.6.0: https://docs.opencv.org/4.6.0/d8/d6a/group__imgcodecs__flags.html#ga292d81be8d76901bff7988d18d2b42ac

If you install the latest master OpenCV the crate should generate this enum variant for you, but I'm running no tests on non-released OpenCV versions so you might encounter other breakage.

**Comment by AsriFox** [comment]
I see. Thank you.
