### ISSUE TITLE
imgproc::match_template fails

### ISSUE THREAD

**Issue by boludoz** [twistedfall/opencv-rust#399]
OS: WINDOWS 11
OPENCV: 4.6.0

CODE:
```
use opencv::{core, imgcodecs, imgproc, prelude::*};

fn main() {
    let s = imgcodecs::imread("s.png", imgcodecs::IMREAD_COLOR).unwrap();
    let t = imgcodecs::imread("t.png", imgcodecs::IMREAD_COLOR).unwrap();
    let mask = imgcodecs::imread("", imgcodecs::IMREAD_GRAYSCALE).unwrap();
    let zero = Mat::zeros(
        s.rows() - t.rows() + 1,
        s.cols() - t.cols() + 1,
        core::CV_32FC1,
    )
    .unwrap();
    let mut result = zero.to_mat().unwrap();
    imgproc::match_template(&s, &t, &mut result, imgproc::TM_CCORR_NORMED, &mask);
    println!("{:?}", result);
}

```
LOG:
`PS C:\RUST\open_example\target\debug> ./open_example.exe
[ WARN:0@0.003] global c:\build\master_winpack-build-win64-vc15\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_(''): can't open/read file: check file path/integrity
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -215, message: "OpenCV(4.6.0) c:\\build\\master_winpack-build-win64-vc15\\opencv\\modules\\core\\src\\matrix.cpp:246: error: (-215:Assertion failed) s >= 0 in function 'cv::setSize'\n" }', src\main.rs:12:36
stack backtrace:
   0:     0x7ff72892f0c2 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff72892f0c2 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff72892f0c2 - std::sys_common::backtrace::_print_fmt
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:66
   3:     0x7ff72892f0c2 - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:45
   4:     0x7ff72893e51b - core::fmt::write
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\fmt\mod.rs:1202
   5:     0x7ff72892cf5a - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\io\mod.rs:1679
   6:     0x7ff728931124 - std::sys_common::backtrace::_print
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:48
   7:     0x7ff728931124 - std::sys_common::backtrace::print
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:35
   8:     0x7ff728931124 - std::panicking::default_hook::closure$1
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:295
   9:     0x7ff728930d5a - std::panicking::default_hook
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:314
  10:     0x7ff728931911 - std::panicking::rust_panic_with_hook
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:698
  11:     0x7ff72893181d - std::panicking::begin_panic_handler::closure$0
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:588
  12:     0x7ff72892faef - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:138
  13:     0x7ff7289314e0 - std::panicking::begin_panic_handler
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:584
  14:     0x7ff728b1d025 - core::panicking::panic_fmt
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:142
  15:     0x7ff728b1d0c3 - core::result::unwrap_failed
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\result.rs:1785
  16:     0x7ff72892360a - enum2$<core::result::Result<opencv::opencv::hub::core::Mat,opencv::error::Error> >::unwrap<opencv::opencv::hub::core::Mat,opencv::error::Error>
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\result.rs:1107
  17:     0x7ff7289226e0 - open_example::main
                               at C:\RUST\open_example\src\main.rs:12
  18:     0x7ff728922ddb - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\ops\function.rs:248
  19:     0x7ff72892246e - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\std\src\sys_common\backtrace.rs:122
  20:     0x7ff72892246e - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\std\src\sys_common\backtrace.rs:122
  21:     0x7ff728922ca1 - std::rt::lang_start::closure$0<tuple$<> >
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\std\src\rt.rs:166
  22:     0x7ff72892aa9e - core::ops::function::impls::impl$2::call_once
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\ops\function.rs:283
  23:     0x7ff72892aa9e - std::panicking::try::do_call
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:492
  24:     0x7ff72892aa9e - std::panicking::try
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:456
  25:     0x7ff72892aa9e - std::panic::catch_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panic.rs:137
  26:     0x7ff72892aa9e - std::rt::lang_start_internal::closure$2
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\rt.rs:148
  27:     0x7ff72892aa9e - std::panicking::try::do_call
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:492
  28:     0x7ff72892aa9e - std::panicking::try
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:456
  29:     0x7ff72892aa9e - std::panic::catch_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panic.rs:137
  30:     0x7ff72892aa9e - std::rt::lang_start_internal
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\rt.rs:148
  31:     0x7ff728922c7a - std::rt::lang_start<tuple$<> >
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\std\src\rt.rs:165
  32:     0x7ff72892290c - main
  33:     0x7ff728b1b338 - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  34:     0x7ff728b1b338 - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  35:     0x7ff83918335d - BaseThreadInitThunk
  36:     0x7ff83af57f38 - RtlUserThreadStart`

**Comment by boludoz** [comment]
I want to do something like this done here: [](https://docs.opencv.org/4.x/d4/dc6/tutorial_py_template_matching.html)
```
import cv2 as cv
import numpy as np
from matplotlib import pyplot as plt
img_rgb = cv.imread('mario.png')
img_gray = cv.cvtColor(img_rgb, cv.COLOR_BGR2GRAY)
template = cv.imread('mario_coin.png',0)
w, h = template.shape[::-1]
res = cv.matchTemplate(img_gray,template,cv.TM_CCOEFF_NORMED)
threshold = 0.8
loc = np.where( res >= threshold)
for pt in zip(*loc[::-1]):
    cv.rectangle(img_rgb, pt, (pt[0] + w, pt[1] + h), (0,0,255), 2)
cv.imwrite('res.png',img_rgb)
```

**Comment by twistedfall** [comment]
That line looks suspicious:
```rust
let mask = imgcodecs::imread("", imgcodecs::IMREAD_GRAYSCALE).unwrap();
```
You're trying to load a file without a name. Are you just trying to make an empty mask? Then this should work:
```rust
let mask = Mat::default();
```

**Comment by boludoz** [comment]
Ok sir, thank you very much, I'll try again.

**Comment by boludoz** [comment]
@twistedfall the problem is in _"let mut result = zero.to_mat().unwrap();"_ and i dont know how fix tath

**Comment by boludoz** [comment]
Ok, apparently the template was bigger than the image, an official example would be useful.
