### ISSUE TITLE
Support OpenCV 4.7.0?

### ISSUE THREAD

**Issue by LeeeSe** [twistedfall/opencv-rust#407]
- Mac M1 12.6.2 
- `brew install opencv`
- opencv 4.7.0
- rustc 1.66.1 (90743e729 2023-01-10)
- log 
[log.txt](https://github.com/twistedfall/opencv-rust/files/10398740/log.txt)

**Comment by twistedfall** [comment]
Thanks! I’m aware of this and the fix should be available in the `rel` branch. I just need to sort out tests and make a release.

**Comment by LeeeSe** [comment]
Thank you for your work!

**Comment by twistedfall** [comment]
This is now released in 0.75.0
