### ISSUE TITLE
Rust compile failed on Mac

### ISSUE THREAD

**Issue by pingqiangguo** [twistedfall/opencv-rust#409]
My operating system is MacOS 11.7. I am attempting to use this library to achieve the ability to convert images to videos. When I trying to compile the project with cargo build, I encounter the following error:
 
 
           Undefined symbols for architecture x86_64:
            "_OBJC_METACLASS_$_NSView", referenced from:
                _OBJC_METACLASS_$_CVView in libopencv_highgui4d.a(window_cocoa.mm.o)
                _OBJC_METACLASS_$_CVSlider in libopencv_highgui4d.a(window_cocoa.mm.o)
            "_OBJC_CLASS_$_NSSlider", referenced from:
                objc-class-ref in libopencv_highgui4d.a(window_cocoa.mm.o)
            "_OBJC_CLASS_$_NSTextField", referenced from:
                objc-class-ref in libopencv_highgui4d.a(window_cocoa.mm.o)
            "_OBJC_CLASS_$_NSBitmapImageRep", referenced from:
                objc-class-ref in libopencv_highgui4d.a(window_cocoa.mm.o)
            "_OBJC_CLASS_$_NSView", referenced from:
                objc-class-ref in libopencv_highgui4d.a(window_cocoa.mm.o)
                _OBJC_CLASS_$_CVView in libopencv_highgui4d.a(window_cocoa.mm.o)
                _OBJC_CLASS_$_CVSlider in libopencv_highgui4d.a(window_cocoa.mm.o)
            "_OBJC_CLASS_$_NSEvent", referenced from:
                objc-class-ref in libopencv_highgui4d.a(window_cocoa.mm.o)
            "_OBJC_CLASS_$_NSMutableDictionary", referenced from:
                objc-class-ref in libopencv_highgui4d.a(window_cocoa.mm.o)
            "_objc_opt_respondsToSelector", referenced from:
                -[CVView setFrameSize:] in libopencv_highgui4d.a(window_cocoa.mm.o)
            "_NSDeviceRGBColorSpace", referenced from:
                -[CVView setImageData:] in libopencv_highgui4d.a(window_cocoa.mm.o)
            "_objc_getProperty", referenced from:
                -[CVWindow sliders] in libopencv_highgui4d.a(window_cocoa.mm.o)
                -[CVWindow slidersKeys] in libopencv_highgui4d.a(window_cocoa.mm.o)
                -[CVView image] in libopencv_highgui4d.a(window_cocoa.mm.o)
                -[CVView imageView] in libopencv_highgui4d.a(window_cocoa.mm.o)
                -[CVSlider slider] in libopencv_highgui4d.a(window_cocoa.mm.o)
                -[CVSlider name] in libopencv_highgui4d.a(window_cocoa.mm.o)
                -[CVSlider initialName] in libopencv_highgui4d.a(window_cocoa.mm.o)
                ...
            "_clWaitForEvents", referenced from:
                _clWaitForEvents_pfn in libopencv_core4d.a(opencl_core.cpp.o)
               (maybe you meant: _clWaitForEvents_pfn)
            "_clSetKernelArg", referenced from:
                _clSetKernelArg_pfn in libopencv_core4d.a(opencl_core.cpp.o)
               (maybe you meant: _clSetKernelArg_pfn)
            "_clSetEventCallback", referenced from:
                _clSetEventCallback_pfn in libopencv_core4d.a(opencl_core.cpp.o)
               (maybe you meant: _clSetEventCallback_pfn)
            "_clReleaseMemObject", referenced from:
                _clReleaseMemObject_pfn in libopencv_core4d.a(opencl_core.cpp.o)
               (maybe you meant: _clReleaseMemObject_pfn)
            "_clReleaseEvent", referenced from:
                _clReleaseEvent_pfn in libopencv_core4d.a(opencl_core.cpp.o)
               (maybe you meant: _clReleaseEvent_pfn)
            "_clReleaseDevice", referenced from:
                _clReleaseDevice_pfn in libopencv_core4d.a(opencl_core.cpp.o)
               (maybe you meant: _clReleaseDevice_pfn)
            "_clReleaseCommandQueue", referenced from:
                _clReleaseCommandQueue_pfn in libopencv_core4d.a(opencl_core.cpp.o)
               (maybe you meant: _clReleaseCommandQueue_pfn)
            "_clGetProgramInfo", referenced from:
                _clGetProgramInfo_pfn in libopencv_core4d.a(opencl_core.cpp.o)
               (maybe you meant: _clGetProgramInfo_pfn)
            "_clGetProgramBuildInfo", referenced from:
                _clGetProgramBuildInfo_pfn in libopencv_core4d.a(opencl_core.cpp.o)
               (maybe you meant: _clGetProgramBuildInfo_pfn)
            "_clGetPlatformIDs", referenced from:
                _clGetPlatformIDs_pfn in libopencv_core4d.a(opencl_core.cpp.o)
               (maybe you meant: _clGetPlatformIDs_pfn)
            "_clGetDeviceInfo", referenced from:
                _clGetDeviceInfo_pfn in libopencv_core4d.a(opencl_core.cpp.o)
               (maybe you meant: _clGetDeviceInfo_pfn)
            "_clEnqueueWriteBufferRect", referenced from:
                _clEnqueueWriteBufferRect_pfn in libopencv_core4d.a(opencl_core.cpp.o)
               (maybe you meant: _clEnqueueWriteBufferRect_pfn)
            "_clEnqueueWriteBuffer", referenced from:
                _clEnqueueWriteBuffer_pfn in libopencv_core4d.a(opencl_core.cpp.o)
               (maybe you meant: _clEnqueueWriteBuffer_pfn, _clEnqueueWriteBufferRect_pfn )
            "_NSZeroRect", referenced from:
                -[CVView drawRect:] in libopencv_highgui4d.a(window_cocoa.mm.o)
            "_clEnqueueUnmapMemObject", referenced from:
                _clEnqueueUnmapMemObject_pfn in libopencv_core4d.a(opencl_core.cpp.o)
[error.log](https://github.com/twistedfall/opencv-rust/files/10417079/error.log)

**Comment by twistedfall** [comment]
I'm seeing a lot of "was built for newer macOS version (11.7) than being linked (11.0)", maybe it's a reason?

**Comment by pingqiangguo** [comment]
My opencv was installed using the vcpkg install opencv command, and when compiling the project with cargo build, I found that if the project did not include the image library, it would also fail to compile. After I added this dependency library, the compilation error was temporarily solved. I'm not sure which additional crates need to be added for cv library to be supported, or if any configuration of features is required?

**Comment by twistedfall** [comment]
Regarding the crates the cargo will take care of all necessary dependencies, but OpenCV library itself might require some external shared libraries. Usually it's handled by the auto-discovery mechanism (using pkg-config, cmake or vcpkg), but sometimes it might give wrong or incomplete results. In this case you can use some helper [environment variables](https://github.com/twistedfall/opencv-rust#environment-variables): `OPENCV_LINK_LIBS`, `OPENCV_LINK_PATHS` and `OPENCV_INCLUDE_PATHS`.

**Comment by jb-alvarado** [comment]
I had the same issue and fix it with building opencv with:

```
-DCMAKE_OSX_DEPLOYMENT_TARGET="11.0" -DWITH_OPENCL=OFF -DWITH_OPENCLAMDFFT=OFF -DWITH_OPENCLAMDBLAS=OFF -DWITH_VA_INTEL=OFF -DWITH_LAPACK=OFF
```

**Comment by twistedfall** [comment]
Looks like there is a solution to this problem so I'm going to close this issue, please feel free to reopen if you need more support on this.
