### ISSUE TITLE
Dose opencv:dnn support Vulkan?

### ISSUE THREAD

**Issue by LeeeSe** [twistedfall/opencv-rust#410]
I installed the VULKAN SDK according to the tutorial on the official VULKAN website and tried to set up VULKAN as a computing backend

`net.set_preferable_backend(opencv::dnn::DNN_BACKEND_VKCOM).unwrap();`
`net.set_preferable_target(opencv::dnn::DNN_TARGET_VULKAN).unwrap();`

But the computation time I get is exactly the same as the CPU, even the GPU is not called at all.
Is it because there is something wrong with my usage or opencv-rust does not support using VULKAN?

**Comment by LeeeSe** [comment]
same as opencl

**Comment by twistedfall** [comment]
OpenCL and CUDA definitely work, I've tested that myself:
* https://github.com/twistedfall/opencv-rust/blob/master/examples/opencl.rs
* https://github.com/twistedfall/opencv-rust/blob/master/examples/cuda.rs

I'm not 100% sure about Vulkan, but after a quick looks I'd say it works the similarly, so it's imperative that OpenCV needs to be built with it support enabled.

Did you build OpenCV yourself or using a pre-compiled distribution? I'd say that the former is the best bet and you can see in the configuration log whether the corresponding features are enabled for sure.

**Comment by LeeeSe** [comment]
I see, maybe I need to build OpenCV manually

**Comment by twistedfall** [comment]
Any luck?
