### ISSUE TITLE
Difficulty using the `opencv::calib3d::find_circles_grid()` function

### ISSUE THREAD

**Issue by molysgaard** [twistedfall/opencv-rust#413]
1. Ubuntu 20.04
2. The way you installed OpenCV: sudo apt install libopencv-dev
3. version information: 
```
Package: libopencv-dev
Version: 4.2.0+dfsg-5
Priority: optional
Section: universe/libdevel
Source: opencv
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Science Team <debian-science-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 409 kB
Depends: libopencv-calib3d-dev (= 4.2.0+dfsg-5), libopencv-contrib-dev (= 4.2.0+dfsg-5), libopencv-core-dev (= 4.2.0+dfsg-5), libopencv-dnn-dev (= 4.2.0+dfsg-5), libopencv-features2d-dev (= 4.2.0+dfsg-5), libopencv-flann-dev (= 4.2.0+dfsg-5), libopencv-highgui-dev (= 4.2.0+dfsg-5), libopencv-imgcodecs-dev (= 4.2.0+dfsg-5), libopencv-imgproc-dev (= 4.2.0+dfsg-5), libopencv-ml-dev (= 4.2.0+dfsg-5), libopencv-objdetect-dev (= 4.2.0+dfsg-5), libopencv-photo-dev (= 4.2.0+dfsg-5), libopencv-shape-dev (= 4.2.0+dfsg-5), libopencv-stitching-dev (= 4.2.0+dfsg-5), libopencv-superres-dev (= 4.2.0+dfsg-5), libopencv-ts-dev (= 4.2.0+dfsg-5), libopencv-video-dev (= 4.2.0+dfsg-5), libopencv-videoio-dev (= 4.2.0+dfsg-5), libopencv-videostab-dev (= 4.2.0+dfsg-5), libopencv-viz-dev (= 4.2.0+dfsg-5), libopencv4.2-java (= 4.2.0+dfsg-5), pkg-config, libc6 (>= 2.14), libgcc-s1 (>= 3.0), libopencv-calib3d4.2 (>= 4.2.0+dfsg), libopencv-contrib4.2 (>= 4.2.0+dfsg), libopencv-core4.2 (>= 4.2.0+dfsg), libopencv-features2d4.2 (>= 4.2.0+dfsg), libopencv-highgui4.2 (>= 4.2.0+dfsg), libopencv-imgcodecs4.2 (>= 4.2.0+dfsg), libopencv-imgproc4.2 (>= 4.2.0+dfsg), libopencv-videoio4.2 (>= 4.2.0+dfsg), libstdc++6 (>= 9), libilmbase-dev
Recommends: opencv-data
Suggests: opencv-doc
Conflicts: libcv-dev, libcvaux-dev, libhighgui-dev
Breaks: libopencv-core-dev (<= 2.3.1-8)
Replaces: libcv-dev, libcvaux-dev, libhighgui-dev
Homepage: https://opencv.org
Download-Size: 93,6 kB
APT-Manual-Installed: no
APT-Sources: http://no.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
```
6. rustc version: `rustc 1.66.0 (69f9c33d7 2022-12-12)`
7. log is attached [cargo-build-log.txt](https://github.com/twistedfall/opencv-rust/files/10517436/cargo-build-log.txt)

# Minimal reproducable example:
I have created a minimal working example in this public git repo: https://github.com/molysgaard/opencv-rs-debugging
It only requires `rustup` to build in a completely reproducible manner, as long as you are on Ubuntu 20.04. I believe that the example does not care that much about the exact opencv version, so I think you can run it on most distros.

# The issue:
The issue is that `opencv::calib3d::find_circles_grid()` requires an argument of type `&core::Ptr<crate::features2d::Feature2D>`.
The argument should be an instance of `opencv::features2d::SimpleBlobDetector`.
The only way I have found to create a `SimpleBlobDetector` is using the `SimpleBlobDetector::create(params)`, which returns a `Ptr<SimpleBlobDetector>`, and I see no good way of converting that to a `Ptr<Feature2D>`.
Because of this, I have not been able to find any way to call `opencv::calib3d::find_circles_grid()`.

# Main question:
How can one convert a `Ptr<SimpleBlobDetector>` to a `Ptr<Feature2D>`?

**Comment by twistedfall** [comment]
Just call `.into()` on `blob_detector`. All classes and those `Ptr<class>` that are used in the function arguments have `From` implementations that convert from derived classes to their base classes and `TryFrom` to convert from base to the derived.

**Comment by molysgaard** [comment]
Ah, I tried that, but I did it directly, `blob_detector.into()` as an argument. Now I see that if I define a new variable which is called into on. It works as intended. Thanks for the help!

**Comment by twistedfall** [comment]
It will work as an argument too, just be sure to keep the reference: `&blob_detector.into()`

**Comment by molysgaard** [comment]
Ah, even better. Thanks, I guess I should just have tried a bit harder.
