### ISSUE TITLE
How to convert slice to Mat and save Mat as image ?

### ISSUE THREAD

**Issue by Tramac** [twistedfall/opencv-rust#414]
```
// Method 1. 
let gray_image = image::GrayImage::from_raw(640, 480, gray_image_slice.to_vec()).unwrap();
gray_image.save(&"gray_image.png");

// Method 2.
let gray_image_cv2 =  Mat::from_slice::<u8>(gray_image.as_ref()).unwrap();
let src_decoded = imgcodecs::imdecode(&gray_image_cv2, imgcodecs::IMREAD_GRAYSCALE).unwrap();
let params: Vector<i32> = Vector::new();
imgcodecs::imwrite(&"gray_image_cv2.png", &src_decoded, &params);
```
The `gray_image.png` is normal, but the `gray_image_cv2.png` is empty, How should I save the image correctly from `Mat` ？

**Comment by Tramac** [comment]
```
use std::ffi::c_void;
use opencv::{
    prelude::*,
    core::Mat,
};

let gray_mat = unsafe {
    Mat::new_rows_cols_with_data(
        640,
        480,
        core::CV_8U,
        gray_image_slice.as_ptr() as *mut c_void,
        core::Mat_AUTO_STEP,
    ).unwrap()
}; 

let params: Vector<i32> = Vector::new();
imgcodecs::imwrite(&"gray_image_cv2.png", &gray_mat, &params);
```
The above code works well.

**Comment by zhang090210** [comment]
If I want to change the params, how should I write them?

**Comment by dontcryme** [comment]
> If I want to change the params, how should I write them?

@zhang090210 

try using the below code :

```
let  mut parms= opencv::core::Vector::default();
parms.push(IMWRITE_JPEG_QUALITY);
parms.push(30);
```

**Comment by Codewithteju** [comment]
Hii @Tramac , How can I convert Vec<u8> into a Mat object, I want to overlay text, so for this I have to convert vec into Mat which I can use it for put_text(). But all am I getting Boxedref<'_, Mat>. Could you please help me in this ?

**Comment by twistedfall** [comment]
@Codewithteju `BoxedRef` is quite recent addition, can you maybe file a new issue and provide a code that you're trying to run and what error you're getting?

**Comment by Codewithteju** [comment]
@twistedfall , Actually, it's not a error, I have vec<u8> which I converted from AVFrame, now wanted to overlay some text on the array so trying to use opencv, I found one method put_text() but this one needs a Mat object, so trying to convert this vec<u8> into Mat for further modifications
Here is the code snippet I am using to proceed further :
pub fn text_image_opencv(vec:&Vec<u8>,width: i32, height: i32, text:&str){
    let mat = 
        Mat::new_rows_cols_with_data::<u8>(height, width, vec.as_ref()).unwrap(); 
}
