### ISSUE TITLE
IOT instruction (core dumped) on dnn TextDetectionModel_EAST::detect

### ISSUE THREAD

**Issue by ChristopherJMiller** [twistedfall/opencv-rust#415]
Before reporting an issue please first check the
[troubleshooting guide](https://github.com/twistedfall/opencv-rust/blob/master/README.md#troubleshooting). If
the issue you're encountering is not solved thereby please state the following in your bugreport:
1. Operating system `Linux ... 6.1.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 24 Jan 2023 21:07:04 +0000 x86_64 GNU/Linux`
2. The way you installed OpenCV: `package`
3. OpenCV version `4.7.0-1`
4. rustc version (`rustc --version`) `rustc 1.66.0 (69f9c33d7 2022-12-12)`
5. Attach the full output of the following command from your project directory:
Upon running a detect on an image:
```
/usr/include/c++/12.2.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = float; _Alloc = std::allocator<float>; reference = float&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
/usr/include/c++/12.2.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = float; _Alloc = std::allocator<float>; reference = float&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
/usr/include/c++/12.2.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = float; _Alloc = std::allocator<float>; reference = float&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
/usr/include/c++/12.2.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = float; _Alloc = std::allocator<float>; reference = float&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
[1]    34917 IOT instruction (core dumped)  cargo run -p [crate_name]
```

Adding additional backtraces appears to not provide any more output (which makes sense due to being warnings from opencv itself)

can confirm this code used to previously work on crate version `0.63.x`, but no longer does on `0.76.x`.

**Comment by twistedfall** [comment]
Thanks! Can you share the minimum example that fails for you on 0.76, but works on 0.63? And if you have some spare time it would be really useful to know which crate version actually broke it.

**Comment by twistedfall** [comment]
I'm going to close this for now, but please feel free to reopen it if you think there is something still to work on here!
