### ISSUE TITLE
Missing autocomplete and documentation [>=0.76]

### ISSUE THREAD

**Issue by zhouzq-thu** [twistedfall/opencv-rust#418]
![Screen Shot 2023-01-31 at 15 50 24](https://user-images.githubusercontent.com/9458157/215699188-de0bb5cd-95b6-4d81-b19f-0f3a3e9659f0.png)

**Comment by twistedfall** [comment]
What is the IDE/editor that are you using? Since v0.76 I've changed the location for the generated sources (in the output directory instead of src), but it should work fine with IntelliJ IDEA and rust-analyzer based IDEs and editors.

**Comment by zhouzq-thu** [comment]
I use vscode

**Comment by twistedfall** [comment]
Looks like I overestimated the readiness of rust-analyzer. There are known issues about resolving `#[path]` for modules: https://github.com/rust-lang/rust-analyzer/issues/11682 https://github.com/rust-lang/rust-analyzer/issues/9173 So far there is no workaround, but I'll try to see if generating a single file can be a solution.

**Comment by twistedfall** [comment]
Can you please check version 0.76.4, it should be fixed there.

**Comment by wangxiaochuTHU** [comment]
New version works with my vscode. 

In my case, after updating the version number in `Cargo.toml` from 0.75 to 0.76.4,  rust-analyzer errored with `[ERROR rust_analyzer::lsp_utils] failed to run build scripts:` at first, and finally it ended up with `cargo clean`.

**Comment by twistedfall** [comment]
It’s great to hear that!
