### ISSUE TITLE
Missing dependency (libstdc++-12-dev)

### ISSUE THREAD

**Issue by PuppiestDoggo** [twistedfall/opencv-rust#431]
Hi !

I'm not sure it is the right place to post it, but for ubuntu-based (and fedora-based) systems you definitely need **libstdc++-12-dev** to be installed on your system. I think it is **gcc-libs** for arch-based systems.

That's all.

Have a nice day!

**Comment by twistedfall** [comment]
Well, it's mentioned in the troubleshooting guide for the missing `limits` header, but my tests show that a clean installation of Ubuntu 22.04 at least doesn't require installing `libstdc++-12-dev`. It uses an older `gcc` version by default and that comes with their own standard C++ library version
