### ISSUE TITLE
Could not find encoder for codec id 62: Encoder not found

### ISSUE THREAD

**Issue by lost22git** [twistedfall/opencv-rust#433]
os => windows 11

opencv => 3.4.16

rustc =>1.68.0-nightly

cargo => 1.68.0-nightly

https://github.com/DvorakDwarf/Infinite-Storage-Glitch/issues/28

**Comment by twistedfall** [comment]
Looks like the OpenCV you're using wasn't built with proper H.264 support. How did you install it? Repository/manual build?

**Comment by lost22git** [comment]
@twistedfall 

scoop install opencv

**Comment by lost22git** [comment]
ignore this issue plz
