### ISSUE TITLE
binding-generator doesn't handle CRLF in OpenCV header files

### ISSUE THREAD

**Issue by grindvoll** [twistedfall/opencv-rust#441]
1. Operating system: Windows 11
2. OpenCV installation: Used 'choco install opencv' 
3. OpenCV version 4.6.0
4. rustc version: 1.65.0

Env vars:
OPENCV_INCLUDE_PATHS=c:\tools\opencv\build\include
OPENCV_LINK_LIBS=opencv_world460
OPENCV_LINK_PATHS=C:\tools\opencv\build\x64\vc15\lib

Certain OpenCV functions - for example the `cv::calib3d::init_undistort_rectify_map` is not exported by the binding-generator due to a bug in handling of CRLF line endings.

Replacing the line endings in the OpenCV header file with LF instead of CRLF solves the problem. However, it would be much better if the binding-generator could handle CRLF as well.

A small working patch with a simple associated test can be found here:

https://github.com/grindvoll/opencv-rust/commit/dd54b2a6609ee644b7a1f63f058b6d7f51a394bc

I am happy to submit a pull request if wanted.

**Comment by twistedfall** [comment]
It's a great catch, thanks! I'll try to release the fix asap

**Comment by grindvoll** [comment]
Thanks, much appreciated!

**Comment by twistedfall** [comment]
This should be fixed in the latest 0.78.0 release!
