### ISSUE TITLE
Errors in generated files with clang-16

### ISSUE THREAD

**Issue by ACGNnsj** [twistedfall/opencv-rust#445]
Many unnamed enums are found in those files.

1. Operating system: Windows 11
2. The way you installed OpenCV: official binary distribution
3. OpenCV version: 4.7.0
4. rustc version: 1.68.0
5. Attach the full output of the following command from your project directory:
[0.log](https://github.com/twistedfall/opencv-rust/files/11046955/0.log)

By the way, the volume G is of exFAT filesystem.

**Comment by twistedfall** [comment]
Hmm, I haven't seen this kind of output before. Can you please do a `cargo clean` and then again attach the output produced by `cargo build -vv`?

**Comment by ACGNnsj** [comment]
The output looks similar to the previous one.
[1.log](https://github.com/twistedfall/opencv-rust/files/11049693/1.log)

**Comment by leofidus** [comment]
I seem to have the same problem, with identical output.

Operating system: Windows 10
The way you installed OpenCV: vcpgk
OpenCV version: 4.7.0
rustc version: 1.68.1

opencv-rs version 0.78, but 0.75 produces very similar result
clang 16

on a normal NTFS volume

**Comment by leofidus** [comment]
It works when I switch to Clang 15.0.7, so I guess the interaction with Clang 16 is the culprit

**Comment by twistedfall** [comment]
Thanks for the insight, I'll check it out!

**Comment by twistedfall** [comment]
This should now be fixed in v0.78.2, thanks for the investigation!
