### ISSUE TITLE
Aruco not working as part of objdetect

### ISSUE THREAD

**Issue by krithik-ranjan** [twistedfall/opencv-rust#447]
1. Operating system: **Windows**
2. The way you installed OpenCV: **chocolatey**
3. OpenCV version: **4.6**
4. rustc version (`rustc --version`): **1.68.2**
5. Attach the full output of the following command from your project directory: https://gist.github.com/krithik-ranjan/3613c5d45bcdf65f3ef24b7baa2f6fd7

Hi, I have been trying to use the `objdetect` module in `opencv-rust` to use ArUco features, but when I compile with the latest version (0.78.2), none of the functions, structs, or constants are accessible in the Rust project (error shown for simply printing `objdetect::DICT_4X4_100`). Please let me know if you need any more information. 

Thank you!

**Comment by twistedfall** [comment]
Hi, can you please run a `cargo clean` and then `cargo build -vv` and paste the output here?

**Comment by krithik-ranjan** [comment]
Hi, sorry I realized I didn't copy over the full output earlier -- I've updated the gist with the output of `cargo build -vv` here https://gist.github.com/krithik-ranjan/3613c5d45bcdf65f3ef24b7baa2f6fd7 

One thing that I noticed was that when during the build process, Cargo generates the OpenCV files in `.\target\debug\build\opencv-4c80bbb60d2ea5c0\out`, but the `opencv/objdetect.rs` here doesn't match the one in the repository at `opencv-rust\docs\objedetect.rs` (it doesn't have any of the ArUco code).

**Comment by twistedfall** [comment]
Can you please try enabling the `aruco` feature in your Cargo.toml too?

**Comment by krithik-ranjan** [comment]
Yes, here is the updated gist: https://gist.github.com/krithik-ranjan/3613c5d45bcdf65f3ef24b7baa2f6fd7 (same error)

**Comment by twistedfall** [comment]
It doesn't even try to build the Aruco module, I don't think your OpenCV installation has it enabled. You most probably need to build OpenCV manually.

**Comment by krithik-ranjan** [comment]
Yes, it seems to be an issue with using Chocolatey to install -- when I look at the source downloaded by Choco, it doesn't have any of the Aruco files in the `objdetect` module (which was the case with OpenCV 4.6.0 but not 4.7.0) so it is probably not installing the latest OpenCV. 
I will try to build opencv from source and test, thank you!

**Comment by krithik-ranjan** [comment]
For anyone facing a similar issue: while Chocolatey isn't updated yet to install the latest OpenCV version (4.7), installing from the Releases page of OpenCV (https://opencv.org/releases/) works well if you don't want to go through the manual build. 

Thank you for the help!
