### ISSUE TITLE
binding-generator  whether  can parse the other C++ headers, generates a C interface to the C++ API, and wraps the C interface in Rust?

### ISSUE THREAD

**Issue by zhengxingjian** [twistedfall/opencv-rust#448]
binding-generator  whether  can parse the other C++ headers, generates a C interface to the C++ API, and wraps the C interface in Rust?

**Comment by twistedfall** [comment]
In theory it can, but I'm afraid it's too much connected to specifically generating bindings for OpenCV to be readily usable for any other application. But in theory it can be extended to be more generic, that's true.
