### ISSUE TITLE
All of the video capture examples are broken on my machine (Fedora 30)

### ISSUE THREAD

**Issue by dralley** [twistedfall/opencv-rust#45]
When attempting to run any of the examples that use video capture, my webcam light turns on, a small and totally empty black window pops up that cannot be closed by any means, including gnome force quit.  I had to find the process number and "kill -9" it.

When it does this, it yields the following error message:

```
[dalley@localhost opencv-test]$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/opencv-test`
[ INFO:0] VIDEOIO: Enabled backends(7, sorted by priority): GSTREAMER(1000); V4L2(990); OPENNI(980); CV_IMAGES(970); CV_MJPEG(960); FIREWIRE(950); UNICAP(940)
OpenCV | GStreamer warning: GStreamer: unable to start pipeline
 (/builddir/build/BUILD/opencv-3.4.4/modules/videoio/src/cap_gstreamer.cpp:872)

(opencv-test:21489): GStreamer-CRITICAL **: 23:15:44.400: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
OpenCV | GStreamer warning: GStreamer: unable to query pipeline state (/builddir/build/BUILD/opencv-3.4.4/modules/videoio/src/cap_gstreamer.cpp:420)
VIDEOIO ERROR: V4L: device /dev/video1: Unable to query number of channels
CvCapture_OpenNI::CvCapture_OpenNI : Failed to enumerate production trees: Can't create any node of the requested type!
```

**Comment by dralley** [comment]
Fixed by changing the video device # from 1 to 0 on this line:

```let mut cam = videoio::VideoCapture::new(1)?;```

**Comment by dralley** [comment]
Reopening this because the examples have code that I think *should* be handling this.  But it gets broken before trying to use camera 0 as it should be.

```
    let mut cam = videoio::VideoCapture::new(1)?;
    let opened = videoio::VideoCapture::is_opened(&cam)?;
    if !opened {
        println!("Using different camera");
        cam = videoio::VideoCapture::new(0)?;
    }
```

**Comment by twistedfall** [comment]
Well, those are just examples and they can't work on any possible machine out there. Though I agree that using device number 0 by default makes more sense than staring with number 1. Can you do a PR with the changes that fix your case by any chance?

**Comment by dralley** [comment]
https://github.com/twistedfall/opencv-rust/pull/47
