### ISSUE TITLE
Support Goto Definition in vscode

### ISSUE THREAD

**Issue by zhouzq-thu** [twistedfall/opencv-rust#450]
The rust-analyzer supports goto definition was fixed by [rust-analyzer:14561](https://github.com/rust-lang/rust-analyzer/pull/14561).
However, opencv-rust doesn't support for now.

**Comment by twistedfall** [comment]
Do you have an idea what needs to be done to support it? I'm not using rust-analyzer personally so I'm might be a bit disconnected from how it works. But I checked previously and at least code hints worked correctly.

**Comment by zhouzq-thu** [comment]
Goto definition works fine for the functions like `dnn::get_available_backends`, but can't goto the right place for the traits (member functions) like `model.set_preferable_backend`. Maybe the `rust-analyzer` still has some bugs.

**Comment by jackos** [comment]
@zhouzq-thu latest rust-analyzer released yesterday fixed this for me

**Comment by zhouzq-thu** [comment]
Yes, it works now. Thanks for sharing.
