### ISSUE TITLE
No default() or new() method for Detail_ImageFeatures

### ISSUE THREAD

**Issue by H0mTanks** [twistedfall/opencv-rust#451]
When trying to use `compute_image_features2`, we need to pass in a `&mut Detail_ImageFeatures`. There's no implementation of a `default()` or `new()` method for this struct. If there is a different way to use this particular function, please provide a snippet.

I'm aware of `compute_image_features`, which takes in a vector of images, this works. However I have to clone from my image references into contiguous memory, which I'd like to avoid.

**Comment by twistedfall** [comment]
Hi, looks like you're right, there doesn't seem to be an obvious way to create an instance of `Detail_ImageFeatures`. I'll need to investigate the sources to see how it's handled internally, but for now indeed, looks like using the `compute_image_features` is the only workaround.

**Comment by twistedfall** [comment]
In v0.80.0 there should now be a default constructor (`Detail_ImageFeatures::default()`) for the `Detail_ImageFeatures` class and some others, can you please check and reopen the task if it doesn't work?
