### ISSUE TITLE
`video_capture` demo freezes when pressing any key instead of closing

### ISSUE THREAD

**Issue by joshuajbouw** [twistedfall/opencv-rust#453]
1. macos M2 Pro v13.2.1
2. official binary distribution
3. OpenCV version: 0.80
4. rustc 1.69.0 (84c898d65 2023-04-16)

When running code similar to the example `video_capture`, the application freezes entirely instead of shutting down when pressing any key. There is some code that runs afterwards as the camera is only supposed to pop up one time only. I'm assuming this is the cause but, perhaps I'm not shutting down the window properly. I've tried altering it to instead use `destroy_window` and `destroy_all_windows` before the break but it still fails.

Not sure how to proceed from here.

**Comment by twistedfall** [comment]
Can you please try `dbg!`ing the value of `key` to see what value it has after the keypress?

**Comment by twistedfall** [comment]
Any luck?

**Comment by twistedfall** [comment]
Please feel free to reopen if needed
