### ISSUE TITLE
Trouble building `tplay` (uses opencv) inside nixpkgs

### ISSUE THREAD

**Issue by colemickens** [twistedfall/opencv-rust#458]
Hi.

I'm trying to package `tplay` for nixpkgs, and it uses opencv, via `opencv-rust`.

However, it's not going super well. I'm following the pattern of other Rust packages, however, it doesn't seem that we have a derivation yet, that uses Rust and opencv.

I'm not a Rust+nixpkgs expert, but I'm starting to suspect maybe there's an issue with how this library is setup to compile with cargo?

```
tplay>   }
tplay>   === Detected OpenCV module header dir at: /nix/store/bqvxgs9gn0czdr9dy0qb01awa7rvwm05-opencv-4.7.0/include/opencv4/opencv2
tplay>   === Found OpenCV version: 4.7.0 in headers located at: /nix/store/bqvxgs9gn0czdr9dy0qb01awa7rvwm05-opencv-4.7.0/include/opencv4
tplay>   === Generating code in: /build/source/target/x86_64-unknown-linux-gnu/release/build/opencv-3a4971fdeed2ef88/out
tplay>   === Placing generated bindings into: /build/source/target/x86_64-unknown-linux-gnu/release/build/opencv-3a4971fdeed2ef88/out/opencv
tplay>   === Using OpenCV headers from: /nix/store/bqvxgs9gn0czdr9dy0qb01awa7rvwm05-opencv-4.7.0/include/opencv4
tplay>   === Clang: clang version 13.0.1
tplay>   === Clang command line args: [
tplay>       "-isystem/nix/store/w4kb26c9699y2n7szfcx4j6db82p1xfr-compiler-rt-libc-13.0.1-dev/include",
tplay>       "-isystem/nix/store/jjppdifv75h6faf06r2l378ccx9bpk72-clang-13.0.1-dev/include",
tplay>       "-isystem/nix/store/bhhb91angi23wsr42apz1in1n9b9ilg3-glibc-2.37-8-dev/include",
tplay>       "-isystem/nix/store/bqvxgs9gn0czdr9dy0qb01awa7rvwm05-opencv-4.7.0/include",
tplay>       "-isystem/nix/store/dj5anrpwcn0p6h3xnqyr5mz30fc7l825-gcc-12.2.0/include/c++/12.2.0",
tplay>       "-isystem/nix/store/dj5anrpwcn0p6h3xnqyr5mz30fc7l825-gcc-12.2.0/include/c++/12.2.0/x86_64-unknown-linux-gnu",
tplay>       "-isystem/nix/store/xdf8w10fgk0dm7zzy7fizzprivalifkj-clang-wrapper-13.0.1/resource-root/include",
tplay>       "-I/nix/store/bqvxgs9gn0czdr9dy0qb01awa7rvwm05-opencv-4.7.0/include/opencv4",
tplay>       "-F/nix/store/bqvxgs9gn0czdr9dy0qb01awa7rvwm05-opencv-4.7.0/include/opencv4",
tplay>       "-I/build/cargo-vendor-dir/opencv-0.80.0/src_cpp",
tplay>       "-F/build/cargo-vendor-dir/opencv-0.80.0/src_cpp",
tplay>       "-DOCVRS_PARSING_HEADERS",
tplay>       "-includeocvrs_ephemeral.hpp",
tplay>       "-std=c++14",
tplay>   ]
tplay>   === Building binding-generator binary:
tplay>   === error: failed to get `libc` as a dependency of package `opencv v0.80.0 (/build/cargo-vendor-dir/opencv-0.80.0)`
tplay>   ===
tplay>   === Caused by:
tplay>   ===   failed to load source for dependency `libc`
tplay>   ===
tplay>   === Caused by:
tplay>   ===   Unable to update registry `crates-io`
tplay>   ===
tplay>   === Caused by:
tplay>   ===   failed to update replaced source registry `crates-io`
tplay>   ===
tplay>   === Caused by:
tplay>   ===   failed to read root of directory source: /build/cargo-vendor-dir/cargo-vendor-dir
tplay>   ===
tplay>   === Caused by
```

I've tried all the troubleshooting I can think of... but note that Nix has a fairly unique compiling strategy/environment.

**Comment by twistedfall** [comment]
From the error it looks like the package is being built with vendored dependencies, i.e. all dependent crates need to be available before starting the built and nothing is downloaded in the process. But `libc` crate is not available for some reason. The `opencv` crate builds a helper binary `binding-generator` that it uses to generate bindings. It's done by issuing another `cargo build` call so that might be not playing together with nix build too well. Maybe you could provide the full build log, it might give some insight.

**Comment by colemickens** [comment]
I don't know if the bindings generation process is different for opencv-rust, but we definitely have other bindgen-using apps/libs packaged. Just mentioning it.

this is the full nix build log for `tplay`: https://gist.github.com/colemickens/8adf2d276af4c76be22b38f71a312343

And of course now I see that there's an earlier failure of running the custom build command. Let me know if you have advice, otherwise I'll take a closer look at that later.

**Comment by colemickens** [comment]
well I guess that is THE error, it just starts higher up than I realized. It actually seems like the bindings generator binary fails to build due to the missing libc, somehow?

**Comment by michael-mueller-git** [comment]
I had exactly the same problems with `buildRustPackage`. So I switched to [crane](https://github.com/ipetkov/crane). But here another error occurs:

```
>   === Building binding-generator binary:
>   === error: failed to select a version for the requirement `libc = "^0.2"` (locked to 0.2.139)
>   === candidate versions found which didn't match: 0.2.142
>   === location searched: directory source `/nix/store/rpnzysdfjbr6sp4k5820i57phmx9kdx8-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0` (which is replacing registry `crates-io`)
>   === required by package `opencv v0.80.0 (/nix/store/8r84qkdv5lk26cavnkpw5dcf52njq4gf-cargo-package-opencv-0.80.0)`
>   === perhaps a crate was updated and forgotten to be re-vendored?
>   Error: "Failed to build the bindings generator"
```

I don't know where the locked version `0.2.139` comes from. My `Cargo.lock` has the Version `0.2.142` from error message above. And why does `0.2.142` not match the requirement `libc = "^0.2"`?

Anyway, by pinning the required locked version in my `Cargo.lock` the error go get resolved. But the the next package version mismatch occures:

```
>   === Building binding-generator binary:
>   === error: failed to select a version for the requirement `once_cell = "^1"` (locked to 1.17.0)
>   === candidate versions found which didn't match: 1.17.1
>   === location searched: directory source `/nix/store/hhcjvgz8sjdv90a1a17i2prgfag7vq8c-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0` (which is replacing registry `crates-io`)
>   === required by package `opencv v0.80.0 (/nix/store/8r84qkdv5lk26cavnkpw5dcf52njq4gf-cargo-package-opencv-0.80.0)`
>   === perhaps a crate was updated and forgotten to be re-vendored?
>   Error: "Failed to build the bindings generator"
```

After specifying [all locked dependencies version](https://github.com/michael-mueller-git/mtfg-rs/blob/v0.0.2/Cargo.toml#L28-L42) inside my `Cargo.toml` i was able to build the nix flake for my project (witch uses `opencv-rust`).

**Comment by twistedfall** [comment]
The 0.81.4 version could fix this problem (the externally built binary is no longer used), but `tplay` needs to be updated to use it first (currently uses 0.80).

**Comment by twistedfall** [comment]
The 0.4.4 version of `tplay` is using the latest `opencv` so this shouldn't be a problem anymore, can you please test it and if the problem persists reopen the issue with the additional details?
