### ISSUE TITLE
Convert Python scripts to Python 3

### ISSUE THREAD

**Issue by dralley** [twistedfall/opencv-rust#46]
This isn't an issue in and of itself, but linux distributions are going to start dropping Python 2 over the course of the next 18 months which will make this more difficult to compile.  I'd be willing to work on this myself but only if I know the PRs wouldn't be rejected, as some people have strong feelings about it.

**Comment by twistedfall** [comment]
Your contribution will be most welcome, no strong feelings about Python 2 here :)

**Comment by dralley** [comment]
https://github.com/twistedfall/opencv-rust/pull/48
