### ISSUE TITLE
The complex binding flow is not presented to the user

### ISSUE THREAD

**Issue by eric642** [twistedfall/opencv-rust#461]
Thank you for your hard work on this library!
My English is not very good, I used the translation software to translate, if some of the wording offended you, please understand.

I think there is an usability improvement in this library. When distributing the library, only the generated bindings should be distributed, and pre-compiled versions of OpenCV should be downloaded based on the user's system and CPU architecture in the [build.rs] (the user can also specify the library path).This is also how python bindings are handled

This way regular users don't have to deal with some of the complexities of generating bindings, out of the box.
What do you think about that? I can help finish the job.

**Comment by twistedfall** [comment]
Hi, thanks for the suggestion. The crate currently supports Linux, macOS and Windows, do you have a solution for all 3 of those operating systems? If so please do contribute, this will be a big boost to usability!
