### ISSUE TITLE
Difficulties cross compiling to arm (`armv7-unknown-linux-gnueabihf`)

### ISSUE THREAD

**Issue by AntoniosBarotsis** [twistedfall/opencv-rust#463]
I have been trying to cross-compile this for `armv7-unknown-linux-gnueabihf` in both native windows and wsl but I can't seem to get it to work. I have been trying this for more than a couple of hours at this point with way too many different attempts to list down so apologies in advance if the information I write here is incomplete, I'll be happy to answer any further questions 😅 

1. Operating system: windows natively and then wsl
2. The way you installed OpenCV: followed the README (`choco` and `apt` commands)
3. OpenCV version: windows: 4.6.0, wsl: 4.2.0
4. rustc version (`rustc --version`): `1.69.0`

## WSL

[logs](https://pastebin.com/raw/4LK1Tp5v)

This is quite verbose, however the important bit seems to be this:

```sh
  Install a sysroot for the target platform and configure it via
  PKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a
  cross-compiling wrapper for pkg-config and set it via
  PKG_CONFIG environment variable., pkg-config has not been configured to support cross-compilation.
```

I found 2 things about this online (apologies if the fix is obvious, I am not used to stuff like this).

### Approach 1

[One mentioned](https://stackoverflow.com/a/68979087/12756474), this gave the following error:

[logs](https://pastebin.com/raw/GnERya5k)

### Approach 2

...and [this approach](https://stackoverflow.com/a/68979087/12756474) which also didn't work

[logs](https://pastebin.com/raw/Tp4daYwP)

## Closing

Thoughts and prayers to whoever decides to read any of this. Do let me know if I can provide any more information to help you, the issue might just be me doing something dumb somewhere.

I have also tried a few other approaches to some aspects of this (like trying to use vcpkg to install opencv) but they didn't go far so I haven't mentioned them here.

**Comment by twistedfall** [comment]
I have added an example Dockerfile that can help you build the image suitable for cross-compiling Rust applications, it's here: https://github.com/twistedfall/opencv-rust/blob/master/tools/rpi-xcompile.Dockerfile and this is the extract from the readme:

> Cross-compilation is notoriously difficult to set up, so you can use this example [rpi-xcompile.Dockerfile](https://github.com/twistedfall/opencv-rust/blob/master/tools/rpi-xcompile.Dockerfile).
> 
> docker build -t rpi-xcompile -f tools/rpi-xcompile.Dockerfile tools
> 
> Building this image requries qemu-arm to be present on the host system and the corresponding binfmt-misc set up (see e.g. https://wiki.debian.org/QemuUserEmulation, only Installing packages should be enough).
> 
> After the successful build you will have an image configured for cross-compilation to Raspberry Pi. It will contain the sample build script /usr/local/bin/cargo-xbuild that you can check for the correct environment setup and the specific command line arguments to use when crosscompiling the project inside the container created from that image.

I'm not quite sure how easy it would be to run that on Windows though.

**Comment by AntoniosBarotsis** [comment]
Thanks a lot for the reply! I think that due to time constraints, I won't be trying to get this to work anymore. Hopefully it helps someone else!

Feel free to close the issue and again, thanks for taking the time to respond!
