### ISSUE TITLE
Example for core::parallel_for_

### ISSUE THREAD

**Issue by LightCannon** [twistedfall/opencv-rust#474]
Hello. I would like to know if there are any example for using the opencv core::parallel_for_?

**Comment by twistedfall** [comment]
Judging by the documentation it's not usable from Rust, I'd recommend using Rust-native parallelization creates like `rayon`

**Comment by LightCannon** [comment]
Any examples for doing so?

**Comment by twistedfall** [comment]
Of using `rayon`? Their crates.io [page](https://crates.io/crates/rayon) has links and examples

**Comment by LightCannon** [comment]
@twistedfall 
I mean an example of using Rayon for parallel processing a core::Mat. 
What I'm getting is that Mat has some traits not implemented which is needed for Rayon to work, but I'm not sure may I'm wrong.

So may you provide a simple example for parallel processing over a Mat?

**Comment by twistedfall** [comment]
Well, it depends on what kind of processing you're going to do, but here is an example of parallel summing of `Mat` elements:
```
use std::time::Instant;

use opencv::prelude::*;
use rayon::prelude::*;

fn main() {
    let mut m =
        Mat::new_rows_cols_with_default(10000, 10000, f64::opencv_type(), 0.into()).unwrap();
    // fill Mat with some data
    let data = m.data_typed_mut::<f64>().unwrap();
    for (i, el) in data.iter_mut().enumerate() {
        *el = i as f64;
    }
    // sum Mat elements in parallel
    let data = m.data_typed::<f64>().unwrap();
    let start = Instant::now();
    let sum = data.par_iter().sum::<f64>();
    println!("Sum is {sum}, time taken: {:?}", start.elapsed());
}
```

**Comment by LightCannon** [comment]
The processing I want is being able to do operations on pixels individually (or a more general, image slices) without having to loop over pixels.
Let's say, a simple example is taking each 4 pixels and calculate their average, or a more simple one, to add some constant (depending on its row and col) to each pixel.

**Comment by twistedfall** [comment]
Well, the `parallelFor` machinery only helps you split the `Range` into several threads, it doesn't really help you specifically with `Mat`. For the similar functionality you can try to use `rayon`s [split](https://docs.rs/rayon/latest/rayon/iter/fn.split.html) function.

**Comment by LightCannon** [comment]
What I want is operating on array in parallel way, like adding some constant or doing some operation on each pixel. However, I do not want to loop pixel by pixel. 
I'm not sure how to do this on the Mat and Rayon. In addition, what should I do if I want to do this edit in place (source and destination are same).
