### ISSUE TITLE
How to convert Mat to Vec<u8>?

### ISSUE THREAD

**Issue by aloussase** [twistedfall/opencv-rust#486]
I have a 3 channel `Mat` that I want to convert to a `Vec<u8>`. I've tried a number of ways, but the result is always a malformed image. I'd be very happy to get some help here.

**Comment by twistedfall** [comment]
I would need some more details to really help, but it sounds like you are missing the step to convert a color image to a grayscale one: https://docs.rs/opencv/latest/opencv/imgproc/fn.cvt_color.html. Something like this should help:
```rust
let mut output = Mat::default();
imgproc::cvt_color(&input, &mut output, imgproc::COLOR_BGR2GRAY, 0))?;
```

**Comment by aloussase** [comment]
Hi, thanks for answering. What I specifically need is to access the color image bytes to send as payload to S3. 

To do that, I need to make a ByteStream out of the Mat. Here is the documentation for ByteStream: https://docs.rs/aws-sdk-s3/0.21.0/aws_sdk_s3/types/struct.ByteStream.html.

I don't know if that helps.

**Comment by aloussase** [comment]
Btw, I was getting qt linking errors when using highgui on arch. I had to install qt6-base, just in case you want to update the readme (it says qt5-base currently). Using version 0.84.4.

**Comment by twistedfall** [comment]
Thanks for the heads-up, I'll update the readme! Can you share the specific code that you're using and explain in more detail what is going wrong with the image uploaded to S3?

**Comment by aloussase** [comment]
Hi sure. Here is some code I am using to load the image from bytes (I get bytes from the multipart request in axum):
```rust
fn mat_from_bytes(bytes: &[u8]) -> Mat {
    let image = Reader::new(Cursor::new(bytes))
        .with_guessed_format()
        .unwrap()
        .decode()
        .unwrap();
    // TODO: Generate a temporary name.
    let path = "/tmp/1.jpg";
    image.save(path).unwrap();
    imgcodecs::imread(path, imgcodecs::IMREAD_COLOR).unwrap()
}
```
I am using the `image` crate because I couldn't get `Mat::from_slice` to work.

Next, here is the code for uploading the image to S3:
```rust
#[async_trait::async_trait]
impl Handle for S3Storage {
    async fn store_image(&self, image: StoreImage) -> Option<String> {
        tracing::info!("Trying to store image in S3: {}", image.name);

        let result = self
            .client
            .put_object()
            .bucket(&self.bucket_name)
            .key(&image.name)
            .body(image.bytes.into())
            .presigned(PresigningConfig::expires_in(Duration::from_secs(60)).unwrap())
            .await;

        match result {
            Ok(presigned) => Some(extract_public_url(presigned.uri().to_string())),
            Err(err) => {
                tracing::error!("Failed to store image in S3: {}: {:?}", image.name, err);
                None
            }
        }
    }
}
```
The image has a `bytes` field which stores the image's bytes as a `Vec<u8>`. Now the problem is how do I get the `Vec<u8>` from a 3 channel color `Mat`. Right now what I am doing is save the file to disk and then use a `ByteStream` to upload it to S3. I works but is not optimal.

Here is the code I am using to process the image in case it serves:
```rust
pub fn combine_images(base_bytes: &[u8], surface_bytes: &[u8]) -> Result<String, Error> {
    let base = mat_from_bytes(base_bytes);
    tracing::info!("Constructed base mat from bytes");

    let surface = mat_from_bytes(surface_bytes);
    tracing::info!("Constructed surface mat from bytes");

    let (base, surface) = shrink_to_same_size(base, surface);
    tracing::info!("Shrank images to the same size");

    let mut mask = surface.clone();
    cvt_color(&mask.clone(), &mut mask, COLOR_BGR2GRAY, 3).unwrap();
    threshold(&mask.clone(), &mut mask, 130.0, 255.0, THRESH_BINARY).unwrap();
    tracing::info!("Created binary mask for the surface image");

    let kernel = unsafe { Mat::new_rows_cols(3, 3, CV_8U).unwrap() };
    close(&mut mask, &kernel);
    open(&mut mask, &kernel);
    erode(
        &mask.clone(),
        &mut mask,
        &kernel,
        Point::new(-1, -1),
        1,
        BORDER_CONSTANT,
        morphology_default_border_value().unwrap(),
    )
    .unwrap();
    tracing::info!("Applied morphological operations to correct mask");

    cvt_color(&mask.clone(), &mut mask, COLOR_GRAY2BGR, 3).unwrap();
    let masked = and_mat_mat(&mask, &surface).unwrap();
    tracing::info!("Applied mask to the surface image");

    let combined = (0.5 * masked + 0.5 * &base).into_result().unwrap();
    tracing::info!("Combined masked surface with base image");

    let mut smoothed = base.clone();
    median_blur(&combined, &mut smoothed, 9).expect("median blur");
    tracing::info!("Applied smoothing operation to final image");

    // TODO: Generate a temporary name.
    let result_filename = "/tmp/result.jpg";

    let params = Vector::new();
    imgcodecs::imwrite("/tmp/result.jpg", &smoothed, &params).unwrap();

    Ok(result_filename.to_string())
}
```

**Comment by twistedfall** [comment]
I think here you might have an inconsistency between having a `Vec` of raw pixel values and a `Vec` of bytes of the encoded image (e.g. JPEG-encoded). Generally you use `imread` or `imdecode` to convert encoded image into raw `Mat`. `Mat::data_bytes()` will give you raw pixel values. And `imwrite`/`imencode` will convert raw `Mat` into an encoded image.

For me it's not clear what kind of bytes are you passing to `mat_from_bytes` and `combine_images`: encoded bytes or raw pixel bytes.

Generally you can always check if you have the correct raw `Mat` by calling [imshow](https://docs.rs/opencv/latest/opencv/highgui/fn.imshow.html) on it (followed by `wait_key(0)`). If the `Mat` has BGR or grayscale pixel values it will show the proper image.

And just a note about:
>     let kernel = unsafe { Mat::new_rows_cols(3, 3, CV_8U).unwrap() };

This creates a `Mat` with non-initialized undefined bytes, which you read afterwards without initializing. I would really recommend using [new_rows_cols_with_default](https://docs.rs/opencv/latest/opencv/core/struct.Mat.html#method.new_rows_cols_with_default).

**Comment by aloussase** [comment]
Ok I think that the arguments to `combine_images` and `mat_from_bytes` are non-encoded bytes because I tried `imshow`ing then and only get a black window. I guess I need to convert the raw
bytes into a Mat somehow then. Thank you for your replies!

**Comment by twistedfall** [comment]
For that you can actually use [Mat::from_slice_rows_cols::< u8 >()](https://docs.rs/opencv/latest/opencv/prelude/struct.Mat.html#method.from_slice_rows_cols)

**Comment by twistedfall** [comment]
Wait, I think I misread you, if you get black windows then it means that the bytes are actually non-raw (e.g. they are encoded).

**Comment by aloussase** [comment]
Shouldn't I be able to see the picture then?

**Comment by aloussase** [comment]
When doing this
```rust
fn mat_from_bytes(bytes: &[u8]) -> Mat {
    let mut mat = Mat::from_slice(bytes).unwrap();
    mat.set_dims(2);
    mat.set_flags(CV_8UC3);

    opencv::highgui::imshow("mat", &mat).unwrap();
    opencv::highgui::wait_key(0).unwrap();

    mat
}
```
I get the following error:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -2, message: "OpenCV(4.8.0) /usr/src/debug/opencv/opencv-4.8.0/modules/core/src/matrix.cpp:462: error: (-2:Unspecified error) in function 'cv::Mat::Mat(cv::Size, int, void*, size_t)'\n>  (expected: '_step >= minstep'), where\n>     '_step' is 4966829\n> must be greater than or equal to\n>     'minstep' is 14900487\n" }', src/imgproc.rs:90:42
```

**Comment by aloussase** [comment]
I got it to work like this:
```rust
fn mat_from_bytes(bytes: &[u8]) -> Mat {
    let mat = Mat::from_slice(bytes).unwrap();
    let mat = imgcodecs::imdecode(&mat, imgcodecs::IMREAD_COLOR).unwrap();

    opencv::highgui::imshow("mat", &mat).unwrap();
    opencv::highgui::wait_key(0).unwrap();

    mat
}
```
Thanks to this SO post: https://stackoverflow.com/questions/13705578/convert-a-string-of-bytes-to-cvmat.

I think my problem is solved now. Thank you very much for the help!

**Comment by twistedfall** [comment]
It's great to hear that!
