### ISSUE TITLE
use ndarray crate to create Mat has a problem

### ISSUE THREAD

**Issue by qq351469076** [twistedfall/opencv-rust#497]
Dear developer, hello. I want to create a standard 3-channel BGR image using ndarray.

Why is the output image 3 row and 3 col? The correct output should be two images merged together, just like the image below.

### **my mistake output:**
```rust
    // create logo  [3 channel    200 *200]
    let mut logo: Array3<u8> = Array3::zeros((3, 200, 200));

    // 1
    logo.slice_mut(s![0, 20..120, 20..120]).fill(25);
    // 2
    logo.slice_mut(s![1, 20..120, 20..120]).fill(75);
    // 3
    logo.slice_mut(s![2, 20..120, 20..120]).fill(125);

    // a
    logo.slice_mut(s![0, 80..180, 80..180]).fill(50);
    // b
    logo.slice_mut(s![1, 80..180, 80..180]).fill(100);
    // c
    logo.slice_mut(s![2, 80..180, 80..180]).fill(150);

    let mat = unsafe {
        Mat::new_rows_cols_with_data(
            200,
            200,
            CV_8UC3,
            logo.as_mut_ptr() as *mut c_void,
            Mat_AUTO_STEP,
        )
        .unwrap()
    };

    imshow("demo", &mat).unwrap();

    wait_key(50000).unwrap();
```
![image](https://github.com/twistedfall/opencv-rust/assets/28567138/eb6be05e-bd6c-4929-85aa-7332ffff2e46)

it seem like 1 and a together,  2 and b together, 3 and c together

and ndarray array debug output seem like ok, its 3 channel
![image](https://github.com/twistedfall/opencv-rust/assets/28567138/e372c6b5-b4d3-4b6d-b863-d8526eff8e47)

### **Watch python tutorial , should output:**
![image](https://github.com/twistedfall/opencv-rust/assets/28567138/d20faa7d-da61-4a55-ade5-84f191ff3c05)
![image](https://github.com/twistedfall/opencv-rust/assets/28567138/6a9bd172-cde2-486b-88a9-2bff50221905)

 
My Env:
win11 21H2 22000.2416
rust 1.70.0
opencv 4.8.0

Cargo.toml
opencv = "0.84.5"
ndarray= "0.15.6"

**Comment by qq351469076** [comment]
When I changed CV_8UC3 to CV_8U, the image shape displayed correctly, but the color appears to be as its name suggests, single-channel grayscale. I really don't know where the problem is. I've been researching for two or three days.
```rust
    let mat = unsafe {
        Mat::new_rows_cols_with_data(
            200,
            200,
            CV_8U,
            logo.as_mut_ptr() as *mut c_void,
            Mat_AUTO_STEP,
        )
        .unwrap()
    };
```
![image](https://github.com/twistedfall/opencv-rust/assets/28567138/631beb9e-075f-4ff6-a129-8639ccf3deae)

**Comment by twistedfall** [comment]
After running some tests I can see that `Array3` memory layout is different from 3-channel `Mat`. The former puts all elements of the 0th dimension first, then 1st and 2nd. 3-channel `Mat` expects that every pixel is encoded by 3 adjacent bytes, it lays out dimensions of the pixels one after another. That's why you get gray pixels of different intensity with color border, for `Mat` it looks like pixels of  `... (100, 100, 150), (150, 150, 150), ...`

**Comment by qq351469076** [comment]
Is there any solution? What method should ndarray use to create 3 channels? Or, the Mat structure of this crate has a similar method that can create 3 channels and assign values through the ROI area?

**Comment by twistedfall** [comment]
Yep, using `Mat::roi` would work perfectly for this case, something like this:
```rust
let mat = Mat::new_rows_cols_with_default(200, 200, Vec3b::opencv_type(), 0.into())?;
Mat::roi(&mat, Rect::new(20, 20, 100, 100))?.set((0., 0., 255.).into())?;
Mat::roi(&mat, Rect::new(80, 80, 100, 100))?.set((0., 255., 0.).into())?;
imshow("demo", &mat)?;
wait_key(0)?;
```

**Comment by qq351469076** [comment]
Thanks, this should be what I want
