### ISSUE TITLE
cascadedetect.cpp runtime panic on macOS

### ISSUE THREAD

**Issue by BenBergman** [twistedfall/opencv-rust#50]
The latest OpenCV 3 in Homebrew is 3.4.5, so I have that installed. Part of the install process involved setting the following environment variables, so I have done that.

```
export PKG_CONFIG_PATH="/usr/local/opt/opencv@3/lib/pkgconfig"
export LDFLAGS="-L/usr/local/opt/opencv@3/lib"
export CPPFLAGS="-I/usr/local/opt/opencv@3/include"
export PATH="/usr/local/opt/opencv@3/bin:$PATH"
```

Trying to run the video_facedetect example, I get this output:

```
$ cargo run --example video_facedetect
   Compiling opencv v0.15.2 (/Users/benjamin.bergman/tasks/ododowa/opencv-rust)
warning: trait objects without an explicit `dyn` are deprecated
    --> src/hub/core.rs:2691:50
     |
2691 | pub fn parallel_for_(range: &core::Range, body: &core::ParallelLoopBody, nstripes: f64) -> Result<()> {
     |                                                  ^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn core::ParallelLoopBody`
     |
     = note: #[warn(bare_trait_objects)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 45.89s
     Running `target/debug/examples/video_facedetect`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -215, message: "OpenCV(3.4.5) /tmp/opencv@3-20190505-97953-1nkl1lm/opencv-3.4.5/modules/objdetect/src/cascadedetect.cpp:1698: error: (-215:Assertion failed) !empty() in function \'detectMultiScale\'\n" }', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
cargo run --example video_facedetect  93.72s user 7.61s system 209% cpu 48.483 total
```

This was run on macOS 10.14.5.

I have tried with Rust 1.37.0-nightly (807429e1b 2019-06-11) and 1.35.0 (3c235d560 2019-05-20)

**Comment by twistedfall** [comment]
This is not a build failure, it's a runtime error of the example. In this particular case it can't find the cascade file at `/usr/local/share/OpenCV/haarcascades/haarcascade_frontalface_alt.xml`. For a quick fix update the line:
```rust
    let xml = "/usr/local/share/OpenCV/haarcascades/haarcascade_frontalface_alt.xml";
```
with the correct path. Probably something like `/usr/local/opt/opencv/share/OpenCV/haarcascades/haarcascade_frontalface_alt.xml`. I have a proper fix in my local master, but it will take a couple of days for me to be able to publish it.

**Comment by BenBergman** [comment]
Thanks @twistedfall ! Since I'm using opencv@3 through homebrew, the proper xml path is `let xml = "/usr/local/Cellar/opencv@3/3.4.5_2/share/OpenCV/haarcascades/haarcascade_frontalface_alt.xml";`

I'll fix the issue title to reflect a runtime error.

**Comment by twistedfall** [comment]
Can you maybe check if the following also works for you. If you replace the aforementioned line with the following:
```rust
let xml = core::find_file("haarcascades/haarcascade_frontalface_alt.xml", true, false)?;
```
and then at the line where `CascadeClassifier` gets instantiated:
```rust
let mut face = objdetect::CascadeClassifier::new(&xml)?;
```
will the example still work?

**Comment by BenBergman** [comment]
Yes, this works for me. I do get this additional warning at runtime though (seems harmless, but should maybe be info, not warning):

```
[ WARN:0] cv::samples::findFile('haarcascades/haarcascade_frontalface_alt.xml') => '/usr/local/opt/opencv@3/lib/../share/OpenCV/haarcascades/haarcascade_frontalface_alt.xml'
```

**Comment by twistedfall** [comment]
Great! The logging is coming from OpenCV and it's out of our control, but you should be able to suppress logging by passing true as the 3rd argument (`silent_mode`)

**Comment by twistedfall** [comment]
The fixed example is now in master and on crates.io
