### ISSUE TITLE
undefined reference to `cv::SparseMatConstIterator::operator--(int)`, probably because it does not have implementation

### ISSUE THREAD

**Issue by fzyzcjy** [twistedfall/opencv-rust#500]
Related

* #499 
* #471 

From the following links, it seems that these does not have implementation in opencv cpp.

* https://github.com/opencv/opencv/issues/21814
* https://github.com/opencv/opencv/issues/21810

**Comment by twistedfall** [comment]
This is now released in v0.85.0
