### ISSUE TITLE
What to set OPENCV_LINK_LIBS to?

### ISSUE THREAD

**Issue by David-OConnor** [twistedfall/opencv-rust#507]
Hi! The README is clear and explicit on OPENCV_LINK_PATHS and OPENCV_INCLUDE_PATHS, but OPENCV_LINK_LIBS is confusing. Ty!

**Comment by David-OConnor** [comment]
Solved: The solution: Open `/opencv/build/x64/vcXX/lib`. It is the filename, extension-optional, of the `.lib` file, eg `opencv_world481.lib`.

**Comment by twistedfall** [comment]
Can you please tell me if you have an idea on how to improve the documentation to make the description clearer?

**Comment by David-OConnor** [comment]
I would include the line about looking in that directory to id the `opencv_world` version; the docs are great other than that.
