### ISSUE TITLE
Suggestion: Implement Send on Ptr<T> where T is Send (and also Sync?)

### ISSUE THREAD

**Issue by callanoc** [twistedfall/opencv-rust#509]
For example: 
ORB is `Send`: https://docs.rs/opencv/latest/opencv/features2d/struct.ORB.html#impl-Send-for-ORB
and the only way to use ORB is through the method `create` which returns a `Ptr<ORB>`.

`Ptr` is not `Send` https://docs.rs/opencv/latest/opencv/core/struct.Ptr.html#impl-Send-for-Ptr%3CT%3E.

Currently the only way to use ORB in threads is to unsafely implement `Send` for it.

Would it be possible to implement `Send` for `Ptr<T>` where `T` is `Send`? And also `Sync`?

Thank you!

**Comment by twistedfall** [comment]
Technically C++ `std::shared_ptr` can [share the owned data](https://en.cppreference.com/w/cpp/memory/shared_ptr) (`Several shared_ptr objects may own the same object` :exploding_head:), so it wouldn't be safe to mark those as `Send`, but I think that in the context of of the crate it might actually be possible. I'll need to check several places in OpenCV source to see if it's possible. But `Sync` is definitely not safe, OpenCV doesn't have a blanket thread-safe promise over all of its classes.

**Comment by Tpt** [comment]
Thank you! So, I guess that the "This is similar to Rust Box, but handled by the C++." comment on [Ptr](https://docs.rs/opencv/latest/opencv/core/struct.Ptr.html) should be read as something like "This is similar to Rust `Arc`, but handled by the C++ and with weaker safety guarantees." Am I correct?

**Comment by twistedfall** [comment]
That's right, I'll update the docs for the `Ptr`, thanks for the suggestion!
