### ISSUE TITLE
Unable to load ONNX model.

### ISSUE THREAD

**Issue by nawinrajkumar** [twistedfall/opencv-rust#512]
@twistedfall 
I have been trying to load an ONNX model using the function **read_net_from_onnx**. On the documentation it said only to upload the model path. I stored the model path onto a variable and loaded the model. While running the code I have an error

![updated](https://github.com/twistedfall/opencv-rust/assets/83204531/4c2d7eb8-a6dd-4423-95c0-256891e36ec3)
 
The code is as follows:
`
let onnx_path = "/home/Projects/rust-inference-onnx/model.onnx";
let model: dnn::Net = dnn::read_net_from_onnx(onnx_path).expect("Unable to load model");
`

**Comment by twistedfall** [comment]
The error is coming from OpenCV itself, not from the crate, so it looks like the model you're trying to load is missing something that's required as explained in the error message. I'm not really familiar with the ONXX models and DNN OpenCV module in general, so I can only provide general guidance.

**Comment by nawinrajkumar** [comment]
Is the model path stored in onnx_path correct? Or should I need to add anything to it?

**Comment by twistedfall** [comment]
It's difficult to say, it looks like your custom model so no way to say for sure.
