### ISSUE TITLE
Build fail in Dockerbuild aarch64 nvidia base image:  error: could not convert 'instance->cv::Ptr<cv::rgbd

### ISSUE THREAD

**Issue by lioriz** [twistedfall/opencv-rust#513]
Building the app in `Dockerfile`:

```
ARG GREEN_BASE_GPU=nvcr.io/nvidia/l4t-base:r32.5.0
ARG MODULE_NAME=rusty_image

FROM ${GREEN_BASE_GPU} AS build-stage
ARG MODULE_NAME
RUN apt-get update -y && apt-get install -y curl gcc
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt install -y libopencv-dev clang libclang-dev # https://qa.yodo.me/t/how-to-install-tzdata-on-a-ubuntu-docker-image/259v
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --target aarch64-unknown-linux-gnu --default-toolchain stable
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup target list

RUN mkdir -p /${MODULE_NAME}
COPY ./src /${MODULE_NAME}/src
COPY ./Cargo.toml /${MODULE_NAME}/Cargo.toml
COPY ./Cargo.lock /${MODULE_NAME}/Cargo.lock
WORKDIR /${MODULE_NAME}
RUN RUST_BACKTRACE=full cargo build -vv --target=aarch64-unknown-linux-gnu
```

Cross compile to `aarch64`, `linux`, base image `nvcr.io/nvidia/l4t-base:r32.5.0`
`opencv` installed in `Dockerfile`: `apt install -y libopencv-dev clang libclang-dev`
`opencv` version 0.86.1
`rustc` version 1.74.0
[Docker_build_log.txt](https://github.com/twistedfall/opencv-rust/files/13392594/Docker_build_log.txt)

I don't understand why the build fail, why do I get the opencv conversion errors.

**Comment by twistedfall** [comment]
Looks like a bug in the binding generation, thanks for the report. Can you please also share the sample Rust program that you're trying to build?

**Comment by lioriz** [comment]
So... the issue has been solved.
I changed the base image from `nvcr.io/nvidia/l4t-base:r32.5.0` to `nvcr.io/nvidia/l4t-tensorrt:r8.5.2-runtime`
Looks like there are some `opencv` and `clang` versions incompatibility between the `nvcr.io/nvidia/l4t-base:r32.5.0` image and the requirement of `rust-opencv`.

`nvcr.io/nvidia/l4t-base:r32.5.0` versions:

- `libopencv-dev`: arm64 3.2.0+dfsg
- `clang`: arm64 1:6.0
- `libclang-dev`: arm64 1:6.0-41

`nvcr.io/nvidia/l4t-tensorrt:r8.5.2-runtime` versions:

- `libopencv-dev`: arm64 4.5.4-8-g3e4c170df4
- `clang`: arm64 1:10.0.0
- `libclang-dev`: arm64 1:10.0-50

Updated Dockerfile:
```
ARG GREEN_BASE_GPU=nvcr.io/nvidia/l4t-tensorrt:r8.5.2-runtime
ARG MODULE_NAME=rusty_image

FROM ${GREEN_BASE_GPU} AS build-stage
ARG MODULE_NAME
RUN apt-get update -y && apt-get install -y curl gcc
RUN apt install -y libopencv-dev clang libclang-dev
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --target aarch64-unknown-linux-gnu --default-toolchain stable
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup target list

RUN mkdir -p /${MODULE_NAME}
COPY ./src /${MODULE_NAME}/src
COPY ./Cargo.toml /${MODULE_NAME}/Cargo.toml
COPY ./Cargo.lock /${MODULE_NAME}/Cargo.lock
WORKDIR /${MODULE_NAME}
RUN RUST_BACKTRACE=full cargo build -vv --target=aarch64-unknown-linux-gnu
```
Dockerbuild log: 
[Docker_build_success_log.txt](https://github.com/twistedfall/opencv-rust/files/13392738/Docker_build_success_log.txt)

Code example:

`Cargo.toml`:
```
.
.
.
[dependencies]
.
.
.
opencv = "0.86.1"

```
`Opencv` usage:
```
use opencv::{core, imgcodecs, imgproc};
.
.
.
let img = match core::Mat::from_slice(&data) {
    Ok(T) => T,
    Err(e) => {
        error!("Failed to create Mat from slice: {}", e);
        continue;
    },
};

let img = match imgcodecs::imdecode(&img, imgcodecs::IMREAD_COLOR) {
    Ok(T) => T,
    Err(e) => {
        error!("Failed to decode image: {}", e);
        continue;
    },
};

let flow_id = match img_info_json["flow_id"].as_i64(){
    Some(T) => T,
    None => {
        error!("Failed to get flow_id");
        continue;
    },
};

let pic_suffix = match img_info_json["pic_suffix"].as_str(){
    Some(T) => T,
    None => {
        error!("Failed to get pic_suffix");
        continue;
    },
};

let ret = match imgcodecs::imwrite(image_dir_path.join(flow_id.to_string() + pic_suffix).to_str().unwrap(), &img, &core::Vector::new()) {
    Ok(T) => T,
    Err(e) => {
        error!("Failed to write image: {}", e);
        continue;
    },
};
```
Sorry if there some bad practice in the code, still new to Rust.

**Comment by twistedfall** [comment]
You are right, the image you were using previously has OpenCV version 3.2 which is no longer supported by the crate. Switching to 3.4 or 4 is the way to go.
