### ISSUE TITLE
Can't build ld.lld: error: undefined symbol: cv::VideoCapture::VideoCapture(std::__cxx11::basic_s tring<char, std::char_traits<char>, std::allocator<char>> const&, int)

### ISSUE THREAD

**Issue by strizhkindenis** [twistedfall/opencv-rust#515]
1. Gentoo Linux
2. installed from portage (so build from source)
3. OpenCV version: 4.8.1
4. rustc version: 1.73.0 (cc66ad468 2023-10-03) (gentoo)
5. [build.txt](https://github.com/twistedfall/opencv-rust/files/13419701/report.txt)

**Comment by twistedfall** [comment]
That's a very weird error to be honest. Judging by the 3 link errors you're getting it looks like OpenCV functions are not accepting `std::string` typed arguments. The only situation that I can think about when it might be happening is that some of the `so` files are from OpenCV 3.x branch. In that branch the `cv::String` type was a separate definition unlike in 4.x where it's an alias to `std::string`. Can you double check that your OpenCV installation is clean?

**Comment by twistedfall** [comment]
I hope you're no longer getting this issue!
