### ISSUE TITLE
roi function has a error

### ISSUE THREAD

**Issue by qq351469076** [twistedfall/opencv-rust#520]
```rust
use opencv::core::{Rect, CV_8UC1};
use opencv::highgui::{imshow, wait_key};
use opencv::prelude::*;

fn main() -> opencv::Result<()> {
    let mat = Mat::new_rows_cols_with_default(200, 200, CV_8UC1, 255.into())?;

    Mat::roi(&mat, Rect::new(20, 20, 100, 100))?.set((255.).into())?;

    imshow("adasd", &mat).unwrap();

    wait_key(10000).unwrap();

    Ok(())
}
```

![image](https://github.com/twistedfall/opencv-rust/assets/28567138/6a42a283-1a42-4e96-bc78-04d3b0d0093e)

hello, how can i repair it ?

dependency:

opencv = "0.88.1"

**Comment by twistedfall** [comment]
`Mat::set` function accepts another `Mat` so you can't pass just a number to it. You're probably looking for a [`Mat::set_scalar`](https://docs.rs/opencv/latest/opencv/prelude/trait.MatTrait.html#method.set_scalar) function.

**Comment by qq351469076** [comment]
Thanks, but there is also an error in another example, which is also the example you mentioned before

```rust
use opencv::core::{Rect, Scalar, Vec3b, CV_8UC1, CV_8UC3, CV_8UC4};

use opencv::highgui::{imshow, wait_key};
use opencv::prelude::*;

fn main() -> opencv::Result<()> {
    let mat = Mat::new_rows_cols_with_default(200, 200, CV_8UC3, 0.into())?;

    Mat::roi(&mat, Rect::new(20, 20, 100, 100))?.set((0., 0., 255.).into())?;

    imshow("adasd", &mat).unwrap();

    wait_key(10000).unwrap();

    Ok(())
}
```

![image](https://github.com/twistedfall/opencv-rust/assets/28567138/b430ce11-c8db-476c-a993-3b58def5149d)

![image](https://github.com/twistedfall/opencv-rust/assets/28567138/83f40437-63d1-4e33-af9f-74daae9399eb)

**Comment by twistedfall** [comment]
There were changes around those functions in v0.86.0, shortly after that comment, so it was true at that moment, but it's no longer the case. You should use `set_scalar` now :) The API is still in flux as new functionality is added or changed.

**Comment by qq351469076** [comment]
Sorry it was my problem but thank you for helping me, this has solved my problem :)
