### ISSUE TITLE
Build fails on NixOS: thread '<unnamed>' panicked at ... Failed to run the bindings generator for ...

### ISSUE THREAD

**Issue by kentookura** [twistedfall/opencv-rust#521]
* Operating system: NixOS
* OpenCV installed via nixpkgs (See `flake.nix` below)
* OpenCV  4.7.0
* rustc 1.74.0 (79e9716c9 2023-11-13)
* Error: [log.txt](https://github.com/twistedfall/opencv-rust/files/13596713/log.txt)

```nix
{
  inputs = {
    nixpkgs.url = "nixpkgs";
    flake-utils.url = "github:numtide/flake-utils";
    rust-overlay.url = "github:oxalica/rust-overlay";
  };

  outputs = { self, nixpkgs, rust-overlay, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        overlays = [ (import rust-overlay) ];
        pkgs = import nixpkgs { inherit system overlays; }; k
      in
      {
        devShell = pkgs.mkShell {
          nativeBuildInputs = [
            pkgs.pkg-config
            pkgs.opencv
          ];
          buildInputs = with pkgs;  [
            pkgs.opencv
            clang
            pkg-config
            stdenv.cc.libc
            (rust-bin.stable.latest.default.override {
              extensions = [ "rust-src" "rust-analyzer-preview" "rustfmt" ];
            })
          ];
        };
      });
}
```
I realize that I probably have to set some environment variables, which would be done using a `shellHook`: https://nixos.wiki/wiki/Development_environment_with_nix-shell

**Comment by twistedfall** [comment]
Well the errors is `/nix/store/hf2gy3km07d5m0p1lwmja0rg9wlnmyr7-gcc-12.3.0/include/c++/12.3.0/cstdlib:75:15: fatal error: 'stdlib.h' file not found` so you're probably missing a standard C library installation.

**Comment by kentookura** [comment]
The fix was to remove `stdenv.cc.libc` from the buildInputs
