### ISSUE TITLE
issue with call create_trackbar fun

### ISSUE THREAD

**Issue by adminSxs** [twistedfall/opencv-rust#522]
**code**
```rust
use opencv::core::mul_f64_mat;
use opencv::highgui::{create_trackbar, imshow, named_window, wait_key, WINDOW_AUTOSIZE};
use opencv::imgcodecs::{imread, IMREAD_COLOR};
fn main()->opencv::Result<()>{
    let img=imread("avatar.png",IMREAD_COLOR)?;
    named_window("window",WINDOW_AUTOSIZE)?;
    create_trackbar("track","window",None,100,Some(Box::new(onchange)))?;

    imshow("window",&img)?;
    wait_key(0)?;
    Ok(())
}
fn onchange(value : i32){
    let a= value as f64/100.;
    println!("val={a}");
    // mul_f64_mat(a,&img);
}
```
<b><font color='red'>I want to in onchange method use img variable, how should to do</font></b>

**Comment by twistedfall** [comment]
The bindings don't expose the `userdata` argument as it's used for internal purposes. To capture the variables in your callback you should use Rust closures. You can check an example of this in the [hough_lines example](https://github.com/twistedfall/opencv-rust/blob/master/examples/hough_lines.rs#L60).

**Comment by adminSxs** [comment]
> The bindings don't expose the `userdata` argument as it's used for internal purposes. To capture the variables in your callback you should use Rust closures. You can check an example of this in the [hough_lines example](https://github.com/twistedfall/opencv-rust/blob/master/examples/hough_lines.rs#L60).

thanks
