### ISSUE TITLE
Ask about mat grammar questions

### ISSUE THREAD

**Issue by qq351469076** [twistedfall/opencv-rust#528]
![image](https://github.com/twistedfall/opencv-rust/assets/28567138/5e8d8835-5954-4256-a288-ade4281fabcb)

Hi, is there any Rust syntax like line 17?

**Comment by qq351469076** [comment]
Or how to iterate over Mat structure to facilitate it

**Comment by twistedfall** [comment]
You should now (in v0.88.3) be able to use `Mat::iter_mut` to get the mutable iterator over all elements.
