### ISSUE TITLE
unresolved imports `opencv::cudafilters`, `opencv::cudaimgproc` no `cudafilters` in the root

### ISSUE THREAD

**Issue by DennisZhangOiler** [twistedfall/opencv-rust#529]
Hi I am trying to run code in example/cuda, but it failed to find those 2 modules, and it's strange that on docs it's in default feature.

**Comment by twistedfall** [comment]
Looks like your OpenCV installation doesn't have CUDA support that's why those modules are missing. To include CUDA support you most likely need to build OpenCV manually. Pre-built binary packages rarely contain it.

**Comment by DennisZhangOiler** [comment]
> Looks like your OpenCV installation doesn't have CUDA support that's why those modules are missing. To include CUDA support you most likely need to build OpenCV manually. Pre-built binary packages rarely contain it.

Thanks!
