### ISSUE TITLE
unresolved import opencv::face

### ISSUE THREAD

**Issue by tcirtsa** [twistedfall/opencv-rust#533]
I don't know why and how to resolve it. Please help me.
![{23732852-0AE1-4ff5-9F88-12C593283209}](https://github.com/twistedfall/opencv-rust/assets/122344862/fa6f263f-54ab-4309-aad9-814521a683a2)
![{9094123F-BBA0-4c44-A2F1-F6A8119BFB46}](https://github.com/twistedfall/opencv-rust/assets/122344862/5aa5dba1-0c51-4146-aa6f-65d5f45c2c06)

**Comment by tcirtsa** [comment]
rustc 1.74.1 (a28077b28 2023-12-04)

**Comment by twistedfall** [comment]
Looks like your OpenCV installation doesn't contain the `face` module, it's part of the `contrib` so you'll most likely need to compile OpenCV manually

**Comment by tcirtsa** [comment]
> Looks like your OpenCV installation doesn't contain the `face` module, it's part of the `contrib` so you'll most likely need to compile OpenCV manually

use cmake to compile the source?

**Comment by tcirtsa** [comment]
> Looks like your OpenCV installation doesn't contain the `face` module, it's part of the `contrib` so you'll most likely need to compile OpenCV manually

how to do? I'm sorry to say that? But I don't know

**Comment by twistedfall** [comment]
It's not a simple matter that I can answer with a single comment. I would suggest you to check multiple guides that are already written: https://www.google.com/search?q=opencv+build+from+source

**Comment by tcirtsa** [comment]
> It's not a simple matter that I can answer with a single comment. I would suggest you to check multiple guides that are already written: https://www.google.com/search?q=opencv+build+from+source

I got it. Thank you.
