### ISSUE TITLE
Allow override pkg_name in build.rs

### ISSUE THREAD

**Issue by jerry73204** [twistedfall/opencv-rust#55]
I'm using Arch Linux and happened to develop several projects on OpenCV 3 and 4.
For sake of package conflict, I install OpenCV 4.1 from official repository, and OpenCV {3.4, 2.x} from AUR (An unofficial package repo used by most Arch lovers).

OpenCV 4 is installed at standard locations and it works fine for me. However, OpenCV 3 is placed under `/opt`. The `build.rs` failed to find `opencv.pc` even with proper `PKG_CONFIG_PATH` is set. The cause is that the file is renamed to `opencv3.pc`, and I find no way to override the pkg\_name in [build.rs](https://github.com/twistedfall/opencv-rust/blob/2f3215705d82131905b300591ed461ef6667ddd2/build.rs#L173).

I see the work around to make a symlink from `opencv.pc` to `opencv3.pc`. I would prefer a configurable way rather than messing up with symlinks. Suppose we introduce `OPENCV_RS_PKG_NAME` env variable in build.rs?

**Comment by twistedfall** [comment]
Should be doable, I’ll look into it

**Comment by twistedfall** [comment]
You can now use `OPENCV_PKGCONFIG_NAME` environment variable in v0.22.1+

**Comment by jerry73204** [comment]
Many thanks!
