### ISSUE TITLE
Can't initialize VIdeoCapture from file

### ISSUE THREAD

**Issue by 111raigeki** [twistedfall/opencv-rust#551]
Hello, I am trying to open a video using VideoCapture::from_file, but I can't get it to read the file properly. The project builds without any issues, but is_opened doesn't return true:
```rust
let mut cam = videoio::VideoCapture::from_file("data/test_vid.mp4", videoio::CAP_ANY)?;

let opened = videoio::VideoCapture::is_opened(&cam)?;//always false independent of file path or file format 
```
I've tried to do the same in python (3.10, opencv-python 4.9.0) and it works just fine. Capturing video from webcam also works fine. 

Information:
1. os: **Mint 21.2**
2. way to install opencv: **manual build (cmake)**
3. opencv version: **4.9.0-dev**
4. rustc version: **1.76.0 (07dca489a 2024-02-04)**
5. crate version: **0.88.8**

**Comment by twistedfall** [comment]
It can be that OpenCV is built without mp4 support for example, but python is using the different OpenCV version that has this support. Please also post `cargo build -vv` after doing `cargo clean`, it contains a lot of helpful debug information that might aid in tracking the source of the issue down.

**Comment by 111raigeki** [comment]
The codecs were indeed the issue - for some reason opencv did not recognize ffmpeg. Thank you for help.

**Comment by benjamingb** [comment]
> The codecs were indeed the issue - for some reason opencv did not recognize ffmpeg. Thank you for help.

@111raigeki 
I have the same problem, what codecs did you need to install?
