### ISSUE TITLE
Question about getting the byte array

### ISSUE THREAD

**Issue by augustocdias** [twistedfall/opencv-rust#56]
After calling `imgcodecs::imencode` I usually call the `to_vec` function from the resulting `VectorOfuchar` object.
Is there a better/faster way to get the array of bytes (`[u8]`) instead of transforming it into a `vec`?

**Comment by twistedfall** [comment]
Ugh, there is actually a `to_slice` method which does exactly that, but it's not marked as public by mistake. I'll push the new version with the fix soon.

**Comment by twistedfall** [comment]
It's available in version 0.23.0
