### ISSUE TITLE
DescriptorMatcher missing match fn with training descriptors

### ISSUE THREAD

**Issue by w-utter** [twistedfall/opencv-rust#565]
OpenCV has varaints of the `match` and `knn_match` fns with training descriptors which are not currently implemented in this wrapper. They seem to have been implemented for some other modules (such as cuda) but are missing in others.

docs for descriptor matcher can be found here [here](https://docs.opencv.org/4.x/db/d39/classcv_1_1DescriptorMatcher.html)

**Comment by twistedfall** [comment]
I will take a look, thanks for the report!

**Comment by twistedfall** [comment]
I think [`DescriptorMatcher::train_match`](https://docs.rs/opencv/latest/opencv/prelude/trait.DescriptorMatcherTraitConst.html#method.train_match) and [`DescriptorMatcher::knn_train_match`](https://docs.rs/opencv/latest/opencv/prelude/trait.DescriptorMatcherTraitConst.html#method.knn_train_match) is what you're looking for.
