### ISSUE TITLE
unable to open ip camera

### ISSUE THREAD

**Issue by learncodingforweb** [twistedfall/opencv-rust#566]
I am using usb camera, it is working fine. using
```
let cam = videoio::VideoCapture::new(0, videoio::CAP_ANY)?; 
```
But how can i open ip camera with url **rtsp://admin:admin@192.168.1.10:554**?

```
opencv = "0.91"
```

rustc --version
rustc 1.77.2 (25ef9e3d8 2024-04-09)

**Comment by twistedfall** [comment]
Does it work with Python or C++ code?

**Comment by learncodingforweb** [comment]
yes, it works with python as
```
cam = cv2.VideoCapture("rtsp://admin:admin@192.168.1.10:554")
```

**Comment by twistedfall** [comment]
I see, then using [`VideoCapture::from_file`](https://docs.rs/opencv/latest/opencv/videoio/struct.VideoCapture.html#method.from_file) should do the trick.

**Comment by learncodingforweb** [comment]
Yes, it is working fine for
```
let cam = videoio::VideoCapture::from_file("rtsp://admin:admin@192.168.1.10:554", videoio::CAP_ANY)?;
```
