### ISSUE TITLE
vcpkg install of dependencies takes >100gigs for me 

### ISSUE THREAD

**Issue by anandijain** [twistedfall/opencv-rust#567]
this isn't so much of a problem with the repo as it is with vcpkg, but i wanted to notify that in my case (win11), trying to vcpkg the dependencies (opencv4 and llvm) ended up failing and eating my disk until empty. 

so i would recommend against that method, i am going to try chocolatey instead. 

![image](https://github.com/twistedfall/opencv-rust/assets/33790004/9e4ded5c-2690-4d04-a2cc-c103f00efe43)

thank you for the bindings

**Comment by anandijain** [comment]
just realized choco needs llvm too, any way to install the dependencies that takes less space?

**Comment by twistedfall** [comment]
In CI I install llvm from choco even when testing OpenCV from vcpkg. Also I only build release libs. That cuts down the compilation time and size considerably. There is also a cleanup step that frees up space (at the cost of increasing compilation time for reinstalls). You can check that in the CI installation script: https://github.com/twistedfall/opencv-rust/blob/master/ci/install-windows-vcpkg.sh

**Comment by twistedfall** [comment]
I hope that helped! I'm going to close this issue as there is nothing actionable from my side.
