### ISSUE TITLE
Multiplying Mat by float

### ISSUE THREAD

**Issue by awebb-nz** [twistedfall/opencv-rust#57]
Firstly, thanks for the library, it has (mostly) been great to use. I apologise if I am missing something simple, but I am trying to convert some c++ code that contains`m *= 7.0;`, where m is a Mat, and 7 is a float or double.

How do you perform something similar in rust?

**Comment by twistedfall** [comment]
Well, C++ operators are currently only implemented manually and there is no `*=` implementation for `Mat` yet, but you can use [Mat::mul](https://docs.rs/opencv/0.23.0/opencv/core/struct.Mat.html#method.mul) method like this:
```rust
        let s: Vec<Vec<f32>> = vec![
            vec![1., 2., 3.],
            vec![4., 5., 6.],
            vec![7., 8., 9.],
        ];

        let mat = Mat::from_slice_2d(&s)?;
        let m = mat.mul(&2., 1.)?.to_mat()?;
        dbg!(&m.data_typed::<f32>());
```
gives you
```
[tests/mat.rs:383] &m.data_typed::<f32>() = Ok(
    [
        2.0,
        4.0,
        6.0,
        8.0,
        10.0,
        12.0,
        14.0,
        16.0,
        18.0,
    ],
)
```

**Comment by awebb-nz** [comment]
Wonderful, thanks for your help. That seems to have worked.

I had looked at that method previously, but I didn't notice the implementation of `ToInputArray` for `f64`.
