### ISSUE TITLE
Build Failed on M3 Pro

### ISSUE THREAD

**Issue by sunwupark** [twistedfall/opencv-rust#575]
Before reporting an issue please first check the
[troubleshooting guide](https://github.com/twistedfall/opencv-rust/blob/master/README.md#troubleshooting). If
the issue you're encountering is not solved thereby please state the following in your bugreport:
1. Operating system
- M3 PRO, MacOS
2. The way you installed OpenCV: package, official binary distribution, manual compilation, etc.
- add opencv = "0.91.3" on Cargo.toml
- brew install opencv
3. OpenCV version
opencv: stable 4.9.0 (bottled)
4. rustc version (`rustc --version`)
- rustc 1.78.0 (9b00956e5 2024-04-29) (Homebrew)
5. Attach the full output of the following command from your project directory:
   ```shell script
   RUST_BACKTRACE=full cargo build -vv 
   ```
`
 Running `CARGO=/opt/homebrew/Cellar/rust/1.78.0/bin/cargo CARGO_CRATE_NAME=ring CARGO_MANIFEST_DIR=/Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20 CARGO_PKG_AUTHORS='Brian Smith <brian@briansmith.org>' CARGO_PKG_DESCRIPTION='Safe, fast, small crypto using Rust.' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE='' CARGO_PKG_LICENSE_FILE=LICENSE CARGO_PKG_NAME=ring CARGO_PKG_README=doc/link-to-readme.md CARGO_PKG_REPOSITORY='https://github.com/briansmith/ring' CARGO_PKG_RUST_VERSION='' CARGO_PKG_VERSION=0.16.20 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=16 CARGO_PKG_VERSION_PATCH=20 CARGO_PKG_VERSION_PRE='' DYLD_FALLBACK_LIBRARY_PATH='/Users/sunwupark/Desktop/SchoolWork/CapstoneDesign/wtransport/target/debug/deps:/Users/sunwupark/lib:/usr/local/lib:/usr/lib' OUT_DIR=/Users/sunwupark/Desktop/SchoolWork/CapstoneDesign/wtransport/target/debug/build/ring-eec60f6ce34ae2dc/out rustc --crate-name ring --edition=2018 /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=80 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked --cfg 'feature="alloc"' --cfg 'feature="default"' --cfg 'feature="dev_urandom_fallback"' --cfg 'feature="once_cell"' -C metadata=ad9cfb01e7885551 -C extra-filename=-ad9cfb01e7885551 --out-dir /Users/sunwupark/Desktop/SchoolWork/CapstoneDesign/wtransport/target/debug/deps -L dependency=/Users/sunwupark/Desktop/SchoolWork/CapstoneDesign/wtransport/target/debug/deps --extern untrusted=/Users/sunwupark/Desktop/SchoolWork/CapstoneDesign/wtransport/target/debug/deps/libuntrusted-259f94f1dc9a299a.rmeta --cap-lints warn -L native=/Users/sunwupark/Desktop/SchoolWork/CapstoneDesign/wtransport/target/debug/build/ring-eec60f6ce34ae2dc/out -l static=ring-core -l static=ring-test`
[opencv 0.91.3] dyld[1998]: Library not loaded: @rpath/libclang.dylib
[opencv 0.91.3]   Referenced from: <F9B9FD3C-8B95-3D5A-B8D6-399C8128F630> /Users/sunwupark/Desktop/SchoolWork/CapstoneDesign/wtransport/target/debug/build/opencv-1b0b9d61994b8dfe/build-script-build
[opencv 0.91.3]   Reason: tried: '/Users/sunwupark/Desktop/SchoolWork/CapstoneDesign/wtransport/target/debug/deps/libclang.dylib' (no such file), '/Users/sunwupark/Desktop/SchoolWork/CapstoneDesign/wtransport/target/debug/libclang.dylib' (no such file), '/opt/homebrew/Cellar/rust/1.78.0/lib/rustlib/aarch64-apple-darwin/lib/libclang.dylib' (no such file), '/Users/sunwupark/lib/libclang.dylib' (no such file), '/usr/local/lib/libclang.dylib' (no such file), '/usr/lib/libclang.dylib' (no such file, not in dyld cache)
libunwind: malformed __unwind_info at 0x19ECC8CA8 bad second level page rin...
error: failed to run custom build command for `opencv v0.91.3`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `CARGO=/opt/homebrew/Cellar/rust/1.78.0/bin/cargo CARGO_CFG_PANIC=unwind CARGO_CFG_TARGET_ABI='' CARGO_CFG_TARGET_ARCH=aarch64 CARGO_CFG_TARGET_ENDIAN=little CARGO_CFG_TARGET_ENV='' CARGO_CFG_TARGET_FAMILY=unix CARGO_CFG_TARGET_FEATURE=aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh CARGO_CFG_TARGET_HAS_ATOMIC=128,16,32,64,8,ptr CARGO_CFG_TARGET_OS=macos CARGO_CFG_TARGET_POINTER_WIDTH=64 CARGO_CFG_TARGET_VENDOR=apple CARGO_CFG_UNIX='' CARGO_ENCODED_RUSTFLAGS='' CARGO_FEATURE_ALPHAMAT=1 CARGO_FEATURE_ARUCO=1 CARGO_FEATURE_ARUCO_DETECTOR=1 CARGO_FEATURE_BARCODE=1 CARGO_FEATURE_BGSEGM=1 CARGO_FEATURE_BIOINSPIRED=1 CARGO_FEATURE_CALIB3D=1 CARGO_FEATURE_CCALIB=1 CARGO_FEATURE_CUDAARITHM=1 CARGO_FEATURE_CUDABGSEGM=1 CARGO_FEATURE_CUDACODEC=1 CARGO_FEATURE_CUDAFEATURES2D=1 CARGO_FEATURE_CUDAFILTERS=1 CARGO_FEATURE_CUDAIMGPROC=1 CARGO_FEATURE_CUDAOBJDETECT=1 CARGO_FEATURE_CUDAOPTFLOW=1 CARGO_FEATURE_CUDASTEREO=1 CARGO_FEATURE_CUDAWARPING=1 CARGO_FEATURE_CVV=1 CARGO_FEATURE_DEFAULT=1 CARGO_FEATURE_DNN=1 CARGO_FEATURE_DNN_SUPERRES=1 CARGO_FEATURE_DPM=1 CARGO_FEATURE_FACE=1 CARGO_FEATURE_FEATURES2D=1 CARGO_FEATURE_FLANN=1 CARGO_FEATURE_FREETYPE=1 CARGO_FEATURE_FUZZY=1 CARGO_FEATURE_GAPI=1 CARGO_FEATURE_HDF=1 CARGO_FEATURE_HFS=1 CARGO_FEATURE_HIGHGUI=1 CARGO_FEATURE_IMGCODECS=1 CARGO_FEATURE_IMGPROC=1 CARGO_FEATURE_IMG_HASH=1 CARGO_FEATURE_INTENSITY_TRANSFORM=1 CARGO_FEATURE_LINE_DESCRIPTOR=1 CARGO_FEATURE_MCC=1 CARGO_FEATURE_ML=1 CARGO_FEATURE_OBJDETECT=1 CARGO_FEATURE_OPTFLOW=1 CARGO_FEATURE_OVIS=1 CARGO_FEATURE_PHASE_UNWRAPPING=1 CARGO_FEATURE_PHOTO=1 CARGO_FEATURE_PLOT=1 CARGO_FEATURE_QUALITY=1 CARGO_FEATURE_RAPID=1 CARGO_FEATURE_RGBD=1 CARGO_FEATURE_SALIENCY=1 CARGO_FEATURE_SFM=1 CARGO_FEATURE_SHAPE=1 CARGO_FEATURE_STEREO=1 CARGO_FEATURE_STITCHING=1 CARGO_FEATURE_STRUCTURED_LIGHT=1 CARGO_FEATURE_SUPERRES=1 CARGO_FEATURE_SURFACE_MATCHING=1 CARGO_FEATURE_TEXT=1 CARGO_FEATURE_TRACKING=1 CARGO_FEATURE_VIDEO=1 CARGO_FEATURE_VIDEOIO=1 CARGO_FEATURE_VIDEOSTAB=1 CARGO_FEATURE_VIZ=1 CARGO_FEATURE_WECHAT_QRCODE=1 CARGO_FEATURE_XFEATURES2D=1 CARGO_FEATURE_XIMGPROC=1 CARGO_FEATURE_XOBJDETECT=1 CARGO_FEATURE_XPHOTO=1 CARGO_MANIFEST_DIR=/Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.91.3 CARGO_PKG_AUTHORS='Pro <twisted.fall@gmail.com>:Mathieu Poumeyrol <kali@zoy.org>' CARGO_PKG_DESCRIPTION='Rust bindings for OpenCV' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE=MIT CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=opencv CARGO_PKG_README=README.md CARGO_PKG_REPOSITORY='https://github.com/twistedfall/opencv-rust' CARGO_PKG_RUST_VERSION=1.66 CARGO_PKG_VERSION=0.91.3 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=91 CARGO_PKG_VERSION_PATCH=3 CARGO_PKG_VERSION_PRE='' DEBUG=true DYLD_FALLBACK_LIBRARY_PATH='/Users/sunwupark/Desktop/SchoolWork/CapstoneDesign/wtransport/target/debug/deps:/Users/sunwupark/Desktop/SchoolWork/CapstoneDesign/wtransport/target/debug:/opt/homebrew/Cellar/rust/1.78.0/lib/rustlib/aarch64-apple-darwin/lib:/Users/sunwupark/lib:/usr/local/lib:/usr/lib' HOST=aarch64-apple-darwin NUM_JOBS=12 OPT_LEVEL=0 OUT_DIR=/Users/sunwupark/Desktop/SchoolWork/CapstoneDesign/wtransport/target/debug/build/opencv-9818e597e1113d65/out PROFILE=debug RUSTC=rustc RUSTDOC=rustdoc TARGET=aarch64-apple-darwin /Users/sunwupark/Desktop/SchoolWork/CapstoneDesign/wtransport/target/debug/build/opencv-1b0b9d61994b8dfe/build-script-build` (signal: 6, SIGABRT: process abort signal)
  --- stderr
  dyld[1998]: Library not loaded: @rpath/libclang.dylib
    Referenced from: <F9B9FD3C-8B95-3D5A-B8D6-399C8128F630> /Users/sunwupark/Desktop/SchoolWork/CapstoneDesign/wtransport/target/debug/build/opencv-1b0b9d61994b8dfe/build-script-build
    Reason: tried: '/Users/sunwupark/Desktop/SchoolWork/CapstoneDesign/wtransport/target/debug/deps/libclang.dylib' (no such file), '/Users/sunwupark/Desktop/SchoolWork/CapstoneDesign/wtransport/target/debug/libclang.dylib' (no such file), '/opt/homebrew/Cellar/rust/1.78.0/lib/rustlib/aarch64-apple-darwin/lib/libclang.dylib' (no such file), '/Users/sunwupark/lib/libclang.dylib' (no such file), '/usr/local/lib/libclang.dylib' (no such file), '/usr/lib/libclang.dylib' (no such file, not in dyld cache)
warning: build failed, waiting for other jobs to finish...
warning: unused doc comment
   --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/src/aead/chacha.rs:110:9
    |
110 | / ...   /// XXX: Although this takes an `Iv`, this actually uses it like a
111 | | ...   /// `Counter`.
    | |____________________^
112 | / ...   extern "C" {
113 | | ...       fn GFp_ChaCha20_ctr32(
114 | | ...           out: *mut u8,
115 | | ...           in_: *const u8,
...   |
119 | | ...       );
120 | | ...   }
    | |_______- rustdoc does not generate documentation for extern blocks
    |
    = help: use `//` for a plain comment
    = note: `#[warn(unused_doc_comments)]` on by default

warning: unnecessary qualification
   --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/src/rand.rs:104:34
    |
104 | pub trait RandomlyConstructable: self::sealed::RandomlyConstructable {}
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: the lint level is defined here
   --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/src/lib.rs:72:23
    |
72  | #![deny(missing_docs, unused_qualifications, variant_size_differences)]
    |                       ^^^^^^^^^^^^^^^^^^^^^
help: remove the unnecessary path segments
    |
104 - pub trait RandomlyConstructable: self::sealed::RandomlyConstructable {}
104 + pub trait RandomlyConstructable: sealed::RandomlyConstructable {}
    |

warning: unnecessary qualification
   --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/src/rand.rs:105:46
    |
105 | ... for T where T: self::sealed::RandomlyConstructable {}
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
help: remove the unnecessary path segments
    |
105 - impl<T> RandomlyConstructable for T where T: self::sealed::RandomlyConstructable {}
105 + impl<T> RandomlyConstructable for T where T: sealed::RandomlyConstructable {}
    |

warning: unnecessary qualification
   --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/src/rsa/signing.rs:169:17
    |
169 |                 error::KeyRejected::invalid_encoding(),
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
help: remove the unnecessary path segments
    |
169 -                 error::KeyRejected::invalid_encoding(),
169 +                 KeyRejected::invalid_encoding(),
    |

warning: unnecessary qualification
   --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/src/rsa/signing.rs:316:26
    |
316 |             .map_err(|_| error::KeyRejected::invalid_encoding())?;
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
help: remove the unnecessary path segments
    |
316 -             .map_err(|_| error::KeyRejected::invalid_encoding())?;
316 +             .map_err(|_| KeyRejected::invalid_encoding())?;
    |

warning: unnecessary qualification
   --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/src/rsa/signing.rs:445:24
    |
445 | ...rr(error::KeyRejected::private_modulus_len_not_multiple_of_512_bits());
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
help: remove the unnecessary path segments
    |
445 -             return Err(error::KeyRejected::private_modulus_len_not_multiple_of_512_bits());
445 +             return Err(KeyRejected::private_modulus_len_not_multiple_of_512_bits());
    |

warning: field `cpu_features` is never read
  --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/src/digest.rs:49:5
   |
38 | pub(crate) struct BlockContext {
   |                   ------------ field in this struct
...
49 |     cpu_features: cpu::Features,
   |     ^^^^^^^^^^^^
   |
   = note: `BlockContext` has a derived impl for the trait `Clone`, but this is intentionally ignored during dead code analysis
   = note: `#[warn(dead_code)]` on by default

warning: unnecessary qualification
   --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/any.rs:104:26
    |
104 |             .map_err(|e| nom::Err::Error(e.into()))?;
    |                          ^^^^^^^^^^^^^^^
    |
note: the lint level is defined here
   --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/lib.rs:157:5
    |
157 |     unused_qualifications,
    |     ^^^^^^^^^^^^^^^^^^^^^
help: remove the unnecessary path segments
    |
104 -             .map_err(|e| nom::Err::Error(e.into()))?;
104 +             .map_err(|e| Err::Error(e.into()))?;
    |

warning: unnecessary qualification
   --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/any.rs:107:26
    |
107 |             .map_err(|e| nom::Err::Error(e.into()))?;
    |                          ^^^^^^^^^^^^^^^
    |
help: remove the unnecessary path segments
    |
107 -             .map_err(|e| nom::Err::Error(e.into()))?;
107 +             .map_err(|e| Err::Error(e.into()))?;
    |

warning: unnecessary qualification
   --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/any.rs:128:26
    |
128 |             .map_err(|e| nom::Err::Error(e.into()))?;
    |                          ^^^^^^^^^^^^^^^
    |
help: remove the unnecessary path segments
    |
128 -             .map_err(|e| nom::Err::Error(e.into()))?;
128 +             .map_err(|e| Err::Error(e.into()))?;
    |

warning: unnecessary qualification
   --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/any.rs:131:26
    |
131 |             .map_err(|e| nom::Err::Error(e.into()))?;
    |                          ^^^^^^^^^^^^^^^
    |
help: remove the unnecessary path segments
    |
131 -             .map_err(|e| nom::Err::Error(e.into()))?;
131 +             .map_err(|e| Err::Error(e.into()))?;
    |

warning: unnecessary qualification
   --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/sequence/vec.rs:100:26
    |
100 |             .map_err(|e| nom::Err::Error(e.into()))?;
    |                          ^^^^^^^^^^^^^^^
    |
help: remove the unnecessary path segments
    |
100 -             .map_err(|e| nom::Err::Error(e.into()))?;
100 +             .map_err(|e| Err::Error(e.into()))?;
    |

warning: unnecessary qualification
   --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/sequence/vec.rs:103:22
    |
103 |             .map_err(nom::Err::Error)?;
    |                      ^^^^^^^^^^^^^^^
    |
help: remove the unnecessary path segments
    |
103 -             .map_err(nom::Err::Error)?;
103 +             .map_err(Err::Error)?;
    |

warning: unnecessary qualification
   --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/sequence.rs:182:22
    |
182 |             _ => Err(nom::Err::Error(Error::LifetimeError.into())),
    |                      ^^^^^^^^^^^^^^^
    |
help: remove the unnecessary path segments
    |
182 -             _ => Err(nom::Err::Error(Error::LifetimeError.into())),
182 +             _ => Err(Err::Error(Error::LifetimeError.into())),
    |

warning: unnecessary qualification
  --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/set/btreeset.rs:50:26
   |
50 |             .map_err(|e| nom::Err::Error(e.into()))?;
   |                          ^^^^^^^^^^^^^^^
   |
help: remove the unnecessary path segments
   |
50 -             .map_err(|e| nom::Err::Error(e.into()))?;
50 +             .map_err(|e| Err::Error(e.into()))?;
   |

warning: unnecessary qualification
  --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/set/btreeset.rs:53:26
   |
53 |             .map_err(|e| nom::Err::Error(e.into()))?;
   |                          ^^^^^^^^^^^^^^^
   |
help: remove the unnecessary path segments
   |
53 -             .map_err(|e| nom::Err::Error(e.into()))?;
53 +             .map_err(|e| Err::Error(e.into()))?;
   |

warning: unnecessary qualification
  --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/set/btreeset.rs:56:22
   |
56 |             .map_err(nom::Err::Error)?;
   |                      ^^^^^^^^^^^^^^^
   |
help: remove the unnecessary path segments
   |
56 -             .map_err(nom::Err::Error)?;
56 +             .map_err(Err::Error)?;
   |

warning: unnecessary qualification
  --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/set/hashset.rs:52:26
   |
52 |             .map_err(|e| nom::Err::Error(e.into()))?;
   |                          ^^^^^^^^^^^^^^^
   |
help: remove the unnecessary path segments
   |
52 -             .map_err(|e| nom::Err::Error(e.into()))?;
52 +             .map_err(|e| Err::Error(e.into()))?;
   |

warning: unnecessary qualification
  --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/set/hashset.rs:55:26
   |
55 |             .map_err(|e| nom::Err::Error(e.into()))?;
   |                          ^^^^^^^^^^^^^^^
   |
help: remove the unnecessary path segments
   |
55 -             .map_err(|e| nom::Err::Error(e.into()))?;
55 +             .map_err(|e| Err::Error(e.into()))?;
   |

warning: unnecessary qualification
  --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/set/hashset.rs:58:22
   |
58 |             .map_err(nom::Err::Error)?;
   |                      ^^^^^^^^^^^^^^^
   |
help: remove the unnecessary path segments
   |
58 -             .map_err(nom::Err::Error)?;
58 +             .map_err(Err::Error)?;
   |

warning: unnecessary qualification
   --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/set.rs:183:22
    |
183 |             _ => Err(nom::Err::Error(Error::LifetimeError.into())),
    |                      ^^^^^^^^^^^^^^^
    |
help: remove the unnecessary path segments
    |
183 -             _ => Err(nom::Err::Error(Error::LifetimeError.into())),
183 +             _ => Err(Err::Error(Error::LifetimeError.into())),
    |

warning: unnecessary qualification
  --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/strings/bmpstring.rs:45:19
   |
45 |             data: alloc::borrow::Cow::Owned(s),
   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: remove the unnecessary path segments
   |
45 -             data: alloc::borrow::Cow::Owned(s),
45 +             data: Cow::Owned(s),
   |

warning: unnecessary qualification
  --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/strings/universalstring.rs:46:19
   |
46 |             data: alloc::borrow::Cow::Owned(s),
   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: remove the unnecessary path segments
   |
46 -             data: alloc::borrow::Cow::Owned(s),
46 +             data: Cow::Owned(s),
   |

warning: unnecessary qualification
  --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/tagged/helpers.rs:37:26
   |
37 |             .map_err(|e| nom::Err::convert(e.into()))?;
   |                          ^^^^^^^^^^^^^^^^^
   |
help: remove the unnecessary path segments
   |
37 -             .map_err(|e| nom::Err::convert(e.into()))?;
37 +             .map_err(|e| Err::convert(e.into()))?;
   |

warning: unnecessary qualification
  --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/tagged/helpers.rs:56:26
   |
56 |             .map_err(|e| nom::Err::convert(e.into()))?;
   |                          ^^^^^^^^^^^^^^^^^
   |
help: remove the unnecessary path segments
   |
56 -             .map_err(|e| nom::Err::convert(e.into()))?;
56 +             .map_err(|e| Err::convert(e.into()))?;
   |

warning: unnecessary qualification
  --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/tagged/helpers.rs:76:26
   |
76 |             .map_err(|e| nom::Err::convert(e.into()))?;
   |                          ^^^^^^^^^^^^^^^^^
   |
help: remove the unnecessary path segments
   |
76 -             .map_err(|e| nom::Err::convert(e.into()))?;
76 +             .map_err(|e| Err::convert(e.into()))?;
   |

warning: unnecessary qualification
  --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/tagged/helpers.rs:96:51
   |
96 |         let (rem, any) = Any::from_der(i).map_err(nom::Err::convert)?;
   |                                                   ^^^^^^^^^^^^^^^^^
   |
help: remove the unnecessary path segments
   |
96 -         let (rem, any) = Any::from_der(i).map_err(nom::Err::convert)?;
96 +         let (rem, any) = Any::from_der(i).map_err(Err::convert)?;
   |

warning: unnecessary qualification
  --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/tagged/helpers.rs:99:26
   |
99 |             .map_err(|e| nom::Err::convert(e.into()))?;
   |                          ^^^^^^^^^^^^^^^^^
   |
help: remove the unnecessary path segments
   |
99 -             .map_err(|e| nom::Err::convert(e.into()))?;
99 +             .map_err(|e| Err::convert(e.into()))?;
   |

warning: unnecessary qualification
  --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/tagged/implicit.rs:77:27
   |
77 |             Err(e) => Err(nom::Err::Error(e)),
   |                           ^^^^^^^^^^^^^^^
   |
help: remove the unnecessary path segments
   |
77 -             Err(e) => Err(nom::Err::Error(e)),
77 +             Err(e) => Err(Err::Error(e)),
   |

warning: unnecessary qualification
   --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/tagged/implicit.rs:185:27
    |
185 |             Err(e) => Err(nom::Err::Error(e)),
    |                           ^^^^^^^^^^^^^^^
    |
help: remove the unnecessary path segments
    |
185 -             Err(e) => Err(nom::Err::Error(e)),
185 +             Err(e) => Err(Err::Error(e)),
    |

warning: unnecessary qualification
   --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/tagged/implicit.rs:220:48
    |
220 | ...   T::check_constraints(&any).map_err(|e| nom::Err::Error(e.into()))?;
    |                                              ^^^^^^^^^^^^^^^
    |
help: remove the unnecessary path segments
    |
220 -         T::check_constraints(&any).map_err(|e| nom::Err::Error(e.into()))?;
220 +         T::check_constraints(&any).map_err(|e| Err::Error(e.into()))?;
    |

warning: unnecessary qualification
   --> /Users/sunwupark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asn1-rs-0.6.1/src/asn1_types/tagged/implicit.rs:231:27
    |
231 |             Err(e) => Err(nom::Err::Error(e)),
    |                           ^^^^^^^^^^^^^^^
    |
help: remove the unnecessary path segments
    |
231 -             Err(e) => Err(nom::Err::Error(e)),
231 +             Err(e) => Err(Err::Error(e)),
    |

warning: `ring` (lib) generated 7 warnings
warning: `asn1-rs` (lib) generated 25 warnings
`

THIS IS MY ~/.zshrc

`export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"
export PATH="$PATH:/Users/sunwupark/kafka_2.13-3.7.0/bin"
export GOPATH="/usr/local/go"
export PATH=$PATH:/usr/local/go/bin
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/opt/homebrew/bin:$PATH"
export PYTHONPATH="/usr/local/bin/python3"
export OPENCV_LINK_LIBS=“/opt/homebrew/Cellar/opencv/4.9.0_8/lib”
export OPENCV_LINK_PATHS=“/opt/homebrew/opt/opencv/4.9.0_8/share/opencv4”
export OPENCV_INCLUDE_PATHS=“/opt/homebrew/opt/opencv/4.9.0_8/include/opencv4”
export LDFLAGS=-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
export DYLD_FALLBACK_LIBRARY_PATH="$(xcode-select --print-path)/usr/lib/"
`

**Comment by twistedfall** [comment]
The error is `Library not loaded: @rpath/libclang.dylib`, please refer to the https://github.com/twistedfall/opencv-rust/blob/master/TROUBLESHOOTING.md, point 7

**Comment by HuakunShen** [comment]
I got `cargo run` in terminal working, but had problems with rust analyzer in vscode.

Then I figured out the solution:
Add the following to vscode workspace settings file:  `.vscode/settings.json`

```json
{
  "terminal.integrated.env.osx": {
    "DYLD_FALLBACK_LIBRARY_PATH": "/Library/Developer/CommandLineTools/usr/lib"
  },
  "rust-analyzer.cargo.extraEnv": {
    "DYLD_FALLBACK_LIBRARY_PATH": "/Library/Developer/CommandLineTools/usr/lib"
  },
  "rust-analyzer.check.extraEnv": {
    "DYLD_FALLBACK_LIBRARY_PATH": "/Library/Developer/CommandLineTools/usr/lib"
  }
}
```

`"terminal.integrated.env.osx"` is used for running `cargo run` in the integrated terminal.
The other two are for rust analyzer running in background.

> The library path is specific to my computer.
