### ISSUE TITLE
Question about ranges

### ISSUE THREAD

**Issue by augustocdias** [twistedfall/opencv-rust#58]
So I'm trying to convert the python code snippet from this [answer](https://stackoverflow.com/a/48818513/684562) to rust, but I'm having troubles with the `ranges` function.
```
alpha_channel = img[:, :, 3]
_, mask = cv.threshold(alpha_channel, 254, 255, cv.THRESH_BINARY)  # binarize mask
color = img[:, :, :3]
new_img = cv.bitwise_not(cv.bitwise_not(color, mask=mask))
```

I believe the equivalent for getting the slices from the array, like python is doing would be the `ranges` function from mat.

So I'm trying something like this

```
            let mut range_alpha = VectorOfRange::new();
            range_alpha.push(core::Range::all()?);
            range_alpha.push(core::Range::all()?);
            range_alpha.push(core::Range::new(3, 3)?);
            let alpha = core::Mat::ranges(&image, &range_alpha)?;
```
The problem is: it seems the image don't have the third dimension in the array because I'm getting this error:

`OpenCV(3.4.5) /tmp/opencv@3-20190923-60723-3pu0wl/opencv-3.4.5/modules/core/src/matrix.cpp:537: error: (-215:Assertion failed) (int)ranges.size() == d in function 'Mat'`

I am reading the image as `IMREAD_UNCHANGED` and I'm sure it has the the alpha channel set.

**Comment by twistedfall** [comment]
Well, first let's check what actual structure `image` has:
```rust
dbg!(&image);
```

**Comment by augustocdias** [comment]
It looks like it has only 2 dimensions, but the python equivalent produces a tridimensional array 

```
[src/image_processor/mod.rs:58] &image = Mat {
    type: "CV_8UC4",
    flags: 1124024344,
    channels: 4,
    depth: "CV_8U",
    dims: 2,
    size: Size_ {
        width: 82,
        height: 82,
    },
    rows: 82,
    cols: 82,
    elem_size: 4,
    elem_size1: 1,
    total: 6724,
    is_continuous: true,
    is_submatrix: false,
}
```

**Comment by twistedfall** [comment]
Well, Mat has only 2 dimensions and [ranges](https://docs.rs/opencv/0.23.0/opencv/core/struct.Mat.html#method.ranges) operates on dimensions, so in this case `range_alpha` should have only 2 elements. From the looks of it you want to operate on channels, not dimensions. So maybe something like [split](https://docs.rs/opencv/0.23.0/opencv/core/fn.split.html) is useful? Examples usage: https://github.com/twistedfall/opencv-rust/blob/master/tests/mat.rs#L362

**Comment by augustocdias** [comment]
It worked!
Here's the final code:

```
            let empty_mat = core::Mat::default()?;
            let mut split = VectorOfMat::new();
            core::split(&image, &mut split)?;
            let alpha = split.get(3)?;
            let mut color = core::Mat::default()?;
            split.remove(3)?;
            core::merge(&split, &mut color)?;
            let mut mask = core::Mat::default()?;
            imgproc::threshold(&alpha, &mut mask, 254.0, 255.0, imgproc::THRESH_BINARY)?;
            let mut not = core::Mat::default()?;
            let mut result = core::Mat::default()?;
            core::bitwise_not(&color, &mut not, &mask)?;
            core::bitwise_not(&not, &mut result, &empty_mat)?;
```

Thank you very much!
