### ISSUE TITLE
raspberry pi 4 GPU usage with opencv

### ISSUE THREAD

**Issue by learncodingforweb** [twistedfall/opencv-rust#582]
1. Operating system - raspberry pi Bookworm 64 bit
2. The way you installed OpenCV:  [Install](https://github.com/twistedfall/opencv-rust/blob/master/INSTALL.md)
3. OpenCV version: 4.6.0
4. rustc version (`rustc --version`): rustc 1.78.0 (9b00956e5 2024-04-29)
5. Attach the full output of the following command from your project directory:
**Tell me solution that usage GPU instead of CPU to improve raspberry pi performance**

**Comment by twistedfall** [comment]
The crate doesn't have any means to enable or disable the GPU acceleration for OpenCV, it's controlled by the build of the C++ OpenCV itself and the OS environment that you use. As far as I know you can use GPU acceleration with OpenCV on RPi only with OpenCL. To my knowledge there is no built-in implementation of OpenCL, but there is an side project for that: https://github.com/doe300/VC4CL. Judging by the message i the readme it's not compatible with RPi 4, but other post suggests there there is an alternative approach: https://raspberrypi.stackexchange.com/questions/143316/opencl-on-rpi-400, so you can try your luck. 

Previously I was able to run VC4CL on RPi Zero, but it lacked certain features that would make it work with OpenCV.
