### ISSUE TITLE
Compiled tracking module is not detected

### ISSUE THREAD

**Issue by CodingCornerPDI** [twistedfall/opencv-rust#586]
I've compiled OpenCV for Windows with the tracking module from opencv-contrib. This has produced opencv_world4100.dll.

Usually, placing this file alongside the executable in target/release would be all the program needs to compile but for whatever reason it's not able to detect the tracking module.

Is there anything specific I need to do to enable this to work? I can't figure out what I'm missing.
I'm using the latest Rust and OpenCV.
Thank you.

[build.log](https://github.com/user-attachments/files/15901075/build.log)

**Comment by twistedfall** [comment]
The list of modules is based on the OpenCV module headers that the build script looks for during the compilation. In your case I would check that "C:\tools\opencv\build\include\opencv2" directory actually contains the "tracking.hpp" file. If it doesn't then the tracking module wasn't actually included in the build or this included directory might be from a different OpenCV installation, not the one you build manually.

**Comment by CodingCornerPDI** [comment]
Yes, that path was still set to use an old installation. Thank you for the help and God bless package managers
