### ISSUE TITLE
How to use Point3_ types?

### ISSUE THREAD

**Issue by J-F-Liu** [twistedfall/opencv-rust#59]
such as `Point3f`, thanks.

**Comment by twistedfall** [comment]
Hi, those types don’t seem to be generated! I’ll take a look. Meanwhile can you please tell me which function/method requires them in your use case?

**Comment by J-F-Liu** [comment]
I need to calibrate cameras with `opencv::calib3d::calibrate_camera`. Its definition is
```rust
pub fn calibrate_camera(object_points: &dyn core::ToInputArray, image_points: &dyn core::ToInputArray, image_size: core::Size, camera_matrix: &mut dyn core::ToInputOutputArray, dist_coeffs: &mut dyn core::ToInputOutputArray, rvecs: &mut dyn core::ToOutputArray, tvecs: &mut dyn core::ToOutputArray, flags: i32, criteria: &core::TermCriteria) -> Result<f64> {
...
} 
```
So how to prepare input data of type `core::ToInputArray` for this function?

**Comment by twistedfall** [comment]
Got it, I missed it somehow. As a workaround for now you can use `Vec3f` instead, it has the same layout. I will add this type to the bindings as soon as possible.

**Comment by J-F-Liu** [comment]
Ok, thanks in advance.

**Comment by J-F-Liu** [comment]
See the 0.24.4 release, there is `VectorOfVectorOfPoint2f` and `VectorOfPoint3f`, how to get `VectorOfVectorOfPoint3f`?

**Comment by twistedfall** [comment]
Yeah, I've added the support for `Point3x` types in 0.24.4. Can you please tell me for which function you need `VectorOfVectorOfPoint3f`?

**Comment by J-F-Liu** [comment]
Still `calibrate_camera` function, `object_points` parameter type is `std::vector<std::vector<cv::Vec3f>>`.

**Comment by twistedfall** [comment]
It's now there in 0.24.5

**Comment by J-F-Liu** [comment]
Great, I can call `calibrate_camera` now.
