### ISSUE TITLE
Performance concern compared with C++

### ISSUE THREAD

**Issue by CrazyChildren** [twistedfall/opencv-rust#593]
This library is amazing for rust coder to use. But I've encountered some problems when using it.
I tested simple Luminance calculation with both C++ and this binding. Performance seems not in the same order of magnitude.
C++ costs about 2ms. However, this binding consumes 85ms. Is there any mistake I've made in use of this library? thx.

Rust code(use `cargo run --release)`:
```rust
let start = get_tick_count()?;
let mut gray_img = unsafe { Mat::new_rows_cols(img.rows(), img.cols(), CV_8UC1)? };

for i in 0..img.rows() {
    for j in 0..img.cols() {
        let pixel = img.at_2d::<Vec3b>(i, j)?;
        let gray =
            (pixel[2] as f32 * 0.299 + pixel[1] as f32 * 0.587 + pixel[0] as f32 * 0.114) as u8;
        *gray_img.at_2d_mut::<u8>(i, j)? = gray;
    }
}

let cost = (get_tick_count()? - start) as f64 / get_tick_frequency()?;
println!("get_gray_img cost: {}ms", cost);
```
C++ code:
```c++
double t = (double)cv::getTickCount();
cv::Mat img_gray(img.rows, img.cols, CV_8UC1);

for (int i = 0; i < img.rows; i++) {
    for (int j = 0; j < img.cols; j++) {
        cv::Vec3b pixel = img.at<cv::Vec3b>(i, j);
        img_gray.at<uchar>(i, j) = float(pixel[2]) * 0.299 + float(pixel[1]) * 0.587 + float(pixel[0]) * 0.114;
    }
}

t = ((double)cv::getTickCount() - t) / cv::getTickFrequency();
std::cout << "Times passed in seconds: " << t << std::endl;
```

**Comment by twistedfall** [comment]
Main difference is that Rust bindings try to be safer than C++ and for example `at_*` functions do range and type checks every invocation while C++ skips all checks in release mode. To improve this particular example you might want to use `at_row()`/`at_row_mut()` to get rows as slices and apply Rust iterators on them like this:
```rust
    for i in 0..img.rows() {
        let img_row = img.at_row::<Vec3b>(i)?;
        let mut gray_img_row = gray_img.at_row_mut::<u8>(i)?;
        img_row
            .iter()
            .zip(gray_img_row.iter_mut())
            .for_each(|(img_p, gray_img_p)| {
                *gray_img_p = (img_p[2] as f32 * 0.299
                    + img_p[1] as f32 * 0.587
                    + img_p[0] as f32 * 0.114) as u8;
            });
    }
```
in my unscientific benchmark that improved the runtime 15x over your example.

**Comment by twistedfall** [comment]
Additionally there are always unsafe `at_*_unchecked` if you like to live dangerously

**Comment by twistedfall** [comment]
For this particular operation you should even drop per row operations and operate on data slice directly:
```rust
    img.data_typed::<Vec3b>()?
        .iter()
        .zip(gray_img.data_typed_mut::<u8>()?)
        .for_each(|(img_p, gray_img_p)| {
            *gray_img_p =
                (img_p[2] as f32 * 0.299 + img_p[1] as f32 * 0.587 + img_p[0] as f32 * 0.114) as u8;
        });
```

**Comment by CrazyChildren** [comment]
thanks for your reply! it's really mainly blamed on type assertion. I've tested many accelerating methods including:
1. in case of in-continuous of mat, using row slice to iterate (your code above). rust's performance is close to C++.(I've also tested in go and python binding. which costs much more even in same code)
2. If mat is continuous, using `data_typed_mut` to get raw uint8 slice of mat data, C++ still more efficient.(maybe because ignore of type transformation)
3. I've also pre-calculated a LUT recording gray result to reduce multiply operation. This turns out only saves a little time.

My conclusion(may not correct):
This binding would cost more time when needed random-access of image data. but it still more efficient than go and python. And you can boost your code by using `at_row` to access data per row. It would get same performance compared with C++
