### ISSUE TITLE
How to invert black and white in image? Can't make bitwise_not operation work

### ISSUE THREAD

**Issue by manuelarte** [twistedfall/opencv-rust#595]
Hi,

If I want to invert black and white in my image using python, I can do it like this:
```python
inverted_image = cv2.bitwise_not(image)
```

But when I try that in Rust I get an error: Error { code: "StsAssert, -215", message: "OpenCV(4.5.4). This is the code:

```rust
let mut inverted_black_and_white: Vector<u8> = Vector::new();
bitwise_not(&image, &mut inverted_black_and_white, &Vector::<i32>::new()).expect("Bitwise operation should work");
```

am I missing something?

**Comment by twistedfall** [comment]
What is the full error message that you're getting? But just a hunch, can you try using `Mat` instead of `Vector`?

**Comment by manuelarte** [comment]
@twistedfall it works if I use Mat

```rust
let mut inverted_black_and_white = Mat::default();
bitwise_not(&image, &mut inverted_black_and_white, &Vector::<i32>::new()).expect("Bitwise operation should work");
```
