### ISSUE TITLE
inconsistency between two versions of linux (Debian and Archlinux) opencv with Aravis support

### ISSUE THREAD

**Issue by elsuizo** [twistedfall/opencv-rust#599]
Hi i have a custom opencv compilation with Aravis support that works fine in Archlinux but fails in Debian 12. 

In the Case of Debian the custom opencv works fine in Cpp but fails in the Rust program.

The main difference is that in the case of archlinux i install the aravis lib from the AUR package and in the case of Debian i compile from source. Any ideas of what is wrong or where search???.

PD: i see a difference in where place the  pkgconfig folder in the two instalations could be the source of inconsistency???

Regards

**Comment by twistedfall** [comment]
Without the full build log as produced by `cargo build -vv` it's difficult to say what goes wrong. Potentially take a look at https://github.com/twistedfall/opencv-rust/blob/master/INSTALL.md for some guides to make it work with manual build, probably setting up the correct `PKG_CONFIG_PATH` might help

**Comment by elsuizo** [comment]
yeah the solution was setting `PKG_CONFIG_PATH` pointing to the `pkgconfig` folder generated by aravis.

Regards
