### ISSUE TITLE
Random results for adding two mats

### ISSUE THREAD

**Issue by h-a-n-n-e-s** [twistedfall/opencv-rust#608]
I would like to sum up depth data from a camera. I get completely random output if I try to add up two mats, as shown below. Mostly the ouptut is all zero, but then for some large factor c, it sometimes shows reasonable data, but then in the next run with the same c, it might be all zero again.
Am I missing something here?

```rust
let mut sum_mat = unsafe {
    Mat::new_rows_cols(height as i32, width as i32, core::CV_32F).unwrap()
};
let c = 100.0;
loop {
    let depth_mat = // ... input from camera, same type as sum_mat

    sum_mat = (&sum_mat + c * &depth_mat).into_result().unwrap().to_mat().unwrap();

    // ... image output 
}
```

**Comment by twistedfall** [comment]
`sum_mat` is using uninitialized memory, use `Mat::new_rows_cols_with_default` to create that Mat with a known value instead.

**Comment by h-a-n-n-e-s** [comment]
That's it, thanks!
If I want all zeros I guess the initialization parameter should be this
`opencv::core::Scalar::from([0.0; 4])`
?

**Comment by twistedfall** [comment]
That or just a shorter `0.into()`
