### ISSUE TITLE
Access values of Mat

### ISSUE THREAD

**Issue by h-a-n-n-e-s** [twistedfall/opencv-rust#610]
Trying to access the individual values and indices of Mat `input` and write to Mat `output`.
Is this the way?
And is `val.1` really the value?

```rust
for (i, val) in input.iter::<f32>().unwrap().enumerate() {
    if val.1 > 42.0 {
        *output.at_mut::<f32>(i as i32).unwrap() = 1.0;
    }
}
```

**Comment by twistedfall** [comment]
This is one of the options, `Mat::iter()` will produce values of `(Point, T)` where the first element is the position in a 2D `Mat` and the second one is the value. If you don’t need the position, then the fastest would be via `Mat::data_typed()` which will return the slice of all the data in a `Mat`. Additionally, for the operation you’re doing in the example, there is already an OpenCV function `threshold`.

**Comment by h-a-n-n-e-s** [comment]
Thanks!

For `Mat.data_typed()` how would I get the index for writing to the output?

Is there also an OpenCV function for a band pass filter?
`if val.1 > min && val.1 < max {...}`

**Comment by twistedfall** [comment]
> For Mat.data_typed() how would I get the index for writing to the output?

Index as in row and column? If you need them then the easiest is to actually use `Mat::iter()`.

> Is there also an OpenCV function for a band pass filter?

There probably is, but I'm not sure about which one it is :)

**Comment by h-a-n-n-e-s** [comment]
> Index as in row and column?

Index as `i` in the original post:
```rust
*output.at_mut::<f32>(i as i32).unwrap() = 1.0;
```
Or is there a better way to write to the output mat? : )

**Comment by twistedfall** [comment]
`Mat::data_typed()` produces a regular Rust slice, so `.iter().enumerate()` will give you an iterator with index

> Or is there a better way to write to the output mat? : )

The same way, if you can operate on a slice (e.g. have a contiguous `Mat` and don't need row/column information) just take a mutable slice with `Mat::data_typed_mut()`
