### ISSUE TITLE
CommandLineParser misbehaves due to improper argv handling

### ISSUE THREAD

**Issue by niemeyer** [twistedfall/opencv-rust#613]
Hello there, and thanks for creating this comprehensive wrapper.

There's currently a bug when using CommandLineParser, observable even with some of the current examples. The problem is rooted on the mishandling of the argv parameter, provided into CommandLineParser without first guaranteeing that the individual pointers refer to C-style null-terminated strings.  The symptom is garbage being observed in the parsed command line parameter values.

I've submitted a candidate fix to #612.

**Comment by twistedfall** [comment]
Thank you for the PR! This is now released as part of 0.92.3
