### ISSUE TITLE
CascadeClassifier From Buffer

### ISSUE THREAD

**Issue by 0xTriboulet** [twistedfall/opencv-rust#614]
I'm currently using the following to initialize a cascade classifier.

objdetect::CascadeClassifier::new(temp_path.to_str().unwrap())?;

I would prefer to load the contents of that file from a buffer as the .xml is being included in my .exe with !include_bytes, and therefore avoid writing down to disk. In my reading of both the OpenCV code and the bindings in this repo, it seems that it should be possible to do, but the binding doesn't currently exist. I'm open to developing it myself, would just like a few pointers on how to go about doing that if possible.

1) where can I find the existing details of the new() implementation 

2) how/where can I see the code for cv_CascadeClassifier_load_const_StringR, this function seems to be constructed at build time if my reading is correct? But it would contain the details that I would like to see for implementing the _from_buffer equivalent.

3) any other tips, tricks, or pointer regarding this would be awesome.

Thanks

**Comment by twistedfall** [comment]
Well, what you're trying to achieve is already possible through a couple of hoops:
```rust
let xml = include_str!("...");
let storage = FileStorage::new_def(xml, i32::from(FileStorage_Mode::READ) | i32::from(FileStorage_Mode::MEMORY))?;
let mut classifier = CascadeClassifier::default()?;
classifier.read(&storage.get_first_top_level_node()?)?;
```

Regarding your questions:
Generally this crate wraps the functionality provided by the OpenCV without adding anything on top so if OpenCV couldn't load the data from the buffer then I would avoid adding it.

> where can I find the existing details of the new() implementation

The build script of the crate generates C++ and Rust wrappers in the output directory (under `target/debug/build`) for every supported OpenCV function. The `new` function for the `CascadeClassifier` looks like this:
```rust
		/// Loads a classifier from a file.
		/// 
		/// ## Parameters
		/// * filename: Name of the file from which the classifier is loaded.
		#[inline]
		pub fn new(filename: &str) -> Result<crate::objdetect::CascadeClassifier> {
			extern_container_arg!(filename);
			return_send!(via ocvrs_return);
			unsafe { sys::cv_CascadeClassifier_CascadeClassifier_const_StringR(filename.opencv_as_extern(), ocvrs_return.as_mut_ptr()) };
			return_receive!(unsafe ocvrs_return => ret);
			let ret = ret.into_result()?;
			let ret = unsafe { crate::objdetect::CascadeClassifier::opencv_from_extern(ret) };
			Ok(ret)
		}
```

> how/where can I see the code for cv_CascadeClassifier_load_const_StringR, this function seems to be constructed at build time if my reading is correct? But it would contain the details that I would like to see for implementing the _from_buffer equivalent.

It's correct, but it doesn't contain any functionality either, it's just a wrapper to call into the actual OpenCV function:
```c++
	void cv_CascadeClassifier_load_const_StringR(cv::CascadeClassifier* instance, const char* filename, Result<bool>* ocvrs_return) {
		try {
			bool ret = instance->load(std::string(filename));
			Ok(ret, ocvrs_return);
		} OCVRS_CATCH(ocvrs_return);
	}
```

**Comment by 0xTriboulet** [comment]
Thanks for the quick reply. For now your proposed solution should work for my purposes. Closing this issue 👍🏽
