### ISSUE TITLE
What's the difference between `gapi::canny` and `imgproc::canny`?

### ISSUE THREAD

**Issue by Guelakais** [twistedfall/opencv-rust#616]

**Comment by twistedfall** [comment]
The one from the `gapi` module is using OpenCV's newer [Graph API](https://docs.opencv.org/4.x/d0/d1e/gapi.html). Currently only a set of features of the `gapi` module is supported in the crate.

**Comment by Guelakais** [comment]
How do you feed the `gapi::canny` with single images and is it better, a new one?

**Comment by twistedfall** [comment]
Whether it's better depends on your particular needs, you can check the usage example here: https://github.com/twistedfall/opencv-rust/blob/master/examples/gapi_api_example.rs. Just beware that not all of the features of the `gapi` module are supported in the crate e.g. a big chunk of it relies on C++ templates and extending C++ classes for custom functionality, those are quite difficult to port to Rust.
