### ISSUE TITLE
opencv-rust/0.93.1 with opencv:4.10.0 works well in local macOS M2, but compile error on ubuntu 24.04

### ISSUE THREAD

**Issue by phial3** [twistedfall/opencv-rust#625]
1. Operating system : ubuntu 24.04
2. The way you installed OpenCV: manual compilation
3. OpenCV version : 4.10.0
4. rustc version (`rustc --version`): 1.81.0
5. Attach the full output of the following command from your project directory:
   ```shell script
   RUST_BACKTRACE=full cargo build -vv 
   ```

first, Works well in my local macOS M2, but compile error on ubuntu 24.04
error info:
```
error[E0061]: this function takes 5 arguments but 4 arguments were supplied
    --> src/common/utils.rs:66:8
     |
66   |     if imgproc::cvt_color(&mat, &mut rgb_mat, imgproc::COLOR_BGR2RGB, 0).is_ok() {
     |        ^^^^^^^^^^^^^^^^^^----------------------------------------------- argument #5 of type `AlgorithmHint` is missing
     |
note: function defined here
    --> /code/tplay/target/release/build/opencv-0a3f7c597e79dae1/out/opencv/imgproc.rs:6207:9
     |
6207 |     pub fn cvt_color(src: &impl ToInputArray, dst: &mut impl ToOutputArray, code: i32, dst_cn: i32, hint: core::AlgorithmHint) -> Result<()> {
     |            ^^^^^^^^^
help: provide the argument
     |
66   |     if imgproc::cvt_color(&mat, &mut rgb_mat, imgproc::COLOR_BGR2RGB, 0, /* AlgorithmHint */).is_ok() {
     |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0061`.
error: could not compile `tplay` (bin "tplay") due to 1 previous error
```

**Comment by phial3** [comment]
in local macOS M2, with opencv 4.10.0，that's right：
```rust
imgproc::cvt_color(&mat, &mut rgb_mat, imgproc::COLOR_BGR2RGB, 0)
```

i don't understand why the parameters change on ubuntu 24.04 with opencv 4.10.0:
```rust
imgproc::cvt_color(&mat, &mut rgb_mat, imgproc::COLOR_BGR2RGB, 0, /* AlgorithmHint */)
```

**Comment by twistedfall** [comment]
It's highly likely that you use the git master or other unreleased version of OpenCV on Ubuntu and not 4.10.0, this new argument is shown in the [4.10.0-dev docs](https://docs.opencv.org/4.x/d8/d01/group__imgproc__color__conversions.html#gaf86c09fe702ed037c03c2bc603ceab14), but not in [4.10.0 docs](https://docs.opencv.org/4.10.0/d8/d01/group__imgproc__color__conversions.html#ga397ae87e1288a81d2363b61574eb8cab).

**Comment by phial3** [comment]
> It's highly likely that you use the git master or other unreleased version of OpenCV on Ubuntu and not 4.10.0, this new argument is shown in the [4.10.0-dev docs](https://docs.opencv.org/4.x/d8/d01/group__imgproc__color__conversions.html#gaf86c09fe702ed037c03c2bc603ceab14), but not in [4.10.0 docs](https://docs.opencv.org/4.10.0/d8/d01/group__imgproc__color__conversions.html#ga397ae87e1288a81d2363b61574eb8cab).

ok, you're right, i compiled OpenCV manually from the git branch 4.x in ubuntu 24.04

**Comment by kevleyski** [comment]
(I just did the same thing, in this case is this not a heads up there will be a fifth param coming?)

**Comment by kitty-eu-org** [comment]
Here is my solution:
build.rs: 
```
fn build_opencv_version() {
    let opencv_version = opencv::core::get_version_string().unwrap();
    let mut vs = opencv_version.split('.').take(2);
    if let (Some(major), Some(minor)) = (vs.next(), vs.next()) {
        if let (Ok(major), Ok(minor)) = (major.parse::<u32>(), minor.parse::<u32>()) {
            if (major, minor) >= (4, 11) {
                println!("cargo:rustc-cfg=opencv_4_11_plus");
                println!("cargo::rustc-check-cfg=cfg(opencv_4_11_plus)");
            }
        }
    }
}
```
use opencv cvt_color file:
```
#[cfg(opencv_4_11_plus)]
use opencv::core::AlgorithmHint;
use opencv::core::{ToInputArray, ToOutputArray};
use opencv::imgproc;

pub fn compat_cvt_color(
    src: &impl ToInputArray,
    dst: &mut impl ToOutputArray,
    code: i32,
    dst_cn: i32,
) -> opencv::Result<()> {
    #[cfg(opencv_4_11_plus)]
    return imgproc::cvt_color(src, dst, code, dst_cn, AlgorithmHint::ALGO_HINT_DEFAULT);

    #[cfg(not(opencv_4_11_plus))]
    return imgproc::cvt_color(src, dst, code, dst_cn);
}
```

**Comment by twistedfall** [comment]
In crate version 0.95 you can use one of the new conditional macros: `opencv_has_inherent_feature_algorithm_hint!` to achieve the same goal, but easier. See example here: https://github.com/twistedfall/opencv-rust/blob/31850617cbb5205974db7c01a3c8553ab7224a12/examples/hough_circle.rs#L96
