### ISSUE TITLE
How to use `match_` or `match__def`

### ISSUE THREAD

**Issue by quanshuli** [twistedfall/opencv-rust#629]
Hello, I'm trying to use `BFMatcher` and I found that the parameters of `match_def` is ` query_descriptors, matches`, but in the C++ it is `queryDescriptors, trainDescriptors, matches`, so `trainDescriptors` is missing from the rust api, how should I use it correctly? Thanks very much.

**Comment by twistedfall** [comment]
That's not entirely true, there are 2 overloads in C++, [with](https://docs.opencv.org/4.x/db/d39/classcv_1_1DescriptorMatcher.html#a0f046f47b68ec7074391e1e85c750cba) and [without](https://docs.opencv.org/4.x/db/d39/classcv_1_1DescriptorMatcher.html#a695c0aceafc907c024c24a0b5cdff758) `trainDescriptors`. The one with `trainDescriptors` is generated as [train_match](https://docs.rs/opencv/latest/opencv/features2d/trait.DescriptorMatcherTraitConst.html#method.train_match).

**Comment by quanshuli** [comment]
Thanks very much for the prompt reply and great work!
