### ISSUE TITLE
`ximgproc::thinning()` not found, the method in C++ header `<opencv2/ximgproc.hpp>` 

### ISSUE THREAD

**Issue by phial3** [twistedfall/opencv-rust#634]
Before reporting an issue please first check the
[troubleshooting guide](https://github.com/twistedfall/opencv-rust/blob/master/README.md#troubleshooting). If
the issue you're encountering is not solved thereby please state the following in your bugreport:
1. Operating system: macOS M2
2. The way you installed OpenCV: package
3. OpenCV version: 4.10.0
4. rustc version : 1.82
5. Attach the full output of the following command from your project directory:
   ```shell script
   RUST_BACKTRACE=full cargo build -vv 
   ```

**Comment by twistedfall** [comment]
Well, it's present in the rather complete build of OpenCV that I test against locally, e.g. it's there in the docs: https://docs.rs/opencv/latest/opencv/ximgproc/fn.thinning.html so it looks like the OpenCV build you're using doesn't have the `ximgproc` module at all.

**Comment by phial3** [comment]
> Well, it's present in the rather complete build of OpenCV that I test against locally, e.g. it's there in the docs: https://docs.rs/opencv/latest/opencv/ximgproc/fn.thinning.html so it looks like the OpenCV build you're using doesn't have the `ximgproc` module at all.

thank u.
