### ISSUE TITLE
opencv 0.93.4 fails to build when using another bindgen library

### ISSUE THREAD

**Issue by yuntao3568** [twistedfall/opencv-rust#635]
【Environment】
1. Operating system：windows11
2. The way I installed OpenCV：Download the `opencv-4.9.0-windows.exe` installation package from the official website

> The following environment variables are set：
> ![屏幕截图 2024-11-18 231222](https://github.com/user-attachments/assets/373c9c89-6d8c-41ab-a631-6aebd2963f0e)

3. OpenCV version：4.9.0
4. rustc version：rustc 1.82.0 (f6e511eec 2024-10-15)

【Phenomenon Description】
I used ` bindgen` tool to generate a carte `HKGYMVS 0.1.0` because I used a third party camera. Then I want to go ahead and add your carte `opencv`, then I get an error: a 'libclang' shared library is not loaded on this thread. PS. Created a new project containing only opencv cartes that can be used normally.
> ` https://github.com/yuntao3568/HKGYMVS`

[log.txt](https://github.com/user-attachments/files/17802823/log.txt)

Then, I find a solution for Troubleshooting: Enable the clang-runtime feature. change `opencv = { version = "0.93.4" }` to `opencv = { version = "0.93.4", features = ["clang-runtime"] }`，still not working properly：`Failed to run the bindings generator for module: highgui
`, `Failed to run the bindings generator for module: calib3d`, etc.

[log2.txt](https://github.com/user-attachments/files/17802922/log2.txt)

【My Ignorant  Guesss】
Is it possible that calling `bindgen `twice has caused some parameters to be affected between the two invocations, leading to a failure in the normal building of` opencv`? Below is the address for HKGYMVS that I created myself:https://github.com/yuntao3568/HKGYMVS

Please, dear author, save this poor soul.ಥ_ಥ

**Comment by twistedfall** [comment]
Sorry, I replied in a hurry without reading your post thoroughly! There is currently an issue on windows with clang-19 with having `clang-runtime` enabled. It's originating in the `clang` crate and the only workaround for now is downgrading clang or disabling `clang-runtime`. Any help investigating it is greatly appreciated!

**Comment by twistedfall** [comment]
This has been reported before here: https://github.com/twistedfall/opencv-rust/issues/628 so I'm going to close this issue in favor of that earlier one.
