### ISSUE TITLE
no method named available found for struct Client in the current scope

### ISSUE THREAD

**Issue by pixelargentum** [twistedfall/opencv-rust#639]
Sorry for the inconvenience. I'm not very experienced in programming and more a photographer who wants to build and compile the following project: https://github.com/FruitieX/negative_scanner 

I succeded with installing opencv-rust on Manjaro Linux (Arch Linux) and compile succesfully a test with opencv (https://www.delftstack.com/howto/rust/opencv-rust)
But compiling FruitieX-project I get the same error as in issue #400, only opencv-version is the newest (0.94.4):

error[E0599]: no method named `available` found for struct `Client` in the current scope
   --> /home/silverpixel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.93.4/build/generator.rs:140:33
    |
140 |                 let available_jobs = client.available().unwrap_or(0);
    |                                             ^^^^^^^^^ method not found in `Client`

**Comment by twistedfall** [comment]
I see, looks like the minimum version requirement got lost at some point, I'm going to release the fix momentarily, but for now you should be able to run `cargo update` in the project directory and it should build successfully afterwards. Although I'm pretty confident that the code in `negative_scanner` will need to be adjusted too, there were a lot of changes between `0.63.1` and `0.93.4` versions.

**Comment by twistedfall** [comment]
Should now be fine again in `0.93.5`
