### ISSUE TITLE
bionic-install-opencv.sh link is broken

### ISSUE THREAD

**Issue by abhijithgopal** [twistedfall/opencv-rust#67]
Relevant section: https://github.com/twistedfall/opencv-rust#compiling-opencv

Points to: https://github.com/twistedfall/opencv-rust/blob/master/ci/bionic-install-opencv.sh
Should point to: https://github.com/twistedfall/opencv-rust/blob/master/ci/install-bionic.sh

**Comment by twistedfall** [comment]
Thanks! Fixed
