### ISSUE TITLE
getRotationMatrix2D symbol lookup error for opencv 4.1.2

### ISSUE THREAD

**Issue by MartinquaXD** [twistedfall/opencv-rust#72]
I'm currently running into a runtime symbol lookup error for undefined symbol: _ZN2cv20getRotationMatrix2D_ENS_6Point_IfEEdd.

It seems to me that something might be broken with the function opencv::imgproc::get_rotation_matrix_2d.

I had some trouble making the rust bindings work so I might have multiple opencv versions >= 4.1.0 installed.
But since I'm using feature "opencv-41" and the signature of that particular function didn't change after 4.1.0, this wouldn't explain the problem, right?

Any help would be really appreciated.

**Comment by twistedfall** [comment]
Hi, can you please specify the OS you're building from and attach the log you get after doing a `cargo clean` and running `cargo build -vv`?

**Comment by twistedfall** [comment]
And also the one thing I see is that in 4.1.2 (as opposed to 4.1.0) it has actually became inline, there is a definition for that function directly in the header:

```cpp
inline
Mat getRotationMatrix2D(Point2f center, double angle, double scale)
{
    return Mat(getRotationMatrix2D_(center, angle, scale), true);
}
```
That would explain the missing symbol. I'll try to see what can be done here.

**Comment by MartinquaXD** [comment]
Thanks for the quick response.
I did the rebuild but I'm not really sure which log file you would like to have. I hope it's the right one.
[output.txt](https://github.com/twistedfall/opencv-rust/files/3956701/output.txt)

**Comment by twistedfall** [comment]
I've tried using this function and it works for me. There might be a problem that it's trying to link object files generated for 4.1.0. Please try doing a `cargo clean` first and building it again. Please also use the latest version of the crate. Should the problem persist please attach the `crate build -vv` log again (there is more logging in the 0.27.x version of the crate).

**Comment by MartinquaXD** [comment]
Reinstalling opencv and rebuilding with the newest version of your crate did the trick.
Thanks :)
