### ISSUE TITLE
Run time error of SimpleBlobDetector 

### ISSUE THREAD

**Issue by J-F-Liu** [twistedfall/opencv-rust#74]
```rust
use opencv::features2d::{Feature2DTrait, SimpleBlobDetector, SimpleBlobDetector_Params};

let mut blob_detector = unsafe {
    let detector_params = SimpleBlobDetector_Params::default()?;
    let blob_detector_ptr = SimpleBlobDetector::create(detector_params)?;
    let raw_ptr = blob_detector_ptr.as_raw_PtrOfSimpleBlobDetector();
    SimpleBlobDetector::from_raw_ptr(raw_ptr)
};
let mask = Mat::default()?;
let mut keypoints = VectorOfKeyPoint::new();
blob_detector.detect(image, &mut keypoints, &mask)?;
```
Got `'cargo run' terminated by signal SIGSEGV (Address boundary error)`.

```rust
let mut blob_detector = unsafe {
    let detector_params = SimpleBlobDetector_Params::default()?;
    let blob_detector_ptr = SimpleBlobDetector::create(detector_params)?;
    let raw_ptr = blob_detector_ptr.as_raw_PtrOfSimpleBlobDetector();
    PtrOfFeature2D::from_raw_ptr(raw_ptr)
};
let mask = Mat::default()?;
let mut keypoints = VectorOfKeyPoint::new();
blob_detector.detect(image, &mut keypoints, &mask)?;
```
Got `'cargo run' terminated by signal SIGBUS (Misaligned address error)`.

How to solve this?

**Comment by twistedfall** [comment]
It looks like `blob_detector_ptr` gets dropped at the end of the `unsafe` block. Can you try moving lines:
```
    let detector_params = SimpleBlobDetector_Params::default()?;
    let blob_detector_ptr = SimpleBlobDetector::create(detector_params)?;
```
above the `unsafe {`? Or you can try `mem::forget`ting `blob_detector_ptr` before the end of the `unsafe` block. In that case be sure to handle the potential memory leak.

**Comment by J-F-Liu** [comment]
Move the code out of unsafe block actually gives:
```
malloc: *** error for object 0x7f9368d533f0: pointer being freed was not allocated
```

Add `mem::forget` works, since the pointer is the same pointer, I think dropping `blob_detector` will also drop it, so no memory leak.

Thanks a lot.

**Comment by twistedfall** [comment]
> Move the code out of unsafe block actually gives:
> 
> ```
> malloc: *** error for object 0x7f9368d533f0: pointer being freed was not allocated
> ```

Ah, makes sense since we're double-freeing the same pointer. Yeah, in this case `mem::forget` would be the only viable choice.

**Comment by J-F-Liu** [comment]
@twistedfall Is it possible to change the method signature from
```rust
pub fn as_raw_PtrOfSimpleBlobDetector(&self) -> *mut c_void
```
to
```rust
pub fn as_raw_PtrOfSimpleBlobDetector(self) -> *mut c_void
```
?

There many `as_raw_` methods, better to change them all.

**Comment by twistedfall** [comment]
Well, `as_*` methods usually return different interpretation of the object, not consume it. And if we are to change it to `(self)` then the method would also destroy the object returning invalid pointer. So it needs to also `mem::forget` it. For me it looks like a task for the new method, something like `into_raw_*`. I'll check. Meanwhile, can you tell me more about how you use it currently and what are your patterns?

**Comment by J-F-Liu** [comment]
`find_circles_grid` method requires `blob_detector: &PtrOfFeature2D`, which need be created this way.
