### ISSUE TITLE
How to work with Cuda?

### ISSUE THREAD

**Issue by TheRadioGuy** [twistedfall/opencv-rust#76]

**Comment by twistedfall** [comment]
There is no support at the moment. It might be quite easy to turn on, it's just that it hasn't received enough attention. Since there is demand, I'll try to look into it. Meanwhile you can use OpenCL, it should work pretty well.

**Comment by TheRadioGuy** [comment]
Ok, thanks!

**Comment by twistedfall** [comment]
Hi, CUDA support was added in 0.42.0
