### ISSUE TITLE
Question: How to convert `Mat` to a Rust `Vec<T>` ? 

### ISSUE THREAD

**Issue by kahlil29** [twistedfall/opencv-rust#79]
First off, I'd like to say thanks for the bindings. 
I managed to read an image and then resize it using the `resize` function. 
So then I have a `Mat` that I want to convert into a rust `Vec<u8>`

For some reason the `data` function returns a single value of type `u8`. 
In my case the value that the `data` function returns to me is `22`. 

I'm very confused because the `Mat` seems to be of the right structure. 
Could you please tell me what I'm supposed to do in order to convert the `Mat` into a `Vec`?

PS : I've tried the `convert_to` function in order to convert into a `VectorOfint` but it errors out with some cpp error that I cannot understand: 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -215, message: "OpenCV(4.2.0) /tmp/opencv-20200105-17262-cwpzm4/opencv-4.2.0/modules/core/src/matrix_wrap.cpp:1365: error: (-215:Assertion failed) d == 2 && (sizes[0] == 1 || sizes[1] == 1 || sizes[0]*sizes[1] == 0) in function \'create\'\n" }', src/libcore/result.rs:1165:5
```

**Comment by twistedfall** [comment]
You should use the `.data_typed::<u8>()` which will yield you `Result<&[u8]>`. After that you can use `.to_vec()` method of slice to get yourself a copied owned `Vec`.

Now that I think about it, it would actually fail for non-continuous `Mat`s, so please make sure that `is_continuous()` is true. For non-continuous `Mat`s the safest way is to employ `MatConstIterator`, check `https://github.com/twistedfall/opencv-rust/blob/master/tests/mat.rs#L430` for some example code.

**Comment by kahlil29** [comment]
Thanks for your prompt reply! 
Turns out I had to convert it into a `Vec3b` (Vec3<u8>) because the image was 3-channel (RGB). 
Your suggestion of `data_typed` worked well in order to go from a `Mat` but now I am stuck with a `Vec3b` and I can't seem to figure out how to convert that into an `array` or `slice`. 
I tried the `from` and `into` functions but they (the current traits) don't seem to fit my use-case.

**Comment by kahlil29** [comment]
Alright I think I figured it out. Managed to get the job done using `deref` 😅

**Comment by twistedfall** [comment]
All `VecX` have `Deref` into the corresponding array. So `Vec3b` can be `Deref`ed to `[u8; 3]` so you can just use all your array and slice methods. In this case just call `to_vec()`.

Ah, too late :)

**Comment by kahlil29** [comment]
Thanks a lot, it's refreshing to have a library author/maintainer who replies so quickly!
