### ISSUE TITLE
Cannot import `xphoto` (Part of extra modules (contrib) )

### ISSUE THREAD

**Issue by kahlil29** [twistedfall/opencv-rust#81]
I'm trying to import it as `use opencv::xphoto;`

Error : 
```
unresolved import `opencv::xphoto`
no `xphoto` in the root
```

**Comment by twistedfall** [comment]
Be sure to enable the `contrib` feature otherwise the additional modules will not be available

**Comment by kahlil29** [comment]
Ah damn, I'm quite new to Rust, so didn't know how to do that. 
I checked the docs and managed to get it to work. 
Thanks for your quick reply. 
Would you be okay if I opened a PR to add an example of adding a (`contrib`) feature to the README of this repo?

**Comment by twistedfall** [comment]
Well, currently README already has a section in Quickstart about it:
```
And enable usage of contrib modules:

opencv = {version = "0.29", features = ["contrib"]}
```
and the explanation of the feature flag:
```
contrib - enable the usage of OpenCV contrib modules for corresponding OpenCV version
```
can you please tell me what you'd like to expand?

**Comment by kahlil29** [comment]
Oops. Totally didn't see that! 
Thanks so much for your help! 😄 
It's really nice having responsive and helpful library maintainers!

**Comment by twistedfall** [comment]
You're welcome :)
