### ISSUE TITLE
[feature request] Add VectorOfVec3{f,d} type

### ISSUE THREAD

**Issue by jerry73204** [twistedfall/opencv-rust#83]
It happens that [opencv::aruco::estimate_pose_single_markers](https://docs.rs/opencv/0.29.0/opencv/aruco/fn.estimate_pose_single_markers.html) takes rvec and tvec of type `std::vector<Vec3d>`, which is missing in this crate. Can you tell the way to add `VectorOfVec3{f,d}` types?

**Comment by twistedfall** [comment]
For now you can use `VectorOfPoint3{f,d}` for that, they have identical layout with `Vec3`. I'll make sure that `VectorOfVec3x` is also included in the future version of the bindings.

**Comment by jerry73204** [comment]
I copied and pasted from `VectorOfPoint6f` to create `VectorOfPoint3f` in `opencv*/{types,sys}.rs`. However, this attempt cannot build. Also, I observed `{types,sys}.rs` duplicate over distinct opencv versions. Are these files generated by automated means? If yes, is there document for that procedure?

**Comment by twistedfall** [comment]
Yep, those are generated code, there is no documentation per se, but in this case to make the new array types get generated too you'll need to update `gen_rust.py` file and modify the top-level `decls_manual_pre` dic. Add some more entries into the `"core"` subdict that follow the logic of `("typedef DummyVectorOfPoint3i", "std::vector<Point3i>", [], []),`. So something like `("typedef DummyVectorOfVec3f", "std::vector<Vec3f>", [], []),` should work. You'd need to build with `buildtime-bindgen` feature afterwards.

**Comment by twistedfall** [comment]
Fixed in v0.30.0. Please note that this version comes with the totally rewritten binding generator and you will need llvm installed instead of python to be able to correctly regenerate bindings. Please see the [changelog](https://github.com/twistedfall/opencv-rust/blob/master/CHANGES.md) and [readme](https://github.com/twistedfall/opencv-rust/blob/master/README.md) for more details.
