### ISSUE TITLE
No way to set DetectorParameters members

### ISSUE THREAD

**Issue by jerry73204** [twistedfall/opencv-rust#84]
The rust side of [DetectorParameters](https://docs.rs/opencv/0.29.0/opencv/aruco/struct.DetectorParameters.html) only exposes _getter_ methods, while _setters_ are not available. It seems the [class members](https://github.com/opencv/opencv_contrib/blob/d0d86695f8902066072417f0c2ff5fd95fe31878/modules/aruco/include/opencv2/aruco.hpp#L156) are decorated with `CV_PROP_RW` and the [header parser code](https://github.com/twistedfall/opencv-rust/blob/921679465d5bda57fe5ad3b8d5075a95870a1cfd/hdr_parser.py#L822) does not respect the distinction b/w `CV_PROP_RW` and `CV_PROP`.

Fixing it once would work on all issues of this kind. Not sure how much time I can dive into the parser code, so I file this bug in case we could have future changes.

**Comment by twistedfall** [comment]
Hi, I’ll need to some time to check it out, but in any case, I’m doing a big ground up rewrite of the parser, so please don’t do any changes to `gen_rust.py` as it will be deprecated in the near future.

**Comment by jerry73204** [comment]
That's good news to me. I can't wait to see the API become more rusty as the parser evolves. As I had used this crate in my project, let me list some wishes that's about to change.

- The `opencv::types::*` types work like C++ rather than rusty code. The `VectorOfXXX` is somewhat too verbose. I would rather derive the `InputArray` trait to built-in types rather that wrapping around C++ types.
- For geometry types like `Point*`, we may take a look at [nalgebra types](https://docs.rs/nalgebra/0.19.0/nalgebra/geometry/index.html). They have done a good job on it.
- If possible, use _expression-return_ pattern instead of passing mut references. For example, change `rodrigues(&src, &mut dst, &mut jacobian)` to `rodrigues(&src) -> (dst, jacobian)`. I suppose the python bindings already have it.

EDIT: typo

**Comment by twistedfall** [comment]
Thanks for your suggestions! The first iteration of the new parser will not contain any major improvements though, just faster generation of more complete bindings. But at the later stages I will definitely keep your points in mind!

**Comment by jerry73204** [comment]
As far as I peek into `gen_rust.py`, the [ClassPropInfo.rw](https://github.com/twistedfall/opencv-rust/blob/921679465d5bda57fe5ad3b8d5075a95870a1cfd/gen_rust.py#L1600) is never used, while the `hdr_parser.py` has done its good job. That might be the source of this issue.

**Comment by twistedfall** [comment]
The unsoundness is fixed in v0.30.0. Please note that this version comes with the totally rewritten binding generator and you will need llvm installed instead of python to be able to correctly regenerate bindings. Please see the [changelog](https://github.com/twistedfall/opencv-rust/blob/master/CHANGES.md) and [readme](https://github.com/twistedfall/opencv-rust/blob/master/README.md) for more details.
