### ISSUE TITLE
set_input on dnn::Net

### ISSUE THREAD

**Issue by johnny-human** [twistedfall/opencv-rust#87]
Hello, I try to set an input value on a network with an image blob, but set_input does not exist on the dnn::Net trait, but it exist on dnn::NetTrait. Is NetTrait not implemented for Net, or am I doing something wrong?

```
let detector: dnn::Net = dnn::read_net_from_caffe(...);
let blob: core::Mat = dnn::blob_from_image(...);
detector.set_input(&blob, ...);
```

**Comment by twistedfall** [comment]
Well, `NetTrait` is implemented for `Net`: https://github.com/twistedfall/opencv-rust/blob/master/src/opencv/hub/dnn.rs#L2947 so maybe you didn't import it with `use opencv::dnn::NetTrait`?

**Comment by johnny-human** [comment]
Thanks, that was a beginners blunder. Well, it is a great API :)

**Comment by twistedfall** [comment]
No problem! :)
