### ISSUE TITLE
Basic example file: window , I cannot run.

### ISSUE THREAD

**Issue by curly-wei** [twistedfall/opencv-rust#92]
Hi:
I passed compilation:
```
$ cargo build      
   Compiling opencvrs v0.1.0 (/home/dewei/Downloads/opencvrs)
    Finished dev [unoptimized + debuginfo] target(s) in 1.67s
```
I sure my test picture 'lena.jpg' exist in '/home/dewei/Downloads/opencvrs/target/debug/lena.jpg'

But I get following result after I run,:
```
$ cargo run 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -215, message: "OpenCV(4.2.0) /build/opencv/src/opencv-4.2.0/modules/highgui/src/window.cpp:384: error: (-215:Assertion failed) size.width>0 && size.height>0 in function \'imshow\'\n" }', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

How do I solved it?

my source code download from example file in opencv-rust:
```
extern crate opencv;
use opencv::{highgui, imgcodecs};
#[allow(dead_code)]
fn main() {
    let image = imgcodecs::imread("lena.jpg",-1).unwrap();
    highgui::named_window("hello opencv!", 0).unwrap();
    highgui::imshow("hello opencv!", &image).unwrap();
    highgui::wait_key(10000).unwrap();
}
```
and I follow first page of this project to write toml:
```
[package]
name = "opencvrs"
version = "0.1.0"
authors = ["avc <xxx88556@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.29"
```

**Comment by twistedfall** [comment]
> OpenCV(4.2.0) /build/opencv/src/opencv-4.2.0/modules/highgui/src/window.cpp:384: error: (-215:Assertion failed) size.width>0 && size.height>0 in function \'imshow\'

This error message is coming from the OpenCV itself, not the crate. So from the looks of it you don't have `lena.jpg` in the current directory or it's empty.

**Comment by curly-wei** [comment]
Hi @twistedfall :
Directory of `lena.jpg`  same as  executed file:
```
./target/debug/
             |
             --- lena.jpg
             --- opencvrs  
             --- opencvrs.d
```
The `opencvrs` is executable file after build

**Comment by twistedfall** [comment]
Well, the way you open it, it needs to be in the current directory, which is not necessary the one of the binary. In you case do a `cd /home/dewei/Downloads/opencvrs/target/debug/` and run the binary manually `./opencvrs`. It should work then. Or move `lena.jpg` to `/home/dewei/Downloads/opencvrs/`

**Comment by curly-wei** [comment]
Oh~
So it is!
Thanks @twistedfall very much.

**Comment by twistedfall** [comment]
No problem :)
