### ISSUE TITLE
Cant clone VecDeque<core::Mat>

### ISSUE THREAD

**Issue by GZYproduction** [twistedfall/opencv-rust#95]
Hey,
I'm trying to make a copy of a `VecDeque` containing `core::Mat`; I'm new to rust, I think this has to do something with the implementation of `core::Mat`. ?(You can derive the Clone Trait, but `core::Mat` doesn't?)

The Linter fails with following error:
"the trait `std::clone::Clone` is not implemented for `opencv::prelude::Mat`"

I'm really interested if someone more experienced knows why this error arises. 

Thanks :)

**Comment by twistedfall** [comment]
Hi, `Mat` does have the `clone` method, but it returns `Result<Mat>` to account on possible exceptions on C++ side. So for now we can't derive `Clone`. Your only solution at the moment would be element by element cloning, something along the lines:
```rust
vec.iter().map(|mat| mat.clone()).collect::<opencv::Result<VecDeque<_>>>();
```

**Comment by GZYproduction** [comment]
@twistedfall Thank you for this awesome project and your help. :+1:
Worked perfectly :smile:
